// A line a day, for whoever opens the platform, and what to do about it.
//
// Three rules about what goes in here.
//
// It has to earn its place on a screen somebody opened to do something else.
// A poster quote about believing in yourself is worse than a blank space: it
// makes a serious platform look like a wall calendar, and the people this is
// for run departments with six-figure budgets and read that instantly.
//
// The attribution has to be right. Hanging somebody's name on a line they
// never said is a small lie printed under our own logo every day. So most of
// these are ours, written for this industry and credited to the house, and
// the ones that are not are lines their authors are genuinely known for.
//
// And every one carries a takeaway. A quotation on its own is decoration; the
// difference between decoration and use is one sentence saying what to do
// before Friday. That sentence is the reason this exists, so it is required
// by the type rather than optional.

export type Thought = {
  text: string
  /** Left out where the line is the house's own. */
  author?: string
  /** What to actually do about it. Never decorative, never optional. */
  why: string
}

export const THOUGHTS: Thought[] = [
  { text: 'Nobody remembers the treatment menu. They remember whether the person doing it seemed glad they came.', why: 'Ask one therapist today what would make her gladder to be there. Then do one of the things she says.' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle', why: 'Pick the one thing that slips when you are busy and build it into the opening checklist, so it stops needing willpower.' },
  { text: 'A spa runs on the things nobody is paid to notice. Warm towels. A door that does not stick. Somebody who read the notes.', why: 'Walk the route a guest takes this week, as a guest would, and write down the first five things you notice.' },
  { text: 'The details are not the details. They make the design.', author: 'Charles Eames', why: 'Choose one detail this month - the arrival, the robe, the aftercare - and make it genuinely excellent before touching anything else.' },
  { text: 'You cannot charge five-star prices for a three-star handover.', why: 'Time your actual turnaround honestly. If the number does not fit the price, change one of the two.' },
  { text: 'If your therapists dread the rota, your guests can feel it by Wednesday.', why: 'Publish the rota further ahead than you currently do. It is the cheapest retention decision available to you.' },
  { text: 'Care about what other people think and you will always be their prisoner.', author: 'Lao Tzu', why: 'Make the unpopular scheduling or standards decision you have been deferring, and explain the reason rather than defending it.' },
  { text: 'Being fully booked is not the same as being profitable, and the difference is usually retail.', why: 'Work out your revenue per treatment hour, not just occupancy. It will change which hours you protect.' },
  { text: 'The best spa manager in the country is somewhere on a rota being told she is not ready.', why: 'Name the person on your team who is ready for more, and give her one real decision this month.' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci', why: 'Cut the two treatments on your menu that nobody orders well. A shorter menu is delivered better.' },
  { text: 'A treatment room that runs late is a design problem, not a discipline problem.', why: 'Watch one full turnaround with a stopwatch and fix the step that costs the time, not the person doing it.' },
  { text: 'Train people well enough so they can leave. Treat them well enough so they do not want to.', author: 'Richard Branson', why: 'Book one piece of training this quarter for somebody who has not had any this year.' },
  { text: 'Any spa can buy the same beds and the same products. Nobody can buy your team.', why: 'Put as much thought into this month\'s team meeting as you would into a supplier negotiation.' },
  { text: 'Luxury is not what you spend. It is what you do not have to ask for twice.', why: 'Find the thing guests always have to ask for, and give it to them before they do.' },
  { text: 'The person who knows every guest by name is on your lowest pay band. Check that is still true tomorrow.', why: 'Look at what you pay reception against what reception decides. Adjust one of them.' },
  { text: 'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.', author: 'Antoine de Saint-Exupery', why: 'Remove a step from your treatment protocol that serves the paperwork rather than the guest.' },
  { text: 'Discounting is a decision to be busy instead of good. It is a fine decision, as long as it is a decision.', why: 'Before the next offer, write down what it costs in margin and what you expect back. Then decide.' },
  { text: 'Your reviews describe your rota three weeks ago.', why: 'Read your last ten reviews next to the rota for those days. The pattern is usually obvious.' },
  { text: 'It is not the strongest who survive, but the ones most responsive to change.', author: 'Leon Megginson', why: 'Name one thing your spa does because it has always done it, and test the alternative for a month.' },
  { text: 'A therapist who has not been trained this year is a therapist somebody else is training.', why: 'Check who on your team has had nothing new in twelve months, and fix that one first.' },
  { text: 'The guest does not know what a good facial costs to deliver. They know exactly what one feels like.', why: 'Stop justifying your price with ingredients and start justifying it with time, skill and consultation.' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', author: 'Will Durant', why: 'Choose one standard and audit it every day for a fortnight. Habits are built by boring repetition.' },
  { text: 'Every spa says it is about wellbeing. Look at the staff room and decide whether you believe it.', why: 'Spend an hour in your own staff room. Whatever you would not accept for a guest, fix.' },
  { text: 'Hiring for attitude is not a soft option. It is the hardest interview to run well.', why: 'Write two questions that reveal how a candidate behaves under pressure, and ask them of everybody.' },
  { text: 'You can teach a treatment in three days. You cannot teach somebody to notice.', why: 'In your next interview, ask what the candidate noticed on the way in. The answer tells you a lot.' },
  { text: 'Design is not just what it looks like. Design is how it works.', author: 'Steve Jobs', why: 'Ask a therapist what she would move in the treatment room. She has wanted to say for months.' },
  { text: 'A twenty-minute turnaround is not a standard, it is a countdown, and your guest can hear it.', why: 'Add five minutes to the turnaround for one week and measure what happens to your reviews.' },
  { text: 'The spa director who reads the P&L is the one who gets to protect the treatment time.', why: 'If you cannot read yours confidently, ask finance to walk you through one line a week.' },
  { text: 'People will forget what you said, but they will never forget how you made them feel.', author: 'Maya Angelou', why: 'This applies to your team as much as your guests. Notice who has not been thanked this month.' },
  { text: 'A brand is what your team says about you on their day off.', why: 'Ask a recent leaver, honestly, what she tells people about working here.' },
  { text: 'Retail is not selling. It is finishing the treatment properly.', why: 'Retrain aftercare as the last two minutes of the treatment, in the room, not at the till.' },
  { text: 'The standard you walk past is the standard you accept.', author: 'David Morrison', why: 'Deal with the thing you have walked past three times this week. Today.' },
  { text: 'If the only way to hit the target is to shorten the massage, the target is wrong.', why: 'Take the number back to whoever set it with the arithmetic of what it actually requires.' },
  { text: 'Your best therapist is being recruited right now, by somebody who remembered her name.', why: 'Have the conversation about her next twelve months before somebody else does.' },
  { text: 'Experience is not the number of years. It is the number of things you would now do differently.', why: 'Write down three things you would do differently from your last role. That is your real CV.' },
  { text: 'It is not enough to be busy. The question is: what are we busy about?', author: 'Henry David Thoreau', why: 'List what took your week. Cross off anything that did not improve a guest hour or a team member.' },
  { text: 'Consistency beats brilliance. A spa that is very good every single day will outlast one that is occasionally extraordinary.', why: 'Find your most variable treatment and make it the same every time before adding anything new.' },
  { text: 'The pre-opening decisions you rush are the operating problems you inherit for a decade.', why: 'If you are pre-opening, slow down on storage, staffing ratios and back of house. Those are the permanent ones.' },
  { text: 'Guests do not compare you to the spa down the road. They compare you to the best hour they have had this year.', why: 'Stop benchmarking locally. Go and experience something excellent outside the industry.' },
  { text: 'Whether you think you can or think you cannot, you are right.', author: 'Henry Ford', why: 'Apply for the thing you have decided you are not ready for. You are closer than you think.' },
  { text: 'Write the job description for the person you want, not the person who left.', why: 'Before you repost the role, ask what the department actually needs now. It is rarely the same job.' },
  { text: 'A quiet Tuesday is a training day, a deep-clean day, or a wasted day. It is never nothing.', why: 'Put something in the diary for your quietest day next week before it fills with nothing.' },
  { text: 'The manager who cannot take a holiday has not built a department, she has built a dependency.', why: 'Pick one decision only you make, and teach somebody else to make it this month.' },
  { text: 'Consultation is not paperwork. It is the only part of the treatment where you find out what they actually need.', why: 'Sit in on one consultation this week. It will tell you more than any mystery shop.' },
  { text: 'Do not judge each day by the harvest you reap, but by the seeds that you plant.', author: 'Robert Louis Stevenson', why: 'Training, a conversation, a standard fixed. None of them show up today and all of them show up in March.' },
  { text: 'The word just does more damage in a spa than any complaint. Just a therapist. Just reception. Just a facial.', why: 'Listen for it in your own sentences this week and stop using it.' },
  { text: 'Your treatment menu should be short enough that every person on your team can deliver all of it brilliantly.', why: 'Count how many of your treatments every therapist can deliver to standard. That number is your real menu.' },
  { text: 'Nobody leaves a job. They leave a rota, a manager, or a ceiling.', why: 'Work out which of the three it was last time somebody left. Then fix that one.' },
  { text: 'The first person a guest speaks to decides what the next two hours feel like. Pay accordingly.', why: 'Look at reception\'s pay, training and turnover as a commercial decision, because it is one.' },
  { text: 'What you tolerate on a Monday is what a guest writes about on Friday.', why: 'Deal with the small thing now. It does not stay small.' },
  { text: 'You do not have a recruitment problem. You have a reputation among therapists, and you can find out what it is by asking one.', why: 'Ask a therapist who turned you down why. It is the cheapest market research available.' },
  { text: 'A guest who has to explain their allergy twice has already decided how organised you are.', why: 'Check that what reception records actually reaches the treatment room. Usually it does not.' },
  { text: 'Take care of your employees and they will take care of your business.', author: 'Richard Branson', why: 'Fix one thing about the working day this week. Breaks, uniform, the broken chair in the staff room.' },
  { text: 'Being good at your job and being able to describe it are two different skills, and only one of them gets you the interview.', why: 'Write three sentences about what changed because you were there. That is your headline.' },
  { text: 'The best career move in this industry is usually the one that looks sideways.', why: 'Consider the smaller property with the better mentor over the bigger title somewhere indifferent.' },
  { text: 'Uniform, lighting, music, scent. Four decisions, made once, felt by every guest for years.', why: 'Review all four this quarter. They are almost certainly inherited rather than chosen.' },
  { text: 'Ask your team what they would change if it were their spa. Then read your own face while they answer.', why: 'Ask it this week. Write the answers down without defending anything.' },
  { text: 'Growth is never by mere chance. It is the result of forces working together.', author: 'James Cash Penney', why: 'Line up training, rota and target so they pull the same way. Most spas have all three fighting.' },
  { text: 'An empty column in a rota is not a gap in staffing. It is a decision about who is going to be exhausted.', why: 'Name who covers your gaps. That person is the one you are most likely to lose.' },
  { text: 'The spa industry does not have a skills shortage. It has a retention problem it keeps describing as a skills shortage.', why: 'Before you post the vacancy, work out why the last three people left.' },
  { text: 'A spa is judged on its worst hour, not its best one.', why: 'Find your worst hour of the week and staff it properly. It is doing more damage than your best hour is doing good.' },
  { text: 'The lightbulb nobody replaced is telling your guest more than your brochure is.', why: 'Walk the guest route tonight with the lights on and a notepad.' },
  { text: 'Standards do not slip. They are lowered, one small permission at a time.', why: 'Notice the permission you gave last week because you were tired. Take it back.' },
  { text: 'If it is only right when the manager is in, it is not a standard, it is a performance.', why: 'Ask somebody to audit a day you are not there, and to be honest about it.' },
  { text: 'Check the guest loo at four o\'clock on a Saturday. That is your actual standard.', why: 'Set a recurring reminder for the busiest hour, not the quietest.' },
  { text: 'A robe that does not fit undoes eight hundred pounds of stonework.', why: 'Count your robe sizes against your actual guests. Most spas stock for a body type they do not have.' },
  { text: 'Nobody has ever complained about a spa being too quiet.', why: 'Find the loudest thing in your relaxation area and remove it this week.' },
  { text: 'The smell of a spa at seven in the morning tells you everything about how it closed.', why: 'Change the closing checklist, not the morning one.' },
  { text: 'Consistency is a system. Brilliance is a person, and people have days off.', why: 'Write down what your best therapist does that others do not, and teach it.' },
  { text: 'You cannot inspect your way to quality. You can only recruit and train your way there.', why: 'If you are auditing more than training, you have the ratio the wrong way round.' },
  { text: 'Write the standard down or it is an opinion, and opinions lose arguments at eight on a Sunday.', why: 'Document the one standard you argue about most. Today.' },
  { text: 'A checklist nobody has changed in two years is a checklist nobody is reading.', why: 'Ask the team to rewrite one checklist. They will delete the dead lines you cannot see.' },
  { text: 'The gap between your treatment protocol and what actually happens in the room is your real brand.', why: 'Have one treatment delivered to you exactly as written, then as usually done. Compare.' },
  { text: 'Fix the thing that annoys the team before the thing that annoys you.', why: 'Ask for the top three irritations and clear one before the end of the week.' },
  { text: 'An immaculate reception and a chaotic back corridor is a spa that cares how it looks, not how it works.', why: 'Spend your next hour of tidying behind the door, not in front of it.' },
  { text: 'If your therapists are hiding the broken trolley, you have a culture problem, not an equipment problem.', why: 'Make reporting a fault the easiest thing in the building to do.' },
  { text: 'Small things done properly are what people mean when they say a place feels expensive.', why: 'Choose one small thing this month and make it flawless before adding anything.' },
  { text: 'Every spa has a smell, a sound and a temperature. Most have chosen none of the three.', why: 'Choose all three deliberately this quarter and write them into the standards.' },
  { text: 'You will be forgiven for being fully booked. You will not be forgiven for being unprepared.', why: 'Prepare tomorrow tonight. It costs fifteen minutes and saves the morning.' },
  { text: 'The best-run spas are quiet. Noise is usually the sound of something not working.', why: 'Listen to your spa for ten minutes. Every raised voice is a process to fix.' },
  { text: 'Exit interviews are too late. The conversation you needed was four months ago.', why: 'Put a proper twenty-minute conversation in the diary with everybody, quarterly.' },
  { text: 'Nobody hands in their notice on the day they decide to leave.', why: 'Notice who has stopped suggesting things. That is the signal, months early.' },
  { text: 'A rota published on Friday for a Monday is a message about how much you value somebody\'s life.', why: 'Move to three weeks ahead. It changes recruitment more than a pay rise would.' },
  { text: 'Your team can forgive a hard week. They cannot forgive an unnecessary one.', why: 'Before you ask for the extra push, be certain it was unavoidable, and say so if it was not.' },
  { text: 'Pay is why people apply. Management is why they stay or go.', why: 'If you cannot move pay, move everything else you control this quarter.' },
  { text: 'The therapist covering everybody else\'s shifts is the one closest to leaving.', why: 'Look at who has covered most in the last eight weeks and give them something back.' },
  { text: 'Ask who has not had a day off with their family this month, then look at the rota again.', why: 'Rotate the unpopular shifts properly. Fairness is visible and so is its absence.' },
  { text: 'A leaver who recommends you is worth more than three who stayed and warn people off.', why: 'Run the last week of somebody\'s notice as well as their first week.' },
  { text: 'Loyalty is not owed to you. It is earned every quarter by somebody, and usually not by the person who thinks they are owed it.', why: 'Ask yourself what you have done this quarter that earned it.' },
  { text: 'If you cannot name what each of your team wants next year, you are not managing them, you are scheduling them.', why: 'Write the list from memory. The blanks are your next five conversations.' },
  { text: 'Two people leaving in a month is a coincidence. Three is a report on you.', why: 'Get somebody outside your department to ask them why. They will not tell you.' },
  { text: 'Overtime is a loan against next month\'s sickness.', why: 'Track overtime against absence for a quarter. The correlation will end the argument.' },
  { text: 'The quiet one on your team is not disengaged. She is deciding.', why: 'Ask her a question that cannot be answered with fine.' },
  { text: 'Somebody on your team is doing a job two grades above her title. She knows, and so does the spa down the road.', why: 'Fix the title and the pay before the market does it for you.' },
  { text: 'Praise in the moment costs nothing and outlasts a bonus.', why: 'Say the specific thing, not well done. Specific praise is the only kind that teaches.' },
  { text: 'A therapist\'s first six weeks decide the next six years.', why: 'Write a proper six-week induction. Most spas have three days and a folder.' },
  { text: 'Handover is where care goes to die. Ten minutes of it is worth an hour of training.', why: 'Make handover a fixed, protected ten minutes rather than a conversation in a corridor.' },
  { text: 'Do not promote your best therapist unless she wants to manage. You will lose two people.', why: 'Create a senior clinical route that pays, so progression does not require leaving the room.' },
  { text: 'The rota is the single most important document in the building and it is usually written last.', why: 'Give it your best hour of the week, not your last one.' },
  { text: 'A team meeting where only one person talks is a briefing, and briefings do not change anything.', why: 'Ask one question and then stay quiet for longer than is comfortable.' },
  { text: 'Cover is not free. Somebody always pays, usually the person who never says no.', why: 'Track who absorbs the gaps. Then either pay for it or stop needing it.' },
  { text: 'If your team only tells you good news, that is the most worrying news you have.', why: 'Reward the person who brings you a problem early, visibly, so others see it.' },
  { text: 'Retention is cheaper than recruitment and nobody puts it in the budget.', why: 'Cost your last vacancy properly, including lost treatment hours. Then spend a tenth of it on keeping people.' },
  { text: 'The people who make your spa work are rarely the ones who tell you they do.', why: 'Look at who everybody asks when something goes wrong. Thank her properly.' },
  { text: 'A guest who has to ask where the loos are has already stopped relaxing.', why: 'Walk in as a first-time guest and count the moments you had to work something out.' },
  { text: 'The best moment in a spa day is often the arrival, and most places treat it as admin.', why: 'Redesign the first five minutes. Everything after it gets easier.' },
  { text: 'Nobody arrives at a spa in a neutral mood. Find out which one and adjust.', why: 'Train one question into the arrival that reveals it, and act on the answer.' },
  { text: 'An apology delivered properly buys more loyalty than a discount.', why: 'Teach the team to apologise without offering money. The money is a habit, not a solution.' },
  { text: 'Guests do not want to be surprised. They want to be understood.', why: 'Spend the effort on remembering rather than on theatre.' },
  { text: 'A treatment that ends abruptly undoes fifty-five minutes of good work in thirty seconds.', why: 'Protect the last three minutes of every treatment in the schedule.' },
  { text: 'The guest is not always right. The guest is always the reason you are open.', why: 'Give the team permission to disagree politely, and back them when they do.' },
  { text: 'Personalisation is not using their name. It is remembering what they said last time.', why: 'Use the notes field properly, and check that the next therapist reads it.' },
  { text: 'A silent therapist is either wonderful or terrible, and the consultation is how you find out which the guest wants.', why: 'Add one line to the consultation asking how much conversation they would like.' },
  { text: 'The follow-up email is part of the treatment, and almost nobody writes it.', why: 'Send one this week to your last ten guests. Watch what it does to rebooking.' },
  { text: 'Aftercare given in the room is service. Aftercare given at the till is selling.', why: 'Move the conversation forward by ten minutes and stop calling it retail.' },
  { text: 'A guest will forgive a delay explained and resent a delay ignored.', why: 'Tell them at five minutes, not at fifteen.' },
  { text: 'Peace and quiet is a product, and most spas give it away in the changing rooms.', why: 'Fix the changing rooms. They are the least loved and most used space you have.' },
  { text: 'You cannot relax somebody who is worried about the time.', why: 'Tell the guest exactly what happens next and when. Certainty is relaxing.' },
  { text: 'The reason people book a spa is rarely the reason they come back.', why: 'Ask ten regulars why they return. The answer will not be on your website.' },
  { text: 'Complaints are unpaid consultancy from somebody who wanted you to be better.', why: 'Read your last five complaints looking for the process, not the person.' },
  { text: 'The first ninety seconds decide what the guest thinks of the next ninety minutes.', why: 'Rehearse the greeting like you would rehearse a treatment.' },
  { text: 'Nobody remembers a good product. They remember good hands.', why: 'Invest in technique training before your next product launch.' },
  { text: 'If the therapist is rushing, the guest is not relaxing, whatever the room looks like.', why: 'Fix the schedule before you spend anything on the interior.' },
  { text: 'A regular is somebody who was treated properly on a day when it would have been easy not to.', why: 'Watch how your team behaves in the last hour of a hard day. That is where regulars are made.' },
  { text: 'Retail is not an add-on. It is the only part of a spa with no ceiling on capacity.', why: 'You cannot add treatment hours without building rooms. You can always sell better.' },
  { text: 'A therapist who believes in the product sells it without noticing. Everybody else is doing a script.', why: 'Give the team the products to use at home. Belief is cheaper than training.' },
  { text: 'You do not have a retail problem. You have a consultation problem.', why: 'Listen to three consultations. The recommendation should be obvious by the end of them.' },
  { text: 'Utilisation without yield is just tiredness.', why: 'Look at your busiest therapist\'s revenue per hour, not her bookings.' },
  { text: 'Know your cost per treatment hour or you are guessing every time you set a price.', why: 'Work it out this week: wages, products, laundry, room. Everything after that is a decision.' },
  { text: 'A twenty per cent discount is a hundred per cent of somebody\'s margin in most spa businesses.', why: 'Do the arithmetic before the offer, not after the month.' },
  { text: 'Memberships are wonderful until the day they are the only thing keeping you open.', why: 'Check what share of revenue is membership. Above half is a risk, not a success.' },
  { text: 'The most profitable hour in a spa is usually the one nobody is trying to fill.', why: 'Look at your midweek mornings. There is a market there nobody has named.' },
  { text: 'Price is a positioning decision made by people who mostly think it is a maths decision.', why: 'Decide who you are for first. The number follows.' },
  { text: 'If you cannot say why you are more expensive, you are not, you are just dearer.', why: 'Write one sentence justifying your price. If it is generic, so is your spa.' },
  { text: 'Every free upgrade teaches a guest what your treatment is really worth.', why: 'Replace upgrades with something that costs you nothing and signals care.' },
  { text: 'The retail display nobody has touched in three weeks is telling you something.', why: 'Move it, cut it, or stop stocking it.' },
  { text: 'Budgets are written in October and lived in February.', why: 'Build in the training and the cover now, or they will be the first things cut.' },
  { text: 'A spa that hits its number by cutting training is borrowing from next year at a terrible rate.', why: 'Ringfence the training line before you agree the budget.' },
  { text: 'Occupancy is vanity. Revenue per available treatment hour is the number that pays wages.', why: 'Change the number on the weekly report and watch what the team optimises for.' },
  { text: 'Selling a course of six is a clinical decision or a commercial one, and the guest can tell which.', why: 'Only sell courses where the protocol genuinely requires them.' },
  { text: 'Commission schemes get you exactly the behaviour you designed, including the parts you did not intend.', why: 'Read your scheme as though you were trying to game it. Somebody already has.' },
  { text: 'A treatment menu with forty items has no bestsellers, only confusion.', why: 'Cut to the treatments you would be proud to be known for.' },
  { text: 'Your quietest month is your training budget, your deep clean and your planning. Spend it deliberately.', why: 'Plan January in November, or January will plan itself badly.' },
  { text: 'Nobody ever grew a spa business by being slightly cheaper than the one next door.', why: 'Compete on something they cannot copy by Friday.' },
  { text: 'Managing is mostly noticing.', why: 'Walk the floor with no agenda for twenty minutes. You will find three things.' },
  { text: 'You set the tone within four minutes of walking through the door, whether you meant to or not.', why: 'Decide what you want the first four minutes to feel like before you arrive.' },
  { text: 'The manager who does everything herself has trained her team to let her.', why: 'Hand over one recurring task permanently this month, with the authority attached.' },
  { text: 'Delegating is not giving somebody a task. It is giving them the decision.', why: 'Next time, give the outcome and the budget rather than the instructions.' },
  { text: 'The best thing a spa director can protect is treatment time. Everything else is negotiable.', why: 'When the pressure comes, cut anything before you cut the minutes in the room.' },
  { text: 'If your team is afraid to tell you something is broken, you will find out from a review.', why: 'Respond to the next piece of bad news with thank you before anything else.' },
  { text: 'A one-to-one that only happens when something is wrong is a disciplinary, not a one-to-one.', why: 'Book them monthly and keep them even when everything is fine.' },
  { text: 'Leadership is deciding what you will not compromise, and then not compromising it on a bad Tuesday.', why: 'Write down your three non-negotiables and tell the team what they are.' },
  { text: 'Your job is to make yourself unnecessary in the room and indispensable to the business.', why: 'Spend an hour this week on something only you can do, and delegate the rest.' },
  { text: 'You cannot delegate the culture. You are the culture, on your worst day especially.', why: 'Notice how you behave when you are tired. That is what the team copies.' },
  { text: 'Every process you add is a tax on the people delivering treatments. Charge it only where it earns.', why: 'Remove one form this month before you add another.' },
  { text: 'The most expensive meeting in a spa is the one that could have been a note on the rota.', why: 'Cancel one recurring meeting and see whether anybody misses it.' },
  { text: 'Hire slowly for the role that sets the standard. Everything downstream is easier.', why: 'Do not fill the senior role with the available person. Wait.' },
  { text: 'A manager who has never done the job on the floor will always be managing a version of it that does not exist.', why: 'Work a full shift on the floor this quarter, properly, not as a visit.' },
  { text: 'Feedback delayed is feedback wasted, and by the following week it is just a grievance.', why: 'Say it the same day, quietly, and in one sentence.' },
  { text: 'You will be remembered for how you handled the difficult week, not the good year.', why: 'Decide now how you want to behave when it goes wrong, because you will not decide well then.' },
  { text: 'Give somebody the reason and they will handle the exception. Give them only the rule and they will not.', why: 'Explain why the standard exists every time you teach it.' },
  { text: 'If you are the only person who can solve it, you have not solved it.', why: 'Write down how you did it and give it to somebody else next time.' },
  { text: 'The strongest managers in this industry are the ones who make fewer decisions, better.', why: 'Push three decisions down this week and defend the people who make them differently to you.' },
  { text: 'Nobody was ever inspired by a spreadsheet, and nobody was ever saved by ignoring one.', why: 'Bring both to the team meeting: the number and the reason it matters to them.' },
  { text: 'Protect your team from the noise above them. That is most of the job.', why: 'Filter, do not forward. Not every message from above needs a team meeting.' },
  { text: 'An underperformer everybody can see and nobody addresses costs you your best people.', why: 'Have the conversation this week. Your good people are watching whether you will.' },
  { text: 'The gap between where you are and where you want to be is usually one uncomfortable conversation.', why: 'Identify it, and have it before the end of the month.' },
  { text: 'Apply for the role you are eighty per cent ready for. Nobody is ever a hundred.', why: 'Send the application you have been drafting. Today.' },
  { text: 'Your CV is not a list of duties. It is evidence of judgement.', why: 'Replace one responsibility line with what changed because you were there.' },
  { text: 'Nobody is going to notice your work on your behalf.', why: 'Tell your manager one specific thing you did well this month. That is not boasting, it is reporting.' },
  { text: 'A sideways move into a better spa beats a promotion into a worse one.', why: 'Ask who you would be learning from, not what the title says.' },
  { text: 'Being indispensable where you are is how careers stall.', why: 'Train your replacement. It is the only way you get to move.' },
  { text: 'You are not behind. You are on a different rota to somebody you have decided to compare yourself with.', why: 'Write your own next step down and stop measuring against somebody else\'s.' },
  { text: 'The skill that will get you your next job is not the one you use most today.', why: 'Look at three job adverts a level above you and learn what they all ask for.' },
  { text: 'Say what you want out loud to somebody who can do something about it.', why: 'Most people never do. It is the single highest-return thing in a career.' },
  { text: 'Train in the thing your spa does not do yet.', why: 'Pick the treatment or system the market is moving towards and learn it first.' },
  { text: 'You learn the most in the six months after something has gone badly wrong.', why: 'Write down what you would do differently while it is still uncomfortable.' },
  { text: 'An interview is not an examination. It is two people finding out whether this would work.', why: 'Prepare three questions of your own. The ones you ask say more than the ones you answer.' },
  { text: 'The question you dread in an interview is the one worth preparing properly.', why: 'Write the honest answer down, out loud, twice. It stops being frightening.' },
  { text: 'Ask what happened to the last person in the role. Listen to how they answer, not just what they say.', why: 'A pause before that answer tells you more than the answer does.' },
  { text: 'A job that will not let you learn is a job that is quietly ending your career.', why: 'If nothing has been new for a year, that is your notice period starting.' },
  { text: 'Your reputation in this industry arrives before your CV does.', why: 'How you leave matters more than how you arrive. Work the notice period properly.' },
  { text: 'The therapist who reads the numbers becomes the manager who protects the treatment.', why: 'Ask to see the department\'s figures. Interest is usually rewarded with access.' },
  { text: 'Nobody remembers who was busy. They remember who was good.', why: 'Do one thing properly today instead of six things adequately.' },
  { text: 'Confidence is what you have after the thing you were dreading has been survived.', why: 'Do the dreaded thing first, before nine, while you have not talked yourself out of it.' },
  { text: 'You do not need permission to be excellent at something.', why: 'Start the training, the reading or the practice this week without asking.' },
  { text: 'Take the training. It outlasts every job you will ever have.', why: 'Say yes to the course even if you are leaving. Especially if you are leaving.' },
  { text: 'A treatment learned once and never revisited becomes a habit, and habits drift.', why: 'Reassess one treatment per therapist per quarter. Drift is invisible until a guest names it.' },
  { text: 'Watch your best therapist work for an hour. You will learn more than from any course.', why: 'Book it in. Observation is the cheapest development you have.' },
  { text: 'Training is not an event. It is the difference between five years of experience and one year five times.', why: 'Put something small in every month rather than one big day a year.' },
  { text: 'The manufacturer\'s protocol exists because somebody tested it. Improve it deliberately, not accidentally.', why: 'Find where your team has drifted from protocol and decide whether to fix it or adopt it.' },
  { text: 'Nobody improves without being watched by somebody who knows what they are looking at.', why: 'Set up peer observation. It costs nothing and works better than a course.' },
  { text: 'The therapist teaching somebody else learns twice.', why: 'Give your strongest people something to teach, and time to prepare it.' },
  { text: 'Practise the consultation, not just the treatment. That is where the skill actually shows.', why: 'Role-play a difficult consultation at the next team meeting.' },
  { text: 'Pressure is a conversation, not a setting.', why: 'Train the team to check twice and to describe rather than ask deeper or lighter.' },
  { text: 'If your induction is a folder, your standards are a folder.', why: 'Replace the folder with a person and a plan for the first six weeks.' },
  { text: 'Cross-training is not a cost. It is what lets you take a holiday.', why: 'Map who can cover what. The blanks are your risk register.' },
  { text: 'The best development in this industry is being sent somewhere better to watch how they do it.', why: 'Send one person somewhere excellent this quarter and make them report back.' },
  { text: 'You cannot deliver a treatment well that you do not understand the purpose of.', why: 'Ask each therapist why a treatment works. The gaps will surprise you.' },
  { text: 'Contraindications are not paperwork. They are the reason the guest trusts you with their body.', why: 'Refresh contraindication training this year, properly, not as a signature exercise.' },
  { text: 'A therapist who cannot explain what the product does is a therapist who cannot sell it or defend the price.', why: 'Ten minutes of product knowledge per week beats one launch day a year.' },
  { text: 'Skill fades quietly. Book the refresher before somebody notices.', why: 'Put refreshers in the calendar the same way you put in the deep clean.' },
  { text: 'Every pre-opening decision you rush becomes an operating cost for a decade.', why: 'Spend the extra fortnight now. It is cheaper than ten years of workaround.' },
  { text: 'The concept is easy. The rota that delivers it is the actual design work.', why: 'Build the staffing model before you sign off the treatment menu.' },
  { text: 'A spa designed without a therapist in the room will be operated by therapists forever.', why: 'Get a working therapist into the design meeting, and pay her for the time.' },
  { text: 'Storage. Nobody ever regrets more of it, and everybody forgets it at drawings stage.', why: 'Double whatever the drawing shows. You will still want more.' },
  { text: 'Design the back of house as carefully as the front. Guests feel the difference without seeing it.', why: 'A good staff area shows up in the treatment before it shows up in the reviews.' },
  { text: 'A brand is a promise that has to be keepable on a Tuesday in February with two people off sick.', why: 'Test the promise against your worst realistic day before you print it.' },
  { text: 'Copying a spa you admire gives you their answers to their problems.', why: 'Understand why they made the choice before you make the same one.' },
  { text: 'Do fewer things. Do them so well that people travel for them.', why: 'Name the one thing you want to be known for and resource it properly.' },
  { text: 'The treatment menu should be written after the team is hired, not before.', why: 'Build the menu around who you have, then train towards who you want.' },
  { text: 'A signature treatment nobody can deliver consistently is a marketing liability.', why: 'Only launch what every therapist can do to the same standard.' },
  { text: 'Opening late with the right team beats opening on time with the wrong one, and nobody believes that in advance.', why: 'Hold the date if the people are not right. Everybody forgets the delay and remembers the first month.' },
  { text: 'The spa that knows exactly who it is for will always beat the one trying not to exclude anybody.', why: 'Write down who you are not for. It is more useful than who you are.' },
  { text: 'Positioning is what you say no to.', why: 'List three things you will not do. That is your position.' },
  { text: 'Wellness is not a category any more. It is a standard, and standards are table stakes.', why: 'Stop using wellness as a differentiator and find a real one.' },
  { text: 'If your differentiator can be bought by the spa down the road next month, it is not one.', why: 'People, training and consistency cannot be bought. Equipment can.' },
  { text: 'This industry pays its most skilled people its lowest wages and then asks why they leave.', why: 'Benchmark your therapist pay against nursing and hospitality management, not against other spas.' },
  { text: 'We are very good at talking about wellbeing and very bad at rotas.', why: 'Audit the rota against what you say publicly about wellbeing.' },
  { text: 'Spa is the only department in a hotel expected to be a profit centre and treated as an amenity.', why: 'Take the P&L to the general manager and ask which of the two it is.' },
  { text: 'The person who cleans your treatment rooms protects your reputation more than your marketing does.', why: 'Pay, train and thank accordingly.' },
  { text: 'Every year the industry says it cannot find good therapists. Every year good therapists leave it.', why: 'Ask a therapist who left the industry why. It is a better use of an hour than a job advert.' },
  { text: 'A career in spa should not require leaving spa to progress.', why: 'Build a route above senior therapist that does not mean giving up the room.' },
  { text: 'If the general manager has never had a treatment in your spa, that is your project for this month.', why: 'Book them in. Everything about the conversation changes afterwards.' },
  { text: 'We measure occupancy hourly and development annually, and then wonder about retention.', why: 'Put one development measure on the weekly report.' },
  { text: 'Qualifications are the floor, not the ceiling, and too much of the industry stops at the floor.', why: 'Ask what each of your team has learned since qualifying. Then fix the blanks.' },
  { text: 'Nobody trains spa managers to read a P&L, and then we call them uncommercial.', why: 'Teach it. An afternoon changes how somebody argues for their department forever.' },
  { text: 'Freelance is not a lesser career. For many of the best people it is the only one that respects their time.', why: 'Build a freelance pool properly rather than treating it as a last resort.' },
  { text: 'A hotel that treats spa as a cost centre has already decided how good it will be.', why: 'Change the conversation with numbers, not with feeling.' },
  { text: 'The word therapist covers three years of training and everybody uses it like it means one thing.', why: 'Be specific in adverts and in conversation. Precision is respect.' },
  { text: 'Guests will pay for expertise. Someone has to be willing to charge for it.', why: 'Price your most skilled treatment as though the skill mattered, because it does.' },
  { text: 'An industry that does not pay for training gets the therapists it has trained by accident.', why: 'Budget training as a fixed cost, not a discretionary one.' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela', why: 'The thing you have been putting off for a month will take an afternoon.' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney', why: 'Take the smallest possible first step today rather than planning the whole thing.' },
  { text: 'Success is the sum of small efforts repeated day in and day out.', author: 'Robert Collier', why: 'Choose the one small thing you will do every day this month and do only that.' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin', why: 'Show the team the standard by doing it once yourself, properly, where they can see.' },
  { text: 'Excellence is to do a common thing in an uncommon way.', author: 'Booker T. Washington', why: 'Take your most ordinary treatment and make it the best in the county.' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', why: 'If you no longer do, that is information about the job, not about you.' },
  { text: 'Culture eats strategy for breakfast.', author: 'Peter Drucker', why: 'The best strategy on paper will lose to how your team actually behaves at four on a Saturday.' },
  { text: 'What gets measured gets managed.', author: 'Peter Drucker', why: 'Be careful what you put on the weekly report. It is what the team will optimise for.' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker', why: 'Decide what your department looks like in two years and start one part of it this week.' },
  { text: 'If you do not know where you are going, any road will get you there.', author: 'Lewis Carroll', why: 'Write the one-year plan on a single page and give it to the team.' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb', why: 'The application that was rejected is data, not a verdict. Send the next one.' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupery', why: 'Put a date and a name against each thing you said you would do this quarter.' },
  { text: 'Not everything that can be counted counts, and not everything that counts can be counted.', author: 'William Bruce Cameron', why: 'Your best therapist\'s effect on the team will never appear in a report. Value it anyway.' },
  { text: 'Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen.', author: 'Winston Churchill', why: 'In your next difficult conversation, plan to speak second.' },
  { text: 'However beautiful the strategy, you should occasionally look at the results.', author: 'Winston Churchill', why: 'Check whether last quarter\'s initiative actually changed a number. Most do not.' },
  { text: 'Management is doing things right. Leadership is doing the right things.', author: 'Peter Drucker', why: 'Ask whether the thing consuming your week is the right thing before you do it better.' },
  { text: 'First say to yourself what you would be, and then do what you have to do.', author: 'Epictetus', why: 'Decide what kind of manager you are trying to be, then check today\'s behaviour against it.' },
  { text: 'Try not to become a person of success, but rather try to become a person of value.', author: 'Albert Einstein', why: 'Be the person others in the industry ring for advice. The rest follows.' },
  { text: 'The two most powerful warriors are patience and time.', author: 'Leo Tolstoy', why: 'The change you are trying to force this month will happen on its own by June if you keep going.' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin', why: 'The course you cannot quite justify is almost always the one worth booking.' },
  { text: 'Without craftsmanship, inspiration is a mere reed shaken in the wind.', author: 'Johannes Brahms', why: 'The concept is worth nothing until somebody can deliver it twelve times a day.' },
  { text: 'It is not the load that breaks you down, it is the way you carry it.', author: 'Lena Horne', why: 'Ask for help before the week you actually need it.' },
  { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African proverb', why: 'The shortcut you take without the team is the one you will be undoing in March.' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln', why: 'There is no small job in a spa. There are jobs done well and jobs done badly.' },
  { text: 'A ship in harbour is safe, but that is not what ships are built for.', author: 'John A. Shedd', why: 'The comfortable role you have outgrown is costing you more than a risky one would.' },
  { text: 'Vision without execution is hallucination.', author: 'Thomas Edison', why: 'Pick the one part of the plan you can start on Monday and start on Monday.' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou', why: 'The system will not fix the standard. Somebody has to hold it, and that is you.' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes', why: 'Be visibly bad at something new this year. Your team needs to see you do it.' },
  { text: 'Efficiency is doing things right. Effectiveness is doing the right things.', author: 'Peter Drucker', why: 'Before you streamline the process, check whether it should exist.' },
  { text: 'Character is doing the right thing when nobody is looking.', author: 'J. C. Watts', why: 'The standard you keep on the quiet Tuesday is the only one that is real.' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh', why: 'One fixed detail a week is fifty-two by this time next year.' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi', why: 'Ship the improvement at ninety per cent rather than waiting for the version that never comes.' },
  { text: 'You cannot go back and change the beginning, but you can start where you are and change the ending.', author: 'C. S. Lewis', why: 'The department you inherited is not your fault. What it looks like in a year is.' },
  { text: 'Do the hard jobs first. The easy jobs will take care of themselves.', author: 'Dale Carnegie', why: 'Put the difficult conversation before nine, while you still have the nerve.' },
  { text: 'Alone we can do so little, together we can do so much.', author: 'Helen Keller', why: 'The problem you have been carrying alone probably has an answer in your own team.' },
  { text: 'Continuous improvement is better than delayed perfection.', author: 'Mark Twain', why: 'Change one thing this week rather than redesigning everything next quarter.' },
  { text: 'The greatest danger in times of turbulence is not the turbulence, it is to act with yesterday\'s logic.', author: 'Peter Drucker', why: 'The rota, the menu and the pricing that worked in 2019 are not neutral choices now.' },
  { text: 'Knowing is not enough, we must apply. Willing is not enough, we must do.', author: 'Johann Wolfgang von Goethe', why: 'You already know what the problem is. This week, do one thing about it.' },
  { text: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.', author: 'Abraham Lincoln', why: 'Time spent on the rota and the induction is not time away from the work. It is the work.' },
  { text: 'An organisation\'s ability to learn is the ultimate competitive advantage.', author: 'Jack Welch', why: 'Whatever went wrong last month, make sure somebody wrote down what you learned.' },
  { text: 'Simplicity is the soul of efficiency.', author: 'Austin Freeman', why: 'The form with fourteen fields is why nobody fills it in.' },
  { text: 'You cannot manage what you do not understand.', author: 'W. Edwards Deming', why: 'Spend a shift doing the job you are about to change.' },
  { text: 'Quality is everyone\'s responsibility.', author: 'W. Edwards Deming', why: 'Ask each person to name the one standard they own personally.' },
  { text: 'The customer\'s perception is your reality.', author: 'Kate Zabriskie', why: 'It does not matter that the delay was unavoidable. It matters that nobody explained it.' },
  { text: 'Details create the big picture.', author: 'Sanford I. Weill', why: 'The towel, the temperature and the timing are not small. They are the whole thing.' },
  { text: 'There is no substitute for hard work.', author: 'Thomas Edison', why: 'Nobody in this industry got good by accident, and everybody good is still practising.' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn', why: 'Choose the habit that would make the biggest difference and protect it for thirty days.' },
  { text: 'The strength of the team is each individual member.', author: 'Phil Jackson', why: 'Work out what each person is best at and build the rota around it.' },
  { text: 'Feedback is the breakfast of champions.', author: 'Ken Blanchard', why: 'Ask one person today what you could do better as their manager, and then be quiet.' },
  { text: 'Hire character. Train skill.', author: 'Peter Schutz', why: 'The technique is teachable in weeks. Kindness under pressure is not.' },
  { text: 'A leader is one who knows the way, goes the way and shows the way.', author: 'John C. Maxwell', why: 'Do the thing you are asking for, once, visibly, before you ask again.' },
  { text: 'Time is the scarcest resource, and unless it is managed nothing else can be managed.', author: 'Peter Drucker', why: 'Protect two hours a week for the work that is not urgent. Nobody else will protect it for you.' },
  { text: 'However difficult life may seem, there is always something you can do and succeed at.', author: 'Stephen Hawking', why: 'On the worst week, choose the one thing you can finish and finish it.' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese proverb', why: 'Start the training, the pipeline or the succession plan this month.' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein', why: 'Give somebody on your team room to get one thing wrong this quarter.' },
  { text: 'The single biggest problem in communication is the illusion that it has taken place.', author: 'George Bernard Shaw', why: 'Ask the team to tell you what they heard, not whether they understood.' },
  { text: 'If you cannot explain it simply, you do not understand it well enough.', author: 'Albert Einstein', why: 'Try explaining your treatment philosophy in two sentences. If you cannot, it is not one yet.' },
  { text: 'Motivation gets you started. Habit keeps you going.', author: 'Jim Rohn', why: 'Build the standard into the checklist so it does not depend on how anybody feels.' },
  { text: 'The price of greatness is responsibility.', author: 'Winston Churchill', why: 'The title comes with the difficult conversations. That is what it is paying for.' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', why: 'A bad month is a month. Look at the quarter before you rewrite the strategy.' },
  { text: 'There are no traffic jams along the extra mile.', author: 'Roger Staubach', why: 'The small extra thing almost nobody does is the cheapest way to stand out.' },
  { text: 'Waste no more time arguing about what a good person should be. Be one.', author: 'Marcus Aurelius', why: 'Stop debating the culture in meetings and behave the way you want it to be.' },
  { text: 'You cannot shake hands with a clenched fist.', author: 'Indira Gandhi', why: 'Go into the difficult conversation assuming you have something to learn.' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them.', author: 'Albert Einstein', why: 'Bring somebody from outside the department into the problem you have been stuck on.' },
  { text: 'Speak in such a way that others love to listen to you. Listen in such a way that others love to speak to you.', author: 'Anonymous', why: 'Two skills, both trainable, and both worth more than any qualification you will earn this year.' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt', why: 'Budget is not the reason. Start with what the rota and the standards allow.' },
  { text: 'Small deeds done are better than great deeds planned.', author: 'Peter Marshall', why: 'Fix the small thing today instead of designing the project you will not start.' },
  { text: 'Change before you have to.', author: 'Jack Welch', why: 'The treatment nobody books yet still has a year left. Replace it now, not when it is embarrassing.' },
  { text: 'Nothing is particularly hard if you divide it into small jobs.', author: 'Henry Ford', why: 'Break the refurbishment, the retrain or the relaunch into weeks and start week one.' },
  { text: 'The function of leadership is to produce more leaders, not more followers.', author: 'Ralph Nader', why: 'Judge yourself on how many of your people got promoted, including away from you.' },
  { text: 'Never mistake motion for action.', author: 'Ernest Hemingway', why: 'A busy week with nothing changed is a week to look at honestly.' },
  { text: 'It is amazing what you can accomplish if you do not care who gets the credit.', author: 'Harry S. Truman', why: 'Give the credit away this week. It comes back with interest.' },
  { text: 'If everyone is moving forward together, then success takes care of itself.', author: 'Henry Ford', why: 'Make sure the rota, the target and the training are all pointing the same way.' },
  { text: 'An ounce of practice is worth more than tons of preaching.', author: 'Mahatma Gandhi', why: 'Demonstrate the standard rather than describing it at another meeting.' },
  { text: 'Great acts are made up of small deeds.', author: 'Lao Tzu', why: 'The five-star review is fifteen small things, none of which were expensive.' },
  { text: 'Be so good they cannot ignore you.', author: 'Steve Martin', why: 'Networking is useful. Being demonstrably excellent is better.' },
  { text: 'The wisest mind has something yet to learn.', author: 'George Santayana', why: 'Ask the newest person on your team what they think. They can still see it clearly.' },
  { text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr', why: 'Today\'s treatment is next month\'s rebooking. There is no other pipeline.' },
  { text: 'A spa without a training plan is a spa with a notice period.', why: 'Write one page per person for the next twelve months. It will change your turnover.' },
  { text: 'The best interview question is: what would you change here in your first month?', why: 'Ask it. The answer tells you whether they were paying attention on the tour.' },
  { text: 'If reception cannot describe your signature treatment, no guest will ever book it.', why: 'Test them today, kindly, and then fix the briefing.' },
  { text: 'Nobody was ever talked into relaxing.', why: 'Reduce the number of decisions a guest has to make from arrival to table.' },
  { text: 'You are not running a spa. You are running about forty small handovers a day.', why: 'Improve one handover point and the whole day feels different.' },
  { text: 'A busy therapist with no gaps has no time to be good, only time to be quick.', why: 'Look at back to back bookings across a shift and put one gap in.' },
  { text: 'Every product house wants your wall. Only one of them will train your team properly.', why: 'Choose on training and support, not on margin and marketing.' },
  { text: 'The treatment your team dislikes delivering is the one your guests can feel.', why: 'Ask which treatment they dread, and either fix it or remove it.' },
  { text: 'A spa that cannot say no to a booking has no standards, only a diary.', why: 'Decide the latest you will take a treatment and hold it.' },
  { text: 'Rebooking in the room is worth more than any marketing budget you will be given.', why: 'Train the two sentences that make rebooking natural rather than transactional.' },
  { text: 'If it takes three people to answer a guest\'s question, that is a training gap, not a hard question.', why: 'Write the ten most common questions and the answers, and put them where reception can see.' },
  { text: 'Your best hour of the week should be spent thinking, not clearing.', why: 'Book it, protect it, and do not let it become admin.' },
  { text: 'A team that never disagrees is a team that has stopped caring or stopped speaking.', why: 'Ask for the strongest objection to your plan and thank whoever gives it.' },
  { text: 'The mystery shop tells you what happens when somebody is watching.', why: 'Ask your own team what happens when nobody is.' },
  { text: 'Nobody wants a career in an industry that cannot describe one.', why: 'Draw the actual route from junior to director and show it to your team.' },
  { text: 'A qualification tells you what somebody learned. A reference tells you what they are like at half past five.', why: 'Always ask a referee about the end of a hard day.' },
  { text: 'Perfume in a treatment room is a decision somebody made without asking.', why: 'Check the smell of your rooms at three in the afternoon, not at eight in the morning.' },
  { text: 'The kindest thing you can do for a new starter is tell her exactly what good looks like.', why: 'Show her, on day one, the standard rather than the rules.' },
  { text: 'Reviews are a lagging indicator. The rota is a leading one.', why: 'Look at next week\'s rota and predict next month\'s reviews.' },
  { text: 'A therapist who is never asked her opinion will stop having one out loud.', why: 'Ask for one improvement idea at every team meeting and action one a month.' },
  { text: 'The most valuable ten minutes in a spa day is the one before it opens.', why: 'Use it deliberately. It sets everything after it.' },
  { text: 'Your uniform tells the team what you think of them.', why: 'Wear it yourself for a shift and see how it feels by hour six.' },
  { text: 'If you have to explain the offer, it is too complicated to sell.', why: 'One sentence, one price, one reason. Anything else is a leaflet nobody reads.' },
  { text: 'A spa manager\'s diary is a statement of priorities, whatever she says they are.', why: 'Look at last week honestly. Does it match what you told the team mattered?' },
  { text: 'Somebody on your team has an idea worth thousands and no way to tell you.', why: 'Create the way. A form, a slot, a walk. It does not matter which.' },
  { text: 'You cannot buy atmosphere. You can only stop destroying it.', why: 'List the five things that break the atmosphere and remove one a week.' },
  { text: 'Every unnecessary sign in a spa is a failure of design.', why: 'Count them. Each one is something the building should have made obvious.' },
  { text: 'Being liked and being respected are different, and only one of them survives a difficult decision.', why: 'Make the right call and explain it. Liking usually follows respect anyway.' },
  { text: 'The guest remembers the therapist. The business depends on the system.', why: 'Build both. A brilliant individual without a system is a risk, not a strategy.' },
  { text: 'A treatment room is a workplace for eight hours and a sanctuary for one.', why: 'Design for both or your therapists will be in pain by forty.' },
  { text: 'Musculoskeletal injury ends more spa careers than boredom does.', why: 'Check bed heights, breaks and technique this month. It is a retention issue.' },
  { text: 'A spa with no succession plan is one resignation from a bad quarter.', why: 'Name a deputy for every key role, even informally, and start training them.' },
  { text: 'Nobody joins the spa industry for the money, and everybody leaves it for the money.', why: 'You cannot compete on love alone. Fix what you can and be honest about the rest.' },
  { text: 'The therapist who asks difficult questions in a team meeting is the one who still cares.', why: 'Protect her. When she stops asking, you have lost her.' },
  { text: 'A guest experience designed on paper has never met a Saturday.', why: 'Walk it through on your busiest day before you sign it off.' },
  { text: 'If the treatment overruns every time, the treatment is longer than the menu says.', why: 'Change the menu, not the therapist.' },
  { text: 'You cannot deliver a calm experience from a chaotic back office.', why: 'Fix the room the team stands in before you fix the one the guest lies in.' },
  { text: 'A spa is a manufacturing business with feelings.', why: 'Respect the process and the people equally. Neither works without the other.' },
  { text: 'The first thing to fix in any struggling spa is the rota. It always is.', why: 'Before the menu, the marketing or the products, look at how people are being scheduled.' },
  { text: 'Nobody has ever improved a spa by adding a treatment.', why: 'Improve what you already have before you write anything new.' },
  { text: 'A therapist told to upsell will. A therapist taught to advise will do it better and mean it.', why: 'Change the word and the training. The number follows.' },
  { text: 'Your busiest therapist is not necessarily your best one. Check the rebooking rate.', why: 'Rebooking is the only honest measure of a treatment.' },
  { text: 'The team believes what you do about the standard, not what you said about it in January.', why: 'Behave the way you want them to on the day it is inconvenient.' },
  { text: 'A spa that never says thank you internally is a spa with high turnover and no idea why.', why: 'Say it specifically, weekly, and to somebody different each time.' },
  { text: 'The right person in the wrong role will leave and blame themselves.', why: 'Before you performance-manage, check whether the job is the problem.' },
  { text: 'Nobody knows your spa is good unless somebody tells them.', why: 'Ask three happy guests for a review this week. Most will say yes and none will be asked.' },
  { text: 'Every hour you spend on the rota saves three on the floor.', why: 'Treat it as the most skilled task of your week, because it is.' },
  { text: 'If your best people are your busiest people, you are burning your assets to hit a number.', why: 'Distribute the difficult work more evenly, deliberately.' },
  { text: 'The last five minutes of a treatment are worth the first fifty.', why: 'Protect them in the schedule and train what happens in them.' },
  { text: 'A spa with no quiet time built into the day has no capacity to recover from anything.', why: 'Leave gaps on purpose. They are not lost revenue, they are resilience.' },
  { text: 'What you measure on Monday is what your team will chase all week.', why: 'Choose the one number that most reflects a good spa and lead with it.' },
  { text: 'A promotion without training is a punishment with a pay rise.', why: 'Fund the management training before the title, not a year after.' },
  { text: 'The team notices which standards you enforce when you are tired.', why: 'Those are your real standards. The rest is aspiration.' },
  { text: 'Two years in one good spa beats five years in three indifferent ones.', why: 'Choose the place you will learn most, and then stay long enough to learn it.' },
  { text: 'You will never have a perfect week. Have a deliberate one.', why: 'Choose the three things that must be true by Friday and let the rest be adequate.' },]

/**
 * The line for a given day.
 *
 * Deterministic, and the same for everybody: two people who open this on the
 * same morning should be able to talk about it. Nothing is stored, nothing is
 * chosen at random, and with a full year in the list nobody sees the same one
 * twice in twelve months.
 *
 * The date is taken in London rather than the viewer's timezone, on purpose.
 * This is one register, in one industry, and a line that changes at four in
 * the afternoon for somebody working in Dubai is a bug worth avoiding for the
 * sake of a small amount of arithmetic.
 */
export function thoughtForDay(now: Date = new Date()): Thought {
  const london = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Europe/London', year: 'numeric', month: '2-digit', day: '2-digit',
  }).format(now)
  const [day, month, year] = london.split('/').map(Number)

  // Days since an arbitrary fixed date, which is all that is needed: it only
  // has to advance by exactly one every midnight.
  const days = Math.floor(Date.UTC(year, month - 1, day) / 86_400_000)
  return THOUGHTS[((days % THOUGHTS.length) + THOUGHTS.length) % THOUGHTS.length]
}
