// The library that has to exist, as a register before it is a set of drafts.
//
// Four hundred and seventy documents, planned by department and tiered by
// when a property actually needs them: before the first guest, in the first
// thirty days, or in the first quarter. Writing them is a long job. Knowing
// exactly which ones are owed, and which are not written yet, is a thing that
// can be true today, and it is the more useful of the two: a register with
// four hundred and seventy known gaps is a plan, and four hundred and seventy
// unwritten documents nobody has listed is an intention.
//
// Three things were corrected on the way in, and all of them are worth
// knowing about.
//
// The titles carried em dashes. Every other thing this platform prints is
// held to the house rule against them, including everything the writing
// assistant produces, and a document title is the most visible text on the
// page. They are hyphens here.
//
// Ten rows had lost their document number into the title column, where it sat
// after a pipe with the department blank, and all ten had been tiered QUARTER
// 1. Pulling the reference back out showed what they actually were:
// duplicates of ten reception booking procedures already listed properly
// further up the sheet. So the library is four hundred and sixty documents,
// not the four hundred and seventy-one on the cover, and the nineteen in the
// first-quarter tier were nine plus those ten counted twice.
//
// The Lib Status and Confidentiality columns are deliberately not imported.
// Across four hundred and sixty rows they are perfectly correlated - Active
// always pairs with Confidential, Archived with Public, To Be Revised with
// Managers Only - which is the signature of a column filled by pattern rather
// than decided per document. The values also read wrong on their face: an
// unwritten procedure cannot be Archived, and End of Day Banking is not
// Public. Importing a wrong answer is worse than importing none, so those two
// are left for a person.

export type BuildTier = 'day-1' | 'month-1' | 'quarter-1'

export const TIER_LABEL: Record<BuildTier, string> = {
  'day-1': 'Before the first guest',
  'month-1': 'First thirty days',
  'quarter-1': 'First quarter',
}

export type PlannedDocument = {
  reference: string
  title: string
  department: string
  tier: BuildTier
  /** Why it sits in that tier, in the words the plan used. */
  why: string
}

export const LIBRARY_PLAN: PlannedDocument[] = [
  { reference: 'FIN-CASH-DISCREPANCY-CLOSE-SOP-317', title: 'Cash Discrepancy Investigation and Closure', department: 'FINANCE TEAM', tier: 'day-1', why: 'Discrepancy investigation from day one' },
  { reference: 'FIN-CASH-FLOAT-SETUP-SOP-311', title: 'Daily Cash Float Setup and Verification', department: 'FINANCE TEAM', tier: 'day-1', why: 'Cash float before first transaction' },
  { reference: 'FIN-CHARGEBACK-DISPUTE-HANDLING-SOP-319', title: 'Chargeback and Dispute Handling', department: 'FINANCE TEAM', tier: 'month-1', why: 'Chargebacks build over time' },
  { reference: 'FIN-COMMISSION-CALC-APPROVAL-SOP-322', title: 'Commission Calculation and Approval Process', department: 'FINANCE TEAM', tier: 'month-1', why: 'Commission after first period' },
  { reference: 'FIN-COMP-SERVICE-APPROVAL-SOP-323', title: 'Complimentary Service Approval and Recording', department: 'FINANCE TEAM', tier: 'day-1', why: 'Complimentary service approval from day one' },
  { reference: 'FIN-DAILY-FLASH-REPORT-SOP-330', title: 'Daily Flash Report Preparation and Distribution', department: 'FINANCE TEAM', tier: 'day-1', why: 'Daily flash report from day one' },
  { reference: 'FIN-DAILY-REVENUE-CLOSE-SOP-314', title: 'Daily Revenue Close and Reconciliation', department: 'FINANCE TEAM', tier: 'day-1', why: 'Daily revenue close from day one' },
  { reference: 'FIN-DEFERRED-REV-RECON-SOP-327', title: 'Monthly Deferred Revenue Reconciliation', department: 'FINANCE TEAM', tier: 'month-1', why: 'Deferred revenue after first month' },
  { reference: 'FIN-DISCOUNT-AUTH-CONTROL-SOP-315', title: 'Discount Authorisation and Exception Control', department: 'FINANCE TEAM', tier: 'day-1', why: 'Discount authorisation from day one' },
  { reference: 'FIN-DISCOUNT-COMP-AUDIT-SOP-324', title: 'Discount and Comp Audit Trail Review', department: 'FINANCE TEAM', tier: 'month-1', why: 'Audit after first month' },
  { reference: 'FIN-ENDDAY-BANKING-SOP-313', title: 'End-of-Day Banking and Safe Drop', department: 'FINANCE TEAM', tier: 'day-1', why: 'Daily banking from day one' },
  { reference: 'FIN-GRATUITY-DISTRIBUTION-SOP-321', title: 'Gratuity Handling and Distribution Rules', department: 'FINANCE TEAM', tier: 'month-1', why: 'Gratuity distribution end of first period' },
  { reference: 'FIN-GV-LIABILITY-BREAKAGE-SOP-326', title: 'Gift Voucher Liability and Breakage Review', department: 'FINANCE TEAM', tier: 'month-1', why: 'Gift voucher liability after first month' },
  { reference: 'FIN-INVOICE-TAX-ISSUANCE-SOP-320', title: 'Invoice Request and Tax Invoice Issuance', department: 'FINANCE TEAM', tier: 'day-1', why: 'Tax invoices from first transaction' },
  { reference: 'FIN-MEM-REV-RECOGNITION-SOP-325', title: 'Membership Revenue Recognition and Liability Control', department: 'FINANCE TEAM', tier: 'month-1', why: 'Revenue recognition after first billing' },
  { reference: 'FIN-MONTHLY-PL-INPUT-SOP-329', title: 'Monthly P&L Input and Commentary Preparation', department: 'FINANCE TEAM', tier: 'month-1', why: 'Monthly P&L after first full month' },
  { reference: 'FIN-PETTY-CASH-CONTROL-SOP-316', title: 'Petty Cash Request and Control', department: 'FINANCE TEAM', tier: 'month-1', why: 'Petty cash as needed' },
  { reference: 'FIN-REFUND-APPROVAL-WORKFLOW-SOP-318', title: 'Refund Approval Workflow', department: 'FINANCE TEAM', tier: 'day-1', why: 'Refund approvals from day one' },
  { reference: 'FIN-SHIFT-CASH-COUNT-SOP-312', title: 'End-of-Shift Cash Count and Sign-Off', department: 'FINANCE TEAM', tier: 'day-1', why: 'End-of-shift cash count daily' },
  { reference: 'FIN-WEEKLY-KPI-PACK-SOP-328', title: 'Weekly Revenue and KPI Pack Preparation', department: 'FINANCE TEAM', tier: 'day-1', why: 'Weekly KPI pack from week one' },
  { reference: 'CLS-ATTENDANCE-B4T-SOP-269', title: 'Class Attendance Marking in Book4Time', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Attendance marking when classes launch' },
  { reference: 'CLS-AV-SYSTEM-FAILURE-SOP-278', title: 'AV and Sound System Failure Procedure', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'AV failure when classes launch' },
  { reference: 'CLS-CANCEL-MEMBER-COMMS-SOP-276', title: 'Class Cancellation and Member Communication', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class cancellations when classes launch' },
  { reference: 'CLS-DELIVERY-SAFETY-SOP-271', title: 'Class Delivery Standards and Safety Briefing', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class delivery safety when classes launch' },
  { reference: 'CLS-EQUIP-SETUP-PACKDOWN-SOP-272', title: 'Equipment Setup and Pack-Down', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Equipment setup when classes launch' },
  { reference: 'CLS-INSTR-ARRIVAL-SETUP-SOP-270', title: 'Instructor Arrival and Pre-Class Setup', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Instructor setup when classes launch' },
  { reference: 'CLS-LATEENTRY-NOSHOW-SOP-268', title: 'Late Entry and No-Show Policy for Classes', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class no-shows build over time' },
  { reference: 'CLS-PRECLASS-HS-BRIEF-SOP-274', title: 'Pre-Class Health and Safety Brief Standard', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Pre-class brief when classes launch' },
  { reference: 'CLS-STUDIO-ENV-SETUP-SOP-275', title: 'Studio Temperature, Lighting and Music Setup', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Studio setup when classes launch' },
  { reference: 'CLS-STUDIO-RESET-CLEAN-SOP-273', title: 'Studio Reset and Cleaning Post-Class', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Studio reset when classes launch' },
  { reference: 'CLS-SUB-INSTR-PROC-SOP-277', title: 'Substitute Instructor Procedure', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Substitute instructor when classes launch' },
  { reference: 'CLS-WAITLIST-MGMT-SOP-267', title: 'Waitlist Management for Classes', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class waitlist builds over time' },
  { reference: 'GYM-CARDIO-ESTOP-TEST-SOP-264', title: 'Cardio Equipment Emergency Stop Testing', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY - emergency stop test before opening' },
  { reference: 'GYM-CLASS-CHECKIN-CAPACITY-SOP-266', title: 'Class Check-In and Capacity Control', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class check-in when classes launch' },
  { reference: 'GYM-CLASS-SCHEDULE-PUBLISH-SOP-265', title: 'Class Schedule Publication and Updates', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Class schedule builds over time' },
  { reference: 'GYM-CLOSE-CHK-246', title: 'Gym Closing Checklist', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Gym closing check daily' },
  { reference: 'GYM-EMERGENCY-RESPONSE-SOP-261', title: 'Emergency Response in Gym Area', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY CRITICAL - gym emergency response' },
  { reference: 'GYM-EQUIP-DEMO-SAFEUSE-SOP-250', title: 'Equipment Demonstration and Safe Use Guidance', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Equipment demo for new users' },
  { reference: 'GYM-EQUIP-FAULT-ISOLATION-SOP-259', title: 'Equipment Fault Tagging and Isolation', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY - equipment fault tagging' },
  { reference: 'GYM-EQUIP-MAINT-SOP-359', title: 'Gym Equipment Maintenance and Calibration', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Equipment maintenance schedule' },
  { reference: 'GYM-EQUIP-READINESS-SOP-247', title: 'Daily Equipment Readiness Walkthrough', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Equipment readiness before gym opens' },
  { reference: 'GYM-EQUIP-WIPEDOWN-SOP-255', title: 'Gym Equipment Wipe-Down Rotation', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'HYGIENE - equipment wipe-down rotation' },
  { reference: 'GYM-FLOOR-SUPERVISION-SOP-251', title: 'Gym Floor Supervision and Support', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Floor supervision during all gym hours' },
  { reference: 'GYM-FREEWEIGHT-RESET-SOP-256', title: 'Free Weights Area Reset and Safety Patrol', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Free weight area safety from day one' },
  { reference: 'GYM-FREEWEIGHT-SPOTTING-SOP-263', title: 'Free Weights Spotting and Safe Practice Standard', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY - spotting standards' },
  { reference: 'GYM-HEALTH-SCREEN-PARQ-SOP-249', title: 'Health Screening and PAR-Q Collection', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY/LEGAL - PAR-Q before gym use' },
  { reference: 'GYM-INDUCTION-SESSION-SOP-248', title: 'Gym Induction and Orientation Session', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Induction for every new gym user' },
  { reference: 'GYM-INJURY-FIRSTAID-SOP-262', title: 'Guest Injury Response and First Aid Escalation', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY CRITICAL - injury first aid' },
  { reference: 'GYM-MEMBER-CONDUCT-SOP-253', title: 'Member Conduct and Etiquette Management', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Conduct management from day one' },
  { reference: 'GYM-NEW-MEMBER-QUICKSTART-SOP-254', title: 'Fitness Programme Quick Start for New Members', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'New member programme from day one' },
  { reference: 'GYM-OPEN-SAFETY-CHK-245', title: 'Gym Opening Safety Checklist', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'SAFETY - gym opening check before any gym access' },
  { reference: 'GYM-PEAK-MGMT-SOP-252', title: 'Peak Period Gym Floor Management', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Peak management once patterns are known' },
  { reference: 'GYM-PREVENTIVE-MAINT-SOP-260', title: 'Preventive Maintenance Request Process', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Preventive maintenance schedule' },
  { reference: 'GYM-SANITISER-REFILL-SOP-258', title: 'Sanitiser, Wipes and Consumables Refill Procedure', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Sanitiser refill from day one' },
  { reference: 'GYM-TOWEL-MGMT-SOP-257', title: 'Studio and Gym Towel Management', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'day-1', why: 'Towel management from day one' },
  { reference: 'PT-ASSESS-GOALSET-SOP-280', title: 'PT Assessment and Goal Setting Session', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT assessment builds over time' },
  { reference: 'PT-CONSENT-HEALTHSCREEN-SOP-282', title: 'Informed Consent and Health Screening for PT', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT health screening when PT launches' },
  { reference: 'PT-DATA-CONFIDENTIALITY-SOP-291', title: 'Confidential Handling of Client Fitness Data', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT data handling when PT launches' },
  { reference: 'PT-ENQUIRY-CONSULT-SOP-279', title: 'PT Enquiry Handling and Consultation Booking', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT builds over time' },
  { reference: 'PT-GOAL-REVIEW-REASSESS-SOP-287', title: 'PT Goal Review and Re-Assessment Session', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT goal review when PT launches' },
  { reference: 'PT-LATECANCEL-NOSHOW-SOP-288', title: 'PT Late Cancellation and No-Show Handling', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT no-shows when PT launches' },
  { reference: 'PT-NOTES-PROGRESS-SOP-286', title: 'PT Session Notes and Progress Tracking', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT notes when PT launches' },
  { reference: 'PT-PACKAGE-PURCHASE-REDEEM-SOP-284', title: 'PT Package Purchase and Redemption', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT packages when PT launches' },
  { reference: 'PT-PROGRAMME-DESIGN-SOP-281', title: 'Programme Design and Documentation', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT programme design builds over time' },
  { reference: 'PT-REFUND-TRANSFER-SOP-289', title: 'PT Refund and Transfer Policy', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT refunds when PT launches' },
  { reference: 'PT-SESSION-BOOK-CONFIRM-SOP-283', title: 'PT Session Booking and Confirmation', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT booking when PT launches' },
  { reference: 'PT-SESSION-DELIVERY-SOP-285', title: 'PT Session Delivery Standards', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'PT delivery when PT launches' },
  { reference: 'PT-TRAINER-CONDUCT-SOP-290', title: 'Trainer Conduct and Professional Standards', department: 'GYM FLOOR TEAM - PERSONAL TRAINERS', tier: 'month-1', why: 'Trainer conduct when PT launches' },
  { reference: 'FAC-STAIN-REWASH-SOP-341', title: 'Stain Treatment and Rewash Procedure', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Stain treatment as needed from day one' },
  { reference: 'HK-AMENITIES-STOCKING-SOP-337', title: 'Stocking Amenities and Guest Supplies', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Amenities stocking from day one' },
  { reference: 'HK-HOURLY-PUBLIC-CHECK-SOP-332', title: 'Hourly Public Area Checks and Reset', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Hourly public area checks from day one' },
  { reference: 'HK-LINEN-COLLECT-BAG-SOP-338', title: 'Linen Collection and Bagging Procedure', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Linen collection daily' },
  { reference: 'HK-LINEN-DISPATCH-TRACK-SOP-339', title: 'Linen Dispatch to Laundry and Tracking', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Linen dispatch daily' },
  { reference: 'HK-LINEN-RECEIPT-QUALITY-SOP-340', title: 'Linen Receipt and Quality Checks', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Linen quality check on receipt' },
  { reference: 'HK-LOCKER-CLEAN-ROTATION-SOP-333', title: 'Locker Room Cleaning Rotation', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Locker cleaning rotation from day one' },
  { reference: 'HK-SHOWER-DESCALE-ROTATION-SOP-336', title: 'Shower and Wet Area Descale Rotation', department: 'HOUSEKEEPING TEAM', tier: 'month-1', why: 'Descale rotation monthly' },
  { reference: 'HK-TOILET-VANITY-CHECK-SOP-334', title: 'Toilet and Vanity Station Check Rotation', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Toilet checks from day one' },
  { reference: 'HK-WASTE-SEGREGATION-SOP-335', title: 'Waste Removal and Segregation', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Waste management from day one' },
  { reference: 'HK-ZONE-CLEAN-SIGNOFF-SOP-331', title: 'Zone Cleaning Schedule and Sign-Off', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Zone cleaning from day one' },
  { reference: 'LIN-PARCOUNT-ESCAL-SOP-342', title: 'Par Level Linen Count and Shortage Escalation', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Par count shortage escalation from day one' },
  { reference: 'OPS-LOCKER-SETUP-AMENITIES-SOP-426', title: 'Locker Room Setup and Guest Amenities Install', department: 'HOUSEKEEPING TEAM', tier: 'day-1', why: 'Locker setup before opening' },
  { reference: 'FIN-PAYROLL-INPUT-SIGNOFF-SOP-394', title: 'Payroll Inputs Submission and Sign-Off', department: 'HR & PEOPLE TEAM', tier: 'month-1', why: 'Payroll after first pay period' },
  { reference: 'HR-ABSENCE-COVER-MGMT-SOP-395', title: 'Absence Reporting and Cover Management', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Absence management from day one' },
  { reference: 'HR-INTERVIEW-SCHED-SOP-385', title: 'Interview Scheduling and Interview Packs', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Interviews should be complete' },
  { reference: 'HR-LEAVER-ACCESS-REMOVE-SOP-391', title: 'Leaver Process and Access Removal', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Leaver process needed from day one' },
  { reference: 'HR-LOCKER-ACCESS-SOP-390', title: 'Staff Locker Allocation and Access', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Staff lockers before opening' },
  { reference: 'HR-OFFER-CONTRACT-SOP-387', title: 'Offer Issuance and Contract Acceptance', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Contracts before staff start' },
  { reference: 'HR-ONBOARD-SCHED-SOP-388', title: 'New Starter Onboarding and Induction Scheduling', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Onboarding induction before opening' },
  { reference: 'HR-OVERTIME-APPROVAL-SOP-396', title: 'Overtime Approval and Control', department: 'HR & PEOPLE TEAM', tier: 'month-1', why: 'Overtime approval after first period' },
  { reference: 'HR-PROBATION-GATE-SOP-409', title: 'Probation Review and Competency Gate Process', department: 'HR & PEOPLE TEAM', tier: 'month-1', why: 'Probation review after first period' },
  { reference: 'HR-REQ-APPROVAL-SOP-384', title: 'Recruitment Requisition and Approval', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Recruitment process should be done' },
  { reference: 'HR-RIGHTWORK-CHECK-SOP-386', title: 'Reference Checks and Right-to-Work Verification', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'LEGAL - right to work checks before day one' },
  { reference: 'HR-ROTA-BUILD-SOP-392', title: 'Rota Build and Approval Process', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Rota must exist before opening' },
  { reference: 'HR-TIMEKEEPING-MGMT-SOP-393', title: 'Timekeeping and Attendance Management', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Timekeeping from day one' },
  { reference: 'HR-UNIFORM-ISSUE-SOP-389', title: 'Uniform Ordering and Issue', department: 'HR & PEOPLE TEAM', tier: 'day-1', why: 'Uniforms before opening' },
  { reference: 'ASSET-REGISTER-TAG-SOP-349', title: 'Asset Register Update and Equipment Tagging', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Asset register before opening' },
  { reference: 'CLN-DEEPCLEAN-PROG-SOP-343', title: 'Deep Cleaning Programme and Frequency Standard', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Deep clean programme before opening' },
  { reference: 'CLN-OOO-REOPEN-SOP-344', title: 'Out-of-Order Area Cleaning and Re-Opening', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Out-of-order area management from day one' },
  { reference: 'CLN-SEASONAL-DEEP-SOP-345', title: 'Seasonal Deep Clean Plan and Closeout', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'quarter-1', why: 'Seasonal deep clean quarterly' },
  { reference: 'FAC-ANTISCALD-CHECK-SOP-355', title: 'Water Temperature Anti-Scald Controls Verification', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - anti-scald controls before opening' },
  { reference: 'FAC-HVAC-SETPOINT-SOP-351', title: 'HVAC Comfort Set-Point Control for Wellness Areas', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'HVAC settings before first guest' },
  { reference: 'FAC-LIGHTING-SCENE-SOP-352', title: 'Ambient Lighting Control and Scene Management', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Lighting scenes before first guest' },
  { reference: 'FAC-POWER-FAILURE-EMERGENCYLIGHT-SOP-442', title: 'Power Failure and Emergency Lighting Procedure', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - power failure plan before opening' },
  { reference: 'FAC-WATER-FAILURE-SUSPENSION-SOP-443', title: 'Water Failure and Service Suspension Procedure', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY - water failure plan before opening' },
  { reference: 'FAC-WATER-PRESSURE-SOP-354', title: 'Water Pressure and Temperature Monitoring', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - water pressure monitoring' },
  { reference: 'HSE-ACCIDENT-NEARMISS-INCIDENT-REPORT-SOP-452', title: 'Accident, Near Miss and Incident Reporting', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - accident reporting from day one' },
  { reference: 'HSE-CHEMICAL-SPILL-RESPONSE-SOP-445', title: 'Chemical Spill Response Procedure', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - spill response before opening' },
  { reference: 'HSE-COSHH-STORAGE-HANDLING-SOP-444', title: 'COSHH Chemical Storage and Handling', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - COSHH before any chemicals on site' },
  { reference: 'HSE-ELECTRICAL-SAFETY-CERTS-SOP-448', title: 'Electrical Safety Inspection and Certificates Control', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - electrical certs before opening' },
  { reference: 'HSE-FIRE-DOOR-ESCAPEROUTE-CHECKS-SOP-454', title: 'Fire Door and Escape Route Daily Checks', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - fire door checks daily' },
  { reference: 'HSE-GAS-SAFETY-CERTS-SOP-449', title: 'Gas Safety Certificate Management (Where Applicable)', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - gas safety certs if applicable' },
  { reference: 'HSE-LEGIONELLA-WATER-SAFETY-SOP-446', title: 'Legionella Control and Water Safety Plan', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - legionella control plan before opening' },
  { reference: 'HSE-PAT-TESTING-RECORDS-SOP-447', title: 'PAT Testing Coordination and Records', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - PAT testing before opening' },
  { reference: 'HSE-POOL-PSOP-MANAGEMENT-SOP-450', title: 'Pool Safety Operating Procedures (PSOP) Management', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - Pool Safety Operating Procedures before opening' },
  { reference: 'HSE-RISK-ASSESS-REVIEW-SIGNOFF-SOP-451', title: 'Risk Assessment Review and Sign-Off Procedure', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - risk assessments signed off before opening' },
  { reference: 'HSE-SAFEGUARDING-VULNERABLE-PERSON-SOP-453', title: 'Safeguarding and Vulnerable Person Procedure', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'LEGAL - safeguarding policy before opening' },
  { reference: 'MAINT-CONTRACTOR-PERMIT-SOP-348', title: 'Contractor Access and Permit Control', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Contractor control from day one' },
  { reference: 'MAINT-PPM-SCHED-SOP-346', title: 'Planned Preventive Maintenance Schedule Management', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'PPM schedule must exist before opening' },
  { reference: 'MAINT-REACTIVE-TRACK-SOP-347', title: 'Reactive Maintenance Request and Tracking', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Reactive maintenance from day one' },
  { reference: 'MAINT-SNAG-CLOSE-SOP-350', title: 'Snag List Management and Closure Verification', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'Snag list management pre-opening' },
  { reference: 'THER-ICEBATH-MAINT-SOP-358', title: 'Ice Bath Equipment Maintenance and Checks', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY - ice bath maintenance before opening' },
  { reference: 'THER-STEAMSAUNA-SAFE-SOP-357', title: 'Steam and Sauna Equipment Safety Checks', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - steam/sauna safety checks before opening' },
  { reference: 'THER-TOWELWARMER-SOP-360', title: 'Towel Warmer Safety Checks and Cleaning', department: 'MAINTENANCE & ENGINEERING TEAM', tier: 'day-1', why: 'SAFETY - towel warmer checks' },
  { reference: 'MEM-ACCESS-RULES-SOP-171', title: 'Member Access Rules and Peak-Time Controls', department: 'MEMBERSHIP', tier: 'day-1', why: 'Access rules must be set before first member arrives' },
  { reference: 'MEM-ARREARS-ESCALATION-SOP-169', title: 'Membership Arrears Chasing and Escalation', department: 'MEMBERSHIP', tier: 'quarter-1', why: 'Arrears build over 60+ days' },
  { reference: 'MEM-BEHAVIOUR-CONDUCT-SOP-175', title: 'Member Behaviour Management and Conduct', department: 'MEMBERSHIP', tier: 'month-1', why: 'Conduct issues build over time' },
  { reference: 'MEM-BENEFIT-REDEMPTION-SOP-174', title: 'Member Benefit Redemption (Spa, Gym, Classes)', department: 'MEMBERSHIP', tier: 'day-1', why: 'Benefits redeemed from first visit' },
  { reference: 'MEM-BILLING-RUN-SOP-163', title: 'Membership Billing Run and Reconciliation', department: 'MEMBERSHIP', tier: 'month-1', why: 'Billing run after first billing cycle' },
  { reference: 'MEM-BOOKING-PRIORITY-SOP-173', title: 'Member Booking Priority and Holds Management', department: 'MEMBERSHIP', tier: 'day-1', why: 'Member booking priority from day one' },
  { reference: 'MEM-CANCELLATION-NOTICE-SOP-167', title: 'Membership Cancellation and Notice Handling', department: 'MEMBERSHIP', tier: 'month-1', why: 'Cancellations build over time' },
  { reference: 'MEM-COMPLAINTS-RECOVERY-SOP-180', title: 'Member Complaints and Service Recovery', department: 'MEMBERSHIP', tier: 'day-1', why: 'Member complaints from day one' },
  { reference: 'MEM-CORPORATE-ENQUIRY-SOP-161', title: 'Corporate Membership Enquiry and Proposal Handling', department: 'MEMBERSHIP', tier: 'month-1', why: 'Corporate memberships build over time' },
  { reference: 'MEM-DD-SETUP-SOP-158', title: 'Direct Debit Setup and Verification', department: 'MEMBERSHIP', tier: 'day-1', why: 'Direct debit setup from first sign-up' },
  { reference: 'MEM-ENQUIRY-QUALIFY-SOP-155', title: 'Membership Enquiry Handling and Qualification', department: 'MEMBERSHIP', tier: 'day-1', why: 'Membership enquiries start immediately' },
  { reference: 'MEM-FAILED-PAYMENT-SOP-164', title: 'Failed Payment Recovery Process', department: 'MEMBERSHIP', tier: 'month-1', why: 'Failed payments after first billing' },
  { reference: 'MEM-FAMILY-ADDON-SOP-162', title: 'Family Add-On Membership Setup and Controls', department: 'MEMBERSHIP', tier: 'month-1', why: 'Family add-ons build over time' },
  { reference: 'MEM-FEEDBACK-QUARTERLY-SOP-183', title: 'Quarterly Member Feedback Survey Process', department: 'MEMBERSHIP', tier: 'quarter-1', why: 'Quarterly feedback survey after Q1' },
  { reference: 'MEM-FOUNDER-OFFER-SOP-160', title: 'Founder Member Offer Management', department: 'MEMBERSHIP', tier: 'day-1', why: 'Founder offer if running at opening' },
  { reference: 'MEM-FREEZE-SUSPEND-SOP-165', title: 'Membership Freeze and Suspension Processing', department: 'MEMBERSHIP', tier: 'month-1', why: 'Freezes build over time' },
  { reference: 'MEM-GUEST-SIGNIN-WAIVER-SOP-176', title: 'Member Guest Sign-In and Liability Waiver', department: 'MEMBERSHIP', tier: 'day-1', why: 'Guest sign-in from first member guest' },
  { reference: 'MEM-GUESTPASS-TRACKING-SOP-172', title: 'Guest Pass Allocation and Tracking', department: 'MEMBERSHIP', tier: 'month-1', why: 'Guest passes build over time' },
  { reference: 'MEM-KPI-MONTHLY-SOP-181', title: 'Monthly Membership KPI Review', department: 'MEMBERSHIP', tier: 'month-1', why: 'Monthly KPI after first full month' },
  { reference: 'MEM-LOCKER-ALLOCATION-SOP-177', title: 'Member Locker Allocation and Key Control', department: 'MEMBERSHIP', tier: 'day-1', why: 'Member lockers from day one' },
  { reference: 'MEM-ONBOARDING-FIRSTVISIT-SOP-159', title: 'Member Welcome Onboarding and First Visit', department: 'MEMBERSHIP', tier: 'day-1', why: 'Member onboarding from first sign-up' },
  { reference: 'MEM-PAYMENT-UPDATE-SOP-170', title: 'Membership Payment Method Update Process', department: 'MEMBERSHIP', tier: 'month-1', why: 'Payment updates build over time' },
  { reference: 'MEM-REFUND-APPROVAL-SOP-168', title: 'Refunds and Fee Adjustments Approval Flow', department: 'MEMBERSHIP', tier: 'month-1', why: 'Refunds post-first billing cycle' },
  { reference: 'MEM-RENEWAL-RECONTRACT-SOP-178', title: 'Renewal Reminder and Re-Contracting Process', department: 'MEMBERSHIP', tier: 'quarter-1', why: 'Renewals after 12 months' },
  { reference: 'MEM-RETENTION-SAVE-SOP-179', title: 'Retention Outreach and Save Process', department: 'MEMBERSHIP', tier: 'month-1', why: 'Retention process after first cancellations' },
  { reference: 'MEM-SIGNUP-CONTRACT-SOP-157', title: 'Membership Sign-Up and Contract Completion', department: 'MEMBERSHIP', tier: 'day-1', why: 'Sign-ups from day one' },
  { reference: 'MEM-TOUR-CONSULT-SOP-156', title: 'Membership Tour and Consultation Process', department: 'MEMBERSHIP', tier: 'day-1', why: 'Membership tours from day one' },
  { reference: 'MEM-UPGRADE-DOWNGRADE-SOP-166', title: 'Membership Upgrade and Downgrade Processing', department: 'MEMBERSHIP', tier: 'month-1', why: 'Upgrades build over time' },
  { reference: 'MEM-USAGE-INTERVENTION-SOP-182', title: 'Member Usage Review and Intervention Process', department: 'MEMBERSHIP', tier: 'month-1', why: 'Usage intervention after first month data' },
  { reference: 'THER-CAPACITY-CONTROL-SOP-233', title: 'Maximum Capacity Control and Queueing', department: 'POOL TEAM', tier: 'day-1', why: 'Capacity control from day one' },
  { reference: 'THER-CHEM-STORAGE-SOP-227', title: 'Chemical Dosing and Storage Control', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - COSHH chemical storage' },
  { reference: 'THER-CLOSE-SAFETY-CHK-222', title: 'Pool and Thermal Closing Checklist', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - closing check daily' },
  { reference: 'THER-CONTAMINATION-RESPONSE-SOP-240', title: 'Contamination Event Response and Closure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - contamination response' },
  { reference: 'THER-FAECAL-INCIDENT-SOP-243', title: 'Faecal Incident Response Procedure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - faecal incident response' },
  { reference: 'THER-FAMILY-ACCESS-SOP-234', title: 'Children and Family Access Rules', department: 'POOL TEAM', tier: 'day-1', why: 'Child access rules must be set before opening' },
  { reference: 'THER-FILTRATION-MAINT-SOP-229', title: 'Filtration Backwash and Maintenance Routine', department: 'POOL TEAM', tier: 'month-1', why: 'Filtration maintenance schedule' },
  { reference: 'THER-GUEST-GUIDANCE-SOP-238', title: 'Thermal Suite Guest Guidance and Etiquette Briefing', department: 'POOL TEAM', tier: 'day-1', why: 'Thermal briefing for every guest' },
  { reference: 'THER-GUEST-SUPERVISION-SOP-232', title: 'Guest Supervision and Behaviour Monitoring', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - guest supervision from first pool/thermal guest' },
  { reference: 'THER-ICEBATH-START-SOP-224', title: 'Ice Bath Start-Up and Shutdown Procedure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - ice bath if operational' },
  { reference: 'THER-OPEN-SAFETY-CHK-221', title: 'Pool and Thermal Opening Safety Checklist', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - pool/thermal opening check before any guest access' },
  { reference: 'THER-OVERHEAT-RESPONSE-SOP-241', title: 'Thermal Overheating and Guest Distress Response', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - overheating response' },
  { reference: 'THER-PLANTROOM-ACCESS-SOP-228', title: 'Pool Plant Room Access and Safety', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - plant room access control' },
  { reference: 'THER-RESCUE-EQUIP-CHECK-SOP-231', title: 'Rescue Equipment and Lifesaving Aids Check', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - rescue equipment check before opening' },
  { reference: 'THER-SIGNAGE-DAILY-CHECK-SOP-237', title: 'Poolside Signage Placement and Daily Check', department: 'POOL TEAM', tier: 'day-1', why: 'Safety signage check daily - LQA requirement' },
  { reference: 'THER-SLIP-HAZARD-SOP-236', title: 'Slip Hazard Patrol and Immediate Controls', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - slip hazard patrol from day one' },
  { reference: 'THER-STARTUP-SHUTDOWN-SOP-223', title: 'Thermal Suite Start-Up and Shutdown Procedure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - thermal start-up/shutdown procedure' },
  { reference: 'THER-TOWEL-STATION-SOP-235', title: 'Towel and Robe Station Management', department: 'POOL TEAM', tier: 'day-1', why: 'Towel station management from day one' },
  { reference: 'THER-VOMITUS-RESPONSE-SOP-244', title: 'Vomitus Contamination Response Procedure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - vomitus response' },
  { reference: 'THER-WATER-CALIBRATION-SOP-230', title: 'Calibration of Water Testing Equipment', department: 'POOL TEAM', tier: 'day-1', why: 'Water testing equipment calibration before first use' },
  { reference: 'THER-WATER-DAILY-LOG-SOP-225', title: 'Daily Water Testing and Logging', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - water testing is a legal requirement' },
  { reference: 'THER-WATER-HOURLY-CHK-SOP-226', title: 'Hourly Water Quality Spot Check', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - hourly water quality checks' },
  { reference: 'THER-WATERFEATURE-ISOLATION-SOP-242', title: 'Water Feature Failure and Isolation Procedure', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY - water feature isolation' },
  { reference: 'THER-WETAREA-INCIDENT-SOP-239', title: 'Wet Area Incident Response and Reporting', department: 'POOL TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - wet area incident response' },
  { reference: 'REC-AFTERCARE-EMAIL-SOP-045', title: 'Aftercare Email Dispatch and Record', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Aftercare emails go out from day one' },
  { reference: 'REC-AFTERCARE-MANUAL-SOP-095', title: 'Send Aftercare and Follow-Up (Manual Trigger)', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Aftercare manual send from day one' },
  { reference: 'REC-ALLERGY-NOTES-SOP-073', title: 'Create Booking Notes for Allergies and Medical Alerts', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Allergy alerts are safety-critical' },
  { reference: 'REC-ARRIVE-SOP-018', title: 'Guest Arrival Greeting and Welcome', department: 'RECEPTION TEAM', tier: 'day-1', why: 'First guest touchpoint - non-negotiable' },
  { reference: 'REC-ASSIGN-ROOM-SOP-058', title: 'Assign Room and Resource to Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Room assignment is daily operation' },
  { reference: 'REC-ASSIGN-THER-SOP-057', title: 'Assign Therapist to Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Therapist assignment is daily scheduling' },
  { reference: 'REC-B4T-CLOSE-SOP-049', title: 'Book4Time End-of-Day Close and Reconciliation', department: 'RECEPTION TEAM', tier: 'day-1', why: 'End-of-day close is daily requirement' },
  { reference: 'REC-B4T-LOGIN-SOP-048', title: 'Book4Time Daily Log-In and System Health Check', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Book4Time is the operational backbone - must work' },
  { reference: 'REC-B4T-OUTPUT-SOP-050', title: 'Book4Time Printer, Receipt and Email Output Checks', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Printing/receipts needed from day one' },
  { reference: 'REC-BDAY-EMAIL-SOP-046', title: 'Birthday and Occasion Email Scheduling', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Birthday comms build over time' },
  { reference: 'REC-BOOK-CLASS-SOP-054', title: 'Create Group Exercise Class Booking', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Classes may not run week one' },
  { reference: 'REC-BOOK-GYM-SOP-053', title: 'Create Gym Access Booking or Day Pass', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Gym bookings if access confirmed' },
  { reference: 'REC-BOOK-LINKED-SOP-061', title: 'Create Linked Bookings for Couples or Groups', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Couples bookings from day one' },
  { reference: 'REC-BOOK-MULTI-SOP-060', title: 'Create Multi-Service Itinerary Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Multi-service itineraries are a core spa day feature' },
  { reference: 'REC-BOOK-PT-SOP-055', title: 'Create Personal Training Session Booking', department: 'RECEPTION TEAM', tier: 'month-1', why: 'PT unlikely week one' },
  { reference: 'REC-BOOK-SPADAY-SOP-052', title: 'Create Spa Day Package Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Spa day packages from day one' },
  { reference: 'REC-BOOK-TREAT-SOP-051', title: 'Create Spa Treatment Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Creating bookings is the core function' },
  { reference: 'REC-BOOK-WALKIN-SOP-056', title: 'Create Walk-In Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Walk-ins will happen' },
  { reference: 'REC-BUFFER-SETUP-SOP-059', title: 'Apply Buffers and Setup Times', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Buffers affect scheduling from day one' },
  { reference: 'REC-CANCEL-CHARGE-SOP-076', title: 'Apply Cancellation Policy Charges', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Cancellation charges from day one' },
  { reference: 'REC-CANCEL-CONFIRM-SOP-098', title: 'Send Cancellation Confirmation and Policy Summary', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Cancellation confirmation from day one' },
  { reference: 'REC-CANCEL-POL-SOP-068', title: 'Cancel Booking and Apply Policy', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Cancellations happen immediately' },
  { reference: 'REC-CHANGE-SERV-SOP-064', title: 'Change Service Type on Existing Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Service changes happen immediately' },
  { reference: 'REC-CHILD-ACC-SOP-036', title: 'Children and Young Persons Access Management', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Child access policy must be clear before opening' },
  { reference: 'REC-CLASS-CHECK-SOP-027', title: 'Fitness Class Arrival and Studio Check-In', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Classes may not run week one' },
  { reference: 'REC-CLOSE-CHK-002', title: 'Reception Closing Checklist', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Operational baseline - spa cannot close safely without this' },
  { reference: 'REC-COMP-TRIAGE-SOP-033', title: 'Guest Complaint Intake and Triage', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Complaints can arise on any visit' },
  { reference: 'REC-CONFIRM-MANUAL-SOP-093', title: 'Send Booking Confirmation (Manual Trigger)', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Manual confirmation triggers needed' },
  { reference: 'REC-CONFIRM-RESEND-SOP-097', title: 'Resend Confirmation and Updated Itinerary', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Resend confirmations - occasional' },
  { reference: 'REC-CONV-STD-SOP-009', title: 'Conversion Standards for Enquiries to Bookings', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Converting enquiries is revenue-critical from day one' },
  { reference: 'REC-DAILY-AMEN-SOP-005', title: 'Daily Guest Amenity and Collateral Setup', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Guest-facing standards from minute one' },
  { reference: 'REC-DATA-CONSENT-SOP-040', title: 'Guest Data Consent Capture and Preferences Recording', department: 'RECEPTION TEAM', tier: 'day-1', why: 'GDPR consent is a legal requirement from day one' },
  { reference: 'REC-DELAY-COMM-SOP-032', title: 'Service Delay Communication to Guests', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Service delays will happen in first week' },
  { reference: 'REC-DEPART-STD-SOP-041', title: 'Guest Departure and Farewell Standards', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Farewell standards are the last impression' },
  { reference: 'REC-DEPOSIT-SOP-074', title: 'Take Deposit at Time of Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Deposits from first booking' },
  { reference: 'REC-DISCOUNT-APPLY-SOP-080', title: 'Apply Discount or Promotion Code', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Discounts and promos from day one' },
  { reference: 'REC-DISCOUNT-RULES-SOP-083', title: 'Apply Staff/Resident/Hotel Guest Discount Rules', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Staff/hotel guest discounts from day one' },
  { reference: 'REC-DUPLICATE-BOOK-SOP-101', title: 'Duplicate Booking Resolution', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Duplicates happen immediately in high-volume ops' },
  { reference: 'REC-DUPLICATE-GUEST-SOP-103', title: 'Resolve Duplicate Guest Profiles', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Profile deduplication builds over time' },
  { reference: 'REC-EMAIL-TROUBLE-SOP-105', title: 'Troubleshoot Email Deliverability and Bounces', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Email troubleshooting as issues arise' },
  { reference: 'REC-ENQ-EMAIL-SOP-007', title: 'Email Enquiry Handling and Response Standards', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Email enquiries live from day one' },
  { reference: 'REC-ENQ-TEL-SOP-006', title: 'Telephone Enquiry Handling and Lead Capture', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Phone enquiries live from day one' },
  { reference: 'REC-ENQ-WEB-SOP-008', title: 'Website and Online Enquiry Triage', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Online triage important but not day-one critical' },
  { reference: 'REC-ESCORT-SOP-025', title: 'Guest Escort and Wayfinding Standards', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Guest wayfinding from arrival' },
  { reference: 'REC-EVENT-SOP-017', title: 'Party and Event Booking Enquiry Handling', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Event bookings build over time' },
  { reference: 'REC-FOLLOWUP-SOP-043', title: 'Post-Visit Follow-Up and Feedback Request', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Post-visit follow-up starts from first guest' },
  { reference: 'REC-GRATUITY-SETUP-SOP-084', title: 'Apply Service Charge or Gratuity Settings', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Gratuity settings must be configured before opening' },
  { reference: 'REC-GROUP-SOP-011', title: 'Group and Corporate Booking Handling', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Group bookings unlikely day one' },
  { reference: 'REC-GYM-CHECK-SOP-022', title: 'Gym Guest Check-In and Orientation', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Gym guests present if access rights confirmed' },
  { reference: 'REC-INFO-SEND-SOP-013', title: 'Send Spa Menu and Information Pack to Enquirers', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Can be handled ad hoc initially' },
  { reference: 'REC-LATE-ARR-SOP-030', title: 'Late Arrival Management and Re-Planning', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Late arrivals happen daily' },
  { reference: 'REC-LOCKER-SOP-024', title: 'Locker Allocation and Key Control', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Every guest needs a locker' },
  { reference: 'REC-LOSTPROP-SOP-044', title: 'Lost Property Intake and Guest Return Process', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Lost property occurs immediately' },
  { reference: 'REC-MED-ACC-SOP-029', title: 'Medical and Accessibility Needs Flagging at Check-In', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Medical flagging is safety-critical - no exceptions' },
  { reference: 'REC-MEM-CHECK-SOP-020', title: 'Member Check-In and Access Verification', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Members present from day one' },
  { reference: 'REC-MEM-CLASS-SOP-062', title: 'Book Class for Member Using Benefit Entitlement', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Class benefit redemption after classes launch' },
  { reference: 'REC-MEM-INFO-SOP-014', title: 'Membership Information Email and Terms Dispatch', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Membership enquiries start immediately' },
  { reference: 'REC-MEM-OVERDUE-SOP-037', title: 'Handling Overdue Membership Payments Enquiries', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Payment issues build over time' },
  { reference: 'REC-MEMBEN-REDEEM-SOP-085', title: 'Redeem Membership Benefit for Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Member benefit redemption from first member visit' },
  { reference: 'REC-MEMBER-PROFILE-UPD-SOP-089', title: 'Update Member Profile and Notes', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Profile updates from first visit' },
  { reference: 'REC-MEMBERSHIP-SELL-SOP-088', title: 'Sell Membership at Front Desk', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Selling memberships from day one' },
  { reference: 'REC-MEMFREEZE-REQ-SOP-091', title: 'Process Membership Freeze Request at Front Desk', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Freezes build over time' },
  { reference: 'REC-MEMPAYMENT-UPD-SOP-090', title: 'Update Membership Payment Method Details', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Payment updates less urgent initially' },
  { reference: 'REC-MEMPRIORITY-BOOK-SOP-086', title: 'Book Member Priority Access Slot', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Member priority booking from day one' },
  { reference: 'REC-MEMRENEW-MANUAL-SOP-099', title: 'Send Membership Renewal Reminder (Manual Trigger)', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Renewals build after 12 months' },
  { reference: 'REC-MEMSUSP-REINSTATE-SOP-092', title: 'Reinstate Suspended Membership After Payment', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Reinstatements build over time' },
  { reference: 'REC-MEMWELCOME-MANUAL-SOP-096', title: 'Send Membership Welcome Message (Manual Trigger)', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Member welcome from first sign-up' },
  { reference: 'REC-MOVE-THER-SOP-065', title: 'Move Booking Between Therapists', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Moving between therapists happens in week one' },
  { reference: 'REC-NOSHOW-CHARGE-SOP-077', title: 'Apply No-Show Charges', department: 'RECEPTION TEAM', tier: 'day-1', why: 'No-show charges from day one' },
  { reference: 'REC-NOSHOW-SOP-031', title: 'No-Show Handling and Charge Communication', department: 'RECEPTION TEAM', tier: 'day-1', why: 'No-shows from day one - revenue protection' },
  { reference: 'REC-NOTES-PREF-SOP-067', title: 'Add Notes, Alerts and Guest Preferences', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Guest preferences must be captured from first visit' },
  { reference: 'REC-OPEN-CHK-001', title: 'Reception Opening Checklist', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Operational baseline - spa cannot open without this' },
  { reference: 'REC-OVERRIDE-AVAIL-SOP-070', title: 'Override Availability for Manager-Approved Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Manager overrides needed from day one' },
  { reference: 'REC-PACKAGE-REDEEM-SOP-087', title: 'Redeem Package Sessions', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Package redemption from day one' },
  { reference: 'REC-PAYFAIL-HANDLING-SOP-102', title: 'Payment Failure Handling at Front Desk', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Payment failures happen from day one' },
  { reference: 'REC-PAYLINK-REMOTE-SOP-082', title: 'Process Payment Link and Remote Payment', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Remote payments less urgent initially' },
  { reference: 'REC-POOL-ACCESS-SOP-023', title: 'Pool and Thermal Access Control', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Pool/thermal access control is safety-critical' },
  { reference: 'REC-POS-FEED-SOP-039', title: 'Compliment and Positive Feedback Capture', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Capturing positive feedback from day one' },
  { reference: 'REC-PREPAY-PACK-SOP-075', title: 'Process Prepayment for Packages', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Package prepayments from day one' },
  { reference: 'REC-PT-CHECK-SOP-028', title: 'Personal Training Client Arrival and Check-In', department: 'RECEPTION TEAM', tier: 'month-1', why: 'PT unlikely to be fully running week one' },
  { reference: 'REC-REBOOK-SOP-042', title: 'Rebooking Conversation and Future Booking Capture', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Rebooking conversation is revenue-critical from day one' },
  { reference: 'REC-RECOVERY-AUTH-SOP-034', title: 'Service Recovery Authorisation at Front Desk', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Service recovery needed from day one' },
  { reference: 'REC-REFUND-PART-SOP-079', title: 'Process Partial Refund and Adjustments', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Partial refunds less common initially' },
  { reference: 'REC-REFUND-SOP-078', title: 'Process Refund to Original Method', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Refunds can be required on day one' },
  { reference: 'REC-REM-CALL-SOP-015', title: 'Appointment Reminder Call Handling (Manual)', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Automated reminders via SPA-PRE-004 cover initially' },
  { reference: 'REC-REMINDER-MANUAL-SOP-094', title: 'Send Appointment Reminder (Manual Trigger)', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Manual reminders needed' },
  { reference: 'REC-RESCHED-SOP-063', title: 'Reschedule Booking and Maintain Resource Logic', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Rescheduling happens daily' },
  { reference: 'REC-RETAIL-SUP-SOP-026', title: 'Retail Browsing Guest Support and Control', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Retail open from day one' },
  { reference: 'REC-REVENUE-CORRECT-SOP-104', title: 'Correct Misallocated Revenue or Service Code', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Revenue correction - less urgent initially' },
  { reference: 'REC-REVIEW-MGMT-SOP-047', title: 'Review Request and Reputation Management Follow-Up', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Reviews build after first visits' },
  { reference: 'REC-ROOM-CONFLICT-SOP-071', title: 'Change Room Allocation and Resolve Conflicts', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Room conflicts likely in first week' },
  { reference: 'REC-SAMEDAY-SOP-016', title: 'Same-Day Availability and Standby List Management', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Same-day availability management critical for utilisation' },
  { reference: 'REC-SHIFT-CLOSE-SOP-004', title: 'Front Desk Shift Close and Handover Pack', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Handover integrity - revenue and booking data' },
  { reference: 'REC-SHIFT-OPEN-SOP-003', title: 'Front Desk Shift Start and System Readiness', department: 'RECEPTION TEAM', tier: 'day-1', why: 'System readiness before first guest arrives' },
  { reference: 'REC-SPADAY-CHECK-SOP-021', title: 'Spa Day Guest Check-In and Briefing', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Spa day guests present from day one' },
  { reference: 'REC-SPECACC-SOP-012', title: 'Special Requests and Accessibility Booking Handling', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Accessibility needs can arise on any visit' },
  { reference: 'REC-SPLIT-MERGE-SOP-066', title: 'Split or Merge Bookings', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Complex booking management builds over time' },
  { reference: 'REC-SYSOUTAGE-CONT-SOP-100', title: 'System Outage Manual Booking Contingency', department: 'RECEPTION TEAM', tier: 'day-1', why: 'System outage contingency - must be ready before opening' },
  { reference: 'REC-VERIFY-SOP-019', title: 'Booking Verification and Guest Identification', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Booking verification before every treatment' },
  { reference: 'REC-VIP-HAND-SOP-035', title: 'VIP and High-Profile Guest Handling at Front Desk', department: 'RECEPTION TEAM', tier: 'day-1', why: 'VIP guests likely in the first week' },
  { reference: 'REC-VOUCH-ENQ-SOP-038', title: 'Gift Voucher Enquiry and Expiry Handling', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Gift vouchers sold/redeemed immediately' },
  { reference: 'REC-VOUCHER-REDEEM-SOP-081', title: 'Redeem Gift Voucher Against Booking', department: 'RECEPTION TEAM', tier: 'day-1', why: 'Gift vouchers redeemed from day one' },
  { reference: 'REC-WAIT-CONVERT-SOP-072', title: 'Convert Waitlist Entry to Confirmed Booking', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Conversion builds over time' },
  { reference: 'REC-WAIT-SOP-010', title: 'Waitlist Handling and Guest Callback', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Waitlist builds over time' },
  { reference: 'REC-WAITLIST-MGMT-SOP-069', title: 'Create and Manage Waitlist', department: 'RECEPTION TEAM', tier: 'month-1', why: 'Waitlist builds over time' },
  { reference: 'RET-DISPLAY-MERCH-SOP-425', title: 'Retail Display Build and Merchandising Setup', department: 'RETAIL TEAM', tier: 'day-1', why: 'Merchandising standards before opening' },
  { reference: 'RTL-COMPLAINTS-QUALITY-SOP-302', title: 'Retail Complaints and Quality Issues Handling', department: 'RETAIL TEAM', tier: 'day-1', why: 'Retail complaints from day one' },
  { reference: 'RTL-CROSSSELL-TREATMENT-HANDOVER-SOP-298', title: 'Cross-Sell from Treatment to Retail Handover', department: 'RETAIL TEAM', tier: 'day-1', why: 'Cross-sell from treatment from day one' },
  { reference: 'RTL-DAILY-STOCK-VARIANCE-SOP-306', title: 'Daily Stock Spot Check and Variance Reporting', department: 'RETAIL TEAM', tier: 'day-1', why: 'Daily stock spot check from day one' },
  { reference: 'RTL-DAMAGED-WRITEOFF-SOP-300', title: 'Damaged Goods and Write-Off Procedure', department: 'RETAIL TEAM', tier: 'month-1', why: 'Write-offs build over time' },
  { reference: 'RTL-DELIVERY-RECEIVING-VERIFY-SOP-303', title: 'Retail Delivery Receiving and Verification', department: 'RETAIL TEAM', tier: 'day-1', why: 'Delivery receiving before opening stock arrives' },
  { reference: 'RTL-FIFO-EXPIRY-CHECK-SOP-305', title: 'FIFO Rotation and Expiry Date Checks', department: 'RETAIL TEAM', tier: 'day-1', why: 'FIFO rotation from first stock delivery' },
  { reference: 'RTL-OPEN-DISPLAY-SOP-292', title: 'Retail Opening Display Standards', department: 'RETAIL TEAM', tier: 'day-1', why: 'Retail display standards from day one' },
  { reference: 'RTL-PLANOGRAM-SETUP-SOP-293', title: 'Retail Planogram Setup and Maintenance', department: 'RETAIL TEAM', tier: 'day-1', why: 'Planogram set before opening' },
  { reference: 'RTL-PROMO-SCRIPT-DISCLOSURE-SOP-301', title: 'Retail Promotion Script and Offer Disclosure', department: 'RETAIL TEAM', tier: 'month-1', why: 'Promo scripts when promos launch' },
  { reference: 'RTL-PROMO-SETUP-POS-SOP-296', title: 'Promotion Setup and POS Messaging', department: 'RETAIL TEAM', tier: 'month-1', why: 'Promos build over time' },
  { reference: 'RTL-REORDER-SUPPLIER-ORDER-SOP-308', title: 'Reorder Thresholds and Supplier Ordering', department: 'RETAIL TEAM', tier: 'month-1', why: 'Reordering after first stock runs low' },
  { reference: 'RTL-RETURNS-EXCHANGES-SOP-299', title: 'Retail Returns and Exchanges', department: 'RETAIL TEAM', tier: 'day-1', why: 'Returns from day one' },
  { reference: 'RTL-SALES-CONVERSATION-SOP-297', title: 'Retail Sales Conversation Standards', department: 'RETAIL TEAM', tier: 'day-1', why: 'Retail sales conversation from day one' },
  { reference: 'RTL-SAMPLING-GWP-CONTROL-SOP-295', title: 'Sampling and Gift-With-Purchase Controls', department: 'RETAIL TEAM', tier: 'month-1', why: 'Sampling campaigns build over time' },
  { reference: 'RTL-STOCK-STORAGE-SECURITY-SOP-304', title: 'Stock Storage, Security and Segregation', department: 'RETAIL TEAM', tier: 'day-1', why: 'Stock security from day one' },
  { reference: 'RTL-STOCK-TRANSFER-SOP-309', title: 'Stock Transfer Between Locations (If Applicable)', department: 'RETAIL TEAM', tier: 'quarter-1', why: 'Stock transfer if multi-location' },
  { reference: 'RTL-STOCK-WRITEOFF-APPROVAL-SOP-310', title: 'Stock Write-Off Approval and Recording', department: 'RETAIL TEAM', tier: 'month-1', why: 'Write-offs build over time' },
  { reference: 'RTL-STOCKTAKE-RECONCILE-SOP-307', title: 'Formal Stocktake and Reconciliation', department: 'RETAIL TEAM', tier: 'month-1', why: 'Formal stocktake monthly' },
  { reference: 'RTL-TESTER-SETUP-HYGIENE-SOP-294', title: 'Tester Setup, Hygiene and Replacement', department: 'RETAIL TEAM', tier: 'day-1', why: 'Tester hygiene from day one' },
  { reference: 'HSE-DEFIB-ACCESS-USE-SOP-440', title: 'Defibrillator Access and Use Protocol', department: 'SECURITY TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - defibrillator protocol before opening' },
  { reference: 'HSE-EMERGENCY-DRILL-PLAN-SOP-430', title: 'Emergency Drill Planning and Execution', department: 'SECURITY TEAM', tier: 'day-1', why: 'SAFETY/LEGAL - emergency drills before opening' },
  { reference: 'HSE-FIRE-ALARM-EVAC-SOP-438', title: 'Fire Alarm Response and Evacuation', department: 'SECURITY TEAM', tier: 'day-1', why: 'SAFETY/LEGAL CRITICAL - fire evacuation before opening' },
  { reference: 'HSE-MEDICAL-EMERGENCY-FIRSTAID-SOP-439', title: 'Medical Emergency Response and First Aid', department: 'SECURITY TEAM', tier: 'day-1', why: 'SAFETY CRITICAL - medical emergency response' },
  { reference: 'SEC-CCTV-EVIDENCE-SOP-366', title: 'CCTV Review Request and Evidence Handling', department: 'SECURITY TEAM', tier: 'month-1', why: 'CCTV evidence requests as needed' },
  { reference: 'SEC-INCIDENT-ESCAL-SOP-365', title: 'Security Incident Reporting and Escalation', department: 'SECURITY TEAM', tier: 'day-1', why: 'Incident escalation from day one' },
  { reference: 'SEC-LOSTPROP-CTRL-SOP-367', title: 'Lost Property Control and Secure Storage', department: 'SECURITY TEAM', tier: 'day-1', why: 'Lost property from day one' },
  { reference: 'SEC-MAJOR-INCIDENT-LOCKDOWN-SOP-441', title: 'Major Incident Lockdown Procedure', department: 'SECURITY TEAM', tier: 'day-1', why: 'SAFETY - lockdown procedure before opening' },
  { reference: 'SEC-MASTERKEY-CTRL-SOP-363', title: 'Key and Locker Master Key Control', department: 'SECURITY TEAM', tier: 'day-1', why: 'SECURITY - master key control before opening' },
  { reference: 'SEC-STAFF-ACCESS-SOP-364', title: 'Staff Access Control and Restricted Areas Procedure', department: 'SECURITY TEAM', tier: 'day-1', why: 'Staff access control before opening' },
  { reference: 'SEC-UNRULY-GUEST-REMOVAL-SOP-368', title: 'Unruly Guest Management and Removal Procedure', department: 'SECURITY TEAM', tier: 'day-1', why: 'Unruly guest management from day one' },
  { reference: 'AUD-AUDIT-EVIDENCE-COLLECTION-SOP-462', title: 'Documented Evidence Collection for Audits', department: 'SPA MANAGEMENT TEAM', tier: 'quarter-1', why: 'Audit evidence collection post-opening' },
  { reference: 'AUD-INTERNAL-AUDIT-PROGRAMME-SCHEDULE-SOP-460', title: 'Internal Audit Programme and Schedule', department: 'SPA MANAGEMENT TEAM', tier: 'quarter-1', why: 'Internal audit programme post-opening' },
  { reference: 'AUD-NONCONFORMANCE-CORRECTIVE-ACTION-SOP-461', title: 'Non-Conformance Reporting and Corrective Actions', department: 'SPA MANAGEMENT TEAM', tier: 'quarter-1', why: 'Non-conformance process post-opening' },
  { reference: 'COM-MEMBERSHIP-TIER-SIGNOFF-SOP-416', title: 'Membership Tier Design and Pricing Sign-Off Process', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Membership tiers signed off before opening' },
  { reference: 'COM-WEEKLY-PERF-REVIEW-SOP-378', title: 'Weekly Commercial Performance Review', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Commercial performance review from week one' },
  { reference: 'DES-GUEST-JOURNEY-WORKSHOP-SOP-415', title: 'Guest Journey Design Workshops and Outputs', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Guest journey design - complete before opening' },
  { reference: 'DES-SIGNAGE-WAYFINDING-APPROVAL-SOP-421', title: 'Signage and Wayfinding Content Approval', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Signage before opening' },
  { reference: 'FAC-EQUIPMENT-COMMISSIONING-SOP-423', title: 'Equipment Delivery Acceptance and Commissioning Control', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Equipment commissioning before opening' },
  { reference: 'FIN-CASH-ESCORT-SEC-SOP-370', title: 'Cash Handling Security and Escort Procedure', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Cash security from day one' },
  { reference: 'FIN-FRAUD-SUSPICIOUS-TRANSACTION-REPORT-SOP-458', title: 'Fraud Prevention and Suspicious Transaction Reporting', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Fraud reporting from day one' },
  { reference: 'FIN-PCI-PAYMENT-COMPLIANCE-SOP-457', title: 'Payment Card Compliance and PCI Controls', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'LEGAL - PCI compliance before first card transaction' },
  { reference: 'GOV-DATA-BREACH-INCIDENT-RESPONSE-SOP-459', title: 'Incident Data Breach Reporting and Response', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'LEGAL - data breach response before opening' },
  { reference: 'GOV-GDPR-SAR-HANDLING-SOP-456', title: 'GDPR Subject Access Request Handling', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'SAR handling as requests arrive' },
  { reference: 'GOV-SOP-LIBRARY-CONTROL-SOP-414', title: 'SOP Library Build and Governance Setup', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'SOP governance from day one' },
  { reference: 'HR-RECRUITMENT-CAMPAIGN-SOP-422', title: 'Recruitment Campaign Launch and Tracking', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Recruitment should be complete before opening' },
  { reference: 'HSE-WEEKLY-REVIEW-SOP-379', title: 'Weekly Health and Safety Review', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Weekly HSE review from week one' },
  { reference: 'OPS-DAILY-LEAD-BRIEF-SOP-371', title: 'Daily Leadership Briefing and Priorities', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily leadership brief from day one' },
  { reference: 'OPS-DAILY-RISK-REVIEW-SOP-375', title: 'Daily Risk Review and Controls Confirmation', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'SAFETY - daily risk review from day one' },
  { reference: 'OPS-DAILY-STANDUP-MTG-SOP-381', title: 'Daily Stand-Up Meeting Agenda and Actions', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily stand-up from day one' },
  { reference: 'OPS-DUTY-MGR-ROUNDS-SOP-372', title: 'Daily Duty Manager Rounds and Standards Check', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily duty manager rounds from day one' },
  { reference: 'OPS-ESCALATION-PROTOCOL-SOP-382', title: 'Operational Escalation and Decision Protocol', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Escalation protocol from day one' },
  { reference: 'OPS-GUEST-FEEDBACK-DAILY-SOP-373', title: 'Daily Guest Feedback Review and Actions', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily feedback review from day one' },
  { reference: 'OPS-MAJOR-INCIDENT-CMD-SOP-383', title: 'Major Incident Command and Communication', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'SAFETY - major incident command before opening' },
  { reference: 'OPS-OPENING-KPI-RAPIDFIX-SOP-435', title: 'Opening Week KPI Monitoring and Rapid Fix Protocol', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'KPI monitoring in opening week' },
  { reference: 'OPS-OPENING-WEEK-DEBRIEF-SOP-434', title: 'Opening Week Daily Debrief and Action Log', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Opening week debrief - immediate post-opening' },
  { reference: 'OPS-POST30DAY-REVIEW-SOP-437', title: '30-Day Post-Opening Review and Improvement Plan', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: '30-day review after first month' },
  { reference: 'OPS-PRIORITIES-BOARD-SOP-376', title: 'Daily Priorities Board Update Procedure', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily priorities from day one' },
  { reference: 'OPS-SOFT-LAUNCH-DAYONE-SOP-433', title: 'Soft Launch Day-One Control Procedure', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Day one control procedure' },
  { reference: 'OPS-SOFT-OPEN-READINESS-SOP-432', title: 'Soft Opening Readiness Review and Sign-Off', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Soft opening readiness sign-off' },
  { reference: 'OPS-STABILISATION-PERIOD-SOP-436', title: 'Stabilisation Period Staffing and Service Adjustments', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Stabilisation period first 30 days' },
  { reference: 'OPS-STAFF-REALLOCATE-SOP-374', title: 'Daily Staffing Adjustment and Redeployment', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Staff reallocation from day one' },
  { reference: 'OPS-WEEKLY-OPS-REVIEW-SOP-377', title: 'Weekly Operations Review Meeting Process', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Weekly ops review from week one' },
  { reference: 'PRE-CRITICAL-PATH-SOP-411', title: 'Pre-Opening Critical Path and Milestone Control', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pre-opening - critical path management' },
  { reference: 'PRE-ROOM-READINESS-STDS-SOP-413', title: 'Pre-Opening Room Readiness Standards Definition', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pre-opening - room readiness before first treatment' },
  { reference: 'PRE-SITE-SNAG-WALK-SOP-412', title: 'Pre-Opening Site Walkthrough and Snag Capture Standard', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pre-opening - site walkthrough' },
  { reference: 'PRE-STAKEHOLDER-MAP-SOP-410', title: 'Pre-Opening Stakeholder Map and Contact Tree', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pre-opening - should be done' },
  { reference: 'PROC-LINEN-SPEC-SOP-420', title: 'Linen Specification and Procurement Control', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Linen spec before opening' },
  { reference: 'PROC-STOCK-PAR-ORDERING-SOP-418', title: 'Opening Stock Par Level Definition and Ordering Control', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Stock par levels before opening' },
  { reference: 'PROC-UNIFORM-ISSUE-SOP-419', title: 'Uniform Procurement and Issue Control', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Uniforms before opening' },
  { reference: 'QUAL-MONTHLY-AUDIT-SOP-380', title: 'Monthly Quality and Audit Review', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Monthly quality audit after first month' },
  { reference: 'RET-RANGE-PRICE-SIGNOFF-SOP-417', title: 'Retail Range Design and Price Architecture Sign-Off', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Retail range priced before opening' },
  { reference: 'SEC-MEMBER-IDCTRL-SOP-361', title: 'Member Access Control and ID Verification', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Member access control from day one' },
  { reference: 'SEC-WORKPLACE-VIOLENCE-THREAT-RESPONSE-SOP-455', title: 'Workplace Violence and Threat Response Procedure', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'SAFETY - violence/threat response' },
  { reference: 'SYS-ADDON-UPGRADE-SOP-114', title: 'Create Add-Ons and Upgrades', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Add-ons needed from day one' },
  { reference: 'SYS-B4T-END2END-TEST-SOP-431', title: 'Book4Time End-to-End Transaction Testing', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Book4Time end-to-end test before opening' },
  { reference: 'SYS-BUFFER-TIMES-SOP-122', title: 'Configure Buffers, Setup and Cleanup Times', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Buffers affect scheduling from day one' },
  { reference: 'SYS-CANCEL-RULES-SOP-123', title: 'Configure Cancellation and No-Show Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Cancellation rules before first booking' },
  { reference: 'SYS-CAPACITY-AREA-SOP-130', title: 'Configure Maximum Capacity by Area', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Capacity limits before opening' },
  { reference: 'SYS-CLASS-CAPACITY-SOP-133', title: 'Configure Class Capacity and Studio Resources', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Classes build over time' },
  { reference: 'SYS-CLASS-CATALOGUE-SOP-116', title: 'Build Class Catalogue and Categories', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Classes build over time' },
  { reference: 'SYS-DASHBOARD-MGMT-SOP-149', title: 'Set Up Daily Management Snapshot Dashboard', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Management dashboard from day one' },
  { reference: 'SYS-DATA-VALIDATION-SOP-148', title: 'Validate Reporting Accuracy and Data Hygiene', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Data validation post-opening' },
  { reference: 'SYS-DEPOSIT-RULES-SOP-124', title: 'Configure Deposits and Prepayment Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Deposit rules before first booking' },
  { reference: 'SYS-EMAIL-TEMPLATE-LIBRARY-SOP-143', title: 'Configure Email Template Library and Tone of Voice', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Email templates before first automated send' },
  { reference: 'SYS-GOLIVE-CUTOVER-SOP-153', title: 'Go-Live Cutover and Support Plan', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Go-live cutover plan is pre-opening essential' },
  { reference: 'SYS-HOLIDAY-HOURS-SOP-132', title: 'Configure Public Holidays and Seasonal Hours', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Opening hours must be set before launch' },
  { reference: 'SYS-HYPERCARE-TRIAGE-SOP-154', title: 'Post-Go-Live Hypercare Issue Triage Process', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Hypercare triage for first 2 weeks' },
  { reference: 'SYS-JOINFEE-CHARGES-SOP-126', title: 'Configure Joining Fees and One-Off Charges', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Joining fees from first membership' },
  { reference: 'SYS-MAINT-HOLDS-SOP-131', title: 'Create Maintenance Holds and Blackout Dates', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Maintenance holds may be needed pre-opening' },
  { reference: 'SYS-MEM-BILLING-SOP-136', title: 'Configure Membership Billing Cycles', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Billing cycles before first direct debit' },
  { reference: 'SYS-MEM-FREEZE-LOGIC-SOP-137', title: 'Configure Freeze, Suspension and Cancellation Logic', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Freeze logic builds over time' },
  { reference: 'SYS-MEM-PRICING-SOP-138', title: 'Configure Member Pricing Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Member pricing before first sale' },
  { reference: 'SYS-MEM-TIERS-SOP-135', title: 'Build Membership Tiers and Benefits', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Membership tiers must be configured before first sale' },
  { reference: 'SYS-MENU-ARCHITECTURE-SOP-112', title: 'Build Service Menu Architecture', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Menu must be built before opening' },
  { reference: 'SYS-MGR-APPROVAL-ROLES-SOP-111', title: 'Configure Manager Approval Roles for Discounts and Refunds', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Approval roles before live' },
  { reference: 'SYS-PACKAGE-BUILD-SOP-115', title: 'Create Packages and Bundles', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Packages needed before first sale' },
  { reference: 'SYS-PAY-GATEWAY-SOP-139', title: 'Configure Payment Gateway Integration', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Payment gateway before first transaction' },
  { reference: 'SYS-PERM-MATRIX-SOP-107', title: 'Permission Matrix Setup and Review', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Permission matrix must be set before opening' },
  { reference: 'SYS-PREGO-LIVE-TEST-SOP-151', title: 'Pre-Go-Live System Test Script Execution', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pre-go-live testing MUST happen before opening' },
  { reference: 'SYS-PRICING-BASE-SOP-120', title: 'Set Base Pricing and Price Lists', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Pricing must be set before first booking' },
  { reference: 'SYS-PRICING-PEAKOFF-SOP-121', title: 'Configure Peak and Off-Peak Pricing Rules', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Peak/off-peak can be refined post-launch' },
  { reference: 'SYS-PROMO-CODES-SOP-127', title: 'Configure Promotional Codes and Campaign Rules', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Promos can be added post-opening' },
  { reference: 'SYS-PT-CAPACITY-SOP-134', title: 'Configure PT Resources and Trainer Capacities', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'PT resources post-opening' },
  { reference: 'SYS-PT-PRODUCTS-SOP-117', title: 'Build Personal Training Products and Packages', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'PT products build over time' },
  { reference: 'SYS-REC-OVERRIDE-PERM-SOP-110', title: 'Configure Reception Override Permissions', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Override permissions before live' },
  { reference: 'SYS-RECEIPT-BRANDING-SOP-142', title: 'Configure Receipt Branding and Legal Text', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Receipt branding before first transaction' },
  { reference: 'SYS-RECEIPT-TEMPLATE-SOP-140', title: 'Configure Receipt and Tax Invoice Templates', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Receipts needed from first transaction' },
  { reference: 'SYS-REPORT-AUTOMATION-SOP-150', title: 'Schedule Automated Report Distribution', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Automated reports can be scheduled post-opening' },
  { reference: 'SYS-REPORT-DAILYREV-SOP-144', title: 'Configure Daily Revenue Reports', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Daily revenue reports from day one' },
  { reference: 'SYS-REPORT-MEMBERSHIP-SOP-146', title: 'Configure Membership Performance Reports', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Membership reports after first month' },
  { reference: 'SYS-REPORT-RETAIL-SOP-147', title: 'Configure Retail Sales Reports', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Retail reports from day one' },
  { reference: 'SYS-REPORT-UTILISATION-SOP-145', title: 'Configure Utilisation and Productivity Reports', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Utilisation reports after first week' },
  { reference: 'SYS-RESOURCE-ALLOC-SOP-129', title: 'Configure Resource Allocation Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Resource allocation before first booking' },
  { reference: 'SYS-RESOURCE-INVENTORY-SOP-128', title: 'Build Room and Resource Inventory', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Rooms/resources before scheduling' },
  { reference: 'SYS-SERVICE-COPY-SOP-118', title: 'Configure Service Descriptions and Guest-Facing Copy', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Guest-facing copy before launch' },
  { reference: 'SYS-SERVICE-IMAGES-SOP-119', title: 'Configure Service Images and Display Order', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Images before launch' },
  { reference: 'SYS-TAX-VAT-SOP-125', title: 'Configure Tax and VAT Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'VAT must be correct from first transaction' },
  { reference: 'SYS-THERAPIST-PROFILE-SOP-108', title: 'Therapist and Trainer Profile Management', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Therapist profiles needed for scheduling' },
  { reference: 'SYS-TREATMENT-CREATE-SOP-113', title: 'Create Treatment Services and Variants', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Treatments must exist in system' },
  { reference: 'SYS-UAT-SIGNOFF-SOP-152', title: 'User Acceptance Testing and Sign-Off', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'UAT sign-off is pre-opening gate' },
  { reference: 'SYS-USER-ACCOUNTS-SOP-106', title: 'Create User Accounts and Assign Roles', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Must be done before any staff log in' },
  { reference: 'SYS-USER-AUDIT-ACCESS-SOP-109', title: 'Audit User Access and Remove Leavers', department: 'SPA MANAGEMENT TEAM', tier: 'month-1', why: 'Audit process post-opening' },
  { reference: 'SYS-VOUCHER-CONFIG-SOP-141', title: 'Configure Gift Voucher Products and Redemption Rules', department: 'SPA MANAGEMENT TEAM', tier: 'day-1', why: 'Gift vouchers before first sale' },
  { reference: 'FAC-MUSIC-ZONING-SOP-353', title: 'Music System Control and Zoning', department: 'SPA SUPERVISORS', tier: 'day-1', why: 'Music zoning before first guest' },
  { reference: 'OPS-TREATMENT-ROOM-STANDARDISE-SOP-424', title: 'Treatment Room Setup Standardisation', department: 'SPA SUPERVISORS', tier: 'day-1', why: 'Treatment room standardisation before opening' },
  { reference: 'RET-HIVALUE-STOCK-SEC-SOP-369', title: 'Retail High-Value Stock Security Controls', department: 'SPA SUPERVISORS', tier: 'day-1', why: 'High-value stock security from day one' },
  { reference: 'SEC-WRISTBAND-TOKEN-SOP-362', title: 'Guest Wristband and Access Token Management', department: 'SPA SUPERVISORS', tier: 'day-1', why: 'Wristband/token management from day one' },
  { reference: 'THER-BED-SERVICE-SOP-356', title: 'Treatment Bed Inspection and Servicing', department: 'SPA SUPERVISORS', tier: 'day-1', why: 'Treatment bed inspection before opening' },
  { reference: 'THER-ADDON-DELIV-SOP-201', title: 'Add-On and Upgrade Delivery Standard', department: 'SPA THERAPISTS', tier: 'month-1', why: 'Add-ons build after core menu is running' },
  { reference: 'THER-BIOHAZARD-RESP-SOP-213', title: 'Biohazard and Blood Spill Response in Treatment Areas', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - biohazard response' },
  { reference: 'THER-BODY-DELIV-SOP-199', title: 'Body Treatment Service Delivery Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Body treatment delivery from day one' },
  { reference: 'THER-CANCEL-MIDSVC-SOP-216', title: 'Treatment Cancellation Mid-Service Procedure', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Mid-treatment cancellations can occur' },
  { reference: 'THER-CONSULT-CONSENT-SOP-188', title: 'Consultation, Consent and Contraindications', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - consultation before every treatment' },
  { reference: 'THER-CONTRA-RECORD-SOP-219', title: 'Product and Contraindication Recording Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Contraindication recording - safety and legal' },
  { reference: 'THER-CORE-CHOREO-SOP-196', title: 'Treatment Choreography Standards (General)', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Core choreography is treatment delivery foundation' },
  { reference: 'THER-COUPLE-DELIV-SOP-200', title: 'Couples Treatment Service Delivery Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Couples treatments from day one' },
  { reference: 'THER-FACIAL-DELIV-SOP-198', title: 'Facial Service Delivery Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Facial delivery from day one' },
  { reference: 'THER-GUEST-PREF-NOTES-SOP-220', title: 'Guest Preference Profile Updates and Notes Hygiene', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Guest preference profiles from first visit' },
  { reference: 'THER-GUEST-REACTION-SOP-215', title: 'Guest Discomfort or Adverse Reaction Response', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - adverse reaction response' },
  { reference: 'THER-HEAT-THERAPY-SOP-194', title: 'Heat Therapy Safety (Steam, Hot Towels, Stones)', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - heat safety before any heat therapy' },
  { reference: 'THER-INCIDENT-ESCALATE-SOP-217', title: 'Clinical Incident Escalation Procedure', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - incident escalation' },
  { reference: 'THER-LATE-RECOVERY-SOP-214', title: 'Late Running Treatment Recovery Protocol', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Late-running treatments happen from day one' },
  { reference: 'THER-LINEN-BED-SOP-207', title: 'Linen Change and Bed Presentation Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Linen change between every treatment' },
  { reference: 'THER-MASS-DELIV-SOP-197', title: 'Massage Service Delivery Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Massage delivery from day one' },
  { reference: 'THER-MEDICAL-CONDITIONS-SOP-189', title: 'Pregnancy and Medical Condition Handling', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - pregnancy/medical' },
  { reference: 'THER-MINORS-CONSENT-SOP-193', title: 'Minors Consent and Age Policy Procedure', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY/LEGAL - minors policy before opening' },
  { reference: 'THER-NOTES-COMPLETE-SOP-218', title: 'Treatment Notes Completion Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Treatment notes after every session' },
  { reference: 'THER-PATCH-FOLLOWUP-SOP-195', title: 'Patch Test Recording and Follow-Up', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Patch test follow-up process needed' },
  { reference: 'THER-PATCH-TEST-SOP-190', title: 'Patch Test and Sensitivity Procedure', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - patch testing before first use' },
  { reference: 'THER-PRIVACY-DRAPING-SOP-191', title: 'Client Privacy, Draping and Modesty Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Draping is fundamental professional standard' },
  { reference: 'THER-PUNCTUALITY-SOP-204', title: 'Therapist Punctuality and Knock/Entry Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Punctuality standard from day one' },
  { reference: 'THER-REFRESH-SVC-SOP-205', title: 'Pre- and Post-Treatment Refreshment Service Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Pre/post treatment refreshments from day one' },
  { reference: 'THER-RETAIL-GUIDE-SOP-203', title: 'Therapist-Guided Retail Recommendation Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Retail recommendation from every treatment' },
  { reference: 'THER-ROOM-CLOSING-SOP-186', title: 'Treatment Room Closing and Shutdown', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Room close after every treatment day' },
  { reference: 'THER-ROOM-OPENING-SOP-185', title: 'Treatment Room Opening Setup Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Room setup before first treatment' },
  { reference: 'THER-ROOM-RESET-SOP-206', title: 'Room Turnover and Reset Standard', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Room reset between every treatment' },
  { reference: 'THER-SAFEGUARDING-SOP-192', title: 'Safeguarding and Vulnerable Guest Protocol in Treatment Areas', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY CRITICAL - safeguarding must be in place before opening' },
  { reference: 'THER-SHARPS-HANDLING-SOP-212', title: 'Handling Sharps and Blades (Where Applicable)', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY - sharps handling if applicable' },
  { reference: 'THER-SHIFT-HANDOVER-SOP-187', title: 'Therapist Shift End Sign-Off and Handover', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Handover from day one' },
  { reference: 'THER-SHIFT-START-SOP-184', title: 'Therapist Shift Start and Room Readiness', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Therapist shift start from day one' },
  { reference: 'THER-SINGLEUSE-CONTROL-SOP-210', title: 'Single-Use Item Control and Disposal', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Single-use control from day one' },
  { reference: 'THER-SPILL-MGMT-SOP-211', title: 'Spillage Management in Treatment Rooms', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Spill management in treatment rooms' },
  { reference: 'THER-TIME-MGMT-SOP-202', title: 'Time Management and On-Schedule Service Delivery', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Time management critical for scheduling' },
  { reference: 'THER-TOOL-CLEAN-SOP-209', title: 'Tool Cleaning and Disinfection Procedure', department: 'SPA THERAPISTS', tier: 'day-1', why: 'SAFETY/HYGIENE - cleaning tools between treatments' },
  { reference: 'THER-TROLLEY-STOCK-SOP-208', title: 'Trolley Restock and Backbar Control', department: 'SPA THERAPISTS', tier: 'day-1', why: 'Trolley stocking before every shift' },
  { reference: 'DES-GUEST-JOURNEY-REHEARSAL-SOP-429', title: 'Guest Journey Rehearsal and Timing Validation', department: 'TRAINING TEAM', tier: 'day-1', why: 'Guest journey rehearsal before opening' },
  { reference: 'OPS-DRYRUN-EXECUTION-SOP-428', title: 'Operational Dry Run Day Plan and Execution', department: 'TRAINING TEAM', tier: 'day-1', why: 'Dry run before soft opening' },
  { reference: 'SYS-B4T-TRAINING-ENV-SOP-427', title: 'Book4Time Training Environment Setup', department: 'TRAINING TEAM', tier: 'day-1', why: 'Book4Time training environment before UAT' },
  { reference: 'TRN-BOOK4TIME-USER-SOP-403', title: 'Retail and Membership Sales Training Delivery', department: 'TRAINING TEAM', tier: 'day-1', why: 'Book4Time user training before going live' },
  { reference: 'TRN-COACHING-OBSERVATION-SOP-408', title: 'Trainer Observation and Coaching Procedure', department: 'TRAINING TEAM', tier: 'month-1', why: 'Coaching observation after first month' },
  { reference: 'TRN-COMPETENCY-SIGNOFF-SOP-406', title: 'Competency Assessment and Sign-Off Process', department: 'TRAINING TEAM', tier: 'day-1', why: 'Competency sign-off before staff go live' },
  { reference: 'TRN-EMERGENCY-PROCEDURES-SOP-405', title: 'Role Play Sessions for Reception and Sales', department: 'TRAINING TEAM', tier: 'day-1', why: 'Emergency procedures training before opening' },
  { reference: 'TRN-INDUCTION-DELIVERY-SOP-397', title: 'Induction Programme Delivery Standard', department: 'TRAINING TEAM', tier: 'day-1', why: 'Induction must be complete before opening' },
  { reference: 'TRN-MANDATORY-COMPLIANCE-SOP-399', title: 'Mandatory Training Compliance Tracking', department: 'TRAINING TEAM', tier: 'day-1', why: 'LEGAL - mandatory training tracked from day one' },
  { reference: 'TRN-NEEDS-ANALYSIS-SOP-401', title: 'Training Needs Analysis and Gap Identification', department: 'TRAINING TEAM', tier: 'month-1', why: 'TNA after first month operational' },
  { reference: 'TRN-RECORDS-MGMT-SOP-400', title: 'Training Records Management and Evidence', department: 'TRAINING TEAM', tier: 'day-1', why: 'Training records from day one' },
  { reference: 'TRN-REFRESHER-SCHEDULING-SOP-407', title: 'Refresher Training Trigger and Scheduling', department: 'TRAINING TEAM', tier: 'quarter-1', why: 'Refresher training quarterly' },
  { reference: 'TRN-ROLEPATH-ASSIGN-SOP-398', title: 'Role-Based Training Pathway Assignment', department: 'TRAINING TEAM', tier: 'day-1', why: 'Training pathways before opening' },]

export function plannedByTier(tier: BuildTier): PlannedDocument[] {
  return LIBRARY_PLAN.filter(entry => entry.tier === tier)
}

export function departments(): string[] {
  return Array.from(new Set(LIBRARY_PLAN.map(entry => entry.department))).sort()
}
