import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

type JobRow={id:string;title:string;tier:string;daysLive:number;totalApps:number;shortlisted:number;avgScore:number;status:string}
const WEB_URL=process.env.EXPO_PUBLIC_WEB_URL||'https://talent.wellnesshousecollective.co.uk'

export default function AnalyticsScreen(){
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [stats,setStats]=useState({activeListings:0,totalAppsMonth:0,totalAppsLastMonth:0,avgMatch:0,avgDaysToFirst:0});const [jobs,setJobs]=useState<JobRow[]>([]);const [funnel,setFunnel]=useState<Record<string,number>>({});const [topSkills,setTopSkills]=useState<string[]>([])
 useEffect(()=>{load()},[])
 async function load(){setLoading(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){router.replace('/login');return}const res=await fetch(`${WEB_URL}/api/mobile/analytics`,{headers:{Authorization:`Bearer ${session.access_token}`}});const body=await res.json().catch(()=>({}));if(res.status===403){router.replace('/home');return}if(!res.ok)throw new Error(body.error||'Could not load analytics.');setStats({activeListings:Number(body.stats?.activeListings||0),totalAppsMonth:Number(body.stats?.totalAppsMonth||0),totalAppsLastMonth:Number(body.stats?.totalAppsLastMonth||0),avgMatch:Number(body.stats?.avgMatch||0),avgDaysToFirst:Number(body.stats?.avgDaysToFirst||0)});setJobs(body.jobs||[]);setFunnel(body.funnel||{});setTopSkills(body.topSkills||[])}catch(e:any){setError(e?.message||'Could not load analytics.')}finally{setLoading(false)}}
 const pct=stats.totalAppsLastMonth>0?Math.round(((stats.totalAppsMonth-stats.totalAppsLastMonth)/stats.totalAppsLastMonth)*100):stats.totalAppsMonth>0?100:0;const maxFunnel=Math.max(1,funnel.total||0);const sortedJobs=useMemo(()=>[...jobs].sort((a,b)=>b.totalApps-a.totalApps),[jobs])
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>EMPLOYER PERFORMANCE</Text><Text style={styles.title}>Analytics</Text><Text style={styles.intro}>A mobile view of how your live roles are performing and how candidates are moving through the funnel.</Text>{loading?<ActivityIndicator color="#0b2f4d" style={{marginTop:28}}/>:null}{error?<Text style={styles.error}>{error}</Text>:null}{!loading?<><View style={styles.grid}><Stat label="Active listings" value={String(stats.activeListings)}/><Stat label="Applications this month" value={String(stats.totalAppsMonth)} sub={pct?`${pct>0?'+':''}${pct}% vs last month`:undefined}/><Stat label="Average match" value={stats.avgMatch?`${stats.avgMatch}%`:'—'}/><Stat label="Avg time to first application" value={`${stats.avgDaysToFirst}d`}/></View><Text style={styles.section}>Application funnel</Text><View style={styles.card}>{[['Applications received','total'],['Pending review','pending'],['Shortlisted','shortlisted'],['Accepted','accepted']].map(([label,key])=>{const count=funnel[key]||0;return <View key={key} style={styles.funnelRow}><View style={{flex:1}}><View style={styles.funnelTop}><Text style={styles.funnelLabel}>{label}</Text><Text style={styles.funnelCount}>{count}</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${Math.max(3,Math.round(count/maxFunnel*100))}%`}]} /></View></View></View>})}<View style={styles.rejected}><Text style={styles.funnelLabel}>Rejected</Text><Text style={styles.funnelCount}>{funnel.rejected||0}</Text></View></View><Text style={styles.section}>Top applicant skills</Text><View style={styles.card}>{topSkills.length?topSkills.map((skill,i)=><View key={skill} style={styles.skillRow}><Text style={styles.rank}>{i+1}</Text><Text style={styles.skill}>{skill}</Text></View>):<Text style={styles.empty}>No applicant skill data yet.</Text>}</View><Text style={styles.section}>Job performance</Text><View style={styles.list}>{sortedJobs.length?sortedJobs.map(job=><Pressable key={job.id} onPress={()=>router.push({pathname:'/employer-job/[id]',params:{id:job.id}})} style={styles.job}><View style={styles.jobTop}><Text style={styles.jobTitle}>{job.title}</Text><Text style={styles.jobStatus}>{job.status.toUpperCase()}</Text></View><Text style={styles.jobMeta}>{job.tier} · {job.daysLive} days · {job.totalApps} applications</Text><Text style={styles.jobMeta}>{job.shortlisted} shortlisted · {job.avgScore?`${job.avgScore}% avg match`:'No match score yet'}</Text><Text style={styles.open}>Open role →</Text></Pressable>):<Text style={styles.empty}>No jobs yet.</Text>}</View></>:null}</ScrollView>
}
function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text>{sub?<Text style={styles.statSub}>{sub}</Text>:null}</View>}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:100},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#0b2f4d',fontSize:30,lineHeight:36,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:24},error:{color:'#9b2c2c',fontSize:12,marginBottom:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{width:'48%',borderWidth:1,borderColor:'#dce3e7',padding:15,minHeight:105},statValue:{color:'#0b2f4d',fontSize:25,fontWeight:'600'},statLabel:{color:'#66747c',fontSize:10,lineHeight:15,marginTop:5},statSub:{color:'#456655',fontSize:9,marginTop:4},section:{color:'#173246',fontSize:17,fontWeight:'600',marginTop:27,marginBottom:10},card:{borderWidth:1,borderColor:'#dce3e7',padding:16},funnelRow:{marginBottom:14},funnelTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},funnelLabel:{color:'#66747c',fontSize:11},funnelCount:{color:'#173246',fontSize:11,fontWeight:'700'},track:{height:8,backgroundColor:'#edf1f3',overflow:'hidden'},fill:{height:8,backgroundColor:'#0b2f4d'},rejected:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:'#edf1f3',paddingTop:12},skillRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#edf1f3'},rank:{width:22,height:22,borderRadius:11,textAlign:'center',lineHeight:22,backgroundColor:'#eef2f4',color:'#0b2f4d',fontSize:10,fontWeight:'700'},skill:{color:'#173246',fontSize:12},list:{gap:10},job:{borderWidth:1,borderColor:'#dce3e7',padding:16},jobTop:{flexDirection:'row',justifyContent:'space-between',gap:10},jobTitle:{color:'#173246',fontSize:15,fontWeight:'600',flex:1},jobStatus:{color:'#456655',fontSize:8,fontWeight:'800',letterSpacing:1.1},jobMeta:{color:'#71808a',fontSize:10,lineHeight:16,marginTop:5},open:{color:'#0b2f4d',fontSize:10,fontWeight:'700',marginTop:10},empty:{color:'#71808a',fontSize:11,lineHeight:17}})