import { useEffect, useState } from 'react'
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

type Role='talent'|'employer'
type AwardItem={name:string;issuer?:string;year?:string;url?:string}
const blank=():AwardItem=>({name:'',issuer:'',year:'',url:''})

export default function AwardsScreen(){
 const [role,setRole]=useState<Role>('talent');const [profileId,setProfileId]=useState('');const [awards,setAwards]=useState<AwardItem[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:account}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();const resolved:Role=account?.role==='employer'?'employer':'talent';setRole(resolved);const table=resolved==='talent'?'candidate_profiles':'employer_profiles';const {data,error:e}=await supabase.from(table).select('id,awards').eq('user_id',user.id).maybeSingle();if(e)setError(e.message);if(data){setProfileId(data.id);setAwards(Array.isArray(data.awards)?data.awards:[])}setLoading(false)}
 function update(i:number,key:keyof AwardItem,value:string){setAwards(current=>current.map((a,index)=>index===i?{...a,[key]:value}:a))}
 async function save(){if(!profileId)return;setSaving(true);setError('');const clean=awards.map(a=>({name:String(a.name||'').trim().slice(0,180),issuer:String(a.issuer||'').trim().slice(0,180),year:String(a.year||'').trim().slice(0,20),url:String(a.url||'').trim().slice(0,500)})).filter(a=>a.name);const table=role==='talent'?'candidate_profiles':'employer_profiles';const {error:e}=await supabase.from(table).update({awards:clean}).eq('id',profileId);setSaving(false);if(e){setError(e.message);return}setAwards(clean);Alert.alert('Saved','Your awards and recognition have been updated.')}
 if(loading)return <View style={styles.center}><ActivityIndicator color="#0b2f4d"/></View>
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>{role==='talent'?'CAREER PROFILE':'PROPERTY PROFILE'}</Text><Text style={styles.title}>Awards & recognition</Text><Text style={styles.intro}>{role==='talent'?'Add genuine professional awards so employers can see the recognition behind your experience.':'Add genuine property, spa or employer awards so Talent can see the recognition behind your brand.'}</Text>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable onPress={()=>setAwards(a=>[...a,blank()])} style={styles.add}><Text style={styles.addText}>+ Add award</Text></Pressable><View style={styles.list}>{awards.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No awards added yet.</Text><Text style={styles.emptyCopy}>Add only genuine awards and include the awarding body and year where possible.</Text></View>:awards.map((award,i)=><View key={i} style={styles.card}><View style={styles.cardTop}><Text style={styles.cardLabel}>AWARD {i+1}</Text><Pressable onPress={()=>setAwards(a=>a.filter((_,x)=>x!==i))}><Text style={styles.remove}>Remove</Text></Pressable></View><Text style={styles.label}>Award name</Text><TextInput style={styles.input} value={award.name||''} onChangeText={v=>update(i,'name',v)} placeholder="e.g. Best Hotel Spa UK"/><Text style={styles.label}>Awarding body</Text><TextInput style={styles.input} value={award.issuer||''} onChangeText={v=>update(i,'issuer',v)} placeholder="e.g. Good Spa Guide"/><View style={styles.row}><View style={styles.half}><Text style={styles.label}>Year</Text><TextInput style={styles.input} value={award.year||''} onChangeText={v=>update(i,'year',v)} placeholder="2026"/></View><View style={styles.half}><Text style={styles.label}>Evidence link</Text><TextInput style={styles.input} value={award.url||''} onChangeText={v=>update(i,'url',v)} placeholder="https://" autoCapitalize="none"/></View></View>{award.url?<Pressable onPress={()=>Linking.openURL(award.url!)}><Text style={styles.link}>Open evidence →</Text></Pressable>:null}</View>)}</View><Pressable disabled={saving} onPress={save} style={[styles.save,saving&&{opacity:.5}]}><Text style={styles.saveText}>{saving?'Saving...':'Save awards'}</Text></Pressable></ScrollView>
}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:100},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#0b2f4d',fontSize:30,lineHeight:36,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:22},error:{color:'#9b2c2c',fontSize:12,marginBottom:14},add:{alignSelf:'flex-start',borderWidth:1,borderColor:'#cbd7dc',paddingHorizontal:16,paddingVertical:10,marginBottom:16},addText:{color:'#0b2f4d',fontSize:11,fontWeight:'700'},list:{gap:12},card:{borderWidth:1,borderColor:'#dce3e7',padding:17},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},cardLabel:{fontSize:9,letterSpacing:1.4,color:'#71808a'},remove:{color:'#9b2c2c',fontSize:10},label:{color:'#71808a',fontSize:9,letterSpacing:1,marginTop:9,marginBottom:5},input:{borderWidth:1,borderColor:'#dce3e7',paddingHorizontal:12,paddingVertical:11,color:'#173246',fontSize:12,backgroundColor:'#fff'},row:{flexDirection:'row',gap:10},half:{flex:1},link:{color:'#0b2f4d',fontSize:10,fontWeight:'700',marginTop:10},empty:{backgroundColor:'#f4f7f8',padding:20},emptyTitle:{color:'#173246',fontSize:14,fontWeight:'600'},emptyCopy:{color:'#71808a',fontSize:11,lineHeight:17,marginTop:5},save:{backgroundColor:'#0b2f4d',paddingVertical:14,alignItems:'center',marginTop:20},saveText:{color:'#fff',fontSize:12,fontWeight:'700'}})