import { useEffect, useState } from 'react'
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

const BUCKET='property-fact-documents'
function entries(obj:any){if(!obj||typeof obj!=='object')return [] as [string,any][];return Object.entries(obj).filter(([,v])=>v!==null&&v!==undefined&&v!==''&&v!==false) as [string,any][]}
function label(k:string){return k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}

export default function BeforeYouArriveScreen(){
 const [packs,setPacks]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [opening,setOpening]=useState('');const [error,setError]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:profile}=await supabase.from('candidate_profiles').select('id').eq('user_id',user.id).maybeSingle();if(profile){const {data,error:e}=await supabase.from('booking_arrival_packs').select('*').eq('candidate_id',profile.id).order('generated_at',{ascending:false});if(e)setError(e.message);setPacks(data||[])}setLoading(false)}
 async function acknowledge(id:string){setBusy(id);const now=new Date().toISOString();const {error:e}=await supabase.from('booking_arrival_packs').update({acknowledged_at:now}).eq('id',id);if(e)setError(e.message);else setPacks(p=>p.map(x=>x.id===id?{...x,acknowledged_at:now}:x));setBusy('')}
 async function openDoc(doc:any){if(!doc?.path)return;setOpening(doc.path);setError('');const {data,error:e}=await supabase.storage.from(BUCKET).createSignedUrl(doc.path,600);setOpening('');if(e||!data?.signedUrl){setError('This document could not be opened.');return}await Linking.openURL(data.signedUrl)}
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>CONFIRMED FLEXIBLE WORK</Text><Text style={styles.title}>Before You Arrive</Text><Text style={styles.intro}>Your confirmed Agency and Residency arrival packs live here, so the practical details are still available after you accept.</Text>{loading?<ActivityIndicator color="#092b45" style={{marginTop:28}}/>:null}{error?<Text style={styles.error}>{error}</Text>:null}{!loading&&packs.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No confirmed arrival packs yet.</Text><Text style={styles.emptyCopy}>A pack will appear here automatically once an Agency shift or Residency placement is confirmed.</Text></View>:null}<View style={styles.list}>{packs.map(pack=>{const s=pack.snapshot||{};const docs=Array.isArray(s.documents)?s.documents:[];return <View key={pack.id} style={styles.card}><Text style={styles.type}>{pack.booking_type==='residency'?'RESIDENCY PLACEMENT':'AGENCY SHIFT'}</Text><Text style={styles.property}>{s.property?.name||'Property'}</Text><Text style={styles.generated}>Generated {pack.generated_at?new Date(pack.generated_at).toLocaleString('en-GB'):'—'}</Text>{pack.acknowledged_at?<View style={styles.ack}><Text style={styles.ackText}>✓ Read & acknowledged</Text></View>:<Pressable disabled={busy===pack.id} onPress={()=>acknowledge(pack.id)} style={styles.primary}><Text style={styles.primaryText}>{busy===pack.id?'Saving...':'I have read this pack'}</Text></Pressable>}<Section title="Getting there" data={s.property}/><Section title="Arrival & shift" data={{...(s.arrival||{}),...(s.booking||{})}}/><Section title="Welfare & breaks" data={s.welfare}/><Section title="Safety essentials" data={s.safety}/><Section title="Spa operations & expectations" data={s.spa}/>{pack.booking_type==='residency'?<Section title="Residency stay details" data={s.residency}/>:null}{docs.length?<View style={styles.section}><Text style={styles.sectionTitle}>Useful documents</Text>{docs.map((doc:any,i:number)=><Pressable key={`${doc.path}-${i}`} disabled={opening===doc.path} onPress={()=>openDoc(doc)} style={styles.doc}><View style={{flex:1}}><Text style={styles.docTitle}>{doc.name||'Document'}</Text><Text style={styles.docCopy}>Secure document from this confirmed property pack</Text></View><Text style={styles.docOpen}>{opening===doc.path?'Opening...':'Open →'}</Text></Pressable>)}</View>:null}</View>})}</View></ScrollView>
}
function Section({title,data}:{title:string;data:any}){const rows=entries(data);if(!rows.length)return null;return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{rows.map(([k,v])=><View key={k} style={styles.fact}><Text style={styles.factLabel}>{label(k)}</Text><Text style={styles.factValue}>{typeof v==='boolean'?(v?'Yes':'No'):String(v)}</Text></View>)}</View>}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:100},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#092b45',fontSize:30,lineHeight:36,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:24},error:{color:'#9b2c2c',fontSize:12,marginBottom:14},list:{gap:14},card:{borderWidth:1,borderColor:'#dce3e7',padding:18},type:{color:'#9c7a42',fontSize:9,fontWeight:'700',letterSpacing:1.4},property:{color:'#173246',fontSize:20,fontWeight:'600',marginTop:6},generated:{color:'#8a969d',fontSize:10,marginTop:5},primary:{backgroundColor:'#092b45',paddingVertical:12,alignItems:'center',marginTop:15},primaryText:{color:'#fff',fontSize:11,fontWeight:'700'},ack:{backgroundColor:'#eef5f0',padding:11,marginTop:15},ackText:{color:'#456655',fontSize:11,fontWeight:'700'},section:{borderTopWidth:1,borderTopColor:'#edf1f3',paddingTop:14,marginTop:16},sectionTitle:{color:'#173246',fontSize:13,fontWeight:'700',marginBottom:7},fact:{paddingVertical:7},factLabel:{color:'#8a969d',fontSize:8,letterSpacing:1,textTransform:'uppercase'},factValue:{color:'#5f6e77',fontSize:11,lineHeight:17,marginTop:3},doc:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#e2e8eb',padding:12,marginTop:8},docTitle:{color:'#173246',fontSize:11,fontWeight:'600'},docCopy:{color:'#71808a',fontSize:9,lineHeight:14,marginTop:2},docOpen:{color:'#9c7a42',fontSize:10,fontWeight:'700'},empty:{backgroundColor:'#f4f7f8',padding:20},emptyTitle:{color:'#173246',fontSize:14,fontWeight:'600'},emptyCopy:{color:'#71808a',fontSize:11,lineHeight:17,marginTop:5}})