import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'
import { calculateMatchScore } from '../src/lib/matching'

export default function DiscoverTalent(){
 const [items,setItems]=useState<any[]>([]); const [jobs,setJobs]=useState<any[]>([]); const [selectedJobId,setSelectedJobId]=useState(''); const [loading,setLoading]=useState(true); const [locked,setLocked]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return}
  const {data:employer}=await supabase.from('employer_profiles').select('id,membership_tier').eq('user_id',user.id).maybeSingle(); const tier=String(employer?.membership_tier||'free').toLowerCase(); if(!['pro','group'].includes(tier)){setLocked(true);setLoading(false);return}
  const {data:jobRows}=employer?.id?await supabase.from('job_listings').select('*').eq('employer_id',employer.id).order('posted_date',{ascending:false}):{data:[] as any[]}; setJobs(jobRows||[]); if(jobRows?.[0]?.id)setSelectedJobId(jobRows[0].id)
  const {data}=await supabase.from('candidate_profiles').select('*').or('profile_visible.eq.true,profile_visible.is.null').eq('stealth_mode',false).order('is_featured',{ascending:false}).limit(100)
  setItems(data||[]); setLoading(false)
 }
 const selectedJob=jobs.find(job=>job.id===selectedJobId)||null
 const ranked=useMemo(()=>items.map(item=>({item,match:selectedJob?calculateMatchScore(item,selectedJob):null})).sort((a,b)=>{if(Boolean(b.item.is_featured)!==Boolean(a.item.is_featured))return Number(Boolean(b.item.is_featured))-Number(Boolean(a.item.is_featured));return Number(b.match?.score||0)-Number(a.match?.score||0)}),[items,selectedJobId,jobs])
 if(locked)return <View style={styles.lockPage}><Text style={styles.lockIcon}>🔒</Text><Text style={styles.lockTitle}>Discover Talent is a Pro feature.</Text><Text style={styles.lockCopy}>Upgrade your Employer plan on the website to unlock full talent search and discovery in the app.</Text><Pressable onPress={()=>router.back()} style={styles.outline}><Text style={styles.outlineText}>Back</Text></Pressable></View>
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>DISCOVER</Text><Text style={styles.title}>Talent</Text><Text style={styles.intro}>{selectedJob?'Candidates are ranked against the role you choose using the same WHC matching logic as the website.':'Choose one of your roles to see the strongest candidate matches.'}</Text>
 {jobs.length?<><Text style={styles.section}>Match against</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.jobPicker}>{jobs.map(job=><Pressable key={job.id} onPress={()=>setSelectedJobId(job.id)} style={[styles.jobChip,selectedJobId===job.id&&styles.jobChipActive]}><Text style={[styles.jobChipText,selectedJobId===job.id&&styles.jobChipTextActive]}>{job.job_title}</Text></Pressable>)}</ScrollView></>:<View style={styles.notice}><Text style={styles.noticeTitle}>Post a role first</Text><Text style={styles.noticeCopy}>Talent discovery works best when it can rank professionals against a real job description and requirements.</Text></View>}
 {loading?<ActivityIndicator color="#092b45" style={{marginTop:30}}/>:null}<View style={styles.list}>{ranked.map(({item,match})=>{const display=item.show_first_name_only&&item.full_name?item.full_name.split(' ')[0]:item.full_name||'Talent profile';return <View key={item.id} style={[styles.card,item.is_featured&&styles.featured]}><View style={styles.row}><Text style={styles.name}>{display}</Text><View style={styles.badges}>{match?<Text style={styles.match}>{match.score}% MATCH</Text>:null}{item.whc_verified?<Text style={styles.badge}>VERIFIED</Text>:null}{item.is_featured?<Text style={styles.badge}>FEATURED</Text>:null}</View></View><Text style={styles.headline}>{item.headline||[item.role_level,item.primary_specialism].filter(Boolean).join(' · ')}</Text><Text style={styles.meta}>{[item.location,item.years_experience?`${item.years_experience} yrs experience`:null].filter(Boolean).join(' · ')}</Text>{match?.matchExplanation?<Text style={styles.explanation}>{match.matchExplanation}</Text>:null}{match?.hardStop?<Text style={styles.warning}>{match.hardStopReason}</Text>:null}{Number(item.review_count||0)>0?<Text style={styles.review}>★ {Number(item.review_score||0).toFixed(1)} · {item.review_count} review{item.review_count===1?'':'s'}</Text>:null}<Pressable onPress={()=>router.push(`/message/${item.user_id}`)} style={styles.messageBtn}><Text style={styles.messageText}>Message</Text></Pressable></View>})}</View></ScrollView>
}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:44},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#092b45',fontSize:31,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:22},section:{color:'#173246',fontSize:12,fontWeight:'600',marginBottom:10},jobPicker:{gap:8,paddingBottom:18},jobChip:{borderWidth:1,borderColor:'#dce3e7',paddingHorizontal:13,paddingVertical:9},jobChipActive:{backgroundColor:'#092b45',borderColor:'#092b45'},jobChipText:{color:'#526976',fontSize:11},jobChipTextActive:{color:'#fff'},notice:{backgroundColor:'#f4f7f8',padding:16,marginBottom:18},noticeTitle:{color:'#173246',fontWeight:'600',fontSize:13},noticeCopy:{color:'#71808a',fontSize:11,lineHeight:17,marginTop:5},list:{gap:12},card:{borderWidth:1,borderColor:'#dce3e7',padding:18},featured:{backgroundColor:'#f7f9fa',borderColor:'#b9c7ce'},row:{flexDirection:'row',justifyContent:'space-between',gap:10},name:{color:'#173246',fontSize:16,fontWeight:'600',flex:1},badges:{flexDirection:'row',gap:6,flexWrap:'wrap',justifyContent:'flex-end'},badge:{fontSize:7,letterSpacing:1,color:'#092b45'},match:{fontSize:8,fontWeight:'700',letterSpacing:.7,color:'#092b45',borderWidth:1,borderColor:'#cdd8dd',paddingHorizontal:7,paddingVertical:3},headline:{color:'#465c69',fontSize:13,marginTop:7},meta:{color:'#71808a',fontSize:11,marginTop:7},explanation:{color:'#526976',fontSize:11,lineHeight:17,marginTop:9},warning:{color:'#8b3c3c',fontSize:11,lineHeight:17,marginTop:8},review:{color:'#526976',fontSize:11,marginTop:9},messageBtn:{marginTop:15,borderWidth:1,borderColor:'#092b45',paddingVertical:10,alignItems:'center'},messageText:{color:'#092b45',fontWeight:'600',fontSize:12},lockPage:{flex:1,backgroundColor:'#fff',padding:28,justifyContent:'center',alignItems:'center'},lockIcon:{fontSize:24,marginBottom:14},lockTitle:{color:'#092b45',fontSize:22,fontWeight:'600',textAlign:'center'},lockCopy:{color:'#66747c',fontSize:13,lineHeight:20,textAlign:'center',marginTop:10,maxWidth:330},outline:{borderWidth:1,borderColor:'#092b45',paddingHorizontal:28,paddingVertical:13,marginTop:24},outlineText:{color:'#092b45',fontWeight:'600'}})