import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

export default function DiscoverTalent(){
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [locked,setLocked]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return}
  const {data:employer}=await supabase.from('employer_profiles').select('membership_tier').eq('user_id',user.id).maybeSingle(); const tier=String(employer?.membership_tier||'free').toLowerCase(); if(!['pro','group'].includes(tier)){setLocked(true);setLoading(false);return}
  const {data}=await supabase.from('candidate_profiles').select('id,user_id,full_name,headline,location,role_level,primary_specialism,years_experience,review_score,review_count,is_featured,whc_verified,stealth_mode,profile_visible,show_first_name_only').eq('profile_visible',true).eq('stealth_mode',false).order('is_featured',{ascending:false}).limit(50)
  setItems(data||[]); setLoading(false)
 }
 if(locked)return <View style={styles.lockPage}><Text style={styles.lockIcon}>🔒</Text><Text style={styles.lockTitle}>Discover Talent is a Pro feature.</Text><Text style={styles.lockCopy}>Upgrade your Employer plan on the website to unlock full talent search and discovery in the app.</Text><Pressable onPress={()=>router.back()} style={styles.outline}><Text style={styles.outlineText}>Back</Text></Pressable></View>
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>DISCOVER</Text><Text style={styles.title}>Talent</Text><Text style={styles.intro}>Professionals currently visible to eligible employers.</Text>{loading?<ActivityIndicator color="#092b45" style={{marginTop:30}}/>:null}<View style={styles.list}>{items.map(item=>{const display=item.show_first_name_only&&item.full_name?item.full_name.split(' ')[0]:item.full_name||'Talent profile';return <View key={item.id} style={[styles.card,item.is_featured&&styles.featured]}><View style={styles.row}><Text style={styles.name}>{display}</Text><View style={{flexDirection:'row',gap:8}}>{item.whc_verified?<Text style={styles.badge}>VERIFIED</Text>:null}{item.is_featured?<Text style={styles.badge}>FEATURED</Text>:null}</View></View><Text style={styles.headline}>{item.headline||[item.role_level,item.primary_specialism].filter(Boolean).join(' · ')}</Text><Text style={styles.meta}>{[item.location,item.years_experience?`${item.years_experience} yrs experience`:null].filter(Boolean).join(' · ')}</Text>{Number(item.review_count||0)>0?<Text style={styles.review}>★ {Number(item.review_score||0).toFixed(1)} · {item.review_count} review{item.review_count===1?'':'s'}</Text>:null}<Pressable onPress={()=>router.push(`/message/${item.user_id}`)} style={styles.messageBtn}><Text style={styles.messageText}>Message</Text></Pressable></View>})}</View></ScrollView>
}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:44},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#092b45',fontSize:31,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:26},list:{gap:12},card:{borderWidth:1,borderColor:'#dce3e7',padding:18},featured:{backgroundColor:'#f7f9fa',borderColor:'#b9c7ce'},row:{flexDirection:'row',justifyContent:'space-between',gap:10},name:{color:'#173246',fontSize:16,fontWeight:'600',flex:1},badge:{fontSize:7,letterSpacing:1,color:'#092b45'},headline:{color:'#465c69',fontSize:13,marginTop:7},meta:{color:'#71808a',fontSize:11,marginTop:7},review:{color:'#526976',fontSize:11,marginTop:9},messageBtn:{marginTop:15,borderWidth:1,borderColor:'#092b45',paddingVertical:10,alignItems:'center'},messageText:{color:'#092b45',fontWeight:'600',fontSize:12},lockPage:{flex:1,backgroundColor:'#fff',padding:28,justifyContent:'center',alignItems:'center'},lockIcon:{fontSize:24,marginBottom:14},lockTitle:{color:'#092b45',fontSize:22,fontWeight:'600',textAlign:'center'},lockCopy:{color:'#66747c',fontSize:13,lineHeight:20,textAlign:'center',marginTop:10,maxWidth:330},outline:{borderWidth:1,borderColor:'#092b45',paddingHorizontal:28,paddingVertical:13,marginTop:24},outlineText:{color:'#092b45',fontWeight:'600'}})