import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

export default function InterviewReady(){
 const [credits,setCredits]=useState<number|null>(null); const [jobs,setJobs]=useState<any[]>([]); const [loading,setLoading]=useState(true)
 useEffect(()=>{load()},[])
 async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return}
  const {data:candidate}=await supabase.from('candidate_profiles').select('id,interview_ready_credits').eq('user_id',user.id).maybeSingle(); setCredits(Number(candidate?.interview_ready_credits||0))
  const {data:apps}=candidate?.id?await supabase.from('applications').select('role_id,status,job_listings:role_id(id,job_title,location,employer_profiles(property_name,company_name))').eq('candidate_id',candidate.id).neq('status','withdrawn').order('created_at',{ascending:false}):{data:[] as any[]}
  setJobs((apps||[]).map((x:any)=>x.job_listings).filter(Boolean)); setLoading(false)
 }
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>CONFIDENCE BUILDER</Text><Text style={styles.title}>Interview Ready</Text><Text style={styles.intro}>Built from your profile, experience and the role you are applying for. It helps you understand what the employer is really hiring for, identify your strongest evidence and prepare for harder questions.</Text>
 {loading?<ActivityIndicator color="#092b45" style={{marginTop:30}}/>:<><View style={styles.creditCard}><Text style={styles.creditNumber}>{credits}</Text><Text style={styles.creditLabel}>{credits===1?'PREPARATION CREDIT':'PREPARATION CREDITS'} LEFT</Text></View>{credits===0?<View style={styles.locked}><Text style={styles.lockTitle}>🔒 New preparation is locked</Text><Text style={styles.lockCopy}>Your current allowance has been used. Existing preparation remains available on the website while mobile AI preparation is being connected to the same secure backend.</Text></View>:null}<Text style={styles.section}>Roles to prepare for</Text>{jobs.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No active applications yet.</Text><Text style={styles.emptyCopy}>Apply for a role and it will appear here automatically.</Text></View>:<View style={styles.list}>{jobs.map(job=><View key={job.id} style={styles.card}><Text style={styles.job}>{job.job_title}</Text><Text style={styles.meta}>{[job.employer_profiles?.property_name||job.employer_profiles?.company_name,job.location].filter(Boolean).join(' · ')}</Text><Text style={styles.note}>Native AI preparation will use this exact role once the mobile authentication bridge is enabled.</Text></View>)}</View>}</>}
 </ScrollView>
}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:44},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#092b45',fontSize:31,fontWeight:'500'},intro:{color:'#66747c',fontSize:14,lineHeight:21,marginTop:10,marginBottom:24},creditCard:{backgroundColor:'#f4f7f8',padding:20,alignItems:'center'},creditNumber:{color:'#092b45',fontSize:34,fontWeight:'600'},creditLabel:{color:'#71808a',fontSize:9,letterSpacing:1.6,marginTop:4},locked:{borderWidth:1,borderColor:'#dce3e7',padding:18,marginTop:14},lockTitle:{color:'#173246',fontSize:14,fontWeight:'600'},lockCopy:{color:'#71808a',fontSize:11,lineHeight:17,marginTop:6},section:{color:'#092b45',fontSize:17,fontWeight:'600',marginTop:28,marginBottom:12},list:{gap:10},card:{borderWidth:1,borderColor:'#dce3e7',padding:18},job:{color:'#173246',fontSize:15,fontWeight:'600'},meta:{color:'#71808a',fontSize:11,marginTop:6},note:{color:'#8a969d',fontSize:10,lineHeight:15,marginTop:10},empty:{backgroundColor:'#f4f7f8',padding:20},emptyTitle:{color:'#173246',fontSize:14,fontWeight:'600'},emptyCopy:{color:'#71808a',fontSize:11,lineHeight:17,marginTop:6}})