import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { supabase } from '../src/lib/supabase'

function stateOf(item:any){if(item.done_at)return'DONE';if(item.opened_at)return'OPEN';return'NEW'}

export default function NotificationsScreen(){
 const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data}=await supabase.from('notifications').select('id,type,title,message,link,is_read,requires_action,opened_at,done_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(75);setItems(data||[]);setLoading(false)}
 async function markDone(item:any){setBusy(item.id);const now=new Date().toISOString();const {error}=await supabase.from('notifications').update({is_read:true,opened_at:item.opened_at||now,done_at:now}).eq('id',item.id);if(!error)setItems(current=>current.map(row=>row.id===item.id?{...row,is_read:true,opened_at:row.opened_at||now,done_at:now}:row));setBusy('')}
 async function markOpened(item:any){if(item.opened_at||item.done_at)return;const now=new Date().toISOString();const {error}=await supabase.from('notifications').update({opened_at:now,is_read:true}).eq('id',item.id);if(!error)setItems(current=>current.map(row=>row.id===item.id?{...row,opened_at:now,is_read:true}:row))}
 async function open(item:any){await markOpened(item);const link=String(item.link||'');if(link.includes('interview-ready'))router.push('/interview-ready');else if(link.includes('application'))router.push('/applications');else if(link.includes('message'))router.push('/messages');else if(link.includes('agency'))router.push('/agency');else if(link.includes('reputation')||link.includes('review')||link.includes('reference'))router.push('/reputation');else if(link.includes('academy'))router.push('/academy');else if(link.includes('before-you-arrive')||link.includes('arrival'))router.push('/before-you-arrive');else if(link.includes('award'))router.push('/awards');else if(link.includes('billing')||link.includes('featured')||link.includes('membership'))router.push('/billing');else if(link.includes('profile')||link.includes('verification'))router.push('/profile')}
 const outstanding=useMemo(()=>items.filter(item=>item.requires_action&&!item.done_at).length,[items]);const actionItems=items.filter(item=>item.requires_action);const updates=items.filter(item=>!item.requires_action)
 const renderItem=(item:any)=>{const state=stateOf(item);return <View key={item.id} style={[styles.card,item.requires_action&&state==='NEW'&&styles.cardNew,item.requires_action&&state==='OPEN'&&styles.cardOpen,state==='DONE'&&styles.cardDone]}><Pressable onPress={()=>open(item)}><View style={styles.row}><Text style={styles.cardTitle}>{item.title}</Text><Text style={item.requires_action?(state==='NEW'?styles.new:state==='OPEN'?styles.openState:styles.seen):styles.info}>{item.requires_action?state:'UPDATE'}</Text></View>{item.message?<Text style={styles.copy}>{item.message}</Text>:null}<Text style={styles.date}>{item.created_at?new Date(item.created_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):''}</Text>{item.link?<Text style={styles.open}>Open related area →</Text>:null}</Pressable>{item.requires_action&&state!=='DONE'?<Pressable disabled={busy===item.id} onPress={()=>markDone(item)} style={styles.doneButton}><Text style={styles.doneText}>{busy===item.id?'Saving…':'✓ Mark done'}</Text></Pressable>:null}</View>}
 return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>UPDATES</Text><Text style={styles.title}>Notifications</Text><Text style={styles.intro}>Actions and ordinary updates are now separate. Only items that genuinely require a response appear in your Home attention number.</Text>{!loading?<View style={styles.summary}><Text style={styles.summaryNumber}>{outstanding}</Text><Text style={styles.summaryCopy}>outstanding action{outstanding===1?'':'s'}</Text></View>:null}{loading?<ActivityIndicator color="#092b45" style={{marginTop:30}}/>:null}{!loading&&items.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>You’re all caught up.</Text><Text style={styles.emptyCopy}>New updates will appear here.</Text></View>:null}{actionItems.length?<><Text style={styles.section}>NEEDS ACTION</Text><View style={styles.list}>{actionItems.map(renderItem)}</View></>:null}{updates.length?<><Text style={styles.section}>OTHER UPDATES</Text><View style={styles.list}>{updates.map(renderItem)}</View></>:null}</ScrollView>
}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#fff'},page:{paddingHorizontal:22,paddingTop:64,paddingBottom:110},back:{color:'#66747c',fontSize:13,marginBottom:34},eyebrow:{color:'#71808a',fontSize:9,letterSpacing:2.1,marginBottom:10},title:{color:'#092b45',fontSize:31,fontWeight:'500'},intro:{color:'#66747c',fontSize:13,lineHeight:20,marginTop:10,marginBottom:18},summary:{backgroundColor:'#f4f7f8',padding:14,flexDirection:'row',alignItems:'baseline',gap:8,marginBottom:18},summaryNumber:{color:'#092b45',fontSize:24,fontWeight:'700'},summaryCopy:{color:'#66747c',fontSize:11},section:{color:'#71808a',fontSize:9,fontWeight:'700',letterSpacing:1.5,marginTop:18,marginBottom:9},list:{gap:10},card:{borderWidth:1,borderColor:'#dce3e7',padding:18,backgroundColor:'#fff'},cardNew:{borderColor:'#efb2b2',backgroundColor:'#fffafa'},cardOpen:{borderColor:'#d9cfaa',backgroundColor:'#fffdf7'},cardDone:{opacity:.58},row:{flexDirection:'row',justifyContent:'space-between',gap:12},cardTitle:{color:'#173246',fontSize:15,fontWeight:'600',flex:1},seen:{color:'#89959c',fontSize:8,letterSpacing:1.2},new:{color:'#d62828',fontSize:8,fontWeight:'800',letterSpacing:1.2},openState:{color:'#8a6a3a',fontSize:8,fontWeight:'800',letterSpacing:1.2},info:{color:'#71808a',fontSize:8,fontWeight:'700',letterSpacing:1.2},copy:{color:'#66747c',fontSize:12,lineHeight:18,marginTop:7},date:{color:'#8b989f',fontSize:10,marginTop:10},open:{color:'#092b45',fontSize:10,fontWeight:'700',marginTop:10},doneButton:{borderTopWidth:1,borderTopColor:'#efdada',marginTop:14,paddingTop:12,alignItems:'flex-end'},doneText:{color:'#8f1d1d',fontSize:11,fontWeight:'700'},empty:{backgroundColor:'#f4f7f8',padding:20},emptyTitle:{color:'#173246',fontSize:15,fontWeight:'600'},emptyCopy:{color:'#71808a',fontSize:12,marginTop:6}})