'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import DashboardShell from '@/components/DashboardShell'
import { createClient } from '@/lib/supabase/client'
import CollapsibleCheckboxSection from '@/components/CollapsibleCheckboxSection'
import { ROLE_LEVELS, TRAVEL_OPTIONS, AVAILABILITY_STATUSES } from '@/lib/constants'
import { SERVICES_CATEGORIES, PRODUCT_HOUSES_FULL as PRODUCT_HOUSES, QUALS_CATEGORIES, SYSTEMS_FULL } from '@/lib/taxonomy'
import type { CvSuggestions } from '@/lib/cv-analysis'
import { Save, Upload, FileText, Sparkles, CheckCircle2, Eye, Award, ShieldCheck, BrainCircuit } from 'lucide-react'
import { courseTitle } from '@/lib/academy'

const BUSINESS_SKILLS = ['Reception & Front of House','Revenue Management','Stock Control','Team Leadership','Staff Training','Rota Management','KPI Reporting','Health & Safety','COSHH Management','Budget Management','Client Consultation','Upselling & Retail','Social Media','Event Coordination','Membership Management']

export default function TalentProfilePage() {
  const supabase=createClient(); const [profile,setProfile]=useState<any>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
  const [analysingCv,setAnalysingCv]=useState(false); const [cvSuggestions,setCvSuggestions]=useState<CvSuggestions|null>(null); const [aiCvConsent,setAiCvConsent]=useState(false)
  const [academyBadges,setAcademyBadges]=useState<{course_slug:string;completed_at:string;certificate_code?:string}[]>([])

  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('candidate_profiles').select('*').eq('user_id',user.id).single();setProfile(data||{});if(data?.id){const {data:completed}=await supabase.from('course_enrollments').select('course_slug,completed_at,certificate_code').eq('candidate_id',data.id).not('completed_at','is',null).order('completed_at',{ascending:false});setAcademyBadges(completed||[])}setLoading(false)})()},[])
  const u=(field:string,value:any)=>setProfile((p:any)=>({...p,[field]:value}))
  const completionItems=[!!profile?.full_name,!!profile?.role_level,!!profile?.headline,!!profile?.bio,(profile?.services_offered?.length||0)>0,(profile?.qualifications?.length||0)>0,!!profile?.cv_url,!!profile?.experience_years,!!profile?.postcode,(profile?.business_skills?.length||0)>0]
  const completionPct=profile?Math.round(completionItems.filter(Boolean).length/completionItems.length*100):0

  async function handleSave(){if(!profile?.id)return;setSaving(true);setMessage('');const data={full_name:profile.full_name,phone:profile.phone||null,postcode:profile.postcode||null,location:profile.postcode||null,has_car:!!profile.has_car,role_level:profile.role_level||null,headline:profile.headline||null,bio:profile.bio||null,experience_years:profile.experience_years?parseInt(profile.experience_years):null,day_rate_min:profile.day_rate_min?parseInt(profile.day_rate_min):null,day_rate_max:profile.day_rate_max?parseInt(profile.day_rate_max):null,availability_status:profile.availability_status||null,right_to_work:profile.right_to_work||null,services_offered:profile.services_offered?.length?profile.services_offered:null,product_houses:profile.product_houses?.length?profile.product_houses:null,qualifications:profile.qualifications?.length?profile.qualifications:null,systems_experience:profile.systems_experience?.length?profile.systems_experience:null,business_skills:profile.business_skills?.length?profile.business_skills:null,career_evidence:profile.career_evidence?.length?profile.career_evidence:null,travel_availability:profile.travel_availability||'uk_only',travel_radius_miles:profile.travel_radius_miles?parseInt(profile.travel_radius_miles):null,has_insurance:!!profile.has_insurance,profile_completion_score:completionPct}
    const res=await fetch('/api/profile/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:profile.id,data})});const result=await res.json().catch(()=>({}));setSaving(false);setMessage(res.ok?'Profile saved successfully!':result.error||'Save failed');setTimeout(()=>setMessage(''),4000)}

  const userId=profile?.user_id||profile?.id
  async function uploadViaApi(file:File,bucket:string,path:string,column?:string){const fd=new FormData();fd.append('file',file);fd.append('bucket',bucket);fd.append('path',path);if(profile?.id&&column){fd.append('profileId',profile.id);fd.append('column',column)}const res=await fetch('/api/upload',{method:'POST',body:fd});const data=await res.json();if(!res.ok){setMessage(`Upload failed: ${data.error}`);return null}return data.url as string}
  async function handlePhotoUpload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!userId)return;const ext=file.name.split('.').pop()||'jpg';const url=await uploadViaApi(file,'site-images',`${userId}/profile/photo.${ext}`,'profile_image_url');if(url){u('profile_image_url',url);setMessage('Photo updated!')}}
  async function handleCvUpload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!userId)return;const ext=file.name.split('.').pop()||'pdf';const url=await uploadViaApi(file,'talent-documents',`${userId}/cv.${ext}`,'cv_url');if(url){u('cv_url',url);setCvSuggestions(null);setAiCvConsent(false);setMessage('CV uploaded. You can now choose whether to analyse it with WHC AI.')}}
  async function handleInsuranceUpload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!userId)return;const ext=file.name.split('.').pop()||'pdf';const url=await uploadViaApi(file,'talent-documents',`${userId}/insurance.${ext}`,'insurance_document_url');if(url){u('insurance_document_url',url);setMessage('Insurance uploaded!')}}
  async function handleCertsUpload(e:React.ChangeEvent<HTMLInputElement>){const files=e.target.files;if(!files||!userId)return;const urls:string[]=[...(profile.certificates_urls||[])];for(const file of Array.from(files)){const url=await uploadViaApi(file,'talent-documents',`${userId}/cert_${Date.now()}_${file.name}`);if(url)urls.push(url)}await fetch('/api/profile/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:profile.id,data:{certificates_urls:urls}})});u('certificates_urls',urls);setMessage('Certificates uploaded!')}
  async function removeCertificate(url:string,index:number){
    if(!profile?.id)return
    if(!window.confirm(`Remove Certificate ${index+1} from your profile?`))return
    const urls=(profile.certificates_urls||[]).filter((item:string)=>item!==url)
    const res=await fetch('/api/profile/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:profile.id,data:{certificates_urls:urls}})})
    const result=await res.json().catch(()=>({}))
    if(!res.ok){setMessage(result.error||'Could not remove certificate.');return}
    u('certificates_urls',urls)
    setMessage('Certificate removed from your profile.')
  }

  async function analyseCurrentCv(){if(!profile?.id||!profile?.cv_url||!aiCvConsent)return;setAnalysingCv(true);setMessage('');const res=await fetch('/api/cv/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:profile.id,aiConsent:true})});const result=await res.json().catch(()=>({}));setAnalysingCv(false);if(!res.ok){setMessage(result.error||'CV analysis failed');return}setCvSuggestions(result.suggestions)}
  function applyCvSuggestions(){if(!cvSuggestions)return;setProfile((c:any)=>({...c,role_level:cvSuggestions.roleLevel||c.role_level,experience_years:cvSuggestions.experienceYears||c.experience_years,services_offered:Array.from(new Set([...(c.services_offered||[]),...(cvSuggestions.services||[])])),product_houses:Array.from(new Set([...(c.product_houses||[]),...(cvSuggestions.productHouses||[])])),qualifications:Array.from(new Set([...(c.qualifications||[]),...(cvSuggestions.qualifications||[])])),systems_experience:Array.from(new Set([...(c.systems_experience||[]),...(cvSuggestions.systems||[])])),business_skills:Array.from(new Set([...(c.business_skills||[]),...(cvSuggestions.businessSkills||[])])),career_evidence:Array.from(new Set([...(c.career_evidence||[]),...(cvSuggestions.careerEvidence||[])]))}));setCvSuggestions(null);setMessage('Suggestions added for your review. Nothing becomes final until you Save Changes.')}

  if(loading)return <DashboardShell role="talent"><div className="h-64 flex items-center justify-center">Loading…</div></DashboardShell>
  if(!profile?.id)return <DashboardShell role="talent"><p>Profile not found.</p></DashboardShell>
  return <DashboardShell role="talent" userName={profile.full_name}><div className="max-w-3xl">
    <div className="flex items-center justify-between gap-3 mb-2"><div><p className="dashboard-eyebrow">Career profile</p><h1 className="dashboard-section-title">Edit Profile</h1></div><div className="flex gap-2"><Link href="/talent/profile/preview" className="btn-secondary inline-flex items-center gap-2"><Eye size={14}/>Preview</Link><button onClick={handleSave} disabled={saving} className="btn-primary inline-flex items-center gap-2"><Save size={14}/>{saving?'Saving...':'Save Changes'}</button></div></div>
    <div className="flex items-center gap-3 mb-8"><div className="flex-1 h-1.5 bg-[#eef2f4] rounded-full overflow-hidden"><div className="h-full bg-[#0b2f4d]" style={{width:`${completionPct}%`}}/></div><span className="text-[12px]">{completionPct}%</span></div>
    {message&&<div className="mb-6 rounded-lg bg-[#f1f4f6] px-4 py-3 text-[12px] text-[#53636f]">{message}</div>}
    <div className="space-y-6">
      <section className="dashboard-card"><p className="eyebrow">WHC Academy achievements</p>{academyBadges.length?<div className="mt-4 space-y-2">{academyBadges.map(b=><div key={b.course_slug} className="flex justify-between border border-border rounded-lg p-3"><div><p className="text-[13px] font-semibold">{courseTitle(b.course_slug)}</p><p className="text-[10px] text-muted">Completed {new Date(b.completed_at).toLocaleDateString('en-GB')}</p></div><Award size={17}/></div>)}</div>:<p className="text-[12px] text-muted mt-2">Completed Academy courses will appear here.</p>}</section>

      <section className="dashboard-card space-y-4"><p className="eyebrow">Personal details</p><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-full overflow-hidden bg-[#eef2f4]">{profile.profile_image_url&&<img src={profile.profile_image_url} alt="" className="w-full h-full object-cover"/>}</div><label className="btn-secondary cursor-pointer inline-flex gap-2"><Upload size={13}/>Upload Photo<input type="file" accept="image/*" className="hidden" onChange={handlePhotoUpload}/></label></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Full name"><input className="input-field" value={profile.full_name||''} onChange={e=>u('full_name',e.target.value)}/></Field><Field label="Phone"><input className="input-field" value={profile.phone||''} onChange={e=>u('phone',e.target.value)}/></Field><Field label="Postcode"><input className="input-field" value={profile.postcode||''} onChange={e=>u('postcode',e.target.value)}/></Field><Field label="Right to work"><select className="input-field" value={profile.right_to_work||''} onChange={e=>u('right_to_work',e.target.value)}><option value="">Select</option><option value="uk">Right to work in the UK</option><option value="ireland">Right to work in Ireland</option><option value="uk_ireland">Right to work in UK & Ireland</option><option value="visa_required">Visa / sponsorship required</option></select></Field></div></section>

      <section className="dashboard-card space-y-4"><p className="eyebrow">Professional details</p><Field label="Current role level"><select className="input-field" value={profile.role_level||''} onChange={e=>u('role_level',e.target.value)}><option value="">Select</option>{ROLE_LEVELS.map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Headline"><input className="input-field" value={profile.headline||''} onChange={e=>u('headline',e.target.value)} placeholder="e.g. Spa Manager | Luxury Hospitality | Commercial & People Leadership"/></Field><Field label="Bio"><textarea rows={4} className="input-field" value={profile.bio||''} onChange={e=>u('bio',e.target.value)}/></Field><div className="grid sm:grid-cols-3 gap-4"><Field label="Experience years"><input type="number" className="input-field" value={profile.experience_years||''} onChange={e=>u('experience_years',e.target.value)}/></Field><Field label="Day rate min"><input type="number" className="input-field" value={profile.day_rate_min||''} onChange={e=>u('day_rate_min',e.target.value)}/></Field><Field label="Day rate max"><input type="number" className="input-field" value={profile.day_rate_max||''} onChange={e=>u('day_rate_max',e.target.value)}/></Field></div><Field label="Availability"><select className="input-field" value={profile.availability_status||''} onChange={e=>u('availability_status',e.target.value)}>{AVAILABILITY_STATUSES.map(a=><option key={a.value} value={a.value}>{a.label}</option>)}</select></Field></section>

      <CollapsibleCheckboxSection title="Services Offered" categories={SERVICES_CATEGORIES} selected={profile.services_offered||[]} onChange={v=>u('services_offered',v)}/>
      <CollapsibleCheckboxSection title="Product Houses" flatItems={PRODUCT_HOUSES} selected={profile.product_houses||[]} onChange={v=>u('product_houses',v)}/>
      <CollapsibleCheckboxSection title="Qualifications & Certifications" categories={QUALS_CATEGORIES} selected={profile.qualifications||[]} onChange={v=>u('qualifications',v)}/>
      <CollapsibleCheckboxSection title="Systems Experience" flatItems={SYSTEMS_FULL} selected={profile.systems_experience||[]} onChange={v=>u('systems_experience',v)}/>
      <CollapsibleCheckboxSection title="Leadership & Business Skills" flatItems={BUSINESS_SKILLS} selected={profile.business_skills||[]} onChange={v=>u('business_skills',v)}/>

      <section className="dashboard-card space-y-4"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">CV intelligence</p><h2 className="text-[23px] mt-1">Turn your CV into better matching evidence.</h2><p className="text-[12px] text-secondary mt-2">WHC first extracts exact facts, then — only when you choose — uses AI to identify transferable leadership and commercial evidence. AI suggestions never change your profile automatically.</p></div><BrainCircuit size={22} className="text-[#6f7f88]"/></div>
        {profile.cv_url?<div className="flex items-center gap-2 border border-border rounded-lg p-3"><FileText size={14}/><a href={profile.cv_url} target="_blank" rel="noopener noreferrer" className="text-[13px] flex-1 truncate">Current CV</a><label className="text-[11px] cursor-pointer">Replace<input type="file" accept=".pdf,.docx" className="hidden" onChange={handleCvUpload}/></label></div>:<label className="border border-dashed border-border rounded-lg p-5 text-center cursor-pointer block"><Upload size={16} className="mx-auto mb-2"/><span className="text-[12px]">Upload CV (PDF or .docx)</span><input type="file" accept=".pdf,.docx" className="hidden" onChange={handleCvUpload}/></label>}
        {profile.cv_url&&<><label className="flex items-start gap-3 rounded-lg border border-[#dfe5e8] bg-[#f7f9fa] p-4"><input type="checkbox" checked={aiCvConsent} onChange={e=>setAiCvConsent(e.target.checked)} className="mt-1"/><span className="text-[11px] leading-5 text-secondary"><strong className="text-ink">Analyse my CV with WHC AI.</strong> I understand WHC will process the text of my CV to create career and matching suggestions. The raw CV text is not added to my public profile and suggestions are not saved unless I approve them.</span></label><button type="button" onClick={analyseCurrentCv} disabled={!aiCvConsent||analysingCv} className="btn-primary w-full inline-flex items-center justify-center gap-2 disabled:opacity-40"><Sparkles size={14}/>{analysingCv?'Analysing privately...':'Analyse CV with WHC AI'}</button></>}
        {cvSuggestions&&<div className="rounded-xl border border-[#dfe5e8] bg-white p-5 space-y-4"><div className="flex items-start gap-2"><ShieldCheck size={17} className="text-[#6f7f88]"/><div><p className="text-[14px] font-semibold">Suggestions ready</p><p className="text-[11px] text-muted">{cvSuggestions.aiEnhanced?'AI-enhanced analysis completed.':'Exact CV extraction completed; AI was unavailable, so no AI inference was used.'}</p></div></div><div className="grid sm:grid-cols-2 gap-3 text-[12px]"><Mini label="Current role" value={cvSuggestions.roleLevel||'Not confidently detected'}/><Mini label="Experience" value={cvSuggestions.experienceYears?`${cvSuggestions.experienceYears} years`:'Not confidently detected'}/><Mini label="Business skills" value={`${cvSuggestions.businessSkills?.length||0} found`}/><Mini label="Career evidence" value={`${cvSuggestions.careerEvidence?.length||0} evidence points`}/></div>
          {!!cvSuggestions.progressionSignals?.length&&<div><p className="eyebrow mb-2">Progression signals</p>{cvSuggestions.progressionSignals.map(x=><p key={x} className="text-[12px] leading-5 text-secondary flex gap-2 mb-2"><CheckCircle2 size={13} className="mt-1 shrink-0"/>{x}</p>)}</div>}
          {!!cvSuggestions.careerEvidence?.length&&<div><p className="eyebrow mb-2">Evidence found in your CV</p>{cvSuggestions.careerEvidence.map(x=><p key={x} className="text-[12px] leading-5 text-secondary flex gap-2 mb-2"><CheckCircle2 size={13} className="mt-1 shrink-0"/>{x}</p>)}</div>}
          <div className="flex gap-2"><button onClick={applyCvSuggestions} className="btn-primary flex-1">Use approved suggestions</button><button onClick={()=>setCvSuggestions(null)} className="btn-secondary">Dismiss</button></div></div>}
      </section>

      {!!profile.career_evidence?.length&&<section className="dashboard-card"><p className="eyebrow">Career evidence used in matching</p><p className="text-[11px] text-muted mt-1">These are short evidence statements you approved from your CV. They help WHC recognise progression potential without changing your current job title.</p><div className="mt-4 space-y-2">{profile.career_evidence.map((x:string)=><div key={x} className="flex gap-2 text-[12px] text-secondary"><CheckCircle2 size={13} className="mt-1 shrink-0"/>{x}</div>)}</div></section>}

      <section className="dashboard-card space-y-4"><p className="eyebrow">Documents & insurance</p><Field label="Certificates"><div className="space-y-2">{(profile.certificates_urls||[]).map((url:string,i:number)=><div key={url} className="flex items-center justify-between gap-3 rounded-lg border border-border px-3 py-2"><a href={url} target="_blank" rel="noopener noreferrer" className="min-w-0 flex-1 truncate text-[12px] underline">Certificate {i+1}</a><button type="button" onClick={()=>removeCertificate(url,i)} className="shrink-0 text-[11px] font-semibold text-red-600 hover:text-red-700">Remove</button></div>)}</div><label className="btn-secondary inline-flex cursor-pointer mt-3">Add certificates<input type="file" accept=".pdf" multiple className="hidden" onChange={handleCertsUpload}/></label></Field><label className="flex gap-2 text-[13px]"><input type="checkbox" checked={!!profile.has_insurance} onChange={e=>u('has_insurance',e.target.checked)}/>I have professional insurance (optional unless a role requires it)</label>{profile.has_insurance&&(profile.insurance_document_url?<a href={profile.insurance_document_url} target="_blank" rel="noopener noreferrer" className="text-[12px] underline">View insurance certificate</a>:<label className="btn-secondary inline-flex cursor-pointer">Upload insurance<input type="file" accept=".pdf" className="hidden" onChange={handleInsuranceUpload}/></label>)}</section>

      <section className="dashboard-card space-y-4"><p className="eyebrow">Travel preferences</p><div className="flex flex-wrap gap-2">{TRAVEL_OPTIONS.map(t=><button type="button" key={t.value} onClick={()=>u('travel_availability',t.value)} className={`px-4 py-2 rounded-lg text-[12px] border ${profile.travel_availability===t.value?'bg-[#0b2f4d] text-white border-[#0b2f4d]':'bg-white border-border'}`}>{t.label}</button>)}</div>{profile.travel_availability==='radius'&&<Field label="Travel radius (miles)"><input type="number" className="input-field" value={profile.travel_radius_miles||''} onChange={e=>u('travel_radius_miles',e.target.value)}/></Field>}</section>
      <button onClick={handleSave} disabled={saving} className="btn-primary w-full inline-flex justify-center gap-2"><Save size={14}/>{saving?'Saving...':'Save All Changes'}</button>
    </div>
  </div></DashboardShell>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="eyebrow block mb-1.5">{label}</label>{children}</div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#f7f9fa] p-3"><p className="text-[10px] text-muted">{label}</p><p className="font-semibold text-ink mt-1">{value}</p></div>}