import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'
import { sellableCatalogue } from '../src/lib/documents/catalogue'
import { kindLabel } from '../src/lib/documents/journey'
import { categoryPacks, everythingPacks } from '../src/lib/documents/pricing'

const body = (file: string) =>
  readFileSync(file, 'utf8')
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '')

const doc = body('src/app/standards/[reference]/page.tsx')
const pack = body('src/app/standards/packs/[slug]/page.tsx')
const sitemap = body('src/app/sitemap.ts')

test('there is a page per pack and per document worth searching for', () => {
  // One URL carrying five hundred and sixty titles ranks for none of them,
  // and gives an assistant nothing specific enough to cite.
  for (const source of [doc, pack]) {
    assert.match(source, /export function generateStaticParams/, 'the pages must be statically generated')
    assert.match(source, /export async function generateMetadata/, 'each needs its own title and description')
    assert.match(source, /alternates: \{ canonical/)
  }
  // Server components. A page whose content arrives after a fetch is a page
  // with nothing in it when it is read.
  assert.doesNotMatch(doc, /'use client'/)
  assert.doesNotMatch(pack, /'use client'/)
})

test('not every document gets a page, and the rule is stated', () => {
  // Four hundred and fifty procedures named "Apply Buffers and Setup Times"
  // would be four hundred and fifty thin pages competing with each other,
  // which is how a site teaches a search engine that it publishes filler.
  assert.match(doc, /WORTH_A_PAGE/)
  const worth = sellableCatalogue().filter(entry =>
    ['Job description', 'Policy', 'Risk assessment', 'Checklist', 'Guide', 'Training',
      'Operating procedure', 'Emergency plan', 'Management report', 'Safe system of work']
      .includes(kindLabel(entry.reference)))
  assert.ok(worth.length > 80, `only ${worth.length} documents would get a page`)
  assert.ok(worth.length < sellableCatalogue().length / 2,
    'if most documents get a page, the rule is not doing anything')
})

test('each page carries the structured data a price needs to appear in a result', () => {
  for (const source of [doc, pack]) {
    assert.match(source, /'@type': 'Product'/)
    assert.match(source, /'@type': 'Offer'/)
    assert.match(source, /priceCurrency: 'GBP'/)
    assert.match(source, /'@type': 'BreadcrumbList'/)
    assert.match(source, /application\/ld\+json/)
  }
  // The price in the schema is the price the shop charges, taken from the
  // same source rather than typed into the markup.
  assert.match(doc, /singlePriceFor\(reference\) \/ 100/)
  assert.match(pack, /pack\.price \/ 100/)
})

test('every generated page is in the sitemap', () => {
  assert.match(sitemap, /standards\/packs\/\$\{pack\.slug\}/)
  assert.match(sitemap, /standards\/\$\{entry\.reference\}/)
  // The rule deciding which documents get a page lives in two files, so it is
  // named in both and this fails if they drift.
  assert.match(sitemap, /PAGEABLE_KINDS/)
  const inSitemap = [...sitemap.matchAll(/'([A-Z][a-z ]+)',/g)].map(match => match[1])
  for (const kind of ['Job description', 'Policy', 'Risk assessment']) {
    assert.ok(inSitemap.includes(kind), `${kind} is pageable and not in the sitemap rule`)
  }
})

test('the pages link to each other rather than sitting alone', () => {
  // A page nothing points at is a page nothing passes authority to.
  assert.match(doc, /standards\/packs\/\$\{cheapest\.slug\}/, 'a document links to the pack that carries it')
  assert.match(doc, /Other \{kind\.toLowerCase\(\)\}s for/, 'and to its siblings')
  assert.match(pack, /standards\/\$\{entry\.reference\}/, 'a pack links to every document in it')
  assert.match(pack, /Other packs/)
})

test('the titles are what somebody types, not what we call it internally', () => {
  assert.match(doc, /spa \$\{kind\.toLowerCase\(\)\} template/,
    'the word "template" is what a buyer searches for and it belongs in the title')
  assert.match(pack, /\$\{pack\.count\} documents/)
})

test('the pages were actually generated by the last build', () => {
  // A route that compiles and generates nothing is a route that exists only
  // in the diff.
  const built = '.next/server/app/standards'
  if (!existsSync(built)) return
  for (const reference of ['MGT-SPADIRECTOR-JD-701', 'SAF-SAFEGUARDING-POL-802']) {
    const page = `${built}/${reference}.html`
    if (!existsSync(page)) continue
    const html = readFileSync(page, 'utf8')
    assert.match(html, /"@type":"Product"/, `${reference} generated without its schema`)
    assert.match(html, /rel="canonical"/, `${reference} generated without a canonical`)
    assert.match(html, /og:image/, `${reference} generated without a share image`)
  }
  const packs = [...categoryPacks(), ...everythingPacks()]
  assert.ok(packs.length >= 14, `only ${packs.length} packs would get a page`)
})
