import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { moneyTone, toneClasses } from '../src/lib/status-tone.ts'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const MIGRATION = 'supabase/migrations/20260904180000_arrival_packs_for_accepted_shifts.sql'
const REBUILT = 'supabase/migrations/20260904190000_arrival_pack_actually_builds.sql'
const PAGE = 'src/app/talent/before-you-arrive/page.tsx'

// The arrival pack - the address, the staff entrance, who to ask for, parking,
// what to bring - is generated by a trigger gated on status in
// ('confirmed','completed'). An accepted Agency booking has status 'accepted',
// and nothing in the application has ever written 'confirmed' to that column.
// So Before You Arrive has shown "no packs yet" to every professional who ever
// took a shift.
test('a pack is generated for the status the platform actually writes', () => {
  const sql = read(MIGRATION)
  assert.match(sql, /status in \('accepted','confirmed','completed'\)/, 'the generator')
  assert.match(sql, /new\.status in \('accepted','confirmed','completed'\)/, 'and the trigger')
  // Residency has its own vocabulary and must not be touched.
  assert.match(sql, /status in \('confirmed','paid','active','completed'\)/)
})

// Somebody who took a booking last week should not have to take another one to
// find out where they are going.
test('the packs that were never made are made now', () => {
  const sql = read(MIGRATION)
  assert.match(sql, /SELECT id FROM public\.agency_bookings WHERE status IN \('accepted','confirmed','completed'\)/)
})

// The status was only the first fault. Running the generator by hand gave
// `record "b" has no field "start_date"`: the booking section was a SQL CASE
// naming agency columns in one branch and residency columns in the other, and
// PL/pgSQL resolves every field in the expression against the row it holds
// whichever branch wins. So an agency booking died on the residency columns
// and a residency booking would have died on shift_date. It had never produced
// a pack for anything.
test('the two booking shapes stop naming each other’s columns', () => {
  const rebuilt = read(REBUILT)
  const body = rebuilt.slice(rebuilt.indexOf('IF p_booking_type = \'agency\' THEN\n    booking_json'))
  assert.match(body, /booking_json := jsonb_build_object\(\n      'date', b->'shift_date'/, 'agency fields in the agency branch')
  assert.match(body, /booking_json := jsonb_build_object\(\n      'start_date', b->'start_date'/, 'residency fields in the residency branch')
  // Procedural branching, not a SQL CASE, is what keeps them apart.
  assert.ok(!/case when p_booking_type = 'agency' then jsonb_build_object/i.test(rebuilt))
})

// A pack is assembled from around fifty optional columns across two tables.
// Any one of them missing took the whole thing down with an error nobody saw,
// because the trigger swallowed it and the professional simply got no pack.
test('a missing column makes a thinner pack, not no pack', () => {
  const rebuilt = read(REBUILT)
  assert.match(rebuilt, /SELECT to_jsonb\(t\) INTO e FROM public\.employer_profiles/, 'read as jsonb, where an absent key is null')
  assert.match(rebuilt, /f := coalesce\(f, '\{\}'::jsonb\)/, 'and no fact file at all is an empty one')
  assert.match(rebuilt, /jsonb_typeof\(e->'product_houses_used'\) = 'array'/, 'a column that is not an array is not treated as one')
  assert.ok(!/\be\.\w+|\bf\.\w+/.test(rebuilt.slice(rebuilt.indexOf('payload := jsonb_build_object'), rebuilt.indexOf('INSERT INTO public.booking_arrival_packs'))),
    'no record-field access survives in the payload')
})

// A backfill that reports success while generating nothing is how this stayed
// invisible for a day.
test('a backfill that fails says so', () => {
  const rebuilt = read(REBUILT)
  const backfill = rebuilt.slice(rebuilt.indexOf('DO $backfill$'))
  assert.ok(!/EXCEPTION WHEN others/.test(backfill), 'the failure is not swallowed this time')
  assert.match(backfill, /RAISE NOTICE 'arrival packs attempted for % agency bookings'/)
})

// Once a shift has passed the pack stops being a briefing and becomes a
// record. Both are worth keeping; a stack of finished shifts on top of
// tomorrow's is the wrong way round.
test('a finished shift moves to the archive', () => {
  const page = read(PAGE)
  assert.match(page, /const upcoming = packs\.filter\(pack => !isPast\(pack\)\)/)
  assert.match(page, /const past = packs\.filter\(isPast\)/)
  assert.match(page, /Archive\{past\.length > 0/)
  assert.match(page, /A pack moves here once its shift has finished/)
  // The end of the shift, not the start, so a pack does not vanish at 09:01.
  assert.match(page, /booking\.end_time \|\| '23:59'/)
})

// The old copy promised a pack "once confirmed", which was the word that broke
// it.
test('the page stops using the word that never happens', () => {
  const page = read(PAGE)
  assert.ok(!/No confirmed arrival packs yet/.test(page))
  assert.match(page, /as soon as you accept an Agency shift/)
})

// Four very different situations rendered as four grey cards with a coloured
// number. From a metre away an open dispute and a settled payment looked the
// same.
test('a colour means one thing everywhere', () => {
  assert.equal(moneyTone(160, 'done'), 'done')
  assert.equal(moneyTone(0, 'done'), 'quiet', 'a zero is neither an achievement nor a problem')
  assert.equal(moneyTone(0, 'action'), 'quiet')
  assert.match(toneClasses('done').card, /emerald/)
  assert.match(toneClasses('waiting').card, /amber/)
  assert.match(toneClasses('action').card, /red/)
  assert.match(toneClasses('quiet').card, /#dddddd/)
})

// The portal repaints every text-amber-* to grey and every bg-amber-50 to
// near-white, deliberately - grey is the brand and a dashboard full of warning
// colours reads as panic. A status carried by amber text is therefore a status
// nobody ever sees, which is exactly what happened to the first version of
// these tiles.
test('no tone relies on a colour the portal strips', () => {
  const tones = read('src/lib/status-tone.ts')
  const css = read('src/app/portal-clean.css')
  assert.match(css, /\[class\*="text-amber-"\]/, 'the rule this is avoiding still exists')
  const values = ['done', 'waiting', 'action', 'quiet'] as const
  for (const tone of values) {
    const classes = toneClasses(tone)
    const all = `${classes.card} ${classes.pill}`
    assert.ok(!/text-amber-|text-yellow-/.test(all), `${tone} must not signal through stripped text`)
    assert.ok(!/\bbg-amber-50\b|\bbg-yellow-50\b/.test(all), `${tone} must not signal through a stripped tint`)
  }
  // Borders and saturated fills survive, so that is what carries it.
  assert.match(tones, /border-l-amber-500/)
  assert.match(tones, /bg-amber-500 text-white/)
})

// A colour nobody can name is decoration. Each tone says its state in words as
// well, which also survives a screenshot, a colourblind reader and the portal.
test('every tone says what it means in words', () => {
  assert.equal(toneClasses('done').word, 'Paid')
  assert.equal(toneClasses('waiting').word, 'Waiting')
  assert.equal(toneClasses('action').word, 'Needs you')
  assert.equal(toneClasses('quiet').word, '', 'nothing to say about nothing')
  assert.match(read('src/app/talent/agency/page.tsx'), /\{classes\.word\}<\/span>/)
})

test('the money row says which figure needs something from you', () => {
  const agency = read('src/app/talent/agency/page.tsx')
  assert.match(agency, /label="Paid to you" amount=\{paidOut\} tone=\{moneyTone\(paidOut, 'done'\)\}/)
  assert.match(agency, /label="Awaiting payout" amount=\{awaitingPayout\} tone=\{moneyTone\(awaitingPayout, 'waiting'\)\}/)
  assert.match(agency, /label="Awaiting property payment" amount=\{awaitingProperty\} tone=\{moneyTone\(awaitingProperty, 'waiting'\)\}/)
  assert.match(agency, /label="On hold" amount=\{onHold\} tone=\{moneyTone\(onHold, 'action'\)\}/, 'a dispute is the one that is yours')
  assert.match(agency, /check Shift Resolution/, 'and it says where to go')
})
