import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { moneyTone, toneClasses } from '../src/lib/status-tone.ts'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const MIGRATION = 'supabase/migrations/20260904180000_arrival_packs_for_accepted_shifts.sql'
const PAGE = 'src/app/talent/before-you-arrive/page.tsx'

// The arrival pack - the address, the staff entrance, who to ask for, parking,
// what to bring - is generated by a trigger gated on status in
// ('confirmed','completed'). An accepted Agency booking has status 'accepted',
// and nothing in the application has ever written 'confirmed' to that column.
// So Before You Arrive has shown "no packs yet" to every professional who ever
// took a shift.
test('a pack is generated for the status the platform actually writes', () => {
  const sql = read(MIGRATION)
  assert.match(sql, /status in \('accepted','confirmed','completed'\)/, 'the generator')
  assert.match(sql, /new\.status in \('accepted','confirmed','completed'\)/, 'and the trigger')
  // Residency has its own vocabulary and must not be touched.
  assert.match(sql, /status in \('confirmed','paid','active','completed'\)/)
})

// Somebody who took a booking last week should not have to take another one to
// find out where they are going.
test('the packs that were never made are made now', () => {
  const sql = read(MIGRATION)
  assert.match(sql, /SELECT id FROM public\.agency_bookings WHERE status IN \('accepted','confirmed','completed'\)/)
  assert.match(sql, /EXCEPTION WHEN others THEN/, 'one bad fact file must not stop the rest')
})

// Once a shift has passed the pack stops being a briefing and becomes a
// record. Both are worth keeping; a stack of finished shifts on top of
// tomorrow's is the wrong way round.
test('a finished shift moves to the archive', () => {
  const page = read(PAGE)
  assert.match(page, /const upcoming = packs\.filter\(pack => !isPast\(pack\)\)/)
  assert.match(page, /const past = packs\.filter\(isPast\)/)
  assert.match(page, /Archive\{past\.length > 0/)
  assert.match(page, /A pack moves here once its shift has finished/)
  // The end of the shift, not the start, so a pack does not vanish at 09:01.
  assert.match(page, /booking\.end_time \|\| '23:59'/)
})

// The old copy promised a pack "once confirmed", which was the word that broke
// it.
test('the page stops using the word that never happens', () => {
  const page = read(PAGE)
  assert.ok(!/No confirmed arrival packs yet/.test(page))
  assert.match(page, /as soon as you accept an Agency shift/)
})

// Four very different situations rendered as four grey cards with a coloured
// number. From a metre away an open dispute and a settled payment looked the
// same.
test('a colour means one thing everywhere', () => {
  assert.equal(moneyTone(160, 'done'), 'done')
  assert.equal(moneyTone(0, 'done'), 'quiet', 'a zero is neither an achievement nor a problem')
  assert.equal(moneyTone(0, 'action'), 'quiet')
  assert.match(toneClasses('done').card, /emerald/)
  assert.match(toneClasses('waiting').card, /amber/)
  assert.match(toneClasses('action').card, /red/)
  assert.match(toneClasses('quiet').card, /#dddddd/)
})

test('the money row says which figure needs something from you', () => {
  const agency = read('src/app/talent/agency/page.tsx')
  assert.match(agency, /label="Paid to you" amount=\{paidOut\} tone=\{moneyTone\(paidOut, 'done'\)\}/)
  assert.match(agency, /label="Awaiting payout" amount=\{awaitingPayout\} tone=\{moneyTone\(awaitingPayout, 'waiting'\)\}/)
  assert.match(agency, /label="Awaiting property payment" amount=\{awaitingProperty\} tone=\{moneyTone\(awaitingProperty, 'waiting'\)\}/)
  assert.match(agency, /label="On hold" amount=\{onHold\} tone=\{moneyTone\(onHold, 'action'\)\}/, 'a dispute is the one that is yours')
  assert.match(agency, /check Shift Resolution/, 'and it says where to go')
})
