import type { CourseContent } from '../academy-types'

const content: CourseContent = {
  slug: 'brand-knowledge',
  aims: `This course equips therapists with working fluency in the product houses that define the UK luxury spa landscape - ESPA, Elemis, Dermalogica, Comfort Zone, Natura Bissé, Aromatherapy Associates, Bamford, VOYA and their peers. It goes beyond memorising product names to teach the deeper structure of brand identity: each house's philosophy, its hero products, and the signature language that signals belonging to guests and employers alike. By the end, you will be able to walk into a venue running any major house and adapt your delivery, your vocabulary and your consultation style to that house's accent, and you will know exactly what to do, and what never to do, when you encounter a house you have not yet trained with.`,
  audience: `Spa and wellness therapists at every stage: newly qualified therapists building a CV that passes brand-based filtering, experienced therapists moving between hotels and houses, and agency or freelance therapists who must adapt to a new product house at short notice. It is equally useful for spa reception and retail teams who support treatment conversations, and for therapists preparing for interviews or trade tests at branded five-star venues.`,
  outcomes: [
    'Articulate the philosophy, hero products and signature language of the major product houses used in UK luxury spas',
    'Adapt consultation style, treatment narrative and retail conversation to match a specific house identity',
    'Distinguish holistic, results-led, dermatological and sensorial brand families and deliver each in its own register',
    'Apply a professional, honest protocol when working with an unfamiliar house, protecting guest trust and rebooking prospects',
  ],
  prerequisites: `None beyond a working therapy background: the course assumes you already deliver treatments professionally and focuses on how to learn and represent a product house, not on treatment technique. It maps the brand landscape; only each house's own accredited training qualifies you to deliver its protocols.`,
  author: { name: 'Talent House Academy', role: 'Developed by Wellness House Collective' },
  references: [
    { label: `Your product house's official training materials - always the authoritative source on its protocols, products and language` },
    { label: `The published websites and brand materials of the houses at venues where you work or apply - read them for register as much as for facts` },
    { label: 'UK Spa Association - industry resources and operational guidance', url: 'https://www.spa-uk.org' },
  ],
  lastReviewed: '2026-08-31',
  version: '1.0',
  lessons: [
    {
      title: 'Why brands are a language',
      whyThisMatters: `Hiring managers at branded spas screen CVs for house names before they read anything else, so your brand fluency is often judged before your hands ever are. For agency and freelance therapists the stakes double: you can be booked at midday and expected to deliver another house's signature treatment convincingly by one o'clock. Fluency in two or three major houses is one of the highest-return career investments a therapist can make.`,
      objectives: [
        'Explain why luxury spas structure their entire operation around a partnership with a product house',
        'Describe the three components of brand fluency and why hiring managers filter candidates on them',
        'Assess your own brand fluency honestly and plan how to close the gaps that limit your employability',
      ],
      sections: [
        {
          heading: 'The house partnership: more than a supplier',
          body: `When a luxury spa selects a product house, it is not making a purchasing decision; it is choosing an identity. The house supplies the treatment menu and the protocols behind every facial and body ritual on it. It supplies the training pathway that every therapist must complete before touching a guest. It stocks the retail wall that generates a significant share of spa revenue, and it shapes the scent, the language and the promise the guest encounters from the booking page onwards. A five-star hotel running ESPA has effectively licensed a philosophy; one running Elemis has licensed a different one. This is why houses guard their protocols and why spas invest heavily in accreditation. For the therapist, the practical consequence is simple: your value to an employer is inseparable from your fluency in the house they have committed to. The spa cannot change its house to suit you; you must speak theirs.`,
        },
        {
          heading: 'Fluency as employability',
          body: `Recruitment in branded spas works on a blunt principle: a therapist already trained in the venue's house can be rostered onto the menu almost immediately, while an untrained one represents weeks of ramp-up, training cost and supervised shifts. Hiring managers therefore screen CVs for house names before they read anything else. Listing "ESPA trained, Level 3" answers the manager's first question in four words. For agency and freelance therapists the stakes double, because there is no ramp-up at all: you may be booked at midday and expected to deliver another house's signature treatment convincingly by one o'clock. The guest booked that named ritual, often at a premium price, and will notice if the sequence, the products or the vocabulary feel improvised. Building a portfolio of two or three major houses, and keeping certificates current, is one of the highest-return career investments a therapist can make.`,
        },
        {
          heading: 'The three pillars of brand fluency',
          body: `Fluency rests on three pillars, and a weakness in any one of them shows. The first is philosophy: what the house believes about skin, wellbeing and the purpose of a treatment. ESPA believes in holistic balance; Dermalogica believes in skin health as a clinical discipline. Philosophy dictates how you consult, how you touch and how you close. The second is hero products: the icons guests ask for by name, such as Elemis Pro-Collagen Marine Cream or an Aromatherapy Associates bath oil. Knowing the heroes means you can answer the question a guest actually asks. The third is signature language: every house owns vocabulary, phrases such as Tri-Enzyme, Pro-Collagen or skin health, that operate like a dialect. Using the right words tells the guest, and the spa manager watching, that you belong. This course provides the map across houses; each house's own accredited training provides the depth beneath it.`,
        },
        {
          heading: 'Learning a house deliberately',
          body: `Treat learning a house the way a language student treats a new language: structured, repeated, tested. Start with the origin story, because philosophy nearly always flows from the founder's background - a skin therapist founds a clinical house, an aromatherapist founds a holistic one. Then learn the top five retail products by name, texture, key actives and the guest each suits, because these are the questions you will face at the couch and the retail wall. Next, learn the two or three signature treatments: their names, their sequence and the promise the marketing makes, since the guest arrives holding that promise. Finally, absorb the register of the brand's own materials - read the website copy aloud and notice the words it repeats. A therapist who can consult, treat and recommend in a house's own register within a week of starting is the therapist managers remember.`,
        },
      ],
      visuals: [
        { kind: 'table', title: 'The three pillars of brand fluency', headers: ['Pillar', 'What it is', 'Where it shows'], rows: [
          ['Philosophy', 'What the house believes about skin, wellbeing and the purpose of a treatment', 'How you consult, how you touch, how you close'],
          ['Hero products', 'The icons guests ask for by name', 'Whether you can answer the question a guest actually asks at the couch and the retail wall'],
          ['Signature language', `The house's own vocabulary, operating like a dialect`, 'Whether the guest, and the manager watching, hear that you belong'],
        ], caption: `A weakness in any one pillar shows. This course provides the map; each house's accredited training provides the depth.` },
        { kind: 'flow', title: 'Learning a house deliberately', steps: [`Origin story - philosophy nearly always flows from the founder's background`, 'Top five retail products - name, texture, key actives, the guest each suits', 'Two or three signature treatments - names, sequence, and the promise the marketing makes', `Register - read the house's own materials aloud and notice the words it repeats`, `Test yourself - can you consult, treat and recommend in the house's own voice?`], caption: 'Structured, repeated, tested - treat a new house the way a language student treats a new language.' },
      ],
      scenario: `You have accepted a role at a hotel spa whose product house you have never trained with, and you start in seven days. The spa manager has promised accredited training "in your first month", but you will be shadowing treatments and supporting the retail wall from day one.\n\nPlan the week using the deliberate-learning method: which of the house's own materials you will study first, in what order you will learn the origin story, hero products and signature treatments, and what you will honestly tell the manager about the limits of your current fluency. Decide what "ready for day one" actually means: not delivering protocols you are untrained in, but consulting and recommending in the house's register without blagging.`,
      activity: `Audit your own brand fluency in writing. List every house you have formally trained with, then for the one you know best write its philosophy in one sentence, name its top five retail products and three pieces of its signature language from memory, and check yourself against the house's own materials. Finally, rewrite the first line of your CV to lead with your strongest house and the protocols you are signed off on.`,
      knowledgeCheck: [
        { q: 'Why do hiring managers at branded spas screen CVs for house names before anything else?', options: ['Because brand names impress guests at reception', 'Because the product houses require it of their partner venues', 'Because an accredited therapist can be rostered onto the menu almost immediately, while an untrained one means weeks of ramp-up and supervised shifts', 'Because it filters out agency therapists'], answer: 2, why: `The screen is economic, not snobbish: house training is the difference between a therapist who earns from week one and one who costs training time first. That is why a buried accreditation is functionally invisible and the four-word CV line matters.` },
        { q: 'The three pillars of brand fluency are:', options: ['Philosophy, hero products and signature language', 'Price list, protocols and retail targets', 'Founder, headquarters and product ranges', 'Training, uniform and treatment menu'], answer: 0, why: `Philosophy dictates how you consult, touch and close; hero products let you answer the questions guests actually ask; signature language signals authentic training. A weakness in any one of the three shows.` },
        { q: 'The best first step when learning a new house deliberately is to:', options: ['Memorise the full price list', 'Book the signature treatment as a guest', 'Learn the protocols from videos', `Start with the origin story, because philosophy nearly always flows from the founder's background`], answer: 3, why: `A skin therapist founds a clinical house; an aromatherapist founds a holistic one. The origin story explains why everything else in the house is the way it is, which makes the products, treatments and register far easier to remember.` },
      ],
      keyTerms: [
        { term: 'Product house', definition: `A skincare brand that partners with spas to supply products, treatment protocols, training and retail, effectively defining the spa's menu and identity.` },
        { term: 'Brand fluency', definition: `Working command of a house's philosophy, hero products and signature language, sufficient to consult, treat and retail in that house's own register.` },
        { term: 'Hero product', definition: `An iconic product guests ask for by name, such as Elemis Pro-Collagen Marine Cream, which anchors the house's reputation and retail sales.` },
        { term: 'Signature language', definition: `The proprietary vocabulary a house uses, such as Tri-Enzyme or skin health, which signals authentic training to guests and managers.` },
      ],
      caseStudy: {
        title: 'The four-word CV line',
        scenario: `Priya, a Level 3 therapist with two years of experience, applies for a senior therapist role at a five-star Cotswolds hotel spa running ESPA. Her CV leads with her massage qualifications and a long list of treatment types, but her ESPA accreditation, completed at a previous hotel, is buried in a final paragraph. She is rejected at screening. A former colleague, now a spa manager, reviews the CV and moves "ESPA trained - full facial and body protocols" to the first line, adding the two hero ranges Priya knows best. Priya reapplies to a sister property and is invited to a trade test within days.`,
        insight: `Nothing about Priya's competence changed; her presentation of brand fluency did. Recruiters at branded spas scan for house names first because accredited therapists can be rostered onto the menu with minimal ramp-up, so a buried accreditation is functionally invisible. The professional response is to structure your CV around houses, list the specific protocols and ranges you are signed off on, and keep certificates ready to show. At the trade test, Priya's task is to prove the claim: consult, treat and recommend in ESPA's holistic, ritual-led register, not merely perform a technically sound facial.`,
      },
      summary: `Luxury spas do not simply stock products; they adopt a house whose philosophy, protocols, training and retail define the entire guest experience. For therapists, fluency in that house is a core employability asset, screened for on every CV and doubly critical on agency shifts. Fluency has three pillars: the house's philosophy, its hero products and its signature language. Learn houses deliberately, lead with them on your CV, and treat each new house as a language worth studying properly rather than a label on a bottle.`,
      nextStep: `Rewrite the opening line of your CV tonight to lead with your strongest house and the protocols you are signed off on - the four-word answer a hiring manager is scanning for.`,
    },
    {
      title: 'The British institutions: ESPA and Elemis',
      whyThisMatters: `ESPA and Elemis sit at the heart of the UK luxury spa landscape, so a working therapist is more likely to encounter these two houses than any others - often within the same week on agency shifts. They also demand opposite accents, which makes them the perfect training pair for code-switching: master the shift between ritual-led and results-led delivery here and every other house becomes easier to place. Guests who know these houses intimately will feel tonal inaccuracy within minutes.`,
      objectives: [
        'Describe the philosophy, hero products and treatment style of ESPA as an aromatherapy-rooted holistic house',
        'Describe the philosophy, hero products and treatment style of Elemis as a results-driven natural house',
        'Adapt your consultation tone and treatment narrative to deliver each house in its own accent',
      ],
      sections: [
        {
          heading: 'ESPA: holistic wellbeing, ritual-led',
          body: `ESPA was born in the UK with aromatherapy and holistic wellness at its core, and everything about the house flows from that root. Its formulations are built on natural actives and essential-oil blends, and its treatments are designed to treat the whole person rather than an isolated concern: a signature ESPA experience characteristically pairs facial work with scalp massage, back work and body ritual within a single treatment. Its hero products include the Optimal Skin range and its iconic bath and body oils, which guests buy to extend the ritual at home. The consultation is personalised and unhurried, often including a choice of oil blend guided by how the guest feels as much as how their skin presents. ESPA spas expect intuitive, ritual-led therapists: practitioners who read a guest's energy, sequence a treatment as a continuous journey, and never let the experience feel like a checklist of steps.`,
        },
        {
          heading: 'The ESPA register: how the house speaks',
          body: `ESPA language is calm, holistic and centred on the guest's inner state. Its recurring vocabulary includes wellbeing, balance, personalised blends, ritual and restoration. In an ESPA consultation you ask how the guest feels, how they sleep, what they need from the next ninety minutes; skin analysis matters, but it sits inside a wider conversation about the whole person. Recommendations are framed as continuing a ritual: a bath oil to close the day, a blend chosen for the guest's current state rather than a generic concern. Pace matters as much as wording. The ESPA accent is slower, softer and more spacious than a clinical consultation, with silence used deliberately during the treatment itself. A therapist who rushes an ESPA consultation, or who frames the treatment purely in terms of visible skin outcomes, is technically compliant but tonally wrong, and regular ESPA guests, who know the house intimately, will feel the difference immediately.`,
        },
        {
          heading: 'Elemis: results-driven naturals',
          body: `Elemis, also British, occupies different ground: clinically framed skincare built on marine and plant actives, positioned squarely on visible outcomes. Its Pro-Collagen family, most famously the Pro-Collagen Marine Cream, is one of the best-selling premium skincare lines in the UK, and guests frequently arrive already knowing it by name. The Elemis facial menu has historically paired hands-on skill with technology through its BIOTEC concept, combining touch with devices to amplify results. The Elemis register is confident and outcome-led: clinically proven, visible results, targeted actives. An Elemis consultation is closer to a diagnostic conversation, identifying the guest's priority concern and mapping a treatment and home-care plan against it, and the close of treatment explicitly reviews what has changed in the skin. Elemis spas prize therapists who can talk results with authority while keeping the warmth and sensory quality of a luxury treatment fully intact; clinical language delivered coldly is as wrong as vagueness.`,
        },
        {
          heading: 'Ritual versus result: matching the accent to the house',
          body: `The deepest skill in this lesson is not product knowledge but code-switching. An ESPA guest has bought a ritual: a whole-person journey where the measure of success is how transformed they feel walking out. An Elemis guest has bought a result: a visible change they expect you to identify, produce and point out. The same core techniques, cleansing, massage, mask work, sit inside both, but the framing, pacing and closing conversation differ completely. At an ESPA venue you close by anchoring the feeling and suggesting how to extend the ritual at home; at an Elemis venue you close by showing the outcome and prescribing the products that maintain it. Before any shift at either house, rehearse the accent: the three or four phrases you will use in consultation, the promise you will make, and the way you will close. Delivering each house in its own voice, not a generic luxury voice, is what separates a competent therapist from a convincing one.`,
        },
      ],
      visuals: [
        { kind: 'table', title: 'Two houses, two accents', headers: ['', 'ESPA', 'Elemis'], rows: [
          ['Root', 'Aromatherapy and holistic wellness', 'Results-driven naturals: marine and plant actives'],
          ['The guest is buying', 'A ritual - how transformed she feels walking out', 'A result - a visible change she expects you to produce and point out'],
          ['Consultation', 'How the guest feels, sleeps, what she needs from the next ninety minutes', 'A diagnostic conversation: priority concern, treatment and home-care plan'],
          ['Register', 'Wellbeing, balance, personalised blends, ritual, restoration', 'Clinically proven, visible results, targeted actives'],
          ['The close', 'Anchor the feeling; suggest how to extend the ritual at home', 'Show the outcome; prescribe the products that maintain it'],
        ], caption: 'The same core techniques sit inside both treatments; the framing, pacing and close differ completely.' },
        { kind: 'flow', title: 'Rehearsing the accent before a shift', steps: [`Revisit the house's hero products and signature treatments`, 'Rehearse three or four consultation phrases in its register', 'Decide the promise you will make in this house', 'Plan the close - the feeling for a ritual house, the visible outcome for a results house'], caption: 'Code-switching is deliberate, not improvised. Ten minutes of rehearsal before the shift is what makes the switch convincing.' },
      ],
      scenario: `You are covering an ESPA venue on Thursday and an Elemis venue on Saturday, and a colleague tells you not to overthink it because "a good facial is a good facial".\n\nThink through what actually goes wrong if you carry one voice into both rooms. On Thursday, an outcome-led close - pointing to visible changes and prescribing maintenance - would be technically compliant but tonally wrong for a guest who bought restoration. On Saturday, a slow, spacious consultation about sleep and inner balance would frustrate a guest who arrived asking for a visible result by name. Plan the ten-minute accent rehearsal you would do before each shift: the phrases, the promise and the close for each house.`,
      activity: `Choose one house you know well and one of the two houses in this lesson. Write four consultation phrases in each house's register, then say both sets aloud and notice how your pace, vocabulary and even posture shift between them. If you work at an ESPA or Elemis venue, check your phrases against the house's own training materials rather than your memory.`,
      knowledgeCheck: [
        { q: 'For an ESPA guest, the measure of a successful treatment is primarily:', options: ['A visible reduction in a named skin concern', 'How transformed she feels walking out of a whole-person ritual', 'The number of products used during the treatment', 'How efficiently the protocol was completed'], answer: 1, why: `ESPA is aromatherapy-rooted holistic wellness: the guest has bought a ritual, and success is restoration she can feel. Framing the treatment purely in terms of visible skin outcomes is tonally wrong at an ESPA venue, however sound the protocol.` },
        { q: 'At an Elemis venue, the professional close of a facial is to:', options: ['Suggest a bath oil to carry the ritual home', 'Keep words to a minimum and let the results speak', 'Anchor how the guest feels in the moment', 'Show the guest the visible change and prescribe the products that maintain it'], answer: 3, why: `Elemis is results-driven: the consultation identified a priority concern, and the close explicitly reviews what has changed and maps home care against it - delivered with warmth, because clinical language delivered coldly is as wrong as vagueness.` },
        { q: 'In this lesson, code-switching means:', options: [`Delivering each house in its own voice, letting its philosophy govern your framing, pacing and close`, 'Alternating between everyday English and technical treatment terminology', 'Switching product ranges partway through a treatment', 'Using one polished, generic luxury voice at every venue'], answer: 0, why: `The deepest skill is not product knowledge but tonal accuracy: the same hands-on techniques sit inside an ESPA ritual and an Elemis facial, and what separates a competent therapist from a convincing one is delivering each in the house's own accent.` },
      ],
      keyTerms: [
        { term: 'Optimal Skin', definition: `A hero ESPA skincare range, sitting alongside the house's iconic bath and body oils as the products guests most associate with the brand.` },
        { term: 'Pro-Collagen', definition: `Elemis's most famous product family, headed by the Marine Cream, one of the best-selling premium skincare lines in the UK.` },
        { term: 'BIOTEC', definition: `The Elemis concept of pairing hands-on facial techniques with technology to amplify visible results.` },
        { term: 'House accent', definition: `The distinctive tone, vocabulary and pacing of a brand's guest experience: ritual-led and holistic for ESPA, confident and outcome-led for Elemis.` },
      ],
      caseStudy: {
        title: 'Two hotels, one weekend',
        scenario: `Daniel, an agency therapist in London, is booked for a Saturday at a Knightsbridge hotel spa running ESPA and a Sunday at a City hotel running Elemis. On Saturday he consults gently, asks his guest how she has been sleeping, blends her oils with her, and delivers the facial as one continuous ritual that flows into scalp and back work, closing by suggesting a bath oil to carry the feeling home. On Sunday his guest arrives asking specifically about Pro-Collagen. Daniel shifts register entirely: he identifies her priority concern, explains the marine actives, delivers the treatment with clear commentary on what each stage is doing, and finishes by showing her the visible change and prescribing the Marine Cream.`,
        insight: `Daniel's protocols were sound on both days, but what earned him rebooking at both venues was tonal accuracy. He recognised that the ESPA guest was buying restoration and the Elemis guest was buying a demonstrable outcome, and he let each house's philosophy govern his pacing, vocabulary and close. The professional discipline is preparation: before each shift he revisited the house's hero products and rehearsed its register, so the switch was deliberate rather than improvised. Agency therapists who deliver every house in the same generic voice are rarely asked back; those who code-switch convincingly become the first name a spa manager calls.`,
      },
      summary: `ESPA and Elemis are the two great British institutions of the spa world, and they demand opposite accents. ESPA is aromatherapy-rooted holistic wellness: personalised blends, ritual-led treatments pairing skin work with scalp, back and body, heroes in the Optimal Skin range and its bath and body oils, and calm, spacious language. Elemis is results-driven naturals: marine and plant actives, the Pro-Collagen family led by the Marine Cream, the BIOTEC pairing of touch and technology, and confident outcome-led language. An ESPA guest expects a ritual; an Elemis guest expects a visible result, talked about with warmth and authority.`,
      nextStep: `Before your next shift at any branded venue, run the four-step accent rehearsal: hero products, consultation phrases, the promise, and the close that matches the house.`,
    },
    {
      title: 'The skin-health scientists and the sensorial houses',
      whyThisMatters: `Beyond the British institutions, the houses you will meet divide into recognisable families - dermatological, European science-led and sensorial - and each expects something different from the therapist delivering it. Knowing the families means you can place an unfamiliar house quickly and know what register it demands before your first guest. And because you will inevitably meet houses you have not trained with, the never-blag-a-brand rule in this lesson protects the three things an agency career runs on: guest trust, venue confidence and your own rebookings.`,
      objectives: [
        `Explain Dermalogica's skin-health philosophy, Face Mapping analysis and education-first culture`,
        'Compare the science-led European houses and the sensorial natural houses, identifying what each expects of a therapist',
        'Apply the professional protocol for working honestly with a house you have not yet trained in',
      ],
      sections: [
        {
          heading: 'Dermalogica: skin health, not beauty',
          body: `Dermalogica was founded by a skin therapist, and that origin defines everything about the house. Its position is deliberately unglamorous: skin health, not beauty. There is no fragrance-led romance and no spa theatre in its self-image; there is diagnosis, prescription and education. Its most famous tool is Face Mapping, a zone-by-zone analysis of the face in which each area is examined and read separately, producing a specific picture of the skin rather than a generic type. Its training arm is the most recognised in the industry, and the house expects its therapists to behave accordingly: a Dermalogica spa or skin centre wants diagnostic confidence, meaning you analyse methodically, prescribe precisely and educate the guest about their own skin at every step. The retail conversation follows naturally from the diagnosis rather than being bolted on at the end. If ESPA therapists are intuitives and Elemis therapists are results communicators, Dermalogica therapists are clinicians and teachers.`,
        },
        {
          heading: 'The European science tier: Comfort Zone, Natura Bissé and the medical-adjacent houses',
          body: `Beyond the British houses sits a tier of European science-led brands, each with a distinct character. Comfort Zone, from Italy, pairs science with a strong sustainability commitment, and its protocols reflect both: evidence-framed skincare delivered with conscience. Natura Bissé, from Spain, is diamond-tier luxury, beloved of five-star city spas, where its high-end facials command some of the highest prices on any UK menu; the house expects flawless, polished delivery to match. QMS Medicosmetics and Biologique Recherche occupy the medical-adjacent tier, with dense, technical protocols and devoted followings among guests who know the products in detail. The rule across this entire tier is uncompromising: if your venue stocks these houses, complete the house training before you improvise anything. Their protocols are precise, their guests are often more knowledgeable than a newly arrived therapist, and an approximation of a Natura Bissé or Biologique Recherche treatment is obvious to anyone who has had the real one.`,
        },
        {
          heading: 'The sensorial and natural houses: where the story is the product',
          body: `A different family of houses wins not on clinical claims but on scent, story and touch. Aromatherapy Associates, British and the recognised authority on aromatherapy, has bath oils with a legendary reputation. Bamford evokes organic English-countryside serenity. VOYA, from Ireland, builds its identity on hand-harvested seaweed. Sodashi and ila occupy the high-vibration natural luxury niche. In these houses the ritual and the narrative are the product: a VOYA guest is buying the west-of-Ireland shoreline and the hand-harvesting story as much as the seaweed itself, and a Bamford guest is buying a morning in the English countryside. The practical consequence for therapists is that you must learn each house's origin story and be able to tell it naturally, weaving provenance into the consultation and the treatment narrative. Delivering a sensorial house's treatment without its story is like performing a song without the melody: technically present, commercially and emotionally empty.`,
        },
        {
          heading: 'The universal rule: never blag a brand',
          body: `One rule holds across every house from Dermalogica to ila: never blag a brand. The temptation is real, particularly on agency shifts, where admitting a gap feels like admitting weakness. It is the opposite. Telling a spa manager "I trained with Elemis and ESPA; I would love to learn your house" earns respect, because it signals professional honesty and genuine interest, and most managers can adjust the column or pair you with house-trained colleagues. Improvising another house's signature ritual and getting it wrong, in front of a guest who may know that treatment by heart, is precisely how agency therapists fail to get rebooked; the guest complains, the venue loses trust in the agency, and your name carries the damage. The honest protocol is simple: declare your actual training, ask focused questions about the protocols you will deliver, study the house materials before the shift, and stay within what you can perform authentically. Honesty costs a moment of pride; blagging can cost a reputation.`,
        },
      ],
      visuals: [
        { kind: 'table', title: 'The brand families and what each expects', headers: ['Family', 'Houses named in this lesson', 'What the therapist must bring'], rows: [
          ['Dermatological', 'Dermalogica', 'Diagnostic confidence: methodical analysis, precise prescription, education at every step'],
          ['European science and medical-adjacent', 'Comfort Zone, Natura Bissé, QMS Medicosmetics, Biologique Recherche', 'House training completed before anything is improvised; flawless, polished delivery'],
          ['Sensorial and natural', 'Aromatherapy Associates, Bamford, VOYA, Sodashi, ila', 'The origin story told naturally - the ritual and the narrative are the product'],
        ], caption: 'Placing a house in its family tells you what register it demands before you meet your first guest.' },
        { kind: 'flow', title: 'The honest protocol for an unfamiliar house', steps: ['Declare your actual training to the manager, early and plainly', 'Ask focused questions about the protocols you will be expected to deliver', 'Study the house materials before the shift', 'Stay within what you can perform authentically', 'Use the gaps in the day to learn the house - convert the limitation into development'], caption: 'Honesty costs a moment of pride; blagging can cost a reputation.' },
      ],
      scenario: `You arrive for an agency shift and discover the venue runs a science-led house you have never trained with - one of those whose regulars often know the protocols in detail. The manager, stretched and hurrying, simply asks whether you are "okay with the menu".\n\nThink through exactly what you say in the next thirty seconds. Which of your actual trainings do you declare, what do you offer to deliver instead, and what do you ask to study between guests? Then trace the consequences of the alternative: an improvised signature treatment in front of a guest who has had the real one, a complaint, and a venue that stops calling your agency. The honest protocol protects the guest's experience, the venue's trust and your own rebooking prospects at once.`,
      activity: `Map the product houses at venues where you currently work, or would like to work, into the three families from this lesson. For each house, note honestly whether you could deliver in its register today or would need to declare a gap. Then draft the two-sentence declaration you would give a spa manager for your weakest house, modelled on "I trained with X and Y; I would love to learn your house".`,
      knowledgeCheck: [
        { q: 'Face Mapping is:', options: ['A planogram for arranging the retail wall', `Dermalogica's zone-by-zone facial analysis, reading each area of the face separately to produce a precise, individual diagnosis`, 'A facial massage sequence', 'A generic industry term for any skin analysis'], answer: 1, why: `Face Mapping is Dermalogica's signature diagnostic tool and a pillar of its skin-health-not-beauty philosophy: each zone is examined and read separately, and the prescription and education that follow flow from that specific picture.` },
        { q: 'For houses such as Natura Bissé and Biologique Recherche, the working rule is:', options: ['Improvise carefully from the classic facial architecture', 'Deliver massage only and avoid facials', 'Complete the house training before you improvise anything - their protocols are precise and their guests often know them in detail', 'Follow whatever the therapist in the next room does'], answer: 2, why: `The science and medical-adjacent tier has dense, technical protocols and devoted, knowledgeable followings. An approximation is obvious to anyone who has had the real treatment, which is why this tier is uncompromising about accredited training first.` },
        { q: 'Telling a spa manager you have not trained in their house:', options: ['Signals weakness and should be avoided where possible', 'Is only necessary for the medical-adjacent houses', 'Should wait until a guest notices something is wrong', 'Earns respect and lets the manager solve the problem operationally, by adjusting the column or pairing you with trained colleagues'], answer: 3, why: `Honest declaration signals professionalism and genuine interest, and managers can usually adjust the day around it. Blagging risks the guest's experience, the venue's trust in the agency and your own name - the exact three things rebooking runs on.` },
      ],
      keyTerms: [
        { term: 'Face Mapping', definition: `Dermalogica's signature zone-by-zone facial analysis, reading each area of the face separately to produce a precise, individual skin diagnosis.` },
        { term: 'Skin health positioning', definition: `Dermalogica's founding philosophy of treating skin as a clinical discipline, "skin health, not beauty", with education at the centre of every treatment.` },
        { term: 'Sensorial house', definition: `A brand such as Aromatherapy Associates, Bamford, VOYA, Sodashi or ila that wins on scent, story and touch, where the ritual and origin narrative are the product.` },
        { term: 'Blagging', definition: `Improvising an unfamiliar house's signature treatment rather than declaring your training honestly; the fastest way for an agency therapist to lose rebookings.` },
      ],
      caseStudy: {
        title: 'The seaweed question',
        scenario: `Megan, an experienced Dermalogica-trained therapist, takes an agency shift at a luxury coastal hotel spa in Cornwall that runs VOYA. Her first guest, a returning regular, is booked for the signature seaweed body ritual and begins chatting about her last visit and the story of the hand-harvested Irish seaweed. Megan has never performed the ritual. Instead of improvising, she had told the spa manager at check-in that VOYA was new to her; the manager moved her onto massage and Dermalogica-compatible facials for the day and asked the senior therapist to walk her through the VOYA story and protocols between guests. The regular guest received her ritual from a house-trained colleague, and Megan finished the day with a standing invitation back.`,
        insight: `Megan's honesty protected three things at once: the guest's experience, the venue's trust in the agency, and her own reputation. A VOYA regular who knows the ritual by heart would have detected an improvisation within minutes, and in a sensorial house, where the narrative of hand-harvested seaweed is inseparable from the treatment, a therapist who cannot tell the story cannot deliver the product. By declaring the gap early, Megan let the manager solve the problem operationally, and by using the day to learn the house's story and protocols she converted a limitation into a development opportunity. That is the behaviour that gets agency therapists rebooked.`,
      },
      summary: `The wider brand landscape divides into families. Dermalogica leads the dermatological tier with its skin-health philosophy, Face Mapping analysis and the industry's most recognised education. Comfort Zone, Natura Bissé, QMS and Biologique Recherche form a European science and medical-adjacent tier whose precise protocols demand house training before any improvisation. Aromatherapy Associates, Bamford, VOYA, Sodashi and ila are sensorial houses where the origin story and ritual are the product itself. Across all of them one rule is universal: never blag a brand. Honest declaration of your training earns respect; improvisation in front of a knowledgeable guest loses rebookings.`,
      nextStep: `Identify the one house that appears most often in job adverts for the venues you want to work in, and take a first concrete step towards its training this month - even if that step is only reading its materials and learning its origin story.`,
    },
  ],
}

export default content
