import type { CourseContent } from '../academy-types'

const content: CourseContent = {
  slug: 'retail-excellence',
  aims: `This course sets out to dismantle the most expensive misconception in the spa industry: that recommending products is "selling" and that selling is beneath a therapist. It repositions retail as the final phase of clinical aftercare, teaches a structured prescription method that begins inside the treatment itself, and equips you to handle guest hesitation with the same grace you bring to a massage. By the end, you will treat your retail figures not as a management imposition but as a professional metric you own, understand and can improve deliberately, in a way that strengthens rather than strains the guest relationship.`,
  audience: `Spa and wellness therapists working in, or aspiring to work in, UK luxury hotels, destination spas and day spas, including beauty therapists, massage therapists and skincare specialists at any career stage. It is particularly valuable for skilled practitioners whose treatment reviews are excellent but whose retail numbers lag, for newly qualified therapists entering commission-based environments for the first time, and for senior therapists preparing for head therapist or spa management roles where they will be expected to coach retail performance in others.`,
  outcomes: [
    'Frame product recommendation as clinical aftercare and deliver it after every treatment without pressure or discomfort',
    'Apply the prescription method: purposeful narration during treatment, a limited two-to-three product prescription linked to findings, and a written prescription card',
    'Diagnose the three common causes of guest hesitation, price, overwhelm and lack of urgency, and respond to each with a graceful, trust-building technique',
    'Track and articulate personal retail metrics, including link rate, retail-to-treatment percentage and average retail transaction, and use them as evidence of professional value in reviews and interviews',
  ],
  lessons: [
    {
      title: 'Reframing retail',
      objectives: [
        'Explain why product recommendation is properly understood as the final stage of aftercare rather than as selling',
        'Describe the commercial benchmarks for strong spa retail, including retail revenue at 10 to 20 percent or more of treatment revenue',
        'Adopt the prescriber mindset, drawing authority from the assessment you have just carried out rather than from sales techniques',
      ],
      sections: [
        {
          heading: 'Why therapists resist retail, and why the resistance is misplaced',
          body: `Ask a room of newly qualified therapists what they dread most and the answer is rarely a difficult massage sequence. It is the moment at the end when they are expected to mention products. The discomfort comes from a false picture: the therapist imagines themselves as a market trader pushing goods on a captive audience. That picture collapses under scrutiny. The guest on your couch has just received sixty minutes of expert assessment and treatment. They will go home to a bathroom shelf assembled from magazine articles, supermarket offers and guesswork. If their cleanser is stripping the barrier you spent an hour repairing, your work is undone within days. Recommending the correct home care is not an add-on to the treatment; it is the mechanism by which the treatment keeps working after the guest leaves. Seen this way, staying silent because you feel awkward is not modesty. It is withholding the most useful information you hold, which is a service failure dressed up as politeness.`,
        },
        {
          heading: 'Recommendation is aftercare: finishing the treatment',
          body: `Every professional treatment has three phases: assessment, intervention and aftercare. Medicine works this way, physiotherapy works this way, and luxury skincare works this way too. Aftercare advice that stops at "drink plenty of water" is incomplete, because for most skin and body concerns the decisive variable is what happens in the 720 hours between visits, not the one hour on your couch. The healthiest professional frame, and the one this course returns to repeatedly, is that recommendation is finishing the treatment. A bespoke facial without a home care prescription is a course of treatment abandoned halfway. UK luxury spas increasingly train to this frame explicitly, because it changes behaviour at both ends: therapists recommend consistently because it is simply part of the protocol, and guests receive the advice as care rather than commerce. The tone of the whole exchange changes when you genuinely believe, and you should, that the guest is better off knowing what you know.`,
        },
        {
          heading: 'The commercial reality: benchmarks and what they signal',
          body: `Retail is also a serious commercial matter, and understanding the numbers makes you a more credible professional. The widely used benchmark for strong spa retail in the UK and internationally is retail revenue running at 10 to 20 percent or more of treatment revenue, supported by a culture in which products are recommended after every treatment. Spas below that range are usually not staffed by worse therapists; they are staffed by therapists who recommend inconsistently or not at all. The margin structure explains why operators care so much: a treatment hour carries heavy costs in payroll, laundry, product usage and room time, while a retail sale requires almost no additional cost once the guest is already in the building. Retail revenue is therefore disproportionately valuable to the business, which is why it features in management reporting, appraisals and hiring decisions. None of this requires pushiness. The best-performing therapists in the sector reach these benchmarks without a single high-pressure moment, using the methods taught in the next lesson.`,
        },
        {
          heading: 'The prescriber mindset: expertise, not persuasion',
          body: `The final reframe is about authority. During the treatment you have examined this guest at close quarters: the dehydration lines across the cheek, the congestion along the jaw, the knotted trapezius, the reactive flush after steam. No retail assistant in a department store, and no algorithm on a website, will ever be better placed to advise this specific person than you are in this specific hour. That is why the professional vocabulary matters: you prescribe, you do not pitch. A pitch tries to create desire for a product; a prescription matches a product to a finding. The guest can feel the difference instantly. Prescribing also disciplines you: it forces every recommendation to trace back to something you actually observed or the guest actually said, which keeps you honest and keeps the guest's trust intact. Hold that standard and the awkwardness disappears, because you are no longer performing a sales role. You are completing a professional consultation, exactly as the guest would hope.`,
        },
      ],
      keyTerms: [
        { term: 'Aftercare', definition: `The advice, home routine and product guidance that extends a treatment's benefit between visits; in professional spa practice, product recommendation is part of aftercare, not separate from it.` },
        { term: 'Retail-to-treatment percentage', definition: 'Retail revenue expressed as a percentage of treatment revenue over the same period; 10 to 20 percent or more is the recognised benchmark for strong spa retail.' },
        { term: 'Prescriber mindset', definition: 'The professional stance of matching products to observed findings, as an expert completing a consultation, rather than persuading a guest towards a purchase.' },
        { term: 'Service failure by omission', definition: 'The idea that withholding a genuinely useful recommendation out of personal awkwardness delivers poorer service, because the guest leaves without information they needed.' },
      ],
      caseStudy: {
        title: 'The facial that lasted a week',
        scenario: `Priya, a therapist at a five-star country house spa in the Cotswolds, delivers an excellent brightening facial to a guest with a compromised skin barrier. Feeling that mentioning products would cheapen the moment, she closes with a warm goodbye and no recommendation. Three weeks later the guest returns for a follow-up and her skin is worse: she had gone home to a foaming supermarket cleanser and a gritty weekly scrub, precisely the products aggravating the barrier. The guest is polite but audibly disappointed, remarking that the facial "did not really last". Priya realises the guest has quietly concluded that the treatment, and by extension Priya, was not very effective.`,
        insight: `Priya's silence was intended as tact but functioned as a service failure. The guest never needed a sales pitch; she needed to be told that her cleanser was working against her skin and what to replace it with. The professional response is to treat the home care conversation as a non-negotiable part of the protocol, delivered as clinical advice: name the finding, name the corrective product, explain the connection. On the follow-up visit Priya did exactly that, the guest swapped one product, and the results held. The lesson is that recommendation protects your reputation as much as the guest's results.`,
      },
      summary: `Retail discomfort rests on a false picture of the therapist as salesperson. In reality, the guest's results depend far more on their home routine than on any single treatment, so recommending the right products is the completion of your work, not a departure from it. The industry benchmark for strong spa retail is a recommendation after every treatment and retail revenue at 10 to 20 percent or more of treatment revenue, achieved by the best therapists without pressure. Adopt the prescriber mindset: you assessed this guest at close quarters, so prescribe from findings, and never withhold advice out of awkwardness.`,
    },
    {
      title: 'The prescription method',
      objectives: [
        'Conduct purposeful narration during the treatment, introducing key products while the guest is experiencing them',
        'Construct a closing prescription of no more than two or three products, each linked explicitly to a consultation or treatment finding',
        'Apply the written prescription card technique, including telling the guest what not to buy, to convert honestly and build long-term trust',
      ],
      sections: [
        {
          heading: 'The recommendation begins in the treatment, not at the till',
          body: `The single biggest structural mistake in spa retail is treating the recommendation as an event that happens at the end, at reception, with the card machine in view. By then the guest has re-entered transactional mode and any mention of products lands as an upsell. The prescription method moves the work earlier: the recommendation begins during the treatment itself, when the guest is relaxed, receptive and physically experiencing the product on their own skin. Your consultation findings determine which products you will use; your use of those products becomes the demonstration; and the close becomes a brief summary of what the guest has already felt. Structured this way, nothing at the end needs to be sold, because the persuasive work has already been done by the product performing honestly on the guest's own skin. This is why experienced spa directors say the till conversation should be the shortest part of the retail process. If it feels like a pitch at the end, the method went wrong an hour earlier.`,
        },
        {
          heading: 'Purposeful narration: the most honest advertising in the industry',
          body: `Purposeful narration means speaking briefly and deliberately at key moments to connect a product with a sensation the guest is having right now. The classic form names the product, states what it is doing, and directs the guest's attention: "I am using the ESPA Optimal Skin cleanser here, notice how it dissolves everything without that tight, stripped feeling." Three short narrations across a facial, at the cleanse, the serum and the mask, are plenty; more becomes chatter and breaks the relaxation you are also being scored on. The technique is honest by construction: you can only narrate what is genuinely happening, and the guest verifies every claim against their own experience in real time. That is why it is often called the most honest advertising in the industry. Narration also solves the memory problem. A product named while the guest feels it working is encoded with the sensation attached, so at the close you are reminding, not introducing, and the guest recognises the product as something they already know and liked.`,
        },
        {
          heading: 'The disciplined close: two or three products, linked to findings',
          body: `At the close of the treatment, prescribe with discipline. The rule is no more than two or three products, and every one must be linked out loud to something you found. "Your skin is dehydrated rather than dry, so the one product I would send you home with is this hyaluronic serum" is a prescription; a tour of the retail shelf is not. Limiting the number matters for two reasons. First, choice overload is real: a guest offered seven products frequently buys none, while a guest offered one clear priority usually acts. Second, restraint is itself the trust signal. Deliberately telling the guest what not to buy, "the moisturiser you already have is perfectly good, keep it", proves that your advice serves their interest rather than the till, and that proof is what converts a first purchase into a repeat routine. Counter-intuitively, the therapist who prescribes least per visit often retails most per year, because guests return to a prescriber they trust and gradually adopt the full routine at their own pace.`,
        },
        {
          heading: 'Write it down: the prescription card',
          body: `The final step is physical: write the prescription down. A small card, branded or handwritten, listing the two or three products, the order of use and one line on why, converts far better than a verbal mention delivered at a busy reception desk. The reasons are practical. Guests emerging from a treatment are pleasantly foggy and retain little of what is said in the last five minutes; a card survives the fog. It also removes the awkward moment at the desk entirely, because the guest can hand the card to reception, or take it home and order later, without any renegotiation of the recommendation. Many UK spas report that a meaningful share of card-based prescriptions convert on a later visit or online rather than on the day, revenue that a purely verbal recommendation simply loses. Finally, the card extends your presence into the guest's bathroom: your name and your advice sit on their shelf for months, which is quiet, continuous relationship-building that no other closing technique achieves.`,
        },
      ],
      keyTerms: [
        { term: 'Purposeful narration', definition: `Briefly naming a product during the treatment and directing the guest's attention to what it is doing, so the recommendation is experienced rather than pitched.` },
        { term: 'Prescription close', definition: 'A closing recommendation limited to two or three products, each explicitly linked to a finding from the consultation or treatment.' },
        { term: 'Prescription card', definition: 'A written card listing the recommended products, order of use and rationale, handed to the guest; it converts better than verbal recommendation and captures later-visit and online sales.' },
        { term: 'Choice overload', definition: 'The tendency of guests offered too many options to buy nothing; the reason disciplined prescriptions outsell full-range presentations.' },
      ],
      caseStudy: {
        title: 'Three sentences in a facial',
        scenario: `Daniel, a senior therapist at a luxury hotel spa in Mayfair, is treating a first-time guest with congested, oily skin who declared at consultation that she "never buys spa products". He says nothing about retail for the first half hour. At the exfoliation stage he remarks, "This is the enzyme peel doing the work, that warmth is it lifting the congestion without any scrubbing." At the close he prescribes exactly two items, the enzyme peel for twice-weekly use and a lightweight moisturiser, and adds that the cleanser she described sounds fine to keep. He writes both on a card with usage notes. At reception the guest buys the peel unprompted and takes the card.`,
        insight: `Daniel never contradicted the guest's "I never buy" position, because he never asked her to be sold to. The narration let the product prove itself on her own skin at the moment of maximum credibility; the two-item limit respected her scepticism; endorsing her existing cleanser demonstrated that his advice was clinical, not commercial; and the card let her decide at the desk without pressure. This is the full prescription method in sequence: narrate during, prescribe two or three from findings, say what not to buy, and write it down. Each step lowered resistance instead of raising it.`,
      },
      summary: `A great recommendation is built during the treatment, not delivered at the till. Narrate purposefully at key moments so the guest experiences the product with its name attached, then close with a disciplined prescription of no more than two or three products, each tied aloud to a specific finding. Tell the guest what not to buy; that restraint is the strongest trust signal in spa retail and raises long-term spend. Finally, write the prescription on a card, because written prescriptions outconvert verbal mentions and keep earning sales long after the guest has left the building.`,
    },
    {
      title: 'Handling hesitation with grace',
      objectives: [
        `Diagnose which of the three underlying causes, price, overwhelm or lack of urgency, sits behind a guest's hesitation`,
        'Apply the matched response to each cause: the warm downsize, the single-step simplification, and the goal-and-timeline connection',
        `Close a genuine no gracefully, record the discussed products on the guest's record, and protect the lifetime value of the relationship`,
      ],
      sections: [
        {
          heading: 'Decoding "I will think about it"',
          body: `"I will think about it" is the most common sentence in spa retail, and the least literal. It almost never means the guest intends to go home and deliberate. In practice it signals one of three underlying states: price, the guest wants the result but the total feels too high today; overwhelm, the routine you described has too many steps to imagine actually doing; or no urgency, the guest believes you but sees no reason to start now rather than someday. Crucially, none of the three is a "no", and none is an invitation to push. Pushing at this moment is the fastest way to convert a soft maybe into a hard never. The professional skill is diagnostic: listen to the wording and watch the behaviour. A guest who picks up the product and checks the price label is telling you it is price. A guest who asks "and when would I use this one?" for the third time is overwhelmed. A guest who agrees with everything warmly and moves towards the door has no urgency. Diagnose first; only then respond.`,
        },
        {
          heading: 'Price and overwhelm: downsize and simplify',
          body: `When the hesitation is price, the graceful response is to agree cheerfully and downsize, never to discount and never to justify. "Completely understand. The serum is the workhorse of everything I showed you, start with just that one and it will do most of the heavy lifting." You have respected the budget, kept your clinical authority intact, and made the purchase easy. A single product that visibly works converts into a routine sale on the next visit far more reliably than a reluctant three-product basket that breeds buyer's remorse. When the hesitation is overwhelm, simplify to one step: "Ignore everything else I said, just swap your cleanser. That change alone will calm the redness." One instruction is memorable and doable; five instructions are homework. In both cases notice the shape of the move: you are reducing what you ask of the guest, which is the exact opposite of the pressure they braced for. That reversal is what makes the technique feel like service, and it is why guests handled this way come back.`,
        },
        {
          heading: 'No urgency: connect to the goal and the timeline',
          body: `The third cause, lack of urgency, needs a different key. The guest believes the product works; they simply file it under "someday". The response is to connect the recommendation to a goal and timeline the guest has already given you, which is one more reason the consultation matters commercially as well as clinically. "You mentioned the wedding in June, starting this now is what gets the result by then, because skin renewal takes several weeks to show" turns an abstract product into the next step of the guest's own plan. Note the ethics of the technique: you are not manufacturing urgency with offer deadlines or scarcity lines, which have no place in luxury service and which Forbes-level standards would penalise as pressure. You are surfacing real urgency that already exists in the guest's life and that they had not connected to the timeline of results. If the guest has shared no goal, do not invent one. Simply state honestly how long results take, and let that fact do the quiet work.`,
        },
        {
          heading: 'The graceful no and the fifty-times rule',
          body: `Sometimes, after a graceful response, it is still a no. Close warmly and completely: "Of course. I will note the two products on your record so we have them whenever you are ready." Then actually note them, because the therapist or receptionist who serves this guest next visit can reopen the conversation seamlessly, and guests are often quietly impressed that their file remembered. The commercial logic for all of this grace is the lifetime value calculation. A regular guest, visiting through the year, buying occasionally, referring friends, is worth on the order of fifty times a single forced sale. The guest who feels zero pressure today very frequently buys on visit two, once trust has compounded; the guest who feels cornered never returns at all, and in a luxury market they tell their friends why. Pressure complaints also travel upwards fast, and in five-star environments they end retail privileges and sometimes careers. Grace under refusal is therefore not softness. It is the highest-return commercial behaviour available to you.`,
        },
      ],
      keyTerms: [
        { term: 'The three causes of hesitation', definition: 'Price, overwhelm and lack of urgency: the three underlying states behind "I will think about it", each requiring a different matched response, and none of them a true no.' },
        { term: 'Warm downsize', definition: 'Responding to price hesitation by cheerfully reducing the prescription to the single most important product, preserving trust and setting up the routine sale on a later visit.' },
        { term: 'Goal-and-timeline connection', definition: 'Linking a recommendation to a goal and date the guest has already stated, surfacing genuine urgency rather than manufacturing it with offers or scarcity.' },
        { term: 'Lifetime value', definition: 'The total worth of a guest relationship over years of visits, purchases and referrals; a regular is worth roughly fifty times one pressured sale, which is why no guest should ever feel cornered.' },
      ],
      caseStudy: {
        title: 'The bride who bought in March',
        scenario: `Elena, a therapist at a five-star spa hotel in Edinburgh, finishes a radiance facial for a guest who mentioned during consultation that she is getting married in June. Elena prescribes a serum and an SPF moisturiser. The guest smiles, says "I will have a think about it", and reaches for her coat. Elena senses no price anxiety, the guest has just booked two further treatments without blinking, and no confusion, the routine is only two steps. She replies, "Of course. One thing worth knowing: you mentioned June, and skin renewal takes a good six to eight weeks to show, so starting in March is what has you glowing for the day itself, not the honeymoon." The guest pauses, laughs, and buys the serum on the spot, adding the moisturiser at her next visit.`,
        insight: `Elena diagnosed before responding. Price and overwhelm were visibly absent, so she treated the hesitation as lack of urgency and connected the prescription to a goal and deadline the guest herself had supplied. Everything she said was factually true, no invented offer, no scarcity, just the real biology of skin renewal mapped onto the guest's real calendar, which is why it read as expertise rather than pressure. Had the guest still declined, Elena's plan was to note both products on the record and close warmly, protecting a wedding-season guest whose lifetime value, including a likely bridal party, dwarfed one serum.`,
      },
      summary: `Hesitation is information, not rejection. "I will think about it" almost always means price, overwhelm or no urgency, and each has a matched, graceful response: downsize warmly to the single workhorse product, simplify to one step, or connect the recommendation to the guest's own goal and timeline. Never push, never discount without authority, and never manufacture urgency. If the answer is still no, close warmly and record the products for next time, because a zero-pressure guest often buys on visit two, and a regular's lifetime value is worth roughly fifty times any single sale.`,
    },
    {
      title: 'Retail as a career skill',
      objectives: [
        `Explain why managers read a therapist's retail performance as a composite measure of consultation quality, product knowledge, guest trust and commercial awareness`,
        'Calculate and track your personal retail metrics, including link rate, retail-to-treatment percentage and average retail transaction',
        'Build genuine product conviction through range knowledge and personal use, while applying the best-friend test to keep every recommendation ethical',
      ],
      sections: [
        {
          heading: 'Why your retail number is really four numbers in disguise',
          body: `When a spa manager reviews therapists for promotion, or a recruiter screens candidates for a five-star opening, retail performance is one of the first figures examined. This is not because managers are obsessed with the till. It is because a strong retail number is impossible to fake and impossible to achieve with a single skill. To retail well without complaints, a therapist must consult thoroughly enough to have findings worth prescribing from, know the product range deeply enough to match it to those findings, hold enough guest trust that recommendations are welcomed, and possess the commercial awareness to follow through consistently. Retail performance is therefore a composite: consultation quality, product knowledge, guest trust and commercial awareness compressed into one figure. A therapist with beautiful hands-on skills but a flat retail line is signalling a gap somewhere in that chain, usually consultation depth or confidence. Conversely, a strong, complaint-free retail record is one of the most persuasive single lines a spa CV can carry, because of everything it silently certifies.`,
        },
        {
          heading: 'Know your numbers: link rate and friends',
          body: `Professionals track their own metrics rather than waiting to be told them. Three matter most. Link rate is the share of your treatments that end with a retail purchase; it measures consistency of recommendation. Retail-to-treatment percentage is your retail revenue as a share of your treatment revenue; the strong-performance benchmark is 10 to 20 percent or more. Average retail transaction is the typical value when a guest does buy; it reflects prescription quality rather than volume. If your spa shares these figures, study yours weekly. If it does not, count privately: a note on your phone recording treatments delivered and products sold each shift is enough to calculate all three. The point of tracking is improvement you can steer. Moving a link rate from 10 percent to 30 percent, roughly from one purchase in ten treatments to one in three, marks you out immediately in any team, and it usually comes not from harder selling but from simply recommending after every treatment instead of when you happen to feel brave. Numbers also arm you for appraisals and interviews, where evidence beats adjectives every time.`,
        },
        {
          heading: 'Conviction: know the range, use the range',
          body: `You cannot prescribe with authority what you would not use yourself. The therapists with the strongest retail records are almost always the ones with the deepest product knowledge: they have read the brand training materials properly, they spend time with the testers, they can explain what a hero ingredient actually does in plain English, and they use the hero products in their own routines. This matters because conviction is audible. A guest can hear the difference between "this one is quite popular" and a first-hand account of what the product does, and only one of those sentences sells. Most UK spa brands, from ESPA to Elemis and the boutique houses, run therapist training and offer staff allocations or discounts precisely so that teams can build this first-hand knowledge; treat those schemes as career investment, not perks. Make a habit of learning one product deeply each week: its key ingredients, who it suits, who it does not suit, and how it fits a routine. Within a season you will know the range better than anyone on the shop floor, which is exactly where a prescriber should be.`,
        },
        {
          heading: 'The quiet rule of luxury retail',
          body: `Everything in this course sits under one governing rule: the guest should leave feeling looked after, never sold to. Luxury retail is quiet. There are no countdown offers, no bundles pressed at the desk, no second attempts after a no. The self-test that keeps you on the right side of the line is the best-friend test: if your recommendation would not survive being read back, word for word, to the guest's best friend, do not make it. "I recommended the serum because her skin was dehydrated and it is the fastest fix" survives easily. "I added the eye cream because I was close to my target" does not. This rule is not merely ethical decoration; it is commercially load-bearing. Trust is the asset that makes every future recommendation land, and one recommendation made for your reasons rather than the guest's can spend years of it in a moment. Hold the rule, track your numbers, build your conviction, and retail stops being the awkward part of the job. It becomes one of the clearest ways you demonstrate, visit after visit, that you are a complete professional.`,
        },
      ],
      keyTerms: [
        { term: 'Link rate', definition: 'The share of your treatments that end with a retail purchase; the primary measure of recommendation consistency, and a figure worth tracking privately even if your spa does not publish it.' },
        { term: 'Average retail transaction', definition: 'The typical value of a retail sale when a guest does buy; reflects the quality and relevance of the prescription rather than the frequency of selling.' },
        { term: 'Product conviction', definition: 'The authority that comes from deep range knowledge and personal use of the hero products; conviction is audible to guests and cannot be faked.' },
        { term: 'Best-friend test', definition: `The ethical self-check of luxury retail: only make a recommendation that would survive being read back, word for word, to the guest's best friend.` },
      ],
      caseStudy: {
        title: 'Two candidates, one head therapist role',
        scenario: `A destination spa in the Lake District is promoting internally to head therapist. Two strong candidates emerge. Marcus has outstanding treatment reviews and a link rate he has never checked; when asked about retail in his interview he says guests "buy when they want to". Sophie brings a small notebook: her link rate has risen from 12 percent to 34 percent over the year, her retail-to-treatment percentage sits at 19 percent, she can name her three best-prescribing products and explain why, and she has had no pressure complaints. She attributes the rise to recommending after every treatment and writing prescription cards. The spa director gives Sophie the role and asks her to coach the team using her own numbers.`,
        insight: `The director was not rewarding salesmanship; she was reading the composite. Sophie's figures certified consistent consultations, real product knowledge, guest trust robust enough to sustain a 34 percent link rate without a single complaint, and the commercial awareness a head therapist must pass on to others. Marcus may be the equal of Sophie on the couch, but he arrived with adjectives where she arrived with evidence, and he had never engaged with the number managers think in. The professional response for any ambitious therapist is Sophie's: track your own metrics, improve them deliberately, and be ready to narrate the improvement.`,
      },
      summary: `Retail performance is a composite figure that reflects consultation quality, product knowledge, guest trust and commercial awareness at once, which is why managers weigh it in hiring and promotion. Own your numbers: track your link rate, retail-to-treatment percentage and average retail transaction, privately if necessary, and improve them by recommending consistently rather than selling harder. Build genuine conviction by knowing the range and using the hero products yourself. Above all, honour the quiet rule of luxury retail: the guest leaves feeling looked after, never sold to, and every recommendation must pass the best-friend test.`,
    },
  ],
}

export default content
