import type { CourseContent } from '../academy-types'

const content: CourseContent = {
  slug: 'upgrading-treatments',
  aims: `This course teaches the commercial craft of upgrading treatments in a luxury spa: why the upgrade is the highest-margin revenue a spa can earn, when in the guest journey an offer is welcomed rather than resented, and the precise professional language that turns a recommendation into a yes without a trace of pressure. Throughout, one principle governs everything, the integrity rule: an upgrade must improve the guest's outcome, not merely enlarge the bill. Therapists who master this discipline lift average spend per guest measurably and sustainably, protect their complaint record, and build the reputation for trusted recommendation that leads to VIP allocations and promotion.`,
  audience: `Spa and wellness therapists working in UK luxury hotels, destination spas and day spas who deliver treatments and are expected to contribute to revenue; senior therapists preparing for supervisory or training roles; and agency therapists who want a repeatable, ethical upgrade method they can apply in any house. No prior sales training is assumed, only professional treatment competence.`,
  outcomes: [
    'Explain the margin economics of treatment upgrades and their role in average spend per guest, a core spa performance metric',
    'Identify and use the three natural upgrade moments in the guest journey: booking or arrival, consultation, and close',
    'Construct upgrade recommendations using outcome-led professional language, with price stated last, plainly and confidently',
    'Apply the integrity rule to every offer, accept a decline gracefully, and record forward recommendations on the guest record for future visits',
  ],
  prerequisites: `None beyond professional treatment competence; no prior sales training is assumed and the method is built from first principles.`,
  author: { name: 'WHC Academy', role: 'Developed by Wellness House Collective' },
  references: [
    { label: 'UK Spa Association - industry resources and operational guidance', url: 'https://www.spa-uk.org' },
    { label: `Your spa's own treatment menu, upgrade price list and brand training - offers only convert when quoted accurately` },
    { label: `Your spa's guest record system guidance - forward recommendations depend on how notes are recorded and shared` },
  ],
  lastReviewed: '2026-08-31',
  version: '1.0',
  lessons: [
    {
      title: 'The economics of the upgrade',
      whyThisMatters: `Upgrade revenue converts to margin at a rate no new booking can match, because the guest, the room and your booked time are already paid for. Average spend per guest is tracked by therapist in every serious spa and read alongside your complaint record when VIP allocations and promotions are decided. Understanding the economics is what lets you offer with confidence rather than apology.`,
      objectives: [
        'Explain why an upgrade earns exceptional margin compared with a new booking',
        'Describe how average spend per guest is used to evaluate therapist performance',
        'Apply the integrity rule to decide when an upgrade should and should not be offered',
      ],
      sections: [
        {
          heading: 'Where spa revenue really comes from',
          body: `Think of a spa as a building full of perishable hours. A treatment room that sits empty for an hour is revenue that can never be recovered, and every serious operator watches occupancy for exactly that reason. But there is a second, quieter loss that fewer therapists see: the booked hour that could have been worth more. A guest who books sixty minutes and would genuinely have benefited from ninety, or from a targeted enhancement, represents value the spa has already paid to attract, house and staff, and then left on the table. This is why upgrades sit at the top of the margin table. When you lengthen a treatment, add an enhancement or move a guest to a superior product line, almost every cost has already been incurred. The room is heated, the couch is dressed, your hands are booked and the guest has travelled in. What remains is largely product cost and your time, so the additional revenue converts to margin at a rate no new booking can match. The guest, the room and the therapist are already committed; the upgrade simply asks that committed hour to do more.`,
        },
        {
          heading: 'Average spend per guest and your career',
          body: `Luxury spas do not judge therapists on treatment quality alone, because quality is assumed at this level. The commercial measure that follows your name through a business is average spend per guest: the total a guest spends, across treatment, upgrades and retail, divided across the guests you serve. Every serious spa tracks it, usually by therapist and by month, and coordinators read it alongside your complaint and rebooking record. The combination matters. A therapist who lifts spend but generates complaints is applying pressure; a therapist whose spend stays flat may be technically excellent but commercially invisible. The professionals who advance fastest are those who lift average spend without a single complaint, because that pattern tells management something precise: this person's recommendations are trusted, and guests are happier for having taken them. Those are the therapists given the VIP suite bookings, the high-value regulars and the first conversation about promotion. Treat your upgrade skill as a professional signature, evidenced in the numbers, rather than an optional extra bolted onto the treatment work.`,
        },
        {
          heading: 'The integrity rule',
          body: `One rule governs every offer you will ever make: the upgrade must make the guest's outcome better, not just the bill bigger. This is not a slogan; it is a working test you apply before you speak. Ask yourself what the guest is trying to achieve today, and whether the upgrade genuinely serves it. A stressed guest with an open afternoon who would clearly benefit from thirty more minutes of work is being served when you offer the extension. The same offer made to a guest who has told you she is desperate to make a lunch booking is not selling, it is noise, and it costs something you cannot easily buy back: trust. A guest who senses that your recommendations track her interests will take them for years. A guest who senses even once that a recommendation tracked the till will quietly discount everything you say afterwards. The integrity rule is also your protection. When an offer passes the test, you can make it with full confidence, because you are prescribing as a professional rather than persuading as a seller, and guests hear the difference instantly.`,
        },
        {
          heading: 'What counts as an upgrade',
          body: `Upgrades take three main forms, and a fluent therapist holds all three in mind. The first is duration: moving a sixty-minute booking to ninety, which suits guests whose needs simply cannot be resolved in the shorter slot, particularly deep tension work. The second is the enhancement: a discrete addition such as a scalp massage, a foot ritual or hot stones layered into the existing treatment, usually adding fifteen to thirty minutes or slotting inside the booked time. The third is the product-line upgrade: delivering the same treatment with a superior range, where the guest pays for measurably better actives, textures and results. Each form answers a different guest situation. Duration answers depth of need, enhancements answer a specific complaint the guest has voiced, and product-line upgrades answer a guest who cares about results and quality more than time. Matching the form of upgrade to the guest's actual situation is the practical expression of the integrity rule, and it is why the consultation, covered in the next lesson, is where the strongest upgrades are born.`,
        },
      ],
      visuals: [
        { kind: 'table', title: 'The three upgrade forms at a glance', headers: ['Form', 'Typical example', 'Added time', 'Guest situation it answers'], rows: [
          ['Duration', '60 minutes moved to 90', '+30 min', 'Depth of need - tension that cannot resolve in the shorter slot'],
          ['Enhancement', 'Scalp massage, foot ritual, hot stones', '+15-30 min, or within the booked time', 'A specific complaint the guest has voiced'],
          ['Product line', 'Same treatment, superior range', 'None', 'A guest who cares about results and quality more than time'],
        ], caption: 'Matching the form to the guest\'s actual situation is the practical expression of the integrity rule. Prices vary by house; know yours before the shift starts.' },
      ],
      scenario: `Your 3pm guest has booked a sixty-minute massage and mentions in the corridor that her lower back has been troubling her for weeks and she has the whole afternoon free. Your column shows the 4pm slot unbooked, and you know ninety minutes would let you work the surrounding areas properly rather than rushing the back itself.\n\nBefore you speak, run the integrity test: what is she trying to achieve today, and does the extension genuinely serve it? Then decide exactly what you would say - and what you would do instead if her next words were that she is meeting a friend at 4.15.`,
      activity: `Before your next shift, find out your spa's current average spend per guest and, if it is tracked, your own figure. Then list the three upgrade forms as they exist on your menu - the duration moves, the enhancements and any product-line steps - with the exact price of each. Say each price aloud once, plainly, until it sounds as routine as a treatment time.`,
      knowledgeCheck: [
        { q: 'Why does upgrade revenue carry a higher margin than the same value from a new booking?', options: ['Because upgrades are priced higher than standard treatments', 'Because upgrades avoid marketing and booking costs only', 'Because the room, the guest and the therapist\'s booked time are already paid for, leaving largely product cost', 'Because upgrades are exempt from therapist commission'], answer: 2, why: 'Almost every cost of the hour was incurred by the original booking; the upgrade asks the committed hour to do more, so the additional revenue converts to margin at a rate a new booking cannot match.' },
        { q: 'A therapist lifts average spend per guest sharply, but her complaint rate rises in the same quarter. Management will most likely read this as:', options: ['Strong commercial performance worth rewarding', 'Evidence of pressure selling that is spending guest trust', 'A coincidence - the two figures are read separately', 'Proof that upgrade prices are set too high'], answer: 1, why: 'Spend is read alongside the complaint and rebooking record precisely to catch this pattern. Rising spend with rising complaints signals pressure; rising spend with a clean record signals trusted recommendation.' },
        { q: 'A guest has told you she must leave on time for a lunch booking. The ninety-minute extension would genuinely help her shoulders. The integrity rule says:', options: ['Say nothing today and note the recommendation on her record for next time', 'Offer it anyway - she can decide for herself', 'Offer a cheaper enhancement instead so something is sold', 'Ask reception to raise it when she pays'], answer: 0, why: 'The upgrade must serve what the guest is trying to achieve today. She cannot use the time, so the professional response is silence now and a forward note, converting the need on a visit when it can genuinely be met.' },
      ],
      nextStep: `On your next shift, apply the integrity test silently to every guest before deciding whether to offer anything - and notice how often the honest answer is that an upgrade genuinely would help.`,
      keyTerms: [
        { term: 'Average spend per guest', definition: `The total revenue a guest generates across treatment, upgrades and retail, tracked per therapist in every serious spa and read alongside complaint and rebooking records as a core performance measure.` },
        { term: 'Margin', definition: `The portion of revenue left after costs. Upgrade revenue carries exceptional margin because the room, the guest and the therapist's booked time are already paid for.` },
        { term: 'The integrity rule', definition: `The governing principle of ethical upselling: an upgrade must improve the guest's outcome, not just increase the bill. Any offer that fails this test damages trust.` },
        { term: 'Enhancement', definition: `A discrete addition layered into an existing treatment, such as scalp massage or hot stones, distinct from extending duration or moving to a superior product line.` },
      ],
      caseStudy: {
        title: 'The hour that was worth more',
        scenario: `Priya is a senior therapist at a five-star country house spa in the Cotswolds. Her 2pm guest, a regular named Mrs Ellison, has booked her usual sixty-minute back massage. In the corridor beforehand, Mrs Ellison mentions she has driven three hours, her shoulders are the worst they have been all year, and she has nothing planned until dinner. Priya knows the sixty-minute slot will barely open the tissue before it is time to close. She also knows the 3pm slot in her column is unbooked. She has perhaps thirty seconds to decide whether to say anything, and how.`,
        insight: `This is a textbook integrity-rule pass: the guest has voiced a greater need, has the time, and the capacity exists. Priya offers once, warmly, framing the outcome: with the state of those shoulders, ninety minutes would let her resolve the tension properly rather than just begin. Mrs Ellison accepts, the empty 3pm hour becomes near-pure margin, and the guest leaves with the result she actually came for. Had Mrs Ellison been rushing to an appointment, the professional response would have been silence today and a note on her record for next time.`,
      },
      summary: `Upgrades are the highest-margin revenue in a spa because the guest, the room and the therapist are already committed; only marginal costs remain. Average spend per guest is tracked in every serious spa, and therapists who lift it without complaints are trusted with VIPs and promoted first. Everything is governed by the integrity rule: an upgrade must improve the guest's outcome, not just the bill. An offer that serves the guest builds trust and revenue together; an offer that serves only the till spends trust you will not get back.`,
    },
    {
      title: 'The three natural moments',
      whyThisMatters: `Most declined upgrades fail on timing, not wording: the right offer at the wrong moment reads as pressure, and the same offer at the right moment reads as care. The forward plant also protects revenue the spa would otherwise lose entirely, converting upgrades weeks later, through colleagues, on visits you may never work. Timing discipline is what separates a therapist who sells more over a year from one who pushes in an afternoon.`,
      objectives: [
        'Identify the three natural upgrade moments in the guest journey and what makes each one work',
        `Construct a consultation-based upgrade offer that answers the guest's own words`,
        'Explain why one offer per moment is the professional limit, and how to plant an upgrade for a future visit',
      ],
      sections: [
        {
          heading: 'The schedule moment: booking and arrival',
          body: `The first natural moment arrives before the treatment begins, at booking or on arrival, and its currency is time. Early in the visit, the guest's day still feels open; she has not yet mentally locked her schedule, so an extension feels like a gift of space rather than a disruption. The phrasing works on that feeling: you have the sixty-minute booked; the ninety is our most rebooked treatment, and today I could extend you at no rush. Would you like the extra half hour? Notice what the words carry. The social proof is real, not invented: our most rebooked treatment is a fact drawn from the spa's own patterns. The offer is anchored to today's practical possibility, at no rush, which tells the guest the extension is genuinely available rather than a squeeze. And it closes with a clean, answerable question. Guests say yes most often at this moment precisely because nothing has been demanded of them yet; the visit is still all possibility. Reception teams and therapists who coordinate on the schedule moment convert extensions that would be impossible to sell an hour later.`,
        },
        {
          heading: 'The diagnosis moment: consultation',
          body: `The consultation is the strongest upgrade moment in the entire journey, because here the offer stops being a sale and becomes an answer. During consultation the guest tells you, in her own words, what is wrong: the scalp that tightens from screen work, the lower back that seizes on long drives, the skin that has felt dull since winter. Your job is to listen for the need the menu can answer, then connect the two explicitly: you mentioned your scalp gets tight from screen work; I can add fifteen minutes of scalp massage that targets exactly that. An upgrade tied to the guest's own words never feels like selling, because structurally it is not selling, it is prescription. The guest raised the problem; the professional supplied the remedy. This is also where the integrity rule is easiest to honour, since the need is documented in the conversation itself. Discipline matters here: recommend the one thing that best answers what you heard, not a tour of the enhancement menu. One precise prescription carries more authority than three possibilities, and authority is what converts.`,
        },
        {
          heading: 'The next-visit moment: planting forward at close',
          body: `Some days the upgrade simply cannot happen: the schedule is full, the guest is short of time, or the moment has passed. The professional response is not to abandon the recommendation but to plant it forward at the close of the visit. The phrasing looks ahead rather than back: next time, try the version with hot stones; with the tension you carry, you would feel the difference. Delivered after an excellent treatment, this lands as expert advice from someone who has just had her hands on the evidence. Then comes the step most therapists skip, and it is the one that makes the plant real: note the recommendation on the guest's record. A note such as recommended 90-minute hot stone next visit, carries significant upper-back tension, means that whoever books or treats this guest next, in a team of any size, can honour the recommendation seamlessly. The guest experiences a spa that remembers her; the spa converts an upgrade weeks after the words were spoken. A forward plant that lives only in your memory is a wish; on the record, it is a plan.`,
        },
        {
          heading: 'One offer per moment: the pressure line',
          body: `The three moments come with a strict professional limit: one offer per moment, made warmly, then accepted or declined without a flicker. The arithmetic of trust is unforgiving here. A single well-timed offer reads as attentiveness; the same offer repeated reads as pressure, and pressure in a relaxation environment is a category error the guest never forgets. If the extension was declined at arrival, it is not raised again in consultation; if the enhancement was declined in consultation, it does not reappear at the till. Declining must cost the guest nothing, not a beat of hesitation in your voice, not a shadow of disappointment on your face, because the moment saying no becomes uncomfortable, every future offer becomes a threat rather than a service. The three-moment structure exists partly to make this discipline easy: because you know another legitimate moment is coming, on this visit or the next, no single offer has to carry the weight of desperation. Therapists who trust the structure sell more over a year than those who push in an afternoon.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'The three moments in the guest journey', steps: ['BOOKING / ARRIVAL - the schedule moment: the day still feels open, so offer time', 'CONSULTATION - the diagnosis moment: the guest names the need, so offer the answer', 'TREATMENT - no offers; deliver', 'CLOSE - the next-visit moment: plant forward, then write it on the record'], caption: 'One offer per moment at most, and a decline closes that moment completely. The treatment itself is never an upgrade moment.' },
      ],
      scenario: `At arrival, your guest declines the offer of a ninety-minute extension - she is short of time today. During consultation she mentions that her scalp aches from screen work, and your menu carries a fifteen-minute scalp enhancement that fits inside her booked hour.\n\nThe extension was declined only minutes ago. Decide: does the one-offer-per-moment rule permit the scalp recommendation, and why? Then decide what you will do at the close of the visit if she declines that too.`,
      activity: `On your next three treatments, mark on your consultation card which of the three moments you used and what you offered, if anything. For any guest where no offer was right on the day, write one forward plant on their record in a format your colleagues could act on: the recommendation, the reason, and the guest's own words that prompted it.`,
      knowledgeCheck: [
        { q: 'The consultation is the strongest upgrade moment in the journey because:', options: ['An offer tied to the guest\'s own stated need functions as prescription rather than selling', 'The guest is at her most relaxed then', 'Prices sound lower before the treatment begins', 'It is the only moment reception cannot reach'], answer: 0, why: 'The guest raised the problem; the professional supplies the remedy. Structurally it is not selling, which is why consultation-based offers never feel like selling and are the easiest to hold to the integrity rule.' },
        { q: 'A guest declined an extension at arrival. During consultation she describes tension that a fifteen-minute enhancement would answer. You should:', options: ['Re-offer the extension - the new information justifies it', 'Offer the enhancement if it genuinely answers her stated need - it is a new moment and a different offer', 'Make no further offers for the rest of the visit', 'Ask her why she declined the extension earlier'], answer: 1, why: 'The declined offer stays closed for good - repetition is what turns an offer into pressure. But consultation is a distinct moment, and a different offer answering her own words is legitimate prescription, not repetition.' },
        { q: 'What turns a forward plant from a wish into a plan?', options: ['Repeating the recommendation to the guest at the till', 'Offering a small discount against the next visit', 'Mentioning it verbally to the coordinator at shift end', 'Writing the recommendation on the guest\'s record so any colleague can honour it at the next booking'], answer: 3, why: 'A plant that lives only in your memory converts only if you happen to treat that guest again. On the record, reception and any colleague can complete the sale weeks later, and the guest experiences a spa that remembers her.' },
      ],
      nextStep: `On your next shift, write at least one forward plant on a guest record in a form a colleague could act on without asking you anything.`,
      keyTerms: [
        { term: 'Schedule moment', definition: `The upgrade window at booking or arrival, when the guest's day still feels open and extensions of time convert best.` },
        { term: 'Diagnosis moment', definition: `The upgrade window during consultation, when a recommendation tied to the guest's own stated need functions as prescription rather than selling.` },
        { term: 'Forward plant', definition: `A recommendation made at the close of a visit for a future treatment, recorded on the guest's record so any colleague can honour it at the next booking.` },
        { term: 'One offer per moment', definition: `The professional limit on upgrade offers: each natural moment carries at most one warm offer, and a decline closes the subject for that moment without repetition.` },
      ],
      caseStudy: {
        title: 'The note that sold a treatment six weeks later',
        scenario: `Daniel works in the spa of a luxury Edinburgh hotel. In consultation, his guest Mr Okafor mentions that long-haul flights leave his calves and lower back wrecked, but today he has exactly sixty minutes between meetings. Daniel delivers a focused sixty-minute massage and, at the close, says that the ninety-minute version with heated basalt stones is built for exactly the flight tension he carries, and that he would feel the difference. Mr Okafor nods, pays and leaves. Daniel then writes on the record: frequent flyer, calves and lumbar priority, recommended 90-minute hot stone next visit. Six weeks later, Mr Okafor is booked in by reception, who see the note and offer the ninety-minute hot stone at booking. He accepts immediately.`,
        insight: `Daniel converted an upgrade he could not deliver by respecting the moment he was actually in. Today offered no room for extra time, so pushing would have failed the integrity rule and soured the close. Instead he used the next-visit moment: a specific, outcome-framed recommendation, then the record note that let a colleague complete the sale. The guest experienced continuity, the spa captured the revenue, and Daniel's name is attached to both the recommendation and the result, exactly the pattern coordinators look for when allocating high-value regulars.`,
      },
      summary: `Upgrades succeed on timing as much as wording. Three natural moments exist in every guest journey: the schedule moment at booking or arrival, when the open day makes extensions welcome; the diagnosis moment in consultation, where an offer tied to the guest's own words becomes prescription rather than selling; and the next-visit moment at close, where a recommendation is planted forward and noted on the guest record so the next booking can honour it. The limit is absolute: one offer per moment, made warmly, with any decline accepted without a flicker, because repetition is what turns an offer into pressure.`,
    },
    {
      title: 'Language that upgrades',
      whyThisMatters: `Two phrasings of the same offer convert at entirely different rates: the words decide whether the guest hears a professional prescribing or a cashier soliciting. How you state the price is equally commercial, because hesitation on your side is heard as doubt about the value, and doubt is contagious. The decline, handled well, is where next visit's yes is earned - which makes this the lesson with the most direct effect on your conversion rate.`,
      objectives: [
        'Construct upgrade offers using recommending language rather than transactional questions',
        'Sequence an offer so the outcome leads and the price comes last, stated plainly and confidently',
        'Demonstrate the professional response to a decline, and explain why it drives future upgrades',
      ],
      sections: [
        {
          heading: 'Recommend, never solicit',
          body: `Two sentences can carry the same commercial content and land in opposite worlds. Do you want to add anything? is a question about spending; it hands the guest a till decision and casts you as a cashier. May I recommend...? is a professional prescribing; it casts you as the expert whose judgement the guest came to buy. Always the second. The distinction is not cosmetic. Recommending language activates the authority you have already earned through the consultation and your hands, while soliciting language discards it. It also changes what a no means: declining a recommendation is declining an option, socially weightless; declining a request to spend can feel like rebuffing a person, which makes guests defensive before you have finished the sentence. Build your personal repertoire around the recommending frame: may I recommend, what I would suggest for you, based on what you have told me, if this were my skin or my shoulders. Every one of these places your expertise between the guest and the price, which is exactly where a luxury guest wants it to be.`,
        },
        {
          heading: 'Lead with the outcome, land on the price',
          body: `The sequence of an offer matters as much as its vocabulary. Lead with the outcome the guest will feel, not the mechanism or the money: so the tension release lasts days rather than hours does the persuading; it is an extra twenty-five pounds for thirty minutes does not. Mechanism and duration can follow, briefly, as evidence that the outcome is real. The price comes last, and how you say it is a skill in itself: plainly, at normal volume, in the same warm register as everything before it. That is an additional twenty-five pounds. Full stop. No softening words, no apologetic drop in tone, no rushing past it. Discomfort is contagious: if the price embarrasses you, the guest hears that you do not believe the value is there, and her doubt is simply your doubt reflected back. Confidence is equally contagious. A price stated as calmly as a treatment time tells the guest this is a normal, worthwhile choice that guests make every day, which, in a well-run spa, is precisely the truth.`,
        },
        {
          heading: 'The power of specificity',
          body: `Generic language is the fingerprint of a script; specific language is the fingerprint of an expert. Compare our premium option with the deeper work your shoulders need. The first could be said to anyone by anyone; the second could only be said to this guest by someone who has assessed her. Specificity does three jobs at once. It proves you listened, because the detail comes from the guest's own consultation. It personalises the value, because the outcome is anchored to her body, her skin, her week, not to a menu description. And it differentiates you from every retail encounter the guest has ever endured, because scripts are what she has learned to deflect. Practical discipline: before any offer, name to yourself the specific finding it answers, the right side of the neck, the dehydration under the oil, the flight on Thursday, and put that finding into the sentence. If you cannot name a specific finding, the offer probably fails the integrity rule and should not be made at all. Specific equals expert; generic equals script, and guests can tell the difference in under five words.`,
        },
        {
          heading: 'Accepting the no beautifully',
          body: `Every offer has two possible endings, and the decline is the one that reveals the professional. The response is short, warm and total: of course, I will make the sixty minutes count. Then, and this is the substance of the skill, you do exactly that. The guest who declines and still receives your absolute best has just run an experiment on you, whether she meant to or not, and your treatment is the result. If the quality after a no is indistinguishable from the quality after a yes, she has learned something valuable: the offer was real, made for her benefit, with nothing riding on her answer. That guest upgrades next time at remarkable rates, because the risk has been removed from saying yes and from saying no alike. The inverse is career poison: a flicker of disappointment, a slightly flatter treatment, a second mention at the end, and the guest learns that offers from you carry a social bill. Handled beautifully, a no is not a lost sale; it is a deposit in the account every future yes is drawn from.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'The shape of a professional offer', steps: ['OUTCOME - the benefit the guest will feel, anchored to her own words', 'EVIDENCE - brief mechanism or duration that makes the outcome credible', 'PRICE - stated last, plainly, at normal volume, then stop', 'ANSWER - accept a yes warmly; accept a no completely, and deliver your best either way'], caption: 'The sequence does the persuading. Reversed - price first, outcome last - the same offer becomes a till transaction.' },
        { kind: 'table', title: 'Soliciting versus recommending', headers: ['Soliciting (avoid)', 'Recommending (use)', 'Why it works'], rows: [
          ['Do you want to add anything?', 'May I recommend...', 'Places your expertise between the guest and the price'],
          ['Our premium option is available', 'The deeper work your shoulders need', 'Specific to this guest - proves you listened'],
          ['It\'s only twenty-five pounds more...', 'That is an additional twenty-five pounds.', 'A plain, confident price signals the value is real'],
        ], caption: 'Generic language is the fingerprint of a script; specific language is the fingerprint of an expert.' },
      ],
      scenario: `In consultation, your guest mentions dull, dehydrated skin after a winter of central heating. Your spa's facial can be delivered with the superior product line for an additional eighteen pounds.\n\nDraft your offer in your head before reading on: which of her words will you anchor it to, what outcome leads, what brief evidence follows, and exactly how will you say the price? Now imagine she pauses and says not today, thanks. Rehearse your reply in full - and what you will do with the remaining hour.`,
      activity: `Write out one complete upgrade offer for the treatment you deliver most often: outcome first, brief evidence, price last. Say it aloud until the price lands in the same warm register as the rest of the sentence, with no softening words. Then rehearse the decline response - of course, I will make the sixty minutes count - until it comes without a beat of hesitation.`,
      knowledgeCheck: [
        { q: 'Why does the price come last in a professional offer?', options: ['Guests remember the last thing said most clearly', 'So the outcome and evidence have established the value before the cost is weighed against it', 'It gives the guest less time to object', 'Because most house scripts require it'], answer: 1, why: 'Lead with the outcome the guest will feel, support it briefly, and only then state the price - plainly and confidently. The sequence lets the value do the persuading before the number arrives.' },
        { q: 'A guest declines your offer. The most commercially valuable response is:', options: ['A brief, warm acceptance, then your absolute best work inside the booked scope', 'A gentle second mention at the end, in case she reconsiders', 'Immediately offering a smaller, cheaper alternative', 'Noting warmly that most guests do take it'], answer: 0, why: 'The declined guest is running an experiment on you. If your quality after a no is indistinguishable from after a yes, she learns the offer was genuine - and guests treated this way upgrade next time at remarkable rates. Any second mention converts the offer into pressure.' },
        { q: 'Which offer best demonstrates the specificity principle?', options: ['You would love our most popular enhancement', 'Many guests add the hot stones at this time of year', 'For the tightness on the right side of your neck, fifteen minutes of focused work would let it release properly', 'Our premium range gives visibly superior results'], answer: 2, why: 'It could only be said to this guest by someone who has assessed her - the finding from her own consultation is in the sentence. The others could be said to anyone by anyone, which is exactly what guests have learned to deflect.' },
      ],
      nextStep: `Make one outcome-led, specifically anchored offer on your next shift, state the price plainly, and whatever the answer, deliver the treatment that proves the offer was genuine.`,
      keyTerms: [
        { term: 'Recommending language', definition: `Offer phrasing built on professional prescription, such as 'may I recommend', which places the therapist's expertise at the centre of the offer, in contrast to transactional questions about adding or spending.` },
        { term: 'Outcome-led framing', definition: `Structuring an offer so the benefit the guest will feel comes first, supporting detail second, and price last, stated plainly and confidently.` },
        { term: 'Specificity', definition: `Anchoring an offer to a named finding from this guest's consultation or treatment. Specific language signals expertise; generic language signals a script.` },
        { term: 'Accepting the no', definition: `Responding to a decline warmly and completely, then delivering the booked treatment at full quality, which teaches the guest that offers are genuine and makes future acceptance more likely.` },
      ],
      caseStudy: {
        title: 'The decline that became a regular',
        scenario: `Sophie, a therapist at a luxury spa hotel in the Lake District, is in consultation with a first-time guest, Ms Hartley, who has booked a sixty-minute massage and mentioned that her neck has been stiff since a house move. Sophie offers once: may I recommend adding our heated neck and shoulder ritual, so the release in that neck lasts well beyond today; it is an additional twenty pounds. Ms Hartley hesitates, then declines; money is tight after the move. Sophie replies, of course, I will make the sixty minutes count, and quietly ensures the neck receives visible, generous attention within the booked hour. At reception afterwards, Ms Hartley rebooks for the following month and asks for Sophie by name.`,
        insight: `Sophie's offer was textbook: recommending language, outcome first, price last and plain, anchored to the guest's own words about her neck. But the decline was where she earned the future. By absorbing the no without a flicker and delivering her absolute best inside the booked scope, she proved the offer had been for the guest's benefit. Ms Hartley left having learned that recommendations from Sophie are safe to accept and safe to refuse, which is exactly why, two visits later, she took the ritual without being asked twice. The no was not a failure; it was the foundation of the relationship.`,
      },
      summary: `The words do the work. Recommend rather than solicit: may I recommend positions you as a professional prescribing, where do you want to add anything makes you a cashier. Lead with the outcome the guest will feel, add brief supporting detail, and state the price last, plainly and confidently, because discomfort with the price on your side creates discomfort on theirs. Be specific, drawing every offer from this guest's own findings, since specific equals expert and generic equals script. And accept every no beautifully, then deliver your absolute best anyway; that is how declined guests become the ones who upgrade next time.`,
    },
  ],
}

export default content
