import type { CourseContent } from '../academy-types'

// Split out of the pack beside it so a course title can be imported
// without dragging every lesson of every course along with it.

export const content: CourseContent = {
  slug: 'cancer-care-awareness',
  aims: `This course gives spa and wellness therapists a confident, compassionate, awareness-level understanding of cancer and its treatments as they affect the spa guest. It teaches the common physical effects of surgery, chemotherapy, radiotherapy and related therapies; the contraindications, cautions and practical adaptations that keep treatments safe and comfortable; the communication and emotional-care skills a disclosure deserves; and the professional frame of scope, consent, documentation and referral. It is explicitly awareness-level training: it does not replace accredited oncology touch certification such as Made for Life or Jennifer Young-style programmes, which many insurers require before therapists treat guests in active treatment. Throughout, the standard is to follow venue protocols, the guest's own medical guidance and insurance requirements, never to diagnose, and when in doubt to adapt conservatively or refer.`,
  audience: `Spa and wellness therapists in UK luxury hotels, destination spas and premium day spas who want to welcome guests living with and beyond cancer safely, warmly and within their professional scope. It suits therapists who have encountered a disclosure mid-consultation and wished they had felt better prepared, agency and freelance therapists who meet unfamiliar venue protocols at short notice, spa managers and head therapists who set consultation and referral policy, and reception teams who handle sensitive bookings and enquiries. It is also a considered first step for any therapist planning to progress to accredited oncology touch certification.`,
  outcomes: [
    'Describe the main cancer treatments and their common effects on the body a therapist works with, in accurate, compassionate language',
    'Identify contraindications and cautions, and adapt pressure, heat, products, positioning and timing to keep treatments safe and comfortable',
    'Conduct a private, calm, present-tense consultation after a disclosure, avoiding both fear-mongering and false reassurance',
    'Apply the professional frame of scope, informed consent, confidentiality, documentation and graceful referral on every sensitive booking',
    'Explain where awareness-level practice ends and where accredited oncology touch training, venue protocol and insurance requirements begin',
  ],
  prerequisites: 'A recognised therapy qualification. This awareness course supplements, and never replaces, specialist clinical training.',
  author: { name: 'WHC Academy', role: 'Developed by Wellness House Collective' },
  references: [
    { label: 'NHS website - general health information for the public', url: 'https://www.nhs.uk' },
    { label: 'Recognised specialist training providers offer accredited oncology touch programmes; ask your venue and insurer which they recognise' },
    { label: `Your own spa's written protocols and insurance documents - the governing references for everything in this course` },
  ],
  lastReviewed: '2026-08-31',
  version: '1.0',
  lessons: [
    {
      title: 'Understanding cancer and its effect on the spa guest',
      whyThisMatters: `Guests living with and beyond cancer are part of every spa's guest book, whether or not the booking says so. For them, a therapist who understands calmly can turn an ordinary hour into a rare experience of being cared for as a person rather than a patient. For you, that steadiness is both a professional duty and one of the most valued skills a luxury spa can hire.`,
      objectives: [
        'Explain, in plain professional language, why cancer is many diseases and why the therapist works with effects, never diagnoses',
        'Describe the common physical footprints of surgery, chemotherapy, radiotherapy and related treatments that matter in the treatment room',
        'Recount why the old blanket refusal of massage is outdated, and state accurately what adapted touch within medical guidance can offer',
      ],
      sections: [
        {
          heading: 'Many diseases, one person on your couch',
          body: `Cancer is an umbrella term for a large family of diseases, differing in site, behaviour, treatment and outlook. That is the first professional reframe: there is no single "guest with cancer", and nothing useful follows from the word alone. The person in front of you may be newly diagnosed, mid-treatment, recently finished, or years into life beyond cancer; they may feel fragile, or they may feel entirely well and simply want the treatment they booked. Your role is never to interpret the diagnosis - that belongs to their medical team - but to understand how their disease and its treatment are affecting them today, and to shape the hour around that. This reframe also protects you from the two commonest errors: treating every guest with a history of cancer as an emergency, and treating none of them as needing any adjustment at all. Both are failures of the same kind, a response to the label rather than the person. The consultation, covered fully in lesson three, is where the label gives way to the individual.`,
        },
        {
          heading: `What the treatments do: the therapist's map`,
          body: `The main medical treatments each leave a footprint a therapist should recognise. Surgery leaves scars, altered sensation, and sometimes the removal or irradiation of lymph nodes, which can create a lifelong risk of lymphoedema, a swelling of the nearby limb when lymphatic drainage is compromised. Chemotherapy commonly brings deep fatigue, nausea and heightened sensitivity to smell, thinning or loss of hair with a tender scalp, dry and reactive skin, easier bruising when platelets are low, and reduced resistance to infection when white cells are low. Some guests have peripheral neuropathy, altered or numbed sensation in hands and feet, which matters enormously for pressure and heat. Radiotherapy affects the treated area specifically: skin there can be red, fragile and sore during and after a course, and is avoided until healed. Hormone therapies can bring hot flushes, joint aches and skin changes; immunotherapies vary widely. Many guests also carry a medical device, a port or PICC line, through which treatment is given. None of this list is for reciting at the guest; it is your quiet map for the adaptations in lesson two.`,
        },
        {
          heading: 'The outdated blanket ban, and what replaced it',
          body: `For decades, therapists were trained to refuse all massage to anyone with cancer, on the belief that touch and increased circulation could spread the disease around the body. That teaching is now understood to be outdated, and the profession has moved on: appropriately adapted touch, delivered by properly trained hands in line with the guest's medical guidance, is widely offered across professional spa and in cancer care settings themselves. The shift matters for two reasons. First, because the old rule caused real harm of its own kind: people at the most isolating time of their lives were turned away at spa reception desks and made to feel contaminated. Second, because the correction is not a swing to "anything goes". The modern standard is adapted touch within a professional frame: awareness training such as this course, accredited oncology touch certification where insurers and venues require it, medical guidance where protocol demands it, and conservative adaptation always. What a spa can offer such a guest is precious: an hour of being touched with skill and care, as a person rather than a patient. Delivering that safely is what the rest of this course teaches.`,
        },
        {
          heading: 'The awareness-level frame, stated plainly',
          body: `Before any technique, fix the frame this whole course sits inside. This is awareness-level training. It exists to make you knowledgeable, calm and safe: able to understand what a guest may be experiencing, hold a sensitive consultation, adapt a treatment conservatively within your venue's protocols, and refer well when referral is the right call. It does not, on its own, qualify you to treat guests in active cancer treatment. That work is the province of accredited oncology touch programmes, of which Made for Life and Jennifer Young-style training are well-known examples in the UK, and many insurers require such certification before a therapist takes those bookings. Every venue also has its own protocol, and many require confirmation that the guest's medical team is content for them to receive treatment. Your personal rule of practice therefore has three clauses: follow the venue's protocol, follow the guest's medical guidance, and stay inside what your insurance covers. Where any of the three is unclear, the default is always the same: adapt conservatively, or refer. Held confidently, this frame is not a restriction; it is what makes every other page of this course usable.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'From label to person: the awareness reframe', steps: ['A diagnosis appears on the consultation form', 'Receive it calmly - the word begins a conversation, it does not end the booking', 'Ask how the guest is affected today - never what the diagnosis means', `Check venue protocol and, where required, the guest's medical guidance`, 'Adapt conservatively within your training - or refer'], caption: 'The reframe this lesson teaches, as a sequence you can rehearse before a guest ever needs it.' },
      ],
      scenario: `A guest arrives for a back, neck and shoulder massage and has written a single word, radiotherapy, on her consultation form. She says brightly that she is absolutely fine, that treatment finished recently, and that she would rather not make a fuss. She moves stiffly, and you do not know what your venue's protocol asks for guests so recently out of treatment. Her cheerfulness is welcome, but it does not replace the protocol check, the present-tense questions about how she is affected today, or the conservative adaptations that follow. If the protocol or your training leaves any doubt, the answer is already written: adapt conservatively, or refer.`,
      activity: `Find and read your spa's written protocol for guests living with and beyond cancer. Note what it permits at your level of training, what requires medical confirmation, and who on the team holds accredited oncology touch certification. If you cannot find a written protocol, raise it with your manager this week: knowing where it lives, and what it says, is the first practical act of awareness.`,
      knowledgeCheck: [
        { q: `A guest writes 'chemotherapy' on her consultation form and nothing more. Your first professional move is to...`, options: ['Cancel the treatment, because chemotherapy rules out all spa treatments', 'Thank her calmly, ask how she is affected today, and check what your venue protocol requires', 'Ask what type of cancer she has so you can plan the treatment yourself', 'Proceed as normal so she does not feel singled out'], answer: 1, why: `The word on the form begins a conversation, not a refusal. Your role is the effects today, the venue protocol and, where required, medical guidance - never interpreting the diagnosis.` },
        { q: 'The old teaching that all massage must be refused to anyone with cancer is best described as...', options: ['Still the safest rule to follow', 'Correct for body treatments but not for facials', 'A current legal requirement in UK spas', 'Outdated - adapted touch within training, protocol and medical guidance is the modern professional standard'], answer: 3, why: `The blanket ban is outdated, but its replacement is not 'anything goes': it is adaptation inside a professional frame of training, venue protocol and the guest's medical guidance.` },
        { q: 'This course prepares you to...', options: ['Understand, adapt conservatively and refer - it is awareness-level and does not replace accredited oncology touch certification', 'Treat guests in active treatment once you have read it carefully', 'Advise guests on managing the side effects of their treatment', 'Decide for yourself which cautions still apply to each guest'], answer: 0, why: 'Awareness-level training makes you knowledgeable, calm and safe within your scope. Treating guests in active treatment belongs to accredited certification, venue protocol and, where required, medical confirmation.' },
      ],
      keyTerms: [
        { term: 'Lymphoedema', definition: `Swelling, most often of a limb, caused by compromised lymphatic drainage, for example after lymph node removal or radiotherapy; the risk can be lifelong and shapes how the nearby limb is treated.` },
        { term: 'Peripheral neuropathy', definition: `Altered, reduced or tingling sensation, typically in the hands and feet, which some cancer treatments cause; it changes how a guest perceives pressure and heat, so the therapist cannot rely on the guest feeling what is too much.` },
        { term: 'PICC line / port', definition: `Medical devices through which treatment is delivered: a fine tube in the arm or a small implanted chamber under the skin. The area around any device is never worked over.` },
        { term: 'Awareness-level training', definition: `Education that prepares a therapist to understand, adapt and refer, without qualifying them to treat guests in active treatment; that requires accredited oncology touch certification, which many insurers mandate.` },
      ],
      caseStudy: {
        title: 'The quiet disclosure at Harewell Manor, the Cotswolds',
        scenario: `Priya is a senior therapist at Harewell Manor, a luxury country house spa in the Cotswolds. Her two o'clock guest, Mrs Ellison, has booked a sixty-minute aromatherapy massage as a birthday gift from her daughter. On the consultation form, under medical history, she has written a single word: chemotherapy. When Priya gently opens the subject, Mrs Ellison says she finished her final cycle six weeks ago, that she is tired all the time, that her skin has never felt so dry, and that she nearly cancelled because a spa refused her a massage two years ago and she could not face that again.`,
        insight: `Priya's awareness training does its quietest, most important work before any technique: she does not flinch, and she does not turn Mrs Ellison away. She thanks her, asks how she feels today and what her medical team has advised, and checks the venue protocol for post-treatment guests, which Harewell Manor's policy and her own training allow her to meet with a conservatively adapted treatment: lighter pressure, gentle products, extra warmth and no time pressure. The lesson is the reframe itself: the word on the form is the beginning of a conversation, not the end of a booking.`,
      },
      summary: `Cancer is many diseases, and the therapist's concern is never the diagnosis but its effects on the guest today. Surgery, chemotherapy, radiotherapy and related treatments leave recognisable footprints: fatigue, fragile and reactive skin, altered sensation, easy bruising, infection risk, tender scalps, medical devices and lifelong lymphoedema risk after lymph node treatment. The old blanket refusal of massage is outdated; the modern standard is adapted touch within a professional frame of protocol, medical guidance and insurance. This course is that frame at awareness level: understand, adapt conservatively, refer well, and never diagnose.`,
      nextStep: 'Before your next shift, find out exactly where your spa keeps its protocol for guests affected by cancer, and read it from start to finish.',
    },
    {
      title: 'Contraindications, cautions and treatment adaptations',
      whyThisMatters: `Adaptation is where awareness becomes care a guest can actually feel. Therapists who can quietly re-engineer pressure, heat, products and positioning within protocol are the ones coordinators trust with the most sensitive bookings, and the guest experiences that skill as personalisation rather than caution.`,
      objectives: [
        'Identify the areas, conditions and circumstances that rule treatment elements out or demand adaptation',
        'Adapt pressure, heat, products, positioning and timing conservatively for a guest affected by cancer treatment',
        'Apply the "what, adapted how" question within venue protocol and medical guidance, defaulting to conservative choices or referral when unsure',
      ],
      sections: [
        {
          heading: 'From refusal to adaptation: the professional question',
          body: `The unskilled responses to a cancer disclosure are refusal and business-as-usual, and both are failures. The professional question is: what treatment, adapted how, is right and safe for this guest today? Answering it starts with three sources that outrank your own judgement: the venue's protocol, which defines what may be offered and with what checks; the guest's medical guidance, which many venues require confirmation of before treating guests in active treatment; and your insurance position, including whether accredited oncology certification is required for this booking at all. Within that frame, the consultation supplies the specifics: where treatment has been given, what has been removed or irradiated, what devices are in place, how energy, skin and sensation are today, and what the guest actually wants from the hour. Often the honest answer is a gentler, shorter, beautifully delivered version of something familiar rather than anything exotic. And the default, whenever any element is uncertain, never changes: adapt conservatively, or refer. A guest is never worse off for a treatment that was slightly gentler than strictly necessary; the reverse is not true.`,
        },
        {
          heading: 'Pressure, and the map of the body',
          body: `Pressure is the first dial to turn down. Skin affected by treatment can be thin, dry and fragile; low platelets can make bruising easy; deep tissue work has no place on this booking. Gentle, slow, rhythmic work, with the flat of the hand rather than digging thumbs, delivers profound relaxation without risk, and for many guests the lightness itself is the luxury. Then apply the map. Radiotherapy sites are avoided while skin is healing, and approached gently, if at all, afterwards. Recent surgical sites and unhealed scars are avoided entirely. The area around any port, PICC line or other device is never worked over, and the couch position should keep pressure off it. A limb at risk of lymphoedema, after lymph node removal or radiotherapy to the nodes, receives only the lightest touch or is omitted altogether, according to your protocol: this is a lifelong precaution, not one that expires when treatment ends. Where peripheral neuropathy has dulled sensation in hands or feet, the guest cannot reliably tell you what is too firm or too hot, so your conservatism must replace their feedback.`,
        },
        {
          heading: 'Heat, products and the treatment environment',
          body: `Heat deserves its own discipline. Saunas, steam rooms, hot tubs, hot stones and strongly heated couches can all be unsuitable for a guest in or recently out of active treatment: sensation may be altered, skin tolerance reduced, and the body's response to heat changed by medication. These are decisions for venue policy and the guest's medical advice, not for therapist instinct in the moment, so know your spa's rules on thermal facilities for these guests before you are asked. A comfortably warm room and a warmed blanket are almost always welcome; concentrated heat sources are the caution. Products follow the same conservative logic. Choose the gentlest, lowest-fragrance options in your range: chemotherapy can heighten smell sensitivity and trigger nausea, and treated skin reacts more readily, so this is not the booking for strong actives, vigorous exfoliation or a new, untested product. Patch testing, wherever the brand or treatment calls for it, matters more than ever. Complete the environment with softness everywhere: low light for tired eyes, extra cushioning for tender joints and scar sites, and blankets offered rather than assumed.`,
        },
        {
          heading: 'Timing, positioning and the shape of the hour',
          body: `The final adaptations concern the shape of the treatment itself. Fatigue after cancer treatment is not ordinary tiredness; it can be sudden and absolute, so a shorter treatment, offered without any sense of short-changing, is often the kinder design: forty-five gentle minutes that end with the guest rested beat sixty that end with them drained. Build in unhurried transitions, help on and off the couch offered gracefully, and no rush at the end of the hour. Positioning is comfort engineering: some guests cannot lie flat comfortably, some cannot lie face down after surgery, and side-lying with cushion support, or working through a semi-reclined position, keeps the treatment possible. Ask, adjust, and check in a little more often than usual, briefly and calmly, without hovering. Scalp work is adapted for hair loss or new growth: many guests love a gentle scalp hold, and some wear a wig or scarf they do not wish to remove, which is simply respected without comment. Finally, record every adaptation you made on the guest's notes: the next therapist should begin where your care left off, not from a blank page.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'The adapt-or-refer decision', steps: ['Consultation reveals a treatment history, a device or an at-risk area', 'Check the venue protocol: what may be offered, by whom, with what confirmation', 'Inside protocol and your training? Adapt conservatively: pressure, heat, products, positioning, timing', 'Any element still uncertain? Choose the gentler option - or refer', `Record every adaptation on the guest's notes`], caption: 'The sequence never changes, whatever the treatment: protocol first, conservative adaptation second, referral whenever doubt remains.' },
      ],
      scenario: `A regular guest arrives for her usual firm full-body massage and mentions, while settling in, that she now has a port fitted and had surgery a few months ago, adding that she would still like proper pressure because light massage never feels worth the money to her. You can feel the pull to please a loyal guest. The lesson's answer is unchanged by her preference: the device area is never worked over, recent surgical sites are avoided, and deep pressure has no place on this booking. Your task is to explain the adapted plan so warmly that gentleness reads as expertise, and to check the protocol on anything you are not certain of before you begin. If any element still feels unclear, you refer rather than guess.`,
      activity: `Take your spa's treatment menu and mark every element that involves concentrated heat, deep pressure or strong products. Then check your venue's written protocol for how each is handled for guests affected by cancer treatment, and note anything the protocol does not answer so you can ask your senior therapist before the situation is live.`,
      knowledgeCheck: [
        { q: `A guest at risk of lymphoedema after lymph node removal asks for firm massage on the affected arm 'to help it drain'. You should...`, options: ['Agree, since firm work will help the drainage', 'Use moderate pressure as a compromise', 'Follow your protocol: the at-risk limb receives only the lightest touch or is left out entirely, explained warmly', 'Ask her to confirm the request in writing first'], answer: 2, why: `The lymphoedema risk can be lifelong, and how the limb is treated is a matter for your venue's protocol, not negotiation or instinct. Explaining the adaptation warmly keeps the guest cared for while keeping her safe.` },
        { q: 'A guest in active treatment asks to use the sauna before her massage. The professional response is to...', options: [`Follow your venue's policy on thermal facilities for these guests and, where it requires it, the guest's medical advice - not your own instinct in the moment`, 'Allow it if she promises to keep the visit short', 'Allow it, because the sauna is part of the spa day she paid for', 'Refuse, and cancel the massage as well to be safe'], answer: 0, why: 'Heat for guests in or recently out of active treatment is a decision for venue policy and medical guidance, because sensation and tolerance may be altered. Neither therapist instinct nor guest enthusiasm replaces that.' },
        { q: 'You have adapted a treatment for a guest recently out of treatment. Afterwards you should...', options: ['Keep the details to yourself for confidentiality', `Record every adaptation on the guest's notes so the next therapist begins where your care left off`, 'Mention her situation at handover so everyone on the team knows', 'Record anything only if something went wrong'], answer: 1, why: `Complete notes are continuity of care and professional protection at once. Confidentiality means sharing only what the treatment and records require - and the record itself is exactly that.` },
      ],
      keyTerms: [
        { term: 'Contraindication', definition: `A condition or circumstance that rules a treatment or element of a treatment out, or requires it to be modified; in cancer-aware practice, most are localised (a site, a limb, a device) rather than a blanket ban on the guest.` },
        { term: 'Conservative adaptation', definition: `The discipline of choosing the gentler option wherever there is doubt: less pressure, less heat, milder products, shorter time. The default response of a professional working at awareness level.` },
        { term: 'Thermal caution', definition: `The principle that concentrated heat, from saunas and steam to hot stones and heated equipment, is a protocol-and-medical-guidance decision for guests in or recently out of treatment, because sensation and tolerance may be altered.` },
        { term: 'At-risk limb', definition: `A limb near removed or irradiated lymph nodes, carrying a lifelong risk of lymphoedema; it receives only the lightest touch or is omitted, according to venue protocol.` },
      ],
      caseStudy: {
        title: 'The hot stones rebooking at The Fairholme, Edinburgh',
        scenario: `Marek works at The Fairholme, a five-star hotel spa in Edinburgh. A regular guest, Ms Docherty, has rebooked her favourite hot stone massage, and mentions at consultation that since her last visit she has had surgery for breast cancer, with lymph nodes removed on the right side, and is partway through radiotherapy. She loves the stones and is visibly hoping nothing needs to change. Marek knows the venue protocol asks for medical guidance for guests in active treatment, that concentrated heat is now a caution, that her right arm is an at-risk limb, and that the radiotherapy site must be avoided entirely.`,
        insight: `Marek neither refuses nor pretends. He explains warmly that today he will swap the stones for his hands, keep her right arm and the treated area out of the work, and check the spa's protocol on medical confirmation before going further, then delivers a slow, gentle massage with a warmed blanket in place of the heat she loves. He records every adaptation on her notes. Ms Docherty leaves relaxed and, more importantly, safe. The insight: adaptation done gracefully feels like personalisation, not loss, and protocol followed calmly protects the guest, the therapist and the spa at once.`,
      },
      summary: `Cancer-aware adaptation replaces the crude question "can they have a treatment?" with the professional one: what treatment, adapted how, today, within venue protocol, medical guidance and insurance cover. Pressure comes down for fragile skin and easy bruising; the body's map is respected, with radiotherapy sites, surgical scars, devices and at-risk limbs avoided or treated ultra-lightly; concentrated heat becomes a protocol decision; products turn gentle and low-fragrance; and the hour itself is reshaped around fatigue, positioning and unhurried pacing. Every adaptation is recorded, and wherever doubt remains, the default holds: adapt conservatively, or refer.`,
      nextStep: `This week, read how your venue's protocol handles thermal facilities for guests in and recently out of treatment, so the answer is ready before a guest asks.`,
    },
    {
      title: 'Communication, consultation and emotional care',
      whyThisMatters: `The consultation can be the most exposed moment of a guest's visit, and how you receive a disclosure decides whether it was safe to make. Guests remember the therapist who was calm, warm and unremarkable about it at the hardest time of their lives, and they ask for her by name.`,
      objectives: [
        'Conduct a private, calm consultation after a cancer disclosure, using practical, present-tense questions',
        `Follow the guest's lead on conversation, protecting dignity and confidentiality throughout the visit`,
        'Avoid both fear-mongering and false reassurance, and respond to emotion with professional presence rather than advice',
      ],
      sections: [
        {
          heading: 'The consultation: calm, private, practical',
          body: `A guest disclosing cancer at a spa consultation is often braced for one of two reactions: alarm, or rejection. Your first professional gift is to show neither. Receive the disclosure as you would any other medical information: a steady expression, a genuine "thank you for telling me", and no drama. Ensure privacy absolutely; this conversation never happens across a reception desk or within earshot of another guest. Then move to practical, present-tense questions, because they are both safer and kinder than history-taking: how are you feeling today? Which areas would you like me to avoid? Is there anywhere tender, or any position that is uncomfortable? What would make this hour really comfortable for you? Notice what those questions do: they hand control to the guest, they gather exactly the information your adaptations need, and they quietly signal competence. Avoid interrogating the diagnosis itself; you need effects, not oncology. Close the consultation by saying back what you will do and what you have adapted, and add the sentence that matters most: you can change your mind about anything, at any point, and nothing needs explaining.`,
        },
        {
          heading: `Following the guest's lead`,
          body: `There is no single right conversational register for these treatments, because guests come for different things. Some want to talk about their illness, and will tell you so by doing it; your job then is easy listening without prying. Many others are in the spa for precisely the opposite reason: to spend one hour being a person and not a patient, in the only room in their week where nobody mentions hospitals. Misjudging this, and forcing solicitous conversation on a guest who wanted ordinary warmth, undoes the very normality they came to buy. So follow their lead exactly: match the topics they open, let silence be comfortable, and never introduce their illness into small talk once the consultation has done its work. The same discipline governs the body: never comment on scars, hair loss, a wig, a headscarf or a device unless the guest raises them, and handle whatever you see with the unremarkable ease of a professional to whom bodies are simply bodies. Dignity in draping and positioning deserves extra care around surgical sites. The finest compliment these guests pay afterwards is usually some version of: she treated me completely normally.`,
        },
        {
          heading: 'The two traps: fear and false comfort',
          body: `Two opposite failures wait on either side of good practice, and both come from kind intentions. The first is fear-mongering: visible anxiety, excessive checking, gasping at the consultation form, treating the guest as if they might break. It converts your treatment room into one more clinical space and tells the guest they are a problem to be managed. Calm competence is the antidote: adapt thoroughly, mention adaptations once, lightly, and then deliver a beautiful treatment. The second trap is false reassurance. Sentences like "I am sure you will be fine", "you will beat this" or "my aunt had that and she was okay" are not yours to say: you do not know, the guest knows you do not know, and for someone whose outlook is uncertain such words can land with real pain. Equally, never offer opinions on their medical treatment, diet or alternative therapies; that is diagnosis's talkative cousin and just as far outside your scope. The professional middle path is warm, steady honesty about what is yours: I will adapt this to keep you comfortable and safe. I am so glad you came in. This hour is yours.`,
        },
        {
          heading: 'When emotion arrives, and where your role ends',
          body: `Spa treatments unlock emotion at the best of times; for a guest carrying a diagnosis, an hour of kind touch can open doors they have been holding shut for months. If tears come, on the couch or in the consultation, your response is presence, not rescue. Pause the work gently, offer a tissue, and let them lead: some will want a moment and then to continue, some will want to talk briefly, a few may want to stop, and all three are fine. You do not need wise words, and you should not attempt counselling; stillness, kindness and unhurried acceptance are the professional skill, and they are enough. Afterwards, allow a soft landing: no bright lights, no brisk turnaround, time to gather themselves before reception. Confidentiality then seals the whole encounter: the guest's condition is shared with colleagues only to the extent the treatment and records require, never as conversation, and their notes are handled with the same discretion as any medical information. Finally, mind yourself: these treatments can move the therapist too. A quiet word with your manager or a trusted senior afterwards is professionalism, not weakness.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'The consultation conversation arc', steps: ['A private setting and a calm welcome', 'The disclosure is received with a steady thank you and no drama', 'Present-tense questions: how are you feeling today, which areas shall I avoid, what would make this hour comfortable?', 'The plan and its adaptations are said back to the guest', 'The closing promise: you can change your mind about anything, at any point'], caption: 'One arc, rehearsable in advance, that hands control to the guest and gathers exactly what your adaptations need.' },
      ],
      scenario: `Your guest disclosed her diagnosis briefly at consultation and made it clear she would rather not discuss it further, so you followed her lead into easy, ordinary conversation. Midway through the treatment she becomes quietly tearful and apologises for it. Nothing in this moment calls for advice or reassurance about her illness, and both would be outside your scope. What the lesson asks of you is stillness, a tissue, and her choice of whether to pause, talk or continue. Afterwards, nothing is shared with colleagues beyond her treatment notes.`,
      activity: `Practise the consultation aloud, ideally with a colleague playing the guest. Say the whole arc: the thank you, the present-tense questions, the adapted plan said back, and the promise that she can change her mind at any point. Rehearse until the words feel like yours, because a disclosure is the wrong moment to be searching for them.`,
      knowledgeCheck: [
        { q: 'A guest discloses her diagnosis at consultation and then chats happily about her garden for the rest of the hour. You should...', options: ['Gently return the conversation to her health so she feels heard', 'Ask how her treatment is going, to show you care', 'Stay silent for the rest of the treatment out of respect', 'Follow her lead completely - many guests come to the spa precisely to spend an hour not being a patient'], answer: 3, why: 'The guest sets the conversational register. Forcing solicitous talk on a guest who wanted ordinary warmth undoes the very normality she came for.' },
        { q: `A tearful guest asks: 'tell me honestly, do you think I will be all right?' The professional response is...`, options: [`'I am sure you will be fine - you seem so strong'`, 'Warm honesty about what is yours to give: you will keep her comfortable and safe today, and this hour is hers - the outlook is never yours to predict', 'To share the story of another guest who recovered well', 'To change the subject as quickly as possible'], answer: 1, why: 'False reassurance is not yours to give and can land painfully. The professional middle path is warm, steady honesty about what you can actually promise: comfort, safety and care today.' },
        { q: `What may be shared with colleagues about a guest's disclosure?`, options: ['Anything, as long as it stays within the team', 'Nothing at all, including treatment notes', 'Only what the treatment and her records require - never as conversation', 'A brief summary at the next team meeting'], answer: 2, why: 'Confidentiality is absolute: the disclosure lives on the secure record for professional use, and travels nowhere else - not the staff room, not the handover chat.' },
      ],
      keyTerms: [
        { term: 'Present-tense consultation', definition: `A consultation style that asks how the guest is affected today - comfort, tender areas, positions, preferences - rather than interrogating diagnosis or history; it gathers what adaptation needs while handing control to the guest.` },
        { term: 'False reassurance', definition: `Comforting predictions the therapist cannot make, such as "you will be fine"; outside professional scope and capable of landing painfully on a guest whose outlook is uncertain.` },
        { term: 'Following the lead', definition: `Letting the guest set the conversational register: engaging with their illness only if they raise it, and otherwise giving them the ordinary, warm normality most came for.` },
        { term: 'Professional presence', definition: `The skill of meeting a guest's emotion with calm stillness, kindness and acceptance rather than advice or counselling; paired with confidentiality, it defines emotional care within a therapist's scope.` },
      ],
      caseStudy: {
        title: 'The tears at Thornleigh Place, Mayfair',
        scenario: `Sofia is a therapist at Thornleigh Place, a luxury hotel spa in Mayfair. Her guest, Mr Okafor, disclosed at consultation that he is between treatment cycles, said briskly that he would rather not discuss it further, and chose a gentle back, neck and shoulder massage. Sofia adapted quietly and followed his lead into easy, ordinary conversation about nothing in particular. Twenty minutes in, during slow work across his shoulders, Mr Okafor begins to cry, silently at first, then openly, and apologises through the towels for "making a scene".`,
        insight: `Sofia stills her hands, keeps one resting calmly on his shoulder, and says only: there is nothing to apologise for, take all the time you need. She offers a tissue, waits without a single question, and when he says he would like to carry on, she resumes more slowly, saying nothing further about it. Afterwards she gives him an unhurried landing and a warm, completely normal goodbye, and shares nothing with colleagues beyond his treatment notes. The lesson: emotional care in a spa is presence, dignity and discretion. Sofia never needed the right words, because staying kindly was the skill.`,
      },
      summary: `Communication is where cancer-aware care is truly delivered. The consultation is private, calm and present-tense: thank the guest, ask how they are affected today, hand them control and confirm they can change their mind at any point. Thereafter, follow their lead entirely: many guests want an hour of not being a patient, and normality is the luxury. Avoid the twin traps of fear-mongering and false reassurance, offering warm honesty about what is yours to promise. Meet tears with presence rather than advice, protect confidentiality absolutely, and let dignity govern every word, drape and silence.`,
      nextStep: 'The next time any guest shares something sensitive, practise the steady thank you and one present-tense question - the habit transfers directly to these consultations.',
    },
    {
      title: 'Scope of practice, consent, referral and accredited training',
      whyThisMatters: `Scope is what makes every other skill in this course safe to use, and it is the boundary insurers, venues and guests all rely on. A therapist who knows exactly what she can offer, and says so gracefully, is trusted with the most delicate bookings and with the training investment that follows.`,
      objectives: [
        'Define the boundary of awareness-level practice and explain where accredited oncology touch certification is required',
        'Apply informed consent, venue protocol, medical guidance and documentation on every sensitive booking',
        `Refer gracefully - to seniors, protocols, accredited colleagues or the guest's medical team - and respond correctly to anything unusual noticed during treatment`,
      ],
      sections: [
        {
          heading: 'Scope: the line that protects everyone',
          body: `Scope of practice is the honest answer to the question: what am I trained, authorised and insured to do? For this course, the answer is precise. Awareness-level training equips you to understand cancer's effects, hold a sensitive consultation, adapt conservatively within venue protocol, and refer well. It does not, on its own, authorise you to treat guests in active cancer treatment. That work belongs to accredited oncology touch programmes, of which Made for Life and Jennifer Young-style training are well-known examples in UK spa, and many insurers require such certification before a therapist takes those bookings at all. Three authorities therefore frame every sensitive booking, and you must know all three before the guest arrives: your venue's protocol, which defines what may be offered and by whom; the guest's medical guidance, which many venues require confirmation of; and your insurance position, both the spa's and, for freelance and agency therapists, your own. Working beyond any of the three is not bravery; it is the single fastest way a well-meaning therapist puts a vulnerable guest, a career and a business at risk simultaneously.`,
        },
        {
          heading: 'Consent, protocol and the paper trail',
          body: `Informed consent for these bookings must be specific, not ceremonial. The guest should understand what you will do, what you have adapted and why, what you will avoid, and that they may pause or stop at any time without explanation; that final clause, said aloud, changes how safe the whole hour feels. Consent is a conversation first and a signature second. Around it sits the venue's protocol, and the professional obligation is to know it before you need it: what your spa offers guests in active treatment, whether medical confirmation is required and in what form, which therapists hold accredited certification, and how sensitive bookings are flagged to the team discreetly. If you work agency shifts, ask for the protocol on arrival, exactly as you would ask where the fire exits are. Then document. Record the disclosure in appropriate professional language, the questions asked, the guidance confirmed, every adaptation made, anything declined, and how the guest responded. Store it with the confidentiality any medical information commands. Complete notes are continuity of care for the guest's next visit, and they are also your professional protection: the difference between "I adapted correctly and can show it" and an unsupported memory.`,
        },
        {
          heading: 'Never diagnose, and the art of the graceful referral',
          body: `Therapists see and touch more skin than almost any other profession, and sooner or later you will notice something a guest may not have: an unusual mole, a lump, a patch of changed skin. The rule is absolute and liberating: never diagnose, never alarm, never reassure. You are not qualified to know what it is, and both "I am sure it is nothing" and a worried face are diagnoses in disguise. The professional script is one calm sentence: I noticed a small area here that I was not sure about, and it may be worth showing your doctor next time you see them. Then let it go; noticing and mentioning is the whole of your role. Referral more broadly is a skill to deliver with grace rather than apology. Upwards, to your senior therapist or manager, whenever a booking sits outside your certainty. Sideways, to an accredited colleague, when the venue holds oncology-trained staff and the booking calls for them. Outwards, to the guest's medical team, when protocol requires confirmation before treatment. Phrased well, referral is service: let me make sure you get the best and safest version of this, is a sentence that builds trust rather than spending it.`,
        },
        {
          heading: 'The path onwards: accredited training and the therapist you become',
          body: `For many therapists, this course is the beginning of something rather than the whole of it. If this work calls to you, the path onwards is accredited oncology touch certification: structured programmes, such as Made for Life or Jennifer Young-style training, that teach adapted treatment for guests in active treatment in the depth that awareness training cannot, and that satisfy the certification requirements many insurers set. Venues notice therapists who hold it; a spa that can safely and warmly welcome guests living with cancer serves its community better and is a better business, and the therapists who make that possible are valued accordingly. Speak to your manager about what your venue holds and what it would support. Until and unless you certify, hold the awareness-level frame with quiet confidence: understand deeply, consult kindly, adapt conservatively, document properly, refer gracefully, and never diagnose. There is nothing apologetic about that list. A guest at a fragile moment of their life, met by a therapist who knows exactly what she can do and exactly where her scope ends, is a guest in the safest possible hands, and that, precisely, is the point of this course.`,
        },
      ],
      visuals: [
        { kind: 'flow', title: 'When you are unsure: the referral ladder', steps: ['A booking or question sits outside your certainty', 'Check the venue protocol first - it may already hold the answer', 'Still unsure? Ask your senior therapist or manager', 'The booking needs accredited certification? Route it to a certified colleague, per protocol', 'Medical confirmation required? Follow the venue process before any treatment', 'Offer what you safely can, warmly - and record everything'], caption: 'Referral is a ladder, not a leap: each rung is a smaller, safer question than guessing.' },
      ],
      scenario: `You are on an agency shift at an unfamiliar spa when reception passes you a booking for a guest who is midway through chemotherapy and hoping for a massage before a family event. You hold awareness-level training only, and you have not yet seen this venue's protocol. The professional sequence is exactly what this lesson teaches: ask for the protocol, tell the coordinator honestly what you are and are not certified for, and let the venue route the booking to a certified colleague if it holds one, with medical confirmation arranged as the protocol requires. Your part may end with offering a gentler alternative within your own scope, and offering it warmly is service, not failure.`,
      activity: `Write down, in two lists, what you are certain your training and insurance cover for guests affected by cancer, and what you are not certain of. Take the second list to your manager or insurer this week and turn every uncertainty into a written answer before a sensitive booking tests it.`,
      knowledgeCheck: [
        { q: `You notice an unusual mole on a guest's shoulder during a massage. You say...`, options: ['One calm sentence: you noticed a small area you were not sure about, and it may be worth showing her doctor - then you let it go', 'Nothing, because it is not your place to have seen it', `'I am sure it is nothing, but keep an eye on it'`, 'That it looks concerning and she should see a specialist urgently'], answer: 0, why: `Noticing and mentioning, once and calmly, is the whole of your role. Both reassurance and alarm are diagnoses in disguise, and neither is yours to give.` },
        { q: 'Before a therapist treats guests in active cancer treatment, many insurers require...', options: ['A signed waiver from the guest', 'Approval from the spa reception team', 'Accredited oncology touch certification - awareness-level training is not a substitute', 'Nothing, provided the therapist feels confident'], answer: 2, why: 'Accredited oncology touch programmes exist precisely for this work, and many insurers mandate them. Knowing what your venue and your own insurance hold is part of professional scope.' },
        { q: 'A sensitive booking sits outside your certainty and the protocol does not fully answer it. You should...', options: ['Proceed carefully and watch how the guest responds', 'Ask the guest what she thinks would be safe', 'Take the booking but shorten the treatment', `Adapt conservatively or refer - to your senior, the protocol's owner or the guest's medical team - and never guess`], answer: 3, why: 'When the answer is genuinely unclear, the default never changes: adapt conservatively or refer. A guest is never worse off for a gentler treatment or a well-made referral; the reverse is not true.' },
      ],
      keyTerms: [
        { term: 'Scope of practice', definition: `The boundary of what a professional is trained, authorised and insured to do; for this course, awareness-level understanding, conservative adaptation and referral, not the treatment of guests in active treatment.` },
        { term: 'Accredited oncology touch training', definition: `Structured, certificated programmes, such as Made for Life or Jennifer Young-style training, that qualify therapists to treat guests in active cancer treatment; many insurers require them before such bookings are taken.` },
        { term: 'Informed consent', definition: `The guest's specific agreement, given with understanding of what will be done, what has been adapted and why, and the standing right to pause or stop at any time without explanation.` },
        { term: 'Graceful referral', definition: `Passing a booking, question or observation to the right authority - senior, accredited colleague, protocol or medical team - phrased as service rather than apology, and completing the awareness-level therapist's role.` },
      ],
      caseStudy: {
        title: 'The mid-chemo enquiry at Alderbrook Hall, Cheshire',
        scenario: `Grace is an agency therapist on her first shift at Alderbrook Hall, a five-star spa hotel in Cheshire. Reception passes her a booking note: the afternoon guest, Mrs Whitfield, has told the team she is midway through chemotherapy and is desperate for a facial before a family wedding. Grace holds awareness-level training but no accredited oncology certification. On arrival she had asked for the venue's protocols, so she knows Alderbrook Hall requires accredited certification for guests in active treatment, holds one certified senior therapist on the team, and asks for confirmation of medical guidance beforehand.`,
        insight: `Grace neither takes the booking beyond her scope nor lets the guest feel refused. She speaks to the spa manager, and the certified senior therapist takes Mrs Whitfield's facial, with medical confirmation arranged per protocol; Grace offers a gentle hand and arm ritual within her own scope so the guest's afternoon is still generous. Everything is documented. Mrs Whitfield gets a safe, beautiful experience for the wedding; Grace is rebooked by the venue, precisely because she knew her edge and handled it gracefully. Scope, held with confidence, is what five-star safety actually looks like.`,
      },
      summary: `Scope is the frame that makes every other lesson safe to use. Awareness-level training means understanding, conservative adaptation and referral; treating guests in active treatment requires accredited oncology touch certification, such as Made for Life or Jennifer Young-style programmes, which many insurers mandate. Every sensitive booking runs on three authorities - venue protocol, the guest's medical guidance and insurance cover - wrapped in specific informed consent and complete, confidential documentation. Never diagnose anything you notice; suggest the guest's doctor, once, calmly. Refer gracefully, consider the accredited path onwards, and hold your boundary with confidence: that is what protects the guest.`,
      nextStep: 'Ask your manager this week which accredited oncology touch programmes your venue and its insurer recognise, and what the path to certification would look like for you.',
    },
  ],
}
