import type { CourseContent } from '../academy-types'

// Split out of the pack beside it so a course title can be imported
// without dragging every lesson of every course along with it.

export const content: CourseContent = {
  slug: 'dermalogica-masterclass',
  aims: `This masterclass gives working spa therapists genuine professional depth in Dermalogica, one of the most influential professional skincare houses in the world. It covers the founding story and the skin health philosophy that shape every treatment, the hero products and ingredient stories a therapist must know cold, and the practical craft of the Dermalogica shift: reading the treatment menu, delivering the diagnostic, education-led signature style built on Face Mapping, retailing the range by prescribing from findings, building honest upsell paths, and upholding the standards that protect the brand's name. Where house-specific details vary by spa, the course teaches the professional method for learning them fast and accurately on day one. This is independent Talent House training and is not affiliated with or endorsed by Dermalogica.`,
  audience: `Spa and wellness therapists working in, or preparing to work in, Dermalogica venues across UK luxury hotels, destination spas, premium day spas and skin clinics. It suits therapists interviewing for a Dermalogica account who want to arrive fluent, agency and freelance therapists who may be asked to deliver the house style at short notice, experienced therapists moving to Dermalogica from a more ritual-led house, and spa managers or head therapists who coach brand standards. Reception and retail colleagues in Dermalogica venues will also gain a working command of the range and its language.`,
  outcomes: [
    `Tell Dermalogica's founding story and articulate its skin health philosophy and USP in confident, guest-ready language`,
    'Name the hero products and ranges and explain their ingredient stories accurately and honestly',
    `Deliver the diagnostic, education-led Dermalogica style, from Face Mapping analysis to the written prescription, at five-star standard`,
    'Retail the range by linking analysis findings to a two or three item home prescription',
    `Build integrity-led upgrade paths between treatment formats and uphold the house's standards on every shift`,
  ],
  lessons: [
    {
      title: 'The house: history, philosophy and USP',
      objectives: [
        `Recount Dermalogica's founding story and explain why its education-first heritage sets it apart from beauty-born brands`,
        `Explain the skin health philosophy and the house's original stance on leaving out common irritants`,
        `Articulate Dermalogica's USP to a guest in one confident, accurate sentence, using the house's own tone of voice`,
      ],
      sections: [
        {
          heading: 'A house born from a classroom',
          body: `Dermalogica's story begins with education, and a therapist who understands that understands the whole brand. Jane Wurwand trained as a skin therapist in Britain before moving to the United States, where she found that the professional training available to working therapists was thin and product-led. Her answer, in 1983, was The International Dermal Institute in Los Angeles: a postgraduate education centre teaching real skin science to qualified therapists. Dermalogica followed in 1986, created because the curriculum needed a product line that lived up to it, a professional range developed by skin therapists, for skin therapists. That sequence, school first and products second, is the deepest fact about the house. Most skincare brands begin with a product and later add training to support sales; Dermalogica began with training and built products to serve it. Its professional education has become one of the most recognised in the industry, and a therapist who has trained with the house carries that recognition on their CV for the rest of their career.`,
        },
        {
          heading: 'Skin health, not beauty',
          body: `The phrase that defines Dermalogica is skin health, not beauty, and it does real work in the treatment room. The house has never sold glamour, pampering or miracle promises. It treats the skin as an organ to be understood, analysed and improved, and it treats the therapist as a professional expert whose knowledge is the service. This positioning shaped the products themselves. The original formulations were famous for what they left out: common irritants such as lanolin, mineral oil, SD alcohol and artificial colours and fragrances were excluded, because the goal was skin function, not sensory indulgence. It also shaped the aesthetic. Dermalogica's presentation is deliberately clinical and unfussy, closer to a prescription than a perfume counter, and its treatments put analysis and education ahead of theatre. None of this means coldness. The house is known for championing professional human touch, and a great Dermalogica treatment is deeply relaxing. But the relaxation is earned through expertise, and the guest should always feel they are in the hands of someone who genuinely understands skin.`,
        },
        {
          heading: 'The USP in one breath',
          body: `Every therapist on a Dermalogica account should be able to state the house USP in a single sentence, because guests ask, interviewers ask, and hesitation reads as ignorance. A reliable version: Dermalogica is professional-grade skincare born from therapist education, delivering personalised skin health through expert analysis rather than beauty promises. Each clause earns its place. Professional-grade, because the range was developed for treatment rooms and the professional channel, not invented for a department store shelf. Born from therapist education, because The International Dermal Institute came first and remains the brand's foundation. Personalised skin health, because the philosophy rejects one-size beauty in favour of analysing this guest's skin today. Through expert analysis, because Face Mapping and the spoken diagnosis are the signature of the house. When a guest compares Dermalogica with a glamorous counter brand, you have an honest, specific answer that elevates the house without disparaging anyone else: they are buying expertise, and the products are the tools of that expertise, which is exactly how the brand would want it said.`,
        },
        {
          heading: 'Speaking Dermalogica: the house voice',
          body: `A product house is also a vocabulary, and the Dermalogica voice is unmistakable: expert, direct, educational and plain-spoken. Its natural words are skin health, analysis, barrier, sensitised, prescription, education. It explains rather than enchants, and it respects the guest's intelligence: a Dermalogica therapist says your skin is dehydrated rather than dry, and here is the difference, where a ritual-led house might speak of comfort and cocooning. Neither voice is superior, but each belongs to its own brand, and a therapist who drifts into vague pampering language in a Dermalogica room sounds like a visitor rather than a resident. Practise translating your knowledge into the house voice: short, confident, evidence-flavoured sentences that teach something. This matters most on agency shifts and interviews, where fluency in the voice is read as fluency in the brand. It also matters for retail, because the Dermalogica guest buys understanding: the therapist who explains why a product suits their skin will outsell the one who merely praises it, every single time.`,
        },
      ],
      keyTerms: [
        { term: 'The International Dermal Institute', definition: `The postgraduate education centre founded by Jane Wurwand in Los Angeles in 1983; Dermalogica was created in 1986 as the product line its curriculum demanded.` },
        { term: 'Skin health', definition: `Dermalogica's defining philosophy: the skin treated as an organ to be analysed, understood and improved by a professional expert, in deliberate contrast to beauty and pampering positioning.` },
        { term: 'Common irritants', definition: `Ingredients the original Dermalogica formulations were famous for excluding, such as lanolin, mineral oil, SD alcohol and artificial colours and fragrances.` },
        { term: 'USP', definition: `Unique selling point: the specific, honest claim that distinguishes a house from its competitors, which every therapist should be able to state in one sentence.` },
      ],
      caseStudy: {
        title: 'The interview at Harewood Manor, the Cotswolds',
        scenario: `Priya is interviewing for a senior therapist role at Harewood Manor, a five-star country house hotel in the Cotswolds whose spa runs a Dermalogica menu alongside its body treatments. The spa director opens with a deceptively simple question: our guests can buy premium skincare anywhere in Cheltenham, so tell me what you would say when a guest asks why we chose Dermalogica. Priya has worked mostly with ritual-led aromatherapy houses, and she feels the pull to answer with the language she knows, talking about indulgence, sensorial escape and luxurious textures, which she senses even as she begins would be the wrong accent for this brand.`,
        insight: `Priya catches herself and answers in the Dermalogica voice instead: the house was founded by a skin therapist who built a training institute before she built a product, its philosophy is skin health rather than beauty, and what the guest is buying at Harewood Manor is expert analysis, a personalised prescription and products developed for professional hands. The director visibly relaxes; she has heard the house described in its own terms. The lesson: brand fluency is voice as much as fact. Knowing the story matters, but telling it in the house's accent is what convinces.`,
      },
      summary: `Dermalogica began with education: Jane Wurwand, a British-trained skin therapist, founded The International Dermal Institute in Los Angeles in 1983 and created Dermalogica in 1986 as the professional range its teaching demanded. The philosophy is skin health, not beauty, expressed in formulations famous for excluding common irritants such as lanolin, mineral oil, SD alcohol and artificial colours and fragrances. The USP, professional skincare born from therapist education and delivered through expert analysis, should live on every therapist's tongue, spoken in the house's direct, educational voice.`,
    },
    {
      title: 'Product knowledge and hero ingredients',
      objectives: [
        `Identify Dermalogica's hero products and ranges and describe what each is famous for`,
        `Explain the house's ingredient approach, recognised actives with irritants excluded, in guest-ready language`,
        'Apply a reliable, honest method for learning any range quickly without inventing claims',
      ],
      sections: [
        {
          heading: 'Heroes first: the icons guests ask for',
          body: `In any house, a handful of products carry the brand's reputation, and mastering them first gives you most of your credibility for a fraction of the effort. For Dermalogica, begin with Daily Microfoliant, the iconic rice-based daily powder exfoliant that activates with water in the hands; it is one of the most recognised products in professional skincare, and guests who know only one Dermalogica product usually know this one. Next, Precleanse, the oil-based cleanser that opens the double cleanse: it dissolves sunscreen, make-up and surface oil so the second cleanser can treat clean skin rather than fight through the day. Special Cleansing Gel has been the everyday second cleanse for a generation of skins, and the UltraCalming range is the house's well-known answer for sensitised, reactive skin. Around these sit trusted moisturisers such as Skin Smoothing Cream, daily broad-spectrum SPF protection and targeted serums for brightness, hydration and ageing concerns. Learn the pillars until you can present each in one fluent sentence: what it is, what it is famous for, and who it suits.`,
        },
        {
          heading: 'The double cleanse and the professional routine',
          body: `Dermalogica did as much as any house to make the professional double cleanse a household idea, and a therapist should be able to teach it in under a minute. The logic is simple and honest. The first cleanse, with the oil-based Precleanse, works on the principle that like dissolves like: it melts away sebum, sunscreen and make-up that a water-based cleanser struggles to shift. The second cleanse, chosen for the guest's skin, then treats the skin itself rather than the residue of the day. From there the routine builds in a teachable order: exfoliation appropriate to the skin's tolerance, with Daily Microfoliant gentle enough for regular use, then targeted serums, then moisturiser, then daily SPF, which the house treats as non-negotiable skin health rather than an optional extra. Teaching this order is retail's best friend, because a guest who understands the sequence understands why each product exists. Ten seconds at the close, cleanse, treat, protect, turns a bag of products into a routine the guest will actually follow, and results at home are what bring them back.`,
        },
        {
          heading: 'Ingredient stories that sell themselves',
          body: `Dermalogica's formulation story has two halves, and both belong in your narration. The first half is what goes in: recognised actives chosen for function, such as hydroxy acids for exfoliation, rice-derived enzymes in the famous powder exfoliant, vitamin C for brightness, hyaluronic acid for hydration, and oat-derived soothers in the calming products for sensitised skin. The second half is what stays out: the house built its name on excluding common irritants, and that remains a powerful, honest thing to say to a guest with reactive skin. The professional skill is telling these stories simply during treatment, in the moment the guest is experiencing the product: one sentence covering what it contains, what it does, and how the skin will respond. Lead with function and benefit, because that is the house voice, and let the guest's own skin verify the claim in real time. Two disciplines keep it professional: never quote an ingredient, percentage or claim you have not verified from the brand's own materials, and never diagnose beyond your remit; describe what you observe and refer on when something needs a doctor.`,
        },
        {
          heading: 'How to learn a range properly',
          body: `No course can teach you every product on your particular spa's shelf, because ranges evolve and stock lists differ, so the meta-skill matters more than any list: the professional method for learning a house fast and honestly. First, heroes before everything; they answer most guest questions and anchor most retail. Second, one category at a time: cleansers as a family, then exfoliants, then moisturisers, then targeted serums, learning each category's logic rather than memorising isolated items. Third, use the testers and the training materials the spa holds; with an education-first house like Dermalogica the materials are unusually good, and the brand's own words are your safest source for claims. Fourth, use the key products on your own skin, because conviction cannot be faked and guests read certainty in seconds; your own skin is also your most persuasive retail display. Fifth, build the habit of the honest gap: when asked something you do not know, say what you do know, offer to check the rest, and then actually check it. A therapist who follows this method can be genuinely fluent in a new Dermalogica account within their first week.`,
        },
      ],
      keyTerms: [
        { term: 'Daily Microfoliant', definition: `Dermalogica's iconic rice-based daily powder exfoliant, activated with water in the hands; gentle enough for regular use and one of the most recognised products in professional skincare.` },
        { term: 'Double cleanse', definition: `The two-step cleansing method the house championed: an oil-based first cleanse with Precleanse to dissolve sunscreen, make-up and oil, then a second cleanser chosen to treat the skin itself.` },
        { term: 'UltraCalming', definition: `Dermalogica's well-known range for sensitised, reactive skin, built around soothing ingredients and the house's founding stance on excluding common irritants.` },
        { term: 'The honest gap', definition: `The professional habit of saying what you know, admitting what you do not, and checking before claiming; the opposite of inventing product details under pressure.` },
      ],
      caseStudy: {
        title: 'The knowledgeable guest at The Wexley, Edinburgh',
        scenario: `Callum is three weeks into a role at The Wexley, a luxury hotel spa in Edinburgh running a Dermalogica menu, having moved from a house he knew inside out. His guest, Dr Innes, is a dermatology registrar with a professional interest in ingredients, and she asks precise questions from the couch: what is actually in the powder exfoliant, why does he cleanse twice, and what would he recommend for her sensitised cheeks that will not flare them. Callum knows his heroes but feels the pressure to sound more expert than he is, and the temptation to guess at specifics he has not yet verified is strong.`,
        insight: `Callum stays inside what he knows. He explains the rice-based Microfoliant and the like-dissolves-like logic of the double cleanse in plain sentences, points her to the UltraCalming range as the house's answer for sensitised skin, and uses the honest gap on the one formulation detail he has not verified, checking the brand materials after the treatment and leaving the answer with reception. Dr Innes buys the Microfoliant and books a repeat. The lesson: with knowledgeable guests, accuracy beats fluency. A modest true sentence builds more trust than an impressive invented one, and the honest gap is a professional tool, not a weakness.`,
      },
      summary: `Dermalogica product mastery starts with the heroes: Daily Microfoliant, the rice-based powder exfoliant guests know by name, Precleanse and the double cleanse it opens, Special Cleansing Gel, and the UltraCalming family for sensitised skin. The ingredient story has two honest halves, recognised actives such as hydroxy acids, vitamin C and hyaluronic acid in, and common irritants out, told in single plain sentences while the guest experiences the product. Beyond any list, the lasting skill is the learning method: heroes first, one category at a time, the brand's own materials, personal use, and the honest gap instead of invention.`,
    },
    {
      title: 'Signature treatments, retail and upselling',
      objectives: [
        `Navigate a Dermalogica treatment menu on day one and deliver the house's diagnostic, education-led style with confidence`,
        'Retail the range by linking Face Mapping findings to a short, honest written prescription',
        `Build integrity-led upsell paths between treatment formats and uphold the brand's standards on every shift`,
      ],
      sections: [
        {
          heading: 'Reading the treatment menu like a professional',
          body: `Every Dermalogica venue's menu differs in detail, so the day one discipline is a reading method, not a memorised list. The organising idea to look for is personalisation: Dermalogica menus are typically led by customised professional skin treatments, commonly offered in shorter and longer formats, in which the therapist designs the facial around the analysis rather than delivering a fixed named protocol. Find those core treatments first and learn exactly how your venue runs them: duration, protocol source, the professional products used, and how the customisation decisions are made. Then map the outer layers: any advanced or resurfacing options the venue offers, targeted express treatments, and the add-ons that can extend a booking. For each, note who it is for and what it must never be sold to, because advanced work carries contraindications and patch test requirements that protect both guest and insurance. Read the protocols the spa holds, shadow a senior therapist where you can, and ask questions before your first guest rather than improvising in front of one. A therapist who can honestly say I know this menu by the end of day one is rare, and remembered.`,
        },
        {
          heading: 'Delivering the signature style: analysis first',
          body: `A Dermalogica treatment is recognisable before the first product is applied, because the house style opens with diagnosis. The signature is Face Mapping, Dermalogica's zone-by-zone analysis of the face, in which the therapist examines the skin systematically, area by area, and explains the findings aloud in plain language before deciding what the treatment will do. Honour this completely. Under time pressure the analysis is the first thing a rushed therapist trims, and it is the one thing the house would never sacrifice, because the analysis is the brand: it is what separates a Dermalogica treatment from a pleasant facial with good products. Narrate as you examine, teach as you treat, and record your findings as a written prescription the guest can take away. Through the treatment, the standard is expert calm: confident hands, decisions explained at natural moments without breaking relaxation, and the professional touch the house has always championed. The guest should leave with visibly treated skin and, just as importantly, understanding their skin better than when they arrived. Education is the experience; that is the founding idea of the entire house, delivered one guest at a time.`,
        },
        {
          heading: 'Retail: prescribing from findings',
          body: `Dermalogica retail is the easiest honest retail in the industry, because the house hands you the method: the prescription. Everything you recommend flows from the analysis the guest has just watched you perform, which means recommendation never feels like selling; it feels like the second half of the diagnosis. During the treatment, narrate the key products at natural moments, one sentence each, while the guest is experiencing them. At the close, prescribe rather than pitch: two or three products, each linked explicitly to a named finding, your cheeks are dehydrated rather than dry, so this is the one product I would send you home with. Teach the order of use in ten seconds, cleanse, treat, protect, so the products become a routine rather than a bagful of hope. Tell the guest what not to buy as well, which builds the trust that compounds over years and is entirely in the spirit of a house that leads with education. Write the prescription down, because written prescriptions convert far better than verbal mentions at a busy desk, and record it on the guest's history so the next therapist can continue the story.`,
        },
        {
          heading: 'Upselling with integrity, and protecting the brand on shift',
          body: `Upsell paths on a Dermalogica menu are natural because the menu is built on depth of personalisation. The guest in the shorter customised format whose analysis reveals real concerns genuinely benefits from the longer format next time; say so at the close, tie it to the specific finding, and note it on their record. The guest with a skin goal and a timeline, a wedding, an event, a stubborn concern, suits a course of treatments at the interval your venue recommends, with home care working between visits; explain it as the professional truth it is, because skin changes over cycles, not overnight. Advanced options are offered only where analysis supports them and requirements such as patch tests are met. The integrity rule is absolute: every upgrade must improve the guest's outcome, not merely the bill. Alongside selling the brand, you protect it: correct products in correct quantities, protocols followed rather than privately improvised, testers and retail immaculate, low stock reported before it forces substitutions, and the analysis never skipped to rescue a late-running column; flag the schedule instead. On a Dermalogica shift, you are the brand's expertise made visible, and your standard is its reputation in that room.`,
        },
      ],
      keyTerms: [
        { term: 'Face Mapping', definition: `Dermalogica's signature zone-by-zone analysis of the face, performed systematically before treatment, explained aloud to the guest and recorded as a written prescription.` },
        { term: 'Customised skin treatment', definition: `The personalised professional facial format that leads most Dermalogica menus, commonly offered in shorter and longer versions, designed around the analysis rather than a fixed named protocol.` },
        { term: 'Prescription', definition: `The written record of analysis findings and the two or three recommended products, linked to named findings; the honest engine of Dermalogica retail and the bridge to the guest's next visit.` },
        { term: 'Upgrade path', definition: `The natural route from one booking to a richer one built on genuine benefit, such as the shorter customised format to the longer, or a single treatment to a course with home care between.` },
      ],
      caseStudy: {
        title: 'The Saturday column at The Aldenham, Mayfair',
        scenario: `Georgia works Saturdays at The Aldenham, a five-star hotel spa in Mayfair with a fully booked Dermalogica column. A late start upstream has left her running twelve minutes behind when her 2pm guest, Mrs Okafor, arrives for the shorter customised treatment before a wedding in six weeks, mentioning congestion along her jaw and dullness she wants gone for the day itself. Georgia knows the fastest way to recover the schedule is to skip the zone-by-zone analysis and go straight to products; she also knows that six-week timeline is exactly the kind of goal the menu was built for, if she handles the close well.`,
        insight: `Georgia protects the analysis, trims elsewhere, and flags the schedule gap to the coordinator instead of quietly absorbing it. Her Face Mapping gives her the close: she names the congestion and dullness she found, prescribes three products in writing, and explains honestly that a six-week goal suits a short course of treatments with home care between, booking the next visit before Mrs Okafor leaves. The lesson: the analysis is never the corner to cut, because everything commercial, the prescription, the course, the rebooking, flows from it. Skipping the diagnosis to save time saves minutes and costs the brand.`,
      },
      summary: `Mastering a Dermalogica shift is a craft with four faces. Read the menu like a professional, understanding how your venue runs its customised skin treatments before anything else. Deliver the signature style faithfully: Face Mapping analysis first, findings explained aloud, education woven through expert touch. Retail by prescribing from findings, two or three products in writing, with honesty about what not to buy. And build genuine upgrade paths, shorter format to longer, single treatment to a course, while protecting the standards, because the analysis is the brand, and it is never the thing you trim.`,
    },
  ],
}
