import type { CourseContent } from '../academy-types'

// Split out of the pack beside it so a course title can be imported
// without dragging every lesson of every course along with it.

export const content: CourseContent = {
  slug: 'ground-wellbeing-masterclass',
  aims: `This masterclass gives working spa therapists genuine professional depth in Ground Wellbeing, the Irish house that has become one of the most distinctive voices in modern luxury spa. It covers the founding story and grounding philosophy that shape every ritual, the need-state logic of the range and the aromatherapy story behind it, and the practical craft of the Ground shift: reading the treatment menu, delivering the slow signature style, retailing the range by linking products to the state the guest arrived with, building honest upsell paths, and upholding the standards that protect the brand's name. Where house-specific details vary by spa or evolve over time, the course teaches the professional method for learning them fast and accurately on day one. This is independent Talent House training and is not affiliated with or endorsed by Ground Wellbeing.`,
  audience: `Spa and wellness therapists working in, or preparing to work in, spas carrying Ground Wellbeing across UK and Irish luxury hotels, destination spas and premium day spas. It suits therapists interviewing for a Ground account who want to arrive fluent, agency and freelance therapists who may be asked to deliver the house style at short notice, experienced therapists moving to Ground from a results-led house who need to adjust their pace and voice, and spa managers or head therapists who coach brand standards. Reception and retail colleagues in Ground spas will also gain a working command of the range and its language.`,
  outcomes: [
    `Tell Ground Wellbeing's founding story and articulate its philosophy and USP in confident, guest-ready language`,
    'Explain the need-state logic of the range and the aromatherapy ingredient story accurately and honestly',
    `Deliver Ground's slow, grounding signature style, from the opening breath to the closing stillness, at five-star standard`,
    'Retail the range by linking products used in treatment to a two or three item prescription tied to the guest, and their need state',
    `Build integrity-led upgrade paths between treatments and uphold the house's standards on every shift`,
  ],
  lessons: [
    {
      title: 'The house: history, philosophy and USP',
      objectives: [
        `Recount Ground Wellbeing's founding story and explain why its treatment-room heritage sets it apart`,
        `Explain the house philosophy of grounding, slowing down and designing for real human states, including its inclusive approach to oncology and menopause guests`,
        `Articulate Ground's USP to a guest in one confident, accurate sentence, using the house's own tone of voice`,
      ],
      sections: [
        {
          heading: 'An Irish house born from the treatment room',
          body: `Ground Wellbeing was founded in 2020 in Cork, Ireland, by Peigín Crowley, and her biography is the brand's foundation stone. Before creating Ground she spent roughly two decades in the luxury spa industry, creating, leading and developing spas for high-end hotels, which means she arrived at her own brand knowing exactly what a treatment room needs, what therapists struggle with, and what guests quietly wish a spa would offer them. Like the strongest houses before it, Ground travelled from the treatment room outwards rather than from a retail counter inwards. The timing matters too: launching in 2020, in the middle of a global pandemic, the brand spoke directly to a moment when the whole world was anxious, sleepless and desperate to feel steady. That origin gave Ground an unusually clear purpose from day one. For a therapist, the story is the answer to the guest who asks what makes this brand different: it was built by a career spa professional, in Ireland, to meet human needs she had watched go unmet for twenty years.`,
        },
        {
          heading: 'The philosophy: grounded, slow, and honest about how people feel',
          body: `The name is the philosophy. Ground exists to help people feel grounded: to slow down, to breathe, to come out of a racing head and back into the body. Where most product houses organise themselves around skin types, ageing concerns or clinical results, Ground organises itself around states of being, creating aromatherapy-led products and rituals for the things guests actually arrive with: poor sleep, stress and anxiety, depletion and low energy, and the need for recovery and rest. Formulations are natural and essential-oil led, made in Ireland, and designed to work on the nervous system and the senses as much as on the skin. The treatments carry the same conviction: slowness is treated as a feature, not an inefficiency, and rituals make deliberate room for breath, stillness and grounding touch. A therapist who delivers a technically perfect but hurried treatment has missed this brand entirely. The promise is not that a guest will look different when they leave; it is that they will feel different, calmer, heavier in the best sense, and back in their own body.`,
        },
        {
          heading: 'Wellbeing that leaves nobody outside the door',
          body: `One of the most distinctive and publicly celebrated strands of Ground's identity is inclusivity. Traditional spa menus have often quietly excluded whole groups of guests: people undergoing cancer treatment turned away at the consultation form, menopausal women offered nothing that acknowledged what their bodies were doing. Ground has become particularly known for moving in the opposite direction, developing products and adapted treatments intended to be suitable for people living with and beyond cancer, and offerings that speak directly to menopause, alongside its broader work on sleep, stress and rest. For a therapist this is both a value and a practical responsibility. It is a value because it changes who walks through the door and how welcome they feel. It is a responsibility because adapted treatments demand genuine training: correct pressure, correct positioning, correct product choices and honest scope of practice. Never improvise an oncology adaptation from goodwill alone; follow the training and protocols your spa provides, and be honest when a request sits outside what you are qualified to deliver. Inclusion done properly is competence, not just kindness.`,
        },
        {
          heading: 'The USP in one breath, and the house voice',
          body: `Every therapist on a Ground account should be able to state the USP in a single sentence, because guests ask, interviewers ask, and hesitation reads as ignorance. A reliable version: Ground is an Irish house, created by a career spa professional, offering slow, grounding aromatherapy rituals organised around how guests feel rather than how they look, with a menu that welcomes people other brands turn away. Each clause earns its place: Irish and founder-led, because provenance and authenticity are central to the story; slow and grounding, because the pace and the touch are the product; organised around feeling, because the need-state logic is what makes the range different; inclusive, because the oncology and menopause work is a genuine point of difference. The house voice follows: calm, warm, human and unhurried, with natural words like ground, breathe, rest, restore and ritual. Avoid clinical percentages and transformation promises; they belong to other houses. Speak as the brand does, and a regular guest of the spa will recognise you as a resident, not a visitor.`,
        },
      ],
      keyTerms: [
        { term: 'Founder-led house', definition: `A brand whose identity, story and standards flow directly from a named founder; for Ground, spa professional Peigín Crowley, who founded the house in Cork in 2020.` },
        { term: 'Grounding', definition: `The felt sense of slowing down and returning to the body, out of a racing mind; the state Ground's rituals, touch and aromatherapy blends are designed to create.` },
        { term: 'Need state', definition: `A human condition such as poor sleep, stress or low energy around which Ground organises its products and treatments, in place of skin types or age brackets.` },
        { term: 'Inclusive wellbeing', definition: `Designing products and adapted treatments so that guests often excluded by traditional menus, including those living with cancer or moving through menopause, can be welcomed safely and knowledgeably.` },
      ],
      caseStudy: {
        title: 'The hesitant guest at Fenwick Park, the Cotswolds',
        scenario: `Aoife is a therapist at Fenwick Park, a country house hotel spa in the Cotswolds that recently added a Ground Wellbeing menu. A guest, Mrs Halloran, lingers at reception reading the brochure and finally admits why she is hesitating: she finished chemotherapy eight months ago, and the last two spas she visited refused to treat her once she disclosed it. She asks Aoife, quietly, whether she would honestly be better off not mentioning it. Aoife senses the guest is braced for another polite rejection, and that how she answers the next question will decide whether Mrs Halloran ever books a spa treatment again.`,
        insight: `Aoife thanks her for disclosing, and explains that this is exactly the kind of guest the house was built for: Ground is known for treatments adapted for people living with and beyond cancer, and the spa's therapists are trained in those protocols. She books Mrs Halloran with a therapist holding that training, completes a full consultation, and never once makes the guest feel like a risk to be managed. The professional lessons: disclosure must always be met with warmth, adapted treatments are delivered through training and protocol rather than improvisation, and the brand's inclusive promise is only real if the therapist in front of the guest honours it.`,
      },
      summary: `Ground Wellbeing is an Irish house founded in 2020 in Cork by Peigín Crowley, a spa professional with around twenty years of luxury hotel spa experience behind her, and it grew out of the treatment room rather than a retail counter. Its philosophy is grounding: slow, aromatherapy-led rituals organised around real human states such as sleep, stress and depleted energy, with a celebrated commitment to inclusive wellbeing for oncology and menopause guests. Its USP, slow grounding rituals built around how guests feel, should live on every therapist's tongue, delivered in the house's calm, human voice.`,
    },
    {
      title: 'Product knowledge and hero ingredients',
      objectives: [
        `Explain the need-state logic that organises the Ground range and how it changes consultation and recommendation`,
        `Describe the house's core formats and its natural, essential-oil led ingredient story in guest-ready language`,
        'Apply a reliable, honest method for learning any Ground account quickly without inventing claims',
      ],
      sections: [
        {
          heading: 'The need state: the logic of the whole range',
          body: `The single most important thing to understand about Ground's range is its organising principle, because it is different from most houses a therapist will have trained with. Conventional skincare ranges sort themselves by skin type or age concern: dry, oily, combination, first signs of ageing. Ground sorts itself by need state: the human condition the product serves, with sleep, calm, energy and recovery among the states the house addresses. This changes the consultation at its root. You do not open a Ground consultation by analysing skin type; you open it by asking how the guest is, how they are sleeping, what their days are demanding of them, and what they most need to feel by the time they leave. The answer points you to a family of products and treatments. It also changes retail completely: a guest is not matched to a moisturiser, they are matched to a ritual for the thing that is actually wrong. Master this logic and the whole range becomes navigable; miss it and you will forever be translating Ground into a skincare language it was never written in.`,
        },
        {
          heading: 'Formats and the aromatherapy heart',
          body: `Ground's formats carry its philosophy. The core of the range is the body: aromatherapy body oils and balms designed for grounding touch, supported by bath salts and soaks that extend the ritual into the guest's own home, candles that carry the blends into their rooms, and facial care in the same calm register. The ingredient story is natural and essential-oil led: blends are built around essential oils chosen for their effect on the nervous system, mood and the senses, in naturally derived bases, made in Ireland. When you narrate a product during treatment, tell that story in one honest sentence: the state it serves, what it broadly contains, and how the guest will feel. Notice what this means commercially: because the formats are rituals rather than corrective steps, Ground retail is unusually giftable and unusually personal. The bath soak is tonight's continuation of today's treatment; the candle is the treatment room rebuilt at home; the balm is grounding touch the guest can give themselves. Sell the state and the ritual, and the format sells itself.`,
        },
        {
          heading: 'Learning the heroes without inventing them',
          body: `Every house has its heroes, the products guests ask for by name, and every Ground account will have a shelf of current bestsellers and signature lines. This course deliberately does not hand you a memorised list, because ranges evolve, spas stock differently, and a stale list confidently recited is worse than an honest question. Instead, apply the professional method on day one. Ask the spa which products anchor its Ground menu and which lines guests reorder most; those are your heroes. Read the house training materials the spa holds, because the brand's own words are your safest source for any claim. Master the heroes first, one fluent sentence each: what it is, which state it serves, who it suits. Then learn one need-state family at a time, so you understand each family's logic rather than isolated items. Finally, use the key products yourself, in your own evenings and baths, because Ground's products are rituals and conviction about a ritual cannot be faked. A therapist who does this is genuinely fluent within a week, on any Ground shelf in any spa.`,
        },
        {
          heading: 'Honesty as a product-knowledge discipline',
          body: `Ground's guests often arrive carrying something real: months of broken sleep, a stressful diagnosis, a body changed by menopause. That raises the stakes on honesty. Never claim a specific ingredient, percentage or clinical effect you have not verified from the brand's own materials, and never promise outcomes a body oil cannot deliver to someone who is genuinely unwell. The honest register sounds like this: this blend was created to support rest, most guests find it deeply calming, and used nightly it becomes a cue your body learns. That is truthful, warm and persuasive. The dishonest register, this will fix your insomnia, is a promise you cannot keep to a guest who deserved better. Practise the honest gap as a habit: when asked something you do not know, say what you do know, offer to check the rest, and actually check it, bringing the answer to reception before the guest leaves. In a house built on care, being caught inventing a detail does not just cost you credibility; it quietly breaks the promise the whole brand is making.`,
        },
      ],
      keyTerms: [
        { term: 'Need-state range', definition: `A product range organised by the human condition it serves, such as sleep, calm, energy or recovery, rather than by skin type, age or price tier; the structure of the Ground range.` },
        { term: 'Ritual format', definition: `A product designed to be used as a repeated, intentional practice, such as a body oil, bath soak or candle, extending the treatment into the guest's home life.` },
        { term: 'Essential-oil led', definition: `Formulated around essential oils chosen for their effect on the nervous system, mood and the senses, in naturally derived bases; the heart of Ground's ingredient story.` },
        { term: 'The honest gap', definition: `The professional habit of saying what you know, admitting what you do not, and checking before claiming; the opposite of inventing product details under pressure.` },
      ],
      caseStudy: {
        title: 'The sleepless guest at The Belgrave Townhouse, London',
        scenario: `Priya works at The Belgrave Townhouse, a boutique five-star hotel spa in London carrying Ground Wellbeing. Her guest, Mr Okafor, books a massage and mentions in consultation that he has barely slept properly since a bereavement earlier in the year, and that a colleague told him this brand does something for sleep. He asks Priya directly: which product should I buy, and will it actually work? Priya joined the account a fortnight ago; she knows the range's logic and its sleep family, but she has not yet memorised every item on the shelf, and she can feel the temptation to bluff a complete answer to a grieving, exhausted man.`,
        insight: `Priya consults by need state, not skin type: she asks about his evenings, his wind-down and his bath habits, then builds the treatment around calm and rest. At the close she prescribes honestly: the sleep-focused oil she used in treatment, and a bath soak to extend the ritual at home, explained as support for rest rather than a cure, used nightly so his body learns the cue. On the one product she is unsure of, she uses the honest gap, checks the spa's training folder, and confirms the answer before he leaves. He buys both, and rebooks. Honesty, matched to real need, is the brand delivered.`,
      },
      summary: `Ground product mastery begins with the range's logic: it is organised by need state, sleep, calm, energy and recovery among them, not by skin type, and that reshapes consultation and retail alike. The formats carry the philosophy, body oils and balms at the core, with bath soaks, candles and facial care extending the ritual home, all natural, essential-oil led and made in Ireland. Because shelves evolve, the lasting skill is the method: learn the spa's current heroes first, one need-state family at a time, use the products yourself, and hold the honest gap rather than invent a claim.`,
    },
    {
      title: 'Signature treatments, retail and upselling',
      objectives: [
        `Navigate a Ground treatment menu on day one and deliver the house's slow, grounding signature style with confidence`,
        'Retail the range by linking the products used in treatment to a short, honest prescription tied to the need state that the guest arrived with',
        `Build integrity-led upsell paths between treatments and uphold the brand's standards on every shift`,
      ],
      sections: [
        {
          heading: 'Reading the treatment menu like a professional',
          body: `Every Ground spa's menu differs in detail, so the day one discipline is a reading method, not a memorised list. Start by asking the head therapist which rituals the spa leads with, because those signatures are the treatments guests arrive already wanting and the ones you will deliver most. Expect the menu to mirror the range's logic: rituals built around need states such as sleep, calm and restoration, body-led treatments in which massage, breath and grounding touch do the work, and adapted offerings for guests who need them, including oncology-adapted and menopause-focused treatments where the spa is trained to provide them. For each treatment on the menu, note four things: duration, protocol source, products used, and who it is for, including any adaptations and their training requirements. Read the protocols the spa holds, shadow a senior therapist where you can, and ask questions before your first guest rather than improvising in front of one. Take special care to learn which treatments require adapted training before you may deliver them; volunteering for a treatment you are not yet qualified to give is not initiative, it is a safeguarding failure.`,
        },
        {
          heading: 'Delivering the signature style: slowness as craft',
          body: `A Ground treatment should be recognisable within its first two minutes, because the house style is the pace itself. Rituals in this house typically make deliberate space for breath at the opening, settling the guest before any product touches skin; for grounding touches, classically including unhurried work on the feet; and for stillness, held without apology, at transitions and at the close. Your movement between phases is slow and continuous, your voice low and spare, and the treatment ends as a landing rather than a stop. Understand what this asks of you technically: slowness under the clock is a craft. It means knowing the protocol so well that you never rush to catch up, staging products so nothing breaks the flow, and rehearsing transitions until they are silent. It also means resisting the instinct, drilled into many therapists by busier houses, to fill silence with conversation or to demonstrate value through constant activity. In this house, the stillness is the value. Guests who book Ground are often depleted, anxious, grieving or unwell; the slow, steady, confident hour is precisely the medicine they came for.`,
        },
        {
          heading: 'Retail: the ritual continued at home',
          body: `Ground retail succeeds when it is framed as the treatment going home with the guest, and the need-state logic makes the links unusually natural. During the treatment, narrate the key products at gentle moments, one sentence each, while the guest is experiencing them. At the close, prescribe rather than pitch: two or three products, each tied explicitly to the state the guest arrived with and to what you found. The strongest links write themselves: the sleep-focused oil for the guest who cannot switch off, applied as a nightly ritual so the body learns the cue; the bath soak that extends tonight what your hands began today; the candle that rebuilds the treatment room's calm in their own home. Explain the ritual, not just the product, because the how and when of use is what makes a Ground purchase work, and a purchase that works is what brings the guest back. Tell them what not to buy as well; in a house built on care, restraint sells. Write the prescription down, and record it on the guest's history so the next therapist can continue the story rather than restart it.`,
        },
        {
          heading: 'Upselling with integrity, and protecting the brand on shift',
          body: `Upsell paths in a Ground spa follow need, never price. The guest who melted into the grounding foot work is a natural candidate for the longer ritual next visit; say so at the close, and note it on their record. The stressed sixty-minute guest carrying months of tension genuinely benefits from ninety minutes, offered once, warmly, at booking or in consultation. Enhancements and bath rituals let a guest deepen today's visit without changing it. The integrity rule is absolute, and in this house it is also emotional: many Ground guests are vulnerable, and an upsell that serves the bill rather than the person is a betrayal of everything the brand claims. Alongside selling the house, you protect it. On shift that means using the correct products in the correct quantities, following the protocol rather than your private variant, keeping retail and testers immaculate, reporting low stock before it forces substitutions, respecting the training boundaries around adapted treatments, and never quietly compressing the slow ritual to rescue a late-running column; flag the schedule instead. Guests experience the brand only through its therapists. On a Ground shift, you are Ground.`,
        },
      ],
      keyTerms: [
        { term: 'Signature ritual', definition: `A treatment a Ground spa leads with, typically built around a need state such as sleep or calm; the first treatments to master on any new Ground menu.` },
        { term: 'Grounding touch', definition: `Slow, steady, intentional contact, classically including unhurried work on the feet, used to settle the nervous system and bring the guest back into their body.` },
        { term: 'Need-led upsell', definition: `An upgrade path built on the guest's genuine state and what they loved, such as sixty minutes to ninety for a depleted guest, never on price or targets alone.` },
        { term: 'Brand standards', definition: `The practices that protect a house's reputation on shift: correct products and quantities, faithful protocols, respected training boundaries, stock reporting and the slow ritual delivered in full.` },
      ],
      caseStudy: {
        title: 'The agency shift at Craigallan Lodge, the Scottish Highlands',
        scenario: `Callum, an experienced agency therapist, arrives at Craigallan Lodge, a five-star highland retreat whose spa runs a Ground Wellbeing menu, for his first shift on the account. He has forty minutes before his first guest. He asks the head therapist which rituals the spa leads with, reads the protocol for the signature sleep-focused ritual he will deliver twice today, confirms the products and the opening breathwork, and checks which treatments on the menu require adapted training he does not yet hold. His second guest, Mrs Whitfield, arrives visibly wired, apologising for checking her phone, and mentions she has not had a proper night's sleep since selling her business.`,
        insight: `Callum's preparation makes the professional move available. He delivers the ritual at the house's pace, holding the opening breath and the foot work without trimming, and watches Mrs Whitfield finally still. At the close he prescribes the sleep oil he used and a bath soak, explained as a nightly ritual, then opens the need-led path: with tension this established, the ninety-minute version next visit is the honest recommendation, and he notes it on her record for whoever treats her next. Nothing was pushed; a real need was heard and answered. One shift, delivered in the house's own accent, and an agency therapist the lodge asks for by name.`,
      },
      summary: `Mastering a Ground shift is a craft with four faces. Read the menu like a professional, signatures first, and know which treatments require adapted training before you touch them. Deliver the slow style faithfully: the opening breath, the grounding foot work, the held stillness, because in this house the pace is the product. Retail as the ritual continued at home, prescribing two or three products tied to the guest's need state. And build need-led upgrade paths while protecting the standards, because on shift the therapist is the brand, and the slow ritual is never the thing you trim.`,
    },
  ],
}
