import type { CourseContent } from '../academy-types'

// Split out of the pack beside it so a course title can be imported
// without dragging every lesson of every course along with it.

export const content: CourseContent = {
  slug: 'murad-masterclass',
  aims: `This masterclass gives working spa therapists genuine professional depth in Murad, one of the founding houses of doctor-led clinical skincare. It covers the founding story and whole-person philosophy that shape everything the brand does, the concern-led product architecture, hero products and signature actives a therapist must know cold, and the practical craft of the Murad shift: reading the treatment menu, delivering the clinical-yet-caring signature style, retailing the range through diagnosis-led prescription, building honest upsell and course-of-treatment paths, and upholding the standards that protect a clinical brand's name. Where house-specific details vary by spa, the course teaches the professional method for learning them fast and accurately on day one. This is independent Talent House training and is not affiliated with or endorsed by Murad.`,
  audience: `Spa and wellness therapists working in, or preparing to work in, spas and clinics that carry Murad across UK luxury hotels, destination spas, premium day spas and skin clinics. It suits therapists interviewing for a Murad account who want to arrive fluent, agency and freelance therapists who may be asked to deliver a clinical house style at short notice, experienced therapists moving to Murad from a ritual-led house, and spa managers or head therapists who coach brand standards. Reception and retail colleagues in Murad spas will also gain a working command of the range and its language.`,
  outcomes: [
    `Tell Murad's founding story and articulate its philosophy and USP in confident, guest-ready language`,
    'Navigate the concern-led range, name the hero products and explain the signature actives accurately and honestly',
    `Deliver Murad's clinical-yet-caring signature style, from skin analysis to written prescription, at five-star standard`,
    'Retail the range by matching two or three products to a genuine diagnosis and the treatment just delivered',
    `Build integrity-led upsell and course-of-treatment paths and uphold a clinical house's standards on every shift`,
  ],
  lessons: [
    {
      title: 'The house: history, philosophy and USP',
      objectives: [
        `Recount Murad's founding story and explain why its doctor-led heritage sets it apart from counter-born brands`,
        `Explain the whole-person philosophy, including internal hydration and the eat your water principle`,
        `Articulate Murad's USP to a guest in one confident, accurate sentence, using the house's own tone of voice`,
      ],
      sections: [
        {
          heading: 'A house born in a dermatology clinic',
          body: `Murad was founded in Los Angeles in 1989 by Dr Howard Murad, a board-certified dermatologist who had also trained as a pharmacist, a combination that mattered enormously. As a practising doctor he saw thousands of patients with real skin concerns; as a pharmacist he understood formulation well enough to build the answers himself. The brand grew directly out of that clinic: products created to solve the problems on the treatment couch in front of him, then refined against the results he could observe in his own patients. This makes Murad one of the original doctor-led skincare houses, arriving years before the modern wave of dermatologist brands. Dr Murad is also widely credited as a pioneer of clinical skincare more broadly, and in particular as one of the first to bring alpha hydroxy acids, notably glycolic acid, into modern formulation. For a therapist, this heritage is the answer to the guest who asks what makes the brand different: these products descend from a doctor's practice, not a marketing plan.`,
        },
        {
          heading: 'The philosophy: skin reflects the whole person',
          body: `The surprise inside this most clinical of houses is how holistic its philosophy is. Dr Murad taught, decades before it became fashionable, that skin is a reflection of whole-body health: diet, cellular hydration, sleep and stress all show on the face, so treating skin topically while ignoring the person attached to it is half a treatment. His well-known book The Water Secret puts internal hydration at the centre of skin health and gives the house its most famous piece of advice: eat your water, meaning get hydration from water-rich raw fruits and vegetables, so cells are hydrated steadily from within rather than by glasses of water that pass straight through. He also wrote and lectured widely on stress as an ageing force and on self-care as genuine skincare. In the treatment room this philosophy licenses you to talk about lifestyle, honestly and without preaching. A Murad therapist who mentions hydration, stress and sleep alongside serums is not going off script; that conversation is the script.`,
        },
        {
          heading: 'The USP in one breath',
          body: `Every therapist on a Murad account should be able to state the house USP in a single sentence, because guests ask, interviewers ask, and hesitation reads as ignorance. A reliable version: Murad is clinical skincare created by a practising dermatologist, organised around real skin concerns, built on proven ingredient science, and delivered with a whole-person view of health. Each clause earns its place. Created by a practising dermatologist, because the doctor-led origin is the deepest point of difference and the source of the brand's authority. Organised around real skin concerns, because the concern-led architecture is how guests experience the range. Built on proven ingredient science, because the house heritage runs through glycolic acid, salicylic acid, retinol and vitamin C, actives with genuine evidence behind them. A whole-person view of health, because the philosophy insists that skin, body and mind are connected. When a guest compares Murad with a glamour brand, you have an honest, specific answer that elevates the house without disparaging anything else.`,
        },
        {
          heading: 'Speaking Murad: the house voice',
          body: `A product house is also a vocabulary, and a clinical house has a distinctive one. The Murad voice is confident, evidence-led and plain: it talks about concerns, results, actives and skin health, and it explains why things work in language a guest can repeat to a friend. It is never cold, though. The whole-person philosophy keeps the voice caring: you are a skin professional who sees the person, not a technician reciting percentages. Contrast this with a ritual-led aromatherapy house, where the natural words are wellbeing, balance and breathe; neither voice is superior, but each belongs to its own brand, and a therapist who drifts into mystical language on a Murad shift sounds like a visitor. Practise the clinical-yet-caring register: not this smells lovely, but this contains salicylic acid, which works inside the pore to clear congestion, and you should see the difference within weeks. Then add the human clause: and because your skin flares when you are stressed, be kind to yourself this month too. That pairing of evidence and empathy is the house.`,
        },
      ],
      keyTerms: [
        { term: 'Doctor-led brand', definition: `A skincare house founded and formulated by a medical professional, with products descending from clinical practice; Murad, founded by dermatologist Dr Howard Murad in 1989, is one of the originals.` },
        { term: 'Whole-person philosophy', definition: `The Murad principle that skin health reflects whole-body health, so diet, hydration, sleep and stress belong in the skincare conversation alongside topical products.` },
        { term: 'Eat your water', definition: `The famous advice from The Water Secret: get hydration from water-rich raw fruits and vegetables so cells hydrate steadily from within.` },
        { term: 'USP', definition: `Unique selling point: the specific, honest claim that distinguishes a house from its competitors, which every therapist should be able to state in one sentence.` },
      ],
      caseStudy: {
        title: 'The glamour comparison at The Fairlowe, Mayfair',
        scenario: `Priya is a therapist at The Fairlowe, a five-star hotel spa in Mayfair whose skin menu is built on Murad. Her guest Mrs Castellano, loyal for years to a famous glamour skincare house, asks during consultation why she should trust a brand she associates with chemists' shelves over the gold-jarred cream she has always loved. Priya senses the trap of criticising the guest's beloved brand, which would only put her on the defensive, but she also knows that a vague answer will confirm the guest's suspicion that this is skincare without romance. She has one sentence to reframe the whole conversation.`,
        insight: `Priya reaches for the founding story and the USP: Murad was created by a practising dermatologist who built these formulas for his own patients, so what Mrs Castellano is trying today is clinical skincare organised around her actual concerns, delivered with a whole-person view of her health. She then lets the skin analysis and the visible result make the rest of the argument. The professional lesson: never disparage the guest's existing brand, and never apologise for a clinical house lacking romance. Its romance is the result, and the doctor-led story is an honest, unanswerable point of difference.`,
      },
      summary: `Murad is one of the original doctor-led skincare houses, founded in Los Angeles in 1989 by Dr Howard Murad, a board-certified dermatologist and trained pharmacist who built the brand out of his own clinical practice and helped pioneer the use of alpha hydroxy acids in modern skincare. Its philosophy is unexpectedly holistic: skin health reflects whole-body health, with The Water Secret and eat your water putting internal hydration at the centre. The USP, clinical skincare by a practising dermatologist, concern-led, science-backed and whole-person, should live on every therapist's tongue, delivered in the clinical-yet-caring house voice.`,
    },
    {
      title: 'Product knowledge and hero ingredients',
      objectives: [
        `Navigate Murad's concern-led range architecture and match product families to the concerns guests present with`,
        'Name the hero products and signature actives and explain each in one honest, guest-ready sentence',
        'Apply a reliable, honest method for learning any clinical range quickly without inventing claims',
      ],
      sections: [
        {
          heading: 'Concern-led architecture: think like a diagnostician',
          body: `The organising principle of the Murad range is the single most useful thing to learn on day one: products are grouped by skin concern, not by skin type, age bracket or price tier. The families answer the problems guests actually present with, such as blemishes and breakouts, visible ageing, uneven tone and pigmentation, dehydration and redness or sensitivity. This architecture rewards a diagnostic habit of mind. Instead of asking which products to show a guest, you ask what concern the skin in front of you is actually presenting, and the answer walks you to the right family. It also protects you from the classic error of treating the skin the guest describes rather than the skin you can see: a guest may ask about ageing while their real, treatable concern today is dehydration. Analyse first, then navigate. Once you hold the concern map in your head, an unfamiliar Murad retail wall stops being a hundred products and becomes half a dozen families, each with a clear job, and your recommendations start sounding like diagnoses rather than suggestions.`,
        },
        {
          heading: 'Heroes first: the icons guests ask for',
          body: `In any house a small number of products carry the reputation, and mastering them first gives you most of your credibility for a fraction of the effort. Among Murad's best-known products are the Clarifying Cleanser, the entry point of the blemish family and one of the most asked-for cleansers in clinical skincare; the Retinol Youth Renewal Night Serum, the house's celebrated retinol offering for visible ageing; the Essential-C range, built around vitamin C for skin stressed by sun and environment; and the Hydro-Dynamic Ultimate Moisture for deep hydration. Your own spa may stock other families and other icons, so apply the method rather than memorising a fixed list: ask which products guests request by name, which the menu's facials actually use, and which anchor each concern family, then learn those heroes until you can present each in a single fluent sentence covering what it is, what it is famous for, and who it suits. A therapist who can do that for six products is more convincing than one who half-knows sixty.`,
        },
        {
          heading: 'The signature actives and how to narrate them',
          body: `Murad's formulation story runs through the great evidence-backed actives of clinical skincare, and a therapist on a Murad account should be able to narrate each in plain language. Glycolic acid, the alpha hydroxy acid Dr Murad helped bring into modern skincare, exfoliates the surface for smoothness and radiance. Salicylic acid, a beta hydroxy acid, works inside the pore, which is why it anchors the blemish family. Retinol drives skin renewal and is the reference active for visible ageing. Vitamin C brightens and helps defend against environmental stress. Hyaluronic acid draws and holds moisture for hydration and plumpness. The narration discipline is one sentence per active: what it is, what the evidence says it does, what the guest will notice, delivered while the guest experiences the product. Two cautions keep it professional. Actives demand respect, so know the patch-test, contraindication and sun-care rules your spa applies, especially around acids and retinol. And never claim a percentage or formulation detail you have not verified from the brand's own materials; in a clinical house, an invented number is a credibility wound that does not heal.`,
        },
        {
          heading: 'How to learn a clinical range properly',
          body: `No course can teach the exact shelf of your particular spa, because ranges evolve and stock lists differ, so the meta-skill matters more than any list: the professional method for learning a clinical house fast and honestly. First, learn the concern map before any individual product, because the architecture is the range's own logic. Second, heroes before everything, as above. Third, one family at a time: learn the blemish family as a system, then ageing, then pigmentation, understanding how the products within each family work together as a routine. Fourth, the house's own training materials are your only safe source for claims; in a clinical brand this rule is absolute, because guests here are often well-read and will check. Fifth, use the key products on your own skin, because conviction cannot be faked and your own results are honest testimony. Finally, build the habit of the honest gap: when asked something you do not know, say what you do know, offer to check the rest, and actually check it. In a house built on a doctor's integrity, that habit is the brand behaviour.`,
        },
      ],
      keyTerms: [
        { term: 'Concern-led range', definition: `A product architecture organised around the skin problems guests present with, such as blemishes, ageing, pigmentation and dehydration, rather than by skin type or price; the organising principle of the Murad range.` },
        { term: 'AHA and BHA', definition: `Alpha hydroxy acids such as glycolic acid exfoliate the skin's surface; beta hydroxy acid, salicylic acid, works inside the pore; both are signature Murad actives demanding proper patch-test and sun-care discipline.` },
        { term: 'Hero product', definition: `An iconic product that carries a house's reputation and that guests ask for by name; for Murad, think of the Clarifying Cleanser, the Retinol Youth Renewal Night Serum and the Essential-C range.` },
        { term: 'The honest gap', definition: `The professional habit of saying what you know, admitting what you do not, and checking before claiming; in a clinical house whose guests read ingredient lists, it is the only safe policy.` },
      ],
      caseStudy: {
        title: 'The well-read guest at Thornbury Manor, the Cotswolds',
        scenario: `Ellie has just joined Thornbury Manor, a luxury Cotswolds spa hotel running a Murad skin menu, from a ritual-led aromatherapy house. In her first week her guest Mr Okafor, who follows skincare science online, asks precise questions: which acid is in the cleanser she is using, why she has chosen it for his congested skin, and whether he should use retinol and acids together at home. Ellie knows roughly half the answers with certainty. She feels the pull to bluff the rest smoothly, reasoning that a confident wrong answer will sound better in the moment than an admission that she is new to the range.`,
        insight: `Ellie holds the clinical standard instead. She answers what she knows cleanly: the cleanser is from the blemish family and salicylic acid works inside the pore, which is exactly why she chose it for his congestion. On combining actives at home she uses the honest gap, explaining the principle she is sure of, then confirming the house's exact guidance after the treatment and sending it via reception with his written prescription. Mr Okafor rebooks and buys both products. In a doctor-led brand, precision plus honesty is the selling style; a single bluffed answer to a well-read guest would have undone all of it.`,
      },
      summary: `Murad product mastery starts with the architecture: a concern-led range organised around blemishes, visible ageing, pigmentation, dehydration and sensitivity, navigated by diagnosing first and walking to the family that answers. Learn the heroes of the families your spa stocks, such as the Clarifying Cleanser, Retinol Youth Renewal Night Serum, Essential-C range and Hydro-Dynamic Ultimate Moisture, and narrate the signature actives, glycolic and salicylic acids, retinol, vitamin C and hyaluronic acid, in one honest sentence each. Beyond any list, the lasting skill is the method: concern map, heroes, one family at a time, the brand's own materials, personal use, and the honest gap instead of invention.`,
    },
    {
      title: 'Signature treatments, retail and upselling',
      objectives: [
        `Navigate a Murad treatment menu on day one and deliver the house's clinical-yet-caring signature style with confidence`,
        'Retail the range through diagnosis-led prescription, matching two or three products to the concern found in treatment',
        `Build integrity-led upsell and course-of-treatment paths and uphold a clinical brand's standards on every shift`,
      ],
      sections: [
        {
          heading: 'Reading the treatment menu like a professional',
          body: `Every Murad spa's menu differs in detail, so the day one discipline is a reading method, not a memorised list. Start with the flagship: most Murad menus are built around a personalised, analysis-led facial, and it is the treatment to learn first and in full, because it teaches you the house's diagnostic structure and the products the spa actually uses. Then map the rest in layers: the concern-led facials that mirror the product families, targeting blemishes, ageing, pigmentation or dehydration; the professional-strength exfoliation or peel treatments where the spa offers them, noting carefully which require specific certification and which you are not yet qualified to deliver; and the boosters or enhancements that can be added to deepen a booking. For each treatment record four things: duration, protocol source, products used, and who it is for, including its contraindications, which matter more in a house built on active ingredients. Read the protocols the spa holds, shadow a senior therapist where you can, and ask questions before your first guest rather than improvising in front of one.`,
        },
        {
          heading: 'Delivering the signature style',
          body: `A Murad treatment should feel like a consultation with a skin professional wrapped in a five-star experience, and that dual identity is the delivery standard. It begins with analysis: proper skin examination before anything is applied, with your findings narrated aloud, because the spoken analysis is what convinces the guest they are in expert hands and it founds every recommendation that follows. Through the treatment, narrate in the clinical-yet-caring voice at natural moments: one plain-language sentence about the active at work and what the guest will notice, never a lecture. Honour the philosophy as well as the science by weaving in the whole-person thread where it is genuine: hydration from water-rich foods, the effect of stress on skin, sleep. At the close, deliver the signature artefact of a clinical house: a personalised prescription, spoken and then written, covering home care, realistic timelines and the recommended return interval. Skin results run in cycles of weeks, and honesty about that builds more trust than promised miracles. The guest should leave with evidence, a plan and a reason to return.`,
        },
        {
          heading: 'Retail: the diagnosis going home',
          body: `Retail in a Murad spa succeeds when it is framed as the treatment plan continuing at home, and the concern-led architecture makes this natural. During the treatment, the products narrate themselves: the cleanser the guest can feel working and the serum matched to their concern are the most honest advertising in the industry. At the close, prescribe rather than pitch: two or three products, each tied explicitly to the concern you diagnosed and, wherever possible, experienced in the treatment itself. Explain the routine in ten seconds, cleanse, treat, protect, because a guest who understands the order actually uses the products, and a guest who gets results returns. Be honest about timelines and about what not to buy; telling a guest their existing moisturiser is fine while swapping their cleanser builds the trust that compounds into bigger baskets over years. Write the prescription down, respect the house's guidance on introducing actives gradually and on sun care alongside acids and retinol, and record everything on the guest's history so the next therapist continues the plan rather than restarting it.`,
        },
        {
          heading: 'Upselling with integrity, and protecting the brand on shift',
          body: `Upsell paths in a clinical house are unusually honest, because they follow the diagnosis. The deepest one is the course of treatments: concerns such as pigmentation, congestion and visible ageing genuinely respond to a series rather than a one-off, so explaining the professional truth, a facial every few weeks matched to the skin's renewal cycle with home care between, is service, not selling. Boosters and enhancements let a guest deepen today's booking; an upgrade from a standard facial to a professional exfoliation, where you are trained and the skin is suitable, answers a diagnosed need. The integrity rule is absolute: every upgrade must improve the guest's outcome, not merely the bill. Alongside selling the brand, you protect it, and in a house built on active ingredients the stakes are higher. Follow protocols exactly, never exceed your certification with professional-strength products, honour patch tests and contraindications without exception, keep testers and retail immaculate, report low stock before it forces substitutions, and never quietly trim an analysis or consultation to rescue a late-running column. On a Murad shift, your discipline is the brand's medical credibility in that room.`,
        },
      ],
      keyTerms: [
        { term: 'Flagship treatment', definition: `The treatment a house is most famous for and the first to master on any new menu; on most Murad menus, a personalised, analysis-led facial that teaches the house's diagnostic structure.` },
        { term: 'Prescription close', definition: `The signature ending of a clinical facial: a spoken then written home-care plan of two or three concern-matched products, realistic timelines and a recommended return interval.` },
        { term: 'Course of treatments', definition: `A planned series of facials at intervals matched to the skin's renewal cycle; the honest recommendation for concerns such as pigmentation and congestion that a single visit cannot resolve.` },
        { term: 'Brand standards', definition: `The practices that protect a clinical house's reputation on shift: exact protocols, certification limits respected, patch tests and contraindications honoured, immaculate presentation and stock reported.` },
      ],
      caseStudy: {
        title: 'The rushed Saturday at Harbourgate Spa, Cornwall',
        scenario: `Tomas works at Harbourgate Spa, a coastal luxury hotel in Cornwall with a fully booked Saturday column of Murad facials. Running fifteen minutes late after a delayed guest, he is tempted to claw the time back invisibly: skip the full skin analysis on his next guest, Mrs Whitfield, who has booked a brightening facial for the pigmentation she mentioned at reception, and drop the written prescription at the close. She would probably never notice. His coordinator has asked everyone to keep the day moving, and the easiest way to obey is to quietly serve the products without the clinical structure around them.`,
        insight: `Tomas protects the structure instead. He flags the delay to his coordinator, who adjusts the column, and delivers the analysis, because examining Mrs Whitfield's skin is what makes her facial a Murad treatment rather than a pleasant hour with good products; it also reveals dehydration alongside the pigmentation, changing his product choices. At the close she receives a written prescription and the honest truth that pigmentation responds to a course of treatments, which she books. The lesson: in a clinical house the analysis and the prescription are the brand, never the bits to trim, and schedules are management's problem to fix, not the standard's.`,
      },
      summary: `Mastering a Murad shift is a craft with four faces. Read the menu like a professional: flagship personalised facial first, then the concern-led facials, peels where certified, and enhancements, always noting contraindications. Deliver the signature style: analysis narrated aloud, clinical-yet-caring narration, the whole-person thread, and the prescription close with honest timelines. Retail as the diagnosis going home, two or three concern-matched products written down. And build honest paths, above all the course of treatments, while protecting the standards, because in a doctor-led house the therapist's discipline is the brand's credibility, and the analysis is never the thing you trim.`,
    },
  ],
}
