import type { CourseContent } from '../academy-types'

// Split out of the pack beside it so a course title can be imported
// without dragging every lesson of every course along with it.

export const content: CourseContent = {
  slug: 'spa-manager-programme',
  aims: 'A practical management programme for professionals stepping into, or already working in, day-to-day spa leadership. It combines people management, rota and payroll control, luxury service standards, commercial performance and operational systems so the learner can run a department with confidence rather than relying on instinct alone.',
  audience: 'Senior therapists, head therapists, supervisors, assistant spa managers and new Spa Managers working in luxury hotels, resorts, destination spas and premium day spas.',
  outcomes: [
    'Run a structured daily operating rhythm and set clear standards for a spa team',
    'Lead briefings, coaching and performance conversations using evidence and fair expectations',
    'Build rotas around demand, skill mix, breaks, payroll and operational resilience',
    'Audit and improve the luxury guest journey, including effective service recovery',
    'Interpret core commercial KPIs and improve utilisation, retail, rebooking and treatment contribution',
    'Build a practical scorecard, SOP framework and 30-day management action plan',
  ],
  prerequisites: 'Experience in a spa or hospitality team; suitable for senior therapists and supervisors stepping up.',
  author: { name: 'WHC Academy', role: 'Developed by Wellness House Collective' },
  references: [
    { label: 'UK Spa Association - industry resources and operational guidance', url: 'https://www.spa-uk.org' },
    { label: 'ACAS - Code of Practice on disciplinary and grievance procedures, and guidance on fair people management', url: 'https://www.acas.org.uk' },
    { label: 'Health and Safety Executive - workplace health and safety guidance, including COSHH', url: 'https://www.hse.gov.uk' },
  ],
  lastReviewed: '2026-08-31',
  version: '1.0',
  lessons: [
    {
      title: "The Spa Manager Role",
      whyThisMatters: "The move from therapist to manager is the single most common failed promotion in the spa industry, and it fails for structural reasons that are entirely avoidable. A manager who masters rhythm, triage and system-fixing runs an operation that performs on their day off - which is precisely what a general manager looks for before trusting anyone with a bigger department, a second site or a director's title.",
      objectives: [
        "Explain why the move from therapist to manager is a change of profession, not a promotion in the same one",
        "Design a daily and weekly operating rhythm that surfaces problems before guests experience them",
        "Apply a triage method for competing operational pressures",
        "Work effectively with the hotel departments a spa depends on",
      ],
      sections: [
        {
          heading: "A change of profession, not a bigger version of the old one",
          body: "The best therapist in the team is often promoted to manager, and the promotion fails more often than anyone admits. The reason is structural, not personal. A therapist's output is the treatment in front of them: five or six excellent hours of hands-on work a day, with immediate feedback from every guest. A manager's output is the consistency of an operation they mostly do not touch: thirty treatments a day delivered by other people, to a standard the manager defined, on a rota the manager built, at a cost the manager controls.\n\nManagement research has a name for the failure mode: the player-coach trap. The new manager keeps covering treatments because it feels productive and familiar, and the actual management work - observation, coaching, planning, prevention - happens in scraps between guests. Within three months the team has learned that standards are whatever the busiest person tolerates, and the manager is exhausted by doing one and a half jobs badly.\n\nThe honest test of a spa manager is uncomfortable but clarifying: how well does the spa run on your day off? If the answer is 'noticeably worse', the operation depends on your presence rather than your systems. Everything in this programme - rhythm, standards, coaching, scorecards, SOPs - exists to make your judgement present in the building when you are not.",
        },
        {
          heading: "The operating rhythm: how control actually happens",
          body: "Control of a spa is not a personality trait; it is a timetable. A workable daily rhythm looks like this.\n\nBefore opening (20-30 minutes): walk the spa as a guest would enter it - scent, temperature, music, lighting, water presentation, towel stocks, treatment room readiness. Then the operational scan: today's bookings against staffing, sickness calls, VIPs and repeat guests, maintenance faults, gaps worth filling with upgrade offers.\n\nThe team briefing (10 minutes, standing, same time every day): today's numbers (bookings, capacity, yesterday's result), VIPs and guest notes, one standard in focus this week, one commercial focus, and who owns what. A briefing is not a lecture; the tone you set at 09:00 is the tone the first guest meets at 10:00.\n\nDuring the day: a manager's most underrated tool is presence at the transition points - arrivals, changeovers, departures - because that is where the experience wobbles, never in the middle of a massage.\n\nEnd of day (10 minutes): revenue against target, complaints or saves, maintenance log, handover notes for tomorrow. Weekly: a one-to-one hour with your senior therapist or deputy, a scorecard review, and one deep-dive (retail one week, rebooking the next).\n\nNone of this is bureaucracy. It is the difference between finding out about a problem at 08:45 and finding out from a guest review.",
        },
        {
          heading: "Triage: deciding what matters when everything is urgent",
          body: "Pressure in a spa arrives in clusters - two sickness calls, a VIP arrival and a broken room heater land in the same half hour. Managers who thrive under this are not calmer by nature; they run a consistent triage order.\n\nFirst, guest safety and legal duty - anything touching health, safety or hygiene outranks everything else, always.\n\nSecond, guest-facing impact in the next hour - the arriving VIP couple and the 10:00 bookings come before anything a guest cannot yet see.\n\nThird, revenue protection - can the sickness gaps be covered by moving treatments between rooms and therapists before you start cancelling? A cancelled £180 ritual is gone forever; a 30-minute delay handled with a genuine apology and a gesture usually is not.\n\nFourth, team strain - who is now doing more than planned, and what do they need to sustain it?\n\nA second lens helps with bigger decisions: is this reversible? Reversible decisions (move a treatment, adjust a rota, trial an offer) should be made fast and adjusted later. Irreversible ones (dismissing someone, cancelling a VIP, committing to a refund policy) deserve the extra hour of thought. Most new managers get this backwards - agonising over reversible calls and rushing the irreversible ones.",
        },
        {
          heading: "Managing sideways: the hotel around the spa",
          body: "In a hotel or resort, the spa's guest experience is co-produced by departments the spa manager does not control. Reception promises arrival times the spa must honour. Housekeeping supplies the linen the treatment depends on. Engineering owns the pool plant, the sauna thermostat and the room that is too cold. Food and beverage delivers the post-treatment lunch on the terrace. When any of them fails, the guest blames the spa, because the spa is where they were standing.\n\nExperienced managers treat these relationships as operational infrastructure and invest in them deliberately: a standing five-minute exchange with front office each morning about arrivals and in-house guests worth inviting down; maintenance faults logged in writing with guest-impact stated ('room 3 unusable, £540 of Saturday bookings at risk') rather than mentioned in a corridor; linen par levels agreed and reviewed seasonally rather than argued about at 08:00.\n\nThe same applies upwards. Your general manager does not experience the spa's effort; they experience its numbers and its complaints. A manager who sends a short weekly note - result, reason, one risk, one ask - is trusted with more autonomy than one who is only heard from when something has gone wrong. Managing upwards is not politics; it is making your department legible to the people who allocate its resources.",
        },
        {
          heading: "Fix the system, then the symptom",
          body: "The defining habit of a real manager is the second question. The first question, under pressure, is 'how do we fix this now?' - and it must be answered. The second question, after the pressure passes, is 'what allowed this to happen?' - and it is the one that changes the operation.\n\nA therapist forgets a contraindication check: today you correct it; afterwards you ask whether the consultation form, the training or the time allowed for consultations is the real gap. Retail sales collapse on Sundays: the symptom invites a pep talk; the system question reveals the Sunday team was never trained on the new product line. Ask 'why' three or four times and you almost always land on a missing standard, a missing skill, or a missing owner - all of which are yours to fix.\n\nThis is also how you avoid the manager's most corrosive habit: treating recurring problems as personal failings of the team. If three different therapists have made the same error, it is not three character flaws; it is one system gap wearing three uniforms. Teams forgive a demanding manager. They do not forgive an unfair one, and blaming people for system failures is the most common unfairness in hospitality management.",
        },
      ],
      visuals: [
        { kind: "flow", title: "The triage order under pressure", steps: [
          "1. Guest safety and legal duty - anything touching health, safety or hygiene outranks everything, always",
          "2. Guest-facing impact in the next hour - the arriving VIPs and the 10:00 bookings before anything a guest cannot yet see",
          "3. Revenue protection - move treatments between rooms and therapists before you start cancelling",
          "4. Team strain - who is now doing more than planned, and what do they need to sustain it",
        ], caption: "Run the order aloud so the team learns it. Then apply the second lens: reversible decisions fast, irreversible decisions slowly." },
        { kind: "flow", title: "The daily operating rhythm", steps: [
          "Before opening (20-30 min): walk the spa as a guest, then scan bookings against staffing, sickness, VIPs and faults",
          "Briefing (10 min, standing, same time daily): numbers, VIPs, one standard in focus, one commercial focus, who owns what",
          "During the day: presence at the transition points - arrivals, changeovers, departures",
          "End of day (10 min): revenue against target, complaints or saves, maintenance log, handover notes",
          "Weekly: a one-to-one with your deputy, the scorecard review, one deep-dive",
        ], caption: "Control is a timetable, not a personality trait. The rhythm is what makes your judgement present when you are not." },
      ],
      scenario: "It is 14:00 on your first full day off in a month when your duty supervisor calls: a guest has slipped near the vitality pool (she is shaken but insists she is fine), the 15:00 couples' ritual room smells strongly of damp, and a therapist is asking to go home unwell after her 16:00 booking.\n\nThink through the call you would want the supervisor to be able to run without you. Which item comes first under the triage order, and why does the guest's own reassurance not settle it? Which of the three decisions are reversible enough for the supervisor to make alone? And what does the fact that she had to phone you at all tell you about the systems you have built so far?",
      activity: "For one working week, keep a note of every decision the team refers up to you. At the end of the week, sort the list into three groups: decisions only you should make, decisions a supervisor could make with a one-page SOP, and decisions the team should simply own. Write the single SOP that would remove the most referrals, and brief it at Monday's huddle.",
      knowledgeCheck: [
        { q: "At 08:45 on a fully booked Saturday you face three issues at once: a treatment room reading 16°C, a VIP couple arriving at 10:00, and £1,150 of bookings orphaned by two sickness calls. Under the triage order, what do you deal with first?", options: ["Start rebuilding the orphaned bookings - revenue is the largest number at stake", "Brief the team on the VIP couple's preferences", "Check the cold room and escalate to engineering - room condition touches guest safety and usability", "Call the agency for emergency cover"], answer: 2, why: "Safety and legal duty outrank everything, and a room at 16°C is unusable for body treatments until checked. The VIPs and the revenue rebuild follow immediately - but in that order, every time, so the team learns the order too." },
        { q: "On the same Saturday, moving treatments between rooms and shifting one guest by 30 minutes with a genuine apology cut the day's loss from over £1,100 to roughly £95. What principle does that illustrate?", options: ["Revenue protection means re-engineering the diary before cancelling - a cancelled treatment is gone forever, a well-handled delay usually is not", "Guests should always be compensated when plans change", "Agency cover is cheaper than cancellation", "Overbooking is a sensible hedge against sickness"], answer: 0, why: "The £1,150 exposure was rebuilt almost entirely by moving inventory, not by spending money. Cancellation is the irreversible option, so it comes last - after rooms, therapists and timings have all been flexed." },
        { q: "Which of these decisions deserves the slowest, most careful judgement?", options: ["Moving a facial to the multi-purpose room", "Trialling an upgrade offer in a quiet daypart", "Adjusting next week's rota", "Committing to refund a VIP's full package after a complaint"], answer: 3, why: "The first three are reversible - make them fast and adjust later. The refund commitment is irreversible and sets a precedent, so it justifies the extra hour of thought. Most new managers get this exactly backwards." },
      ],
      keyTerms: [
        { term: "Player-coach trap", definition: "The failure mode where a promoted expert keeps doing their old job hands-on and the management work happens in the gaps, so neither is done well." },
        { term: "Operating rhythm", definition: "The fixed daily and weekly cadence of walks, briefings, reviews and one-to-ones through which a manager controls the operation without standing over it." },
        { term: "Triage order", definition: "A consistent priority sequence for competing pressures: safety and legal duty, imminent guest impact, revenue protection, then team strain." },
        { term: "Reversible decision", definition: "A decision that can be cheaply undone, and should therefore be made quickly; irreversible decisions justify slower, more careful judgement." },
        { term: "Transition points", definition: "The moments between stages of the guest journey - arrival, changeover, departure - where experience most often degrades and manager presence matters most." },
      ],
      caseStudy: {
        title: "The fully booked Saturday",
        scenario: "At 08:45 on a fully booked Saturday, a luxury hotel spa takes two sickness calls, reception confirms a VIP couple arriving at 10:00, and the therapist opening room 3 reports the heating has failed. The team gathers around the new manager asking what to do. The day holds £4,100 of treatment bookings; the two absent therapists were due to deliver £1,150 of it.",
        insight: "The manager runs the triage order aloud so the team learns it. Safety first: room 3 is checked - 16°C, unusable for body treatments; engineering is called with the guest impact stated in pounds. Next-hour guests: the VIP couple's 10:00 ritual is unaffected and their preferences are re-confirmed. Revenue: the £1,150 of orphaned bookings is rebuilt - two treatments move to the multi-purpose room, one guest accepts a 30-minute shift with a complimentary upgrade, one 25-minute express facial cannot be saved and is rebooked for Sunday with a gesture. Final exposure: roughly £95 lost from £4,100, versus over £1,100 if the team had started cancelling at 08:50. The following Tuesday, the manager writes the sickness-cover sequence and the room-fault escalation into one-page SOPs, so the next crisis is a checklist rather than a performance.",
      },
      summary: "Management is a different profession from therapy: its product is consistency, its method is rhythm and triage, and its measure is how well the spa runs when the manager is not in the building.",
      nextStep: "Tomorrow, run the pre-opening walk and the ten-minute briefing exactly as this module describes them, and note which problems surfaced before a guest could meet them.",
    },
    {
      title: "People Leadership & Performance",
      whyThisMatters: "A spa's payroll is its largest cost and its team is its entire product, which makes people leadership the most commercially loaded skill a manager owns. Losing one senior therapist costs £6,000-£12,000 before the cultural damage is counted, and an unfair or careless performance conversation can trigger exactly that loss - or a grievance that consumes weeks. Managers who lead with clarity, precise feedback and fair process keep the teams that keep the guests.",
      objectives: [
        "Define standards as observable behaviours a team can actually follow",
        "Deliver feedback using the situation-behaviour-impact structure",
        "Distinguish capability, conduct and wellbeing issues and follow a fair process for each",
        "Quantify what losing a therapist really costs, and manage retention as a commercial discipline",
      ],
      sections: [
        {
          heading: "Clarity is the first act of leadership",
          body: "Most performance problems in spas are clarity problems wearing a disguise. 'She has a bad attitude at reception' usually decodes to: nobody has defined what a five-star welcome looks like, so everyone performs their own version, and hers is the weakest. People cannot reliably meet a standard they cannot describe.\n\nA usable standard is observable behaviour, not adjective. 'Be more welcoming' is an adjective; 'stand, make eye contact, use the guest's name within the first two sentences, and offer to take their robe' is a standard. 'Better room resets' is an adjective; 'room reset complete within eight minutes: couch re-dressed, towels replaced, oils wiped and returned to position, temperature checked, door left ajar' is a standard - and it can be trained, checked and coached without anyone's character being on trial.\n\nWrite standards for the moments that recur dozens of times a day: the telephone answer, the arrival, the consultation opening, the treatment close, the retail recommendation, the goodbye, the room reset. Six or eight one-page standards, briefed one per week on rotation, will move a team further than any motivational speech, because they replace the manager's mood as the definition of good with something stable, fair and learnable.",
        },
        {
          heading: "Feedback that changes behaviour: situation, behaviour, impact",
          body: "The most reliable feedback structure in management practice is situation-behaviour-impact (SBI), and it fits on the back of a hand.\n\nSituation: name the specific moment - 'this morning, with the 10 o'clock facial guest'. Behaviour: describe what you observed, as a camera would record it - 'the consultation lasted under two minutes and skin concerns weren't asked about'. Impact: state the consequence - 'she mentioned at checkout that the treatment didn't address her congestion, and she declined products she'd normally be an obvious match for'.\n\nThen stop talking. Ask for their view. Half the time you will learn something operational - the previous treatment ran over, so the consultation was squeezed - which turns a performance conversation into a scheduling fix.\n\nWhat makes SBI work is what it leaves out: verdicts on character. 'You're careless' invites a defence of the whole self; 'the consultation was two minutes' invites a fix. The same structure carries praise, and praise delivered with this precision ('the way you handled the overheated guest in the thermal suite - moving her to the relaxation room and bringing iced water before she asked - is exactly the standard') teaches the team what excellence looks like far faster than 'well done today'.\n\nTiming matters as much as structure: coach within a day, privately, in minutes. An observation saved up for a quarterly review has usually expired.",
        },
        {
          heading: "One-to-ones and the briefing: the two meetings that matter",
          body: "A spa team needs exactly two recurring conversations, done well, and most spas do neither.\n\nThe daily briefing (covered in module one) is operational and collective. The one-to-one is developmental and individual: 30 minutes, monthly, for every permanent team member, in a quiet room, with the manager mostly listening. A reliable agenda: how are you, genuinely; what's working and what's frustrating you operationally; your numbers this month (utilisation, retail, rebooking, guest mentions) discussed as information rather than judgement; what you want next - skills, treatments, progression - and one agreed action each.\n\nManagers cancel one-to-ones the moment the diary tightens, and the cancellation teaches the team precisely what their development is worth. Held consistently, the one-to-one is where you hear about the knee trouble before it becomes long-term absence, the wedding before it collides with peak season, the ambition before it becomes a resignation letter, and the friction between two therapists before it splits the team.\n\nIt is also where fairness becomes visible. Rota grievances, commission disputes and favouritism accusations shrink dramatically in teams where everyone has guaranteed, private access to the manager's attention on a fixed schedule - because the scarce resource being fought over is no longer scarce.",
        },
        {
          heading: "When coaching is not enough: fair formal process",
          body: "Some issues outgrow coaching, and the manager's job is to know which lane the issue is in, because each has a different fair response.\n\nCapability: the person is trying but cannot yet reach the standard - a therapist whose deep tissue work generates repeated guest comments. The fair response is a structured plan: the standard restated, specific training arranged, a review date set, and improvement genuinely expected before conclusions are drawn.\n\nConduct: the person can meet the standard but chooses not to - persistent lateness, ignoring the mobile phone policy, rudeness to a colleague. The fair response is a clear warning process with documented expectations.\n\nWellbeing: the performance dip has a cause outside work - health, caring pressures, finances. The fair response starts with support and adjustment, not sanction.\n\nMisdiagnosing the lane is where managers create grievances: treating a capability gap as misconduct is unjust; treating misconduct as a training need is naive and corrodes the rest of the team's standards.\n\nIn the UK, formal action should follow the ACAS Code of Practice and your company's own procedure: issues raised promptly, investigated properly, put to the person with the evidence, a right to be accompanied at formal meetings, decisions communicated in writing with a right of appeal. Document contemporaneously - a dated note of what was discussed, agreed and offered. Fair process is not bureaucracy protecting the employee from you; it is the discipline that protects your decisions when they are challenged, and it is what your best people watch to decide whether standards in this spa are real.",
        },
        {
          heading: "Retention is a commercial line, not an HR nicety",
          body: "Losing a good therapist is one of the most expensive events in a spa's year, and almost no spa costs it honestly. Walk through a realistic UK example.\n\nA senior therapist on £30,000 resigns. Direct replacement costs: advertising or platform fees, management time interviewing, and typically eight to twelve weeks to hire and notice-out. During those weeks her column - perhaps £3,500 of monthly treatment revenue - is covered partially by agency staff at a 25-40% premium, partially not at all. Add onboarding: four to six weeks before a new therapist delivers full productivity, brand training for the product house, and the quiet cost of regular guests who followed the departed therapist or drifted away during the gap. Sensibly totalled, replacing one senior therapist costs £6,000-£12,000 - a fifth to a third of her salary - before counting the cultural cost of a team watching the exit.\n\nThat number reframes retention spend. The £500 advanced course she asked for, the rota flexibility for her college day, the £1,500 pay adjustment that matches her market value - all are cheap against the replacement bill. The one-to-one is your early-warning system; the market data is your benchmark; and the honest question each month is: who here would be hardest to replace, and what have I done about it lately?",
        },
      ],
      visuals: [
        { kind: "flow", title: "SBI: the feedback structure that changes behaviour", steps: [
          "Situation: name the specific moment - 'this morning, with the 10 o'clock facial guest'",
          "Behaviour: describe what a camera would record - 'the consultation lasted under two minutes and skin concerns weren't asked about'",
          "Impact: state the consequence - 'she mentioned the treatment didn't address her congestion, and declined products'",
          "Then stop talking: ask for their view - half the time you learn something operational",
        ], caption: "What SBI leaves out is the point: no verdicts on character. 'You're careless' invites a defence of the whole self; 'the consultation was two minutes' invites a fix." },
        { kind: "table", title: "What losing a senior therapist on £30,000 really costs", headers: ["Cost element", "Typical scale"], rows: [
          ["Hiring: advertising, platform fees, management time interviewing", "Plus 8-12 weeks to hire and notice-out"],
          ["Covering her column during the vacancy", "Circa £3,500 of monthly treatment revenue, partly covered by agency at a 25-40% premium, partly lost"],
          ["Onboarding to full productivity", "4-6 weeks, plus brand training for the product house"],
          ["Guest attrition", "Regulars who follow the departed therapist or drift away during the gap"],
          ["Sensible total", "£6,000-£12,000 - a fifth to a third of salary, before the cultural cost"],
        ], caption: "This arithmetic reframes retention spend: the £500 course, the rota flexibility and the £1,500 pay adjustment are all cheap against the replacement bill." },
      ],
      scenario: "Your strongest receptionist, reliable for three years, has been late four times in a fortnight and yesterday snapped at a colleague within earshot of guests. Two therapists want you to 'do something'; your instinct is a formal warning.\n\nBefore you act, work through the lanes from this module. What would make this conduct, and what would make it wellbeing wearing conduct's clothes? What does three years of reliability tell you about the probability of each? Plan the opening two minutes of the conversation - and notice how differently it goes if you open with SBI and a question rather than a verdict.",
      activity: "Cost the resignation you can least afford: take your strongest team member and work through the replacement table honestly - hiring, coverage at agency premium, lost column revenue, onboarding weeks, guests at risk. Put a pound figure on it. Then list what that person has asked you for in the last six months, price the list, and compare the two numbers at your next one-to-one planning session.",
      knowledgeCheck: [
        { q: "A therapist four months in has retail at 3% against a team average of 11%, but consistently warm guest comments about her treatments. Colleagues say she 'just won't sell'. What is the most likely lane, and therefore the fair response?", options: ["Conduct - she is choosing not to meet the standard, so begin the warning process", "Capability and belief - watch her treatment closes before concluding anything, then coach the reframe", "Wellbeing - refer her to occupational health", "A hiring error - manage her out before probation ends"], answer: 1, why: "Warm guest feedback plus low retail points to a skill or belief gap, not defiance - and the case study confirms it: she thought recommending was pushy. A warning would have been unfair and useless; observation before diagnosis is the discipline." },
        { q: "Which of these openings is correctly structured SBI feedback?", options: ["'You've been careless with consultations lately and it's showing'", "'Everyone has noticed your attitude has slipped'", "'You're one of my best - but you need to try harder with retail'", "'This morning with the 10 o'clock guest, the consultation lasted under two minutes - at checkout she said the treatment missed her main concern'"], answer: 3, why: "It names the situation, describes what a camera would record, and states the impact - with no character verdict. The other three are adjectives and verdicts, which invite defence rather than a fix." },
        { q: "A senior therapist on £30,000 asks for a £1,500 adjustment to match her market value, and you know replacing her would cost £6,000-£12,000. The commercially literate response is to...", options: ["Treat the adjustment as cheap insurance against a replacement bill four to eight times larger, and evidence the market rate to justify it", "Refuse - pay rises outside the annual review set a precedent", "Offer a one-off bonus instead so the baseline is protected", "Wait to see whether she actually resigns before deciding"], answer: 0, why: "The replacement cost arithmetic settles the argument: £1,500 against £6,000-£12,000 plus the cultural cost of a team watching the exit. Waiting for the resignation letter means negotiating at the worst possible moment, if at all." },
      ],
      keyTerms: [
        { term: "SBI feedback", definition: "Situation-behaviour-impact: feedback that names the moment, describes observable behaviour without character judgement, and states the consequence." },
        { term: "Capability vs conduct", definition: "The distinction between someone unable to meet a standard despite effort (a training and support issue) and someone choosing not to meet it (a disciplinary issue)." },
        { term: "ACAS Code of Practice", definition: "The UK statutory guidance on fair disciplinary and grievance handling; tribunals can adjust awards where it is unreasonably ignored." },
        { term: "One-to-one", definition: "A fixed, private, monthly conversation per team member covering wellbeing, performance data and development - the manager's early-warning and retention system." },
        { term: "Replacement cost", definition: "The full cost of losing a team member: hiring, coverage premium, lost revenue during vacancy, onboarding time and lost guest relationships - typically 20-35% of salary for a senior therapist." },
      ],
      caseStudy: {
        title: "The therapist everyone had given up on",
        scenario: "A resort spa's newest therapist, four months in, has the lowest retail figures in the team (3% of treatment revenue against a team average of 11%), and two colleagues have told the manager she 'just won't sell'. The previous manager had labelled her a poor hire. Guest comments about her treatments, however, are consistently warm.",
        insight: "The manager watches two of her treatment closes before concluding anything. The observation shows the real gap: her treatments are excellent, but she closes with 'no pressure, it's all online if you want it' - she believes recommending products is pushy, and no one has ever shown her otherwise. That is capability (and belief), not conduct, so a warning would have been both unfair and useless. In a one-to-one, the manager reframes recommendation as clinical aftercare - the same duty as advising SPF after a facial peel - and they agree a two-week experiment: one genuine, specific product recommendation per guest, phrased as advice, results reviewed together. Her retail rises to 8% within a month and 12% by the following quarter, with no change in her guest scores. The manager also corrects the team narrative in the next briefing, praising the improvement specifically - because the label 'won't sell' was becoming a self-fulfilling verdict, and teams take their cues about fairness from what the manager tolerates being said about the weakest member.",
      },
      summary: "People leadership is clarity first, precise feedback second, fair process third and retention economics always: teams deliver standards they can see, from managers they experience as fair.",
      nextStep: "This week, deliver one piece of precise SBI praise to a team member - name the moment, the behaviour and the impact - and book the one-to-ones you have been postponing.",
    },
    {
      title: "Rotas, Capacity & Payroll Control",
      whyThisMatters: "The rota is the spa's biggest financial decision made weekly: payroll is the largest controllable cost on the P&L, and every scheduling choice either serves demand or pays for empty hands. A manager who can cost a rota, read utilisation by daypart and hold thresholds on overtime and agency is demonstrating exactly the commercial literacy that directors and general managers promote.",
      objectives: [
        "Forecast demand by daypart and build the rota from it",
        "Calculate capacity, sellable hours and utilisation for a real spa",
        "Manage payroll ratio, overtime and agency use against clear thresholds",
        "Build resilience into scheduling without inflating cost",
      ],
      sections: [
        {
          heading: "Demand first: the rota is a forecast, not a favour",
          body: "Most spa rotas are built backwards: start from who wants which shifts, then hope the bookings fit. The professional sequence is the reverse: forecast the demand, define the capacity and skill mix needed to serve it, then optimise for preferences inside that frame.\n\nSpa demand is more predictable than it feels. It moves with day of week (in most hotel spas, Friday to Sunday carries 55-65% of weekly treatment revenue), with daypart (late morning and mid-afternoon peaks; a trough at opening and after 17:00 in day-spa-dominated operations, the reverse in some resort settings), with hotel occupancy and guest mix (leisure occupancy converts to treatments at several times the rate of corporate), with school holidays, and with seasonal gifting cycles.\n\nBuild the forecast from your own booking history: last four weeks weighted for trend, same period last year for seasonality, occupancy forecast from the front office, and known events. Then translate it to therapist-hours by daypart, including skill mix - a Saturday of couples' rituals and advanced facials needs different hands than a Tuesday of express treatments.\n\nA rota built this way is also fairer, and you can say so: fairness is not everyone getting the shifts they prefer; it is the demand being covered so no one is abandoned on a slammed Saturday, and preferences being balanced transparently over the month rather than won by whoever complains loudest.",
        },
        {
          heading: "The capacity maths every manager should know by heart",
          body: "Take a spa with six treatment rooms open ten hours a day. Its theoretical capacity is 60 room-hours a day - the absolute ceiling on treatment revenue. No amount of marketing sells the 61st hour.\n\nNow the supply side. A therapist rostered for eight hours does not deliver eight treatment hours. Subtract a lunch break, two short breaks, setup and reset time between guests, and consultation minutes, and a well-run eight-hour shift yields roughly five and a half to six sellable hours. Rostering five therapists gives about 28-30 sellable hours against your 60 room-hour ceiling - which is fine on a Tuesday and a disaster on a Saturday.\n\nUtilisation is the bridge metric: booked treatment hours divided by sellable therapist hours. If today's five therapists offer 28 sellable hours and 19 are booked, utilisation is 68%. Across the industry, sustained utilisation of 65-80% is healthy; below 55% you are paying for empty hands (a scheduling or demand problem); above 85% for long periods you are running hot - no room for walk-ins or recovery, and a burnout risk.\n\nThe management skill is reading utilisation by daypart, not just by day. A day that averages 70% often hides a 95% morning and a 40% late afternoon - and the response to each is different: protect and price the morning; fill the afternoon with targeted offers, maintenance time or training rather than discounting the whole day.",
        },
        {
          heading: "Payroll ratio: the number your P&L is quietly judged on",
          body: "Payroll is the largest controllable cost in every spa, and the ratio your director watches is payroll as a percentage of revenue. Across hotel spas, total spa payroll (including on-costs) commonly runs at 40-55% of revenue; day spas often sit slightly lower. The exact benchmark matters less than your own trend and your explanation of it.\n\nWhat moves the ratio is rarely headline salaries; it is the quiet leaks. Overtime that has become routine rather than exceptional. Agency cover booked at a 25-40% premium to fill holes that better rota planning would have prevented. Full staffing maintained through dayparts that history says are empty. Commission structures that pay out on revenue the spa would have earned anyway.\n\nManage it with thresholds, not vibes: know your budgeted ratio; review overtime and agency as separate lines weekly (they are the smoke alarms); and cost every rota before publishing it - hours times loaded rates takes minutes in a spreadsheet and turns 'this rota feels heavy' into 'this rota is £640 over budget, and here is where'.\n\nOne caution in the other direction: the cheapest rota is rarely the most profitable one. Cutting Saturday to the bone saves £300 of payroll and loses more than that in unserved demand, declined walk-ins and rushed treatments that never convert to retail or rebooking. The target is fit, not thinness - capacity shaped to demand.",
        },
        {
          heading: "Absence, resilience and the agency question",
          body: "A rota that only works when everyone turns up is not a plan; it is a bet. Spas run on physically demanding work, and sickness rates reflect it - massage-heavy columns carry genuine repetitive strain risk, which is a scheduling issue as much as a welfare one: cap consecutive deep-tissue hours, vary treatment mix across a shift, and treat a therapist's sore wrists in week two as an operational warning, not a complaint.\n\nBuild resilience deliberately: know your realistic absence rate (hospitality commonly runs 3-5%) and plan cover for it rather than being surprised weekly; cross-train so more than one person can deliver your top ten treatments; keep a bank of vetted casual therapists who know your standards before you need them at 08:45; and write the sickness-cover sequence as an SOP so any supervisor can run it.\n\nAgency and platform cover deserves a policy, not a habit. Used well, it is a resilience tool: genuine peaks, unexpected absence, maternity gaps. Used badly, it becomes structural - a standing 15-20% of treatment hours at premium rates covering vacancies nobody is filling, with guests experiencing therapists who do not know the products or the building. The discipline is a monthly review of agency spend with one question: how much of this covered genuine variance, and how much covered a permanent vacancy or a planning failure? The first is the cost of resilience. The second is the most expensive way to staff a spa yet invented, and it should convert into recruitment urgency, not next month's agency booking.",
        },
      ],
      visuals: [
        { kind: "table", title: "The capacity maths at a glance", headers: ["Measure", "Working", "Result"], rows: [
          ["Theoretical room capacity", "6 rooms × 10 open hours", "60 room-hours a day - the ceiling"],
          ["Sellable hours per 8-hour shift", "Minus breaks, setup, reset and consultation time", "5.5-6 hours"],
          ["Five therapists rostered", "5 × ~5.75 sellable hours", "28-30 sellable hours"],
          ["Utilisation today", "19 booked hours ÷ 28 sellable hours", "68% - inside the healthy band"],
        ], caption: "Fine on a Tuesday, a disaster on a Saturday: the same rostering against the same 60 room-hours reads completely differently once demand is in the picture." },
        { kind: "table", title: "The thresholds a manager holds", headers: ["Signal", "Healthy range", "What a breach means"], rows: [
          ["Utilisation (sustained)", "65-80% of sellable hours", "Below 55%: paying for empty hands. Above 85%: running hot - no recovery slack, burnout risk"],
          ["Payroll ratio (incl. on-costs)", "Commonly 40-55% of revenue in hotel spas", "Trend matters more than the point value; explain every movement"],
          ["Agency premium", "25-40% above payroll rates", "Fine for genuine variance; ruinous as a standing substitute for recruitment"],
          ["Absence rate", "Hospitality commonly 3-5%", "Plan cover for it; do not be surprised by it weekly"],
        ], caption: "Review overtime and agency as separate lines weekly - they are the smoke alarms of the payroll ratio." },
      ],
      scenario: "Your GM emails: 'Payroll ratio must come down three points next quarter.' Your instinct is to trim Saturday, because that is where the most hours are.\n\nBefore replying, think it through with this module's tools. Where would a cut actually cost more than it saves, and where is the ratio genuinely leaking - overtime that has become routine, agency covering a vacancy nobody is filling, full staffing through dayparts your history says are empty? Draft the three-line reply that offers the GM a costed alternative rather than a thinner Saturday.",
      activity: "Cost your own current rota before the next one is published: hours multiplied by loaded rates for every shift, totalled by day. Set the result beside four weeks of utilisation by daypart. Mark every daypart where you are paying for capacity that history says will not sell, and every daypart where demand exceeds what you have rostered. Move hours before you cut them.",
      knowledgeCheck: [
        { q: "Five therapists offer 28 sellable hours today and 19 hours are booked. What is utilisation, and how should you read it?", options: ["61% - below the healthy band, cut a shift", "73% - running slightly hot", "68% - healthy overall, but check the daypart split before concluding anything", "59% - paying for empty hands"], answer: 2, why: "19 ÷ 28 = 68%, inside the 65-80% band - but a day averaging 68% often hides a 95% morning and a 40% late afternoon, and the response to each is different. Averages are where scheduling mistakes hide." },
        { q: "Payroll is 4 points over budget, Saturday utilisation is 96% with walk-ins refused, and Tuesday sits at 41%. The first management move is to...", options: ["Rebuild the rota from the demand curve - move hours from Tuesday to Saturday rather than adding or cutting headcount", "Add a sixth therapist to Saturday and accept the payroll cost", "Cut a Tuesday shift and bank the saving", "Discount Tuesdays to lift demand toward the staffing"], answer: 0, why: "The spa is overstaffed into its quietest day and understaffed into its best one - the case study's exact pattern. Moving hours serves refused Saturday demand and trims Tuesday waste in one decision, before any spend or discount is considered." },
        { q: "Agency staff have covered 15-20% of treatment hours for four consecutive months. What has this become, and what should it trigger?", options: ["A sensible flexibility buffer - continue while it works", "A welfare issue - agency staff need better induction", "Proof the rota is under-resourced - add permanent hours across the week", "Structural agency use - the most expensive staffing model available, and it should convert into recruitment urgency"], answer: 3, why: "Agency at a 25-40% premium is a resilience tool for genuine variance. Standing at 15-20% of hours, it is a permanent vacancy being paid for at premium rates by guests who meet therapists who do not know the products or the building." },
      ],
      keyTerms: [
        { term: "Sellable hours", definition: "The treatment hours a rostered therapist can actually deliver after breaks, setup, reset and consultation time - typically 5.5-6 hours from an 8-hour shift." },
        { term: "Utilisation", definition: "Booked treatment hours divided by sellable therapist hours; sustained 65-80% is healthy, below 55% signals waste, above 85% signals strain." },
        { term: "Payroll ratio", definition: "Total spa payroll including on-costs as a percentage of spa revenue; commonly 40-55% in hotel spas, and the trend matters more than the point value." },
        { term: "Daypart", definition: "A distinct segment of the trading day (early morning, late morning, afternoon, evening) analysed separately for demand, utilisation and pricing decisions." },
        { term: "Structural agency use", definition: "Agency or platform cover that has stopped being a response to variance and become a standing substitute for recruitment - the most expensive staffing model available." },
      ],
      caseStudy: {
        title: "The rota that felt fair and lost £2,000 a week",
        scenario: "A city hotel spa runs a fixed rota agreed years ago: the same five therapists Monday to Friday, four at weekends, because 'weekends should be lighter for the senior team'. The manager inherits it along with two complaints: guests cannot get Saturday bookings, and payroll is 4 points over budget. Saturday utilisation is 96% with walk-ins turned away; Tuesday utilisation is 41%.",
        insight: "The numbers tell the story the rota's history obscures: the spa is overstaffed into a quiet Tuesday and understaffed into its single highest-demand day. The manager rebuilds from the demand curve: Saturday moves to six therapists (opening the sixth room all day), Tuesday drops to three with the multi-purpose room dark until 12:00, and the displaced hours move to Friday afternoon and Sunday morning where booking-refusal data shows unmet demand. Two senior therapists object to losing their fixed Tuesday. The manager holds the line on demand coverage but negotiates transparently on preferences: alternating Saturdays off, published eight weeks ahead. Result within a quarter: Saturday revenue up around £1,400 a week from served demand, Tuesday payroll down £430 a week with utilisation at a healthy 63%, agency spend near zero, and - the part that surprised the team - fewer rota grievances than under the 'fair' fixed rota, because the logic was now visible and applied to everyone equally.",
      },
      summary: "The rota is the spa's biggest financial decision made weekly: forecast demand, do the capacity maths, watch utilisation by daypart, hold thresholds on overtime and agency, and let fairness mean transparent logic rather than frozen habit.",
      nextStep: "Before your next rota is published, cost it in a spreadsheet - hours times loaded rates - and check it against four weeks of utilisation by daypart.",
    },
    {
      title: "Guest Journey, Standards & Service Recovery",
      whyThisMatters: "Reputation in luxury hospitality is built at the edges of the experience - arrivals, waits and departures - and destroyed by how failures are handled, not by whether they happen. A manager who can turn standards into auditable habits and empower recovery to run at the speed of the complaint protects review scores, rate premium and repeat revenue in one discipline. It is also the skill senior leaders most often test when deciding who is ready for a bigger operation.",
      objectives: [
        "Map the full guest journey and identify its moments of truth",
        "Convert luxury standards into auditable operating habits",
        "Run service recovery that restores trust and captures the learning",
        "Use complaint and feedback data as an improvement system",
      ],
      sections: [
        {
          heading: "The journey is the product",
          body: "Guests do not buy treatments; they buy an arc of experience that begins at the booking enquiry and ends with how they feel walking to the car park. The treatment - the part the spa industry obsesses over - occupies perhaps 60 of the 150 minutes a guest spends with you, and it is almost never where the experience fails. It fails at a phone that rang eleven times, a receptionist who could not find the booking, a changing room with someone else's towel on the bench, a 12-minute wait in a robe with no explanation, a checkout where the only conversation was about payment.\n\nMap your journey honestly: enquiry and booking, pre-arrival communication, arrival and welcome, orientation, changing, thermal or waiting time, consultation, treatment, close and aftercare advice, retail conversation, checkout, departure. For each stage, two questions: what does the guest see, hear, smell and wait for here, and who owns it?\n\nBehavioural research gives managers one enormously useful shortcut: the peak-end rule. People's memory of an experience is dominated by its most intense moment and its ending, not its average. Operationally, this means the goodbye is disproportionately valuable - a warm, named farewell with a small final gesture colours the memory of the entire visit - and a weak checkout can undo ninety excellent minutes. Spend your standards effort accordingly: arrival and departure first, the middle second.",
        },
        {
          heading: "From standards on paper to habits on the floor",
          body: "Luxury benchmarks - Forbes Travel Guide standards, LQA audits, brand SOPs - can feel like paperwork until you understand what they actually encode: the removal of variance. A five-star operation is not one where magical things happen; it is one where the welcome, the room, the temperature, the timing and the goodbye are the same on a wet Tuesday with a therapist who had a bad night as on launch day. Consistency, not flourish, is the luxury.\n\nStandards become habits through short, meaningful checks, not thick binders. Three that work: an opening audit (ten minutes, checklist of what the first guest will encounter - scent, music level, temperature, water and towel presentation, room readiness); a mid-shift spot check at the transition points; and a closing audit that doubles as setup for tomorrow. Rotate who conducts them - a therapist auditing the journey sees it differently, and ownership spreads.\n\nTwo disciplines keep the system honest. First, audit what the guest experiences, not what the team did ('does the relaxation room smell right?' rather than 'was the diffuser refilled?'). Second, close the loop visibly: an audit that finds the same fault three weeks running and changes nothing teaches the team that standards are theatre. Every red item gets an owner and a date, and recurring reds get the module-one treatment: what system keeps allowing this?",
        },
        {
          heading: "Service recovery: the moment trust is actually built",
          body: "Things will go wrong in a good spa - a double booking, a cold room, a therapist off sick with a full column. What separates operations is not the absence of failure but the speed and grace of recovery. Service research even documents a recovery paradox: a guest whose problem is handled superbly can end up more loyal than one who never had a problem - not a reason to engineer failures, but proof of how much a good recovery is worth.\n\nA reliable recovery sequence: listen fully without interrupting or explaining; acknowledge the specific impact ('you booked this for your anniversary and the start was rushed - I understand why that stung'); apologise plainly, without 'if' or 'but'; resolve concretely, now, with something within your gift; and follow up - the message the next day asking whether the resolution worked is the step almost nobody takes and the one guests retell.\n\nEmpowerment is the operational key. Define what the team may offer without asking: for instance, any therapist or receptionist may extend a treatment, waive an upgrade charge or gift a take-home product up to a stated value; the duty manager may comp a treatment; only the spa manager refunds packages. A guest kept waiting while three people find someone with authority experiences the failure twice.\n\nCompensation is one tool, not the definition of recovery. Most guests want three things in order: to be heard, to be taken seriously, and for it to be fixed. Money mishandled ('we'll knock ten per cent off') can even cheapen a complaint that was really about care.",
        },
        {
          heading: "Complaints are data wearing an unpleasant disguise",
          body: "A single complaint is an event; logged complaints are an operating instrument. Keep the log simple - date, stage of journey, root cause category (booking error, timing, temperature, treatment quality, communication, billing), resolution, cost of gesture, and whether the guest was recovered - and review it monthly beside your other KPIs.\n\nThe patterns are where the money is. Complaints clustering at checkout point at a systems or training gap, not at unlucky guests. Three temperature complaints in the same treatment room are a £150 engineering fix disguised as three £40 gestures. A rise in 'rushed treatment' comments tracks almost perfectly with utilisation running above 85% - which turns a service problem into the scheduling conversation from the previous module.\n\nExtend the same discipline to the feedback you never receive directly: review-platform comments, guest-satisfaction surveys, and the quiet signal of regulars who stop returning. A monthly ten-minute scan of online reviews with the same root-cause categories keeps the operation honest about the gap between the spa you run and the spa guests describe.\n\nFinally, feed the wins back. A save worth retelling - read it out at the briefing. A pattern fixed - tell the team what changed because of their logging. A recovery culture survives only if the team sees complaints treated as fuel for improvement rather than as evidence-gathering for blame.",
        },
      ],
      visuals: [
        { kind: "flow", title: "The recovery sequence", steps: [
          "Listen fully - no interrupting, no explaining",
          "Acknowledge the specific impact - 'you booked this for your anniversary and the start was rushed'",
          "Apologise plainly - no 'if', no 'but'",
          "Resolve concretely, now, with something within your gift",
          "Follow up the next day - the step almost nobody takes and the one guests retell",
        ], caption: "Most guests want three things in order: to be heard, to be taken seriously, and for it to be fixed. Compensation is one tool, not the definition of recovery." },
        { kind: "table", title: "Empowerment thresholds: who may offer what, without asking", headers: ["Role", "May offer immediately"], rows: [
          ["Therapist or receptionist", "Extend a treatment, waive an upgrade charge, gift a take-home product up to a stated value"],
          ["Duty manager", "Comp a treatment"],
          ["Spa manager only", "Refund packages"],
        ], caption: "A guest kept waiting while three people find someone with authority experiences the failure twice. Set the thresholds in writing before they are needed." },
      ],
      scenario: "Reviewing the month, you find four 'rushed treatment' comments - all midweek, all afternoons - and your daypart data shows utilisation running at 88-92% in exactly those slots. The therapists involved are among your best.\n\nThink through what is actually failing here. Is this a coaching conversation, a diary problem or a pricing signal? What would a gesture to each guest fix, and what would it leave untouched? Decide what you would change this week, and which module of this programme the real fix lives in.",
      activity: "Walk your own guest journey end to end as a guest would: book by phone, arrive, change, wait, and check out. Note every wait, every handover and everything you see, hear and smell at each stage. Then write the empowerment thresholds for your team - what each role may offer in recovery without asking - and brief them at the next huddle.",
      knowledgeCheck: [
        { q: "The peak-end rule tells you that memory of an experience is dominated by its most intense moment and its ending. Where should a manager spend standards effort first?", options: ["Evenly across every stage of the journey", "Arrival and departure - a weak checkout can undo ninety excellent minutes", "The treatment itself, since it is the product", "The thermal areas, where guests spend most time"], answer: 1, why: "The treatment is almost never where the experience fails, and the goodbye colours the memory of the whole visit. Standards effort goes to the beginnings and endings first, the middle second." },
        { q: "In the anniversary case, a £70 gesture kept a £340 booking and won a rebooking - yet the module treats the episode as a partial failure. Why?", options: ["The gesture was too generous for the error", "The supervisor exceeded her empowerment threshold", "The couple should have been refunded in full", "It was the third occurrence of the same booking error in two months, and the first two were never logged - the gesture fixed the couple, only the system change fixed the spa"], answer: 3, why: "Recovery without root-cause capture buys the same failure again at £70 a time. The phone-booking rule and the error log are what stopped occurrence four - complaints are data wearing an unpleasant disguise." },
        { q: "Three temperature complaints arrive from the same treatment room in a month, each settled with a £40 gesture. The correct management reading is...", options: ["A £150 engineering fix is disguised as £120 of gestures - the pattern, not the individual complaints, is the real finding", "The therapists in that room need coaching on managing expectations", "Guests are increasingly sensitive and thresholds should be reviewed", "The gestures are working, since each guest left satisfied"], answer: 0, why: "Logged complaints reviewed monthly turn events into an operating instrument. Clustering by room and root cause reveals the cheap permanent fix hiding behind repeated gestures." },
      ],
      keyTerms: [
        { term: "Moment of truth", definition: "Any touchpoint where the guest forms or revises their judgement of the operation - concentrated at arrival, waits, and departure rather than mid-treatment." },
        { term: "Peak-end rule", definition: "The finding that memory of an experience is dominated by its most intense moment and its ending, making the departure disproportionately valuable to manage." },
        { term: "Service recovery paradox", definition: "The documented effect where a guest whose problem is handled excellently can become more loyal than one who experienced no problem at all." },
        { term: "Empowerment threshold", definition: "The pre-agreed value and actions each role may offer in recovery without seeking authority, so resolution happens at the speed of the complaint." },
        { term: "Root cause category", definition: "The classification of a complaint by underlying driver (booking, timing, temperature, quality, communication, billing) so patterns become visible and fixable." },
      ],
      caseStudy: {
        title: "The anniversary couple and the twelve-minute wait",
        scenario: "A couple arrives for a £340 anniversary ritual. Reception cannot find the booking - it was taken by phone and never entered. The next couples' slot is in 90 minutes. The wife is visibly upset; the husband is asking for a refund of the deposit and naming a review site. A junior receptionist, alone at the desk, freezes and calls the manager - who is 25 minutes away.",
        insight: "The recovery succeeds and fails in the same afternoon. The duty supervisor, empowered under the spa's thresholds, acts within four minutes: acknowledges the error without hedging ('we took the booking and we lost it - that is entirely ours'), offers the couple the thermal suite and a champagne lunch on the terrace while the team re-engineers the diary, and personally confirms the ritual will run at 15:30 with the two senior therapists and a room upgrade. The couple stays, the treatment lands, and the follow-up call the next morning finds them delighted - they later book for their following anniversary: the recovery paradox in action, at a cost of roughly £70. The failure is quieter: the booking loss came from phone bookings being scribbled on paper during busy periods, and this was its third occurrence in two months - the first two 'resolved' with gestures and never logged. The manager institutes a no-exceptions rule that phone bookings are entered into the system during the call, and adds booking-error tracking to the monthly log. The gesture fixed the couple; only the system change fixed the spa.",
      },
      summary: "The journey, not the treatment, is the product: manage its beginnings and endings hardest, turn standards into short auditable habits, empower recovery to run at the speed of the complaint, and mine every failure for the system change hiding inside it.",
      nextStep: "This week, start a simple complaint log - date, journey stage, root cause, resolution, cost - and put its first monthly review in the diary.",
    },
    {
      title: "Revenue, Retail & Treatment Profitability",
      whyThisMatters: "A busy spa and a profitable spa are not the same building, and the difference is whether the manager can decompose revenue into its drivers and cost the menu honestly. The ability to say 'utilisation held but ATV fell £8, so this is a mix problem, not a demand problem' - and to prove it - is what separates managers who receive targets from managers who are trusted to set them.",
      objectives: [
        "Break spa revenue into its drivers and diagnose which one is underperforming",
        "Calculate treatment contribution per room-hour and use it in menu decisions",
        "Manage retail and rebooking as coached behaviours with honest benchmarks",
        "Improve commercial results without corroding guest trust",
      ],
      sections: [
        {
          heading: "Revenue has an anatomy: learn to read it",
          body: "'Revenue is down' is not a diagnosis; it is a symptom with five possible diseases. Treatment revenue is capacity × utilisation × average treatment value (ATV), and the wider spa adds retail, rebooking and memberships on top. Each driver fails differently and is fixed differently, so the first management act is decomposition.\n\nWorked example: a spa with 60 room-hours a day at 70% utilisation and a £95 ATV takes roughly £3,990 a day. Revenue falls 8%. Before any initiative, split it: if utilisation held but ATV fell to £87, guests are trading down or the booking mix has shifted to shorter treatments - a menu, pricing or upgrade-offer question. If ATV held but utilisation fell to 64%, demand is softening or availability is mismatched to when guests want to book - a marketing, scheduling or daypart question. If both held and the loss is in retail, it is a coaching question. Three different problems, three different responses - and the wrong response to the right symptom (discounting when the issue was Sunday staffing) costs twice.\n\nA useful summary metric for the whole engine is revenue per available treatment hour - total treatment revenue divided by total room-hours open. It rolls utilisation and ATV into one number a director instantly understands, and tracked weekly by daypart it shows precisely where the spa earns and where it idles.",
        },
        {
          heading: "Contribution per room-hour: the menu's honest scoreboard",
          body: "Price is not profitability, and the menu decisions that look obvious by price often invert when you cost them properly. The tool is contribution per room-hour: selling price, minus direct product cost, divided by the total room time consumed (treatment plus reset).\n\nCompare two treatments honestly. A 60-minute signature massage at £120 uses perhaps £4 of oils and 70 minutes of room time including reset: contribution roughly £116, or about £99 per room-hour. A 90-minute luxury ritual at £150 uses £22 of premium product and 105 minutes of room time: contribution £128, or about £73 per room-hour. The ritual looks superior on the price list and is a quarter less productive per hour of your scarcest asset. That does not mean delete it - it may anchor the brand, delight VIPs and drive retail - but it means know the trade-off, schedule it into softer dayparts where the room would otherwise idle, and never discount it reflexively.\n\nRun this maths across the whole menu once a quarter and treatments sort themselves into four families: stars (high demand, high contribution - protect and feature), workhorses (high demand, modest contribution - engineer costs or nudge price), sleepers (low demand, high contribution - market them), and passengers (low demand, low contribution - candidates for removal unless they serve a strategic purpose you can name). Menus accumulate passengers over the years the way wardrobes accumulate clothes; the quarterly review is how you keep the rooms working for the business.",
        },
        {
          heading: "Retail: aftercare with a till receipt",
          body: "Retail is the most emotionally loaded number in spa management, because therapists hear 'sell more' as a request to betray the guest. The reframe that actually works is clinical: a facial without home-care advice is an unfinished treatment, exactly as a physiotherapy session without exercises is unfinished. The recommendation is aftercare; the purchase is the guest's choice; the therapist's duty is that the advice was specific, genuine and theirs.\n\nBenchmarks keep ambition honest: across the industry, retail commonly runs at 8-15% of treatment revenue in hotel spas, with strong operations above 20% and day spas often higher still. Track it per therapist, monthly, as a coaching datum rather than a league table - the spread inside a team is usually 3% to 25%, and the gap is almost never willingness; it is technique and belief, which module case studies elsewhere in this programme address.\n\nWhat managers control: the prescription habit (the recommendation begins during the treatment - 'I'm using the recovery balm on your shoulders because...' - so the close is a reminder, not an ambush); product knowledge (a therapist will not recommend what she cannot explain; every new line needs training before it needs shelf space); linkage of the retail conversation to the consultation's stated concern; and the environment - a retail area guests pass at checkout, tester access, and price points that include an entry option.\n\nWhat managers should not do: per-transaction pressure, public shaming by numbers, or commission structures so aggressive they leak into the treatment room. Guests smell it, reviews say it, and the lifetime value destroyed exceeds the month's retail gained.",
        },
        {
          heading: "Rebooking and repeat revenue: the cheapest sale in the building",
          body: "The most expensive guest to serve is a new one - acquired through marketing spend, unknown to the team, statistically least likely to return. The cheapest revenue in the spa is the next booking of the guest standing at your checkout, glowing, wallet already open. Yet most spas let her leave with a loyalty card and a hope.\n\nRebooking is a behaviour, coached like any other: the therapist closes the treatment with a professional next step ('for what we worked on today, I'd want to see that shoulder again in three to four weeks - shall I have reception hold a slot with me?'), and reception makes it effortless. Track rebooking rate - departing guests who leave with a future booking - per therapist and monthly; moving it from 10% to 25% in a spa doing 600 treatments a month adds roughly 90 pre-sold visits a quarter before any marketing spend.\n\nMemberships and series (a course of six facials, a monthly massage membership) industrialise the same logic: predictable revenue, higher visit frequency, and guests whose relationship is with the spa rather than a discount site. Price them so the benefit is real but the economics hold - a membership that simply discounts peak-time visits the guest would have bought anyway is generosity, not strategy; one that shifts visits into soft dayparts and adds retail attachment is a commercial engine.\n\nThe compounding effect is what makes this module matter: a guest who rebooks, joins the membership and takes home products is worth several times her first visit - and every step of that ladder was built by behaviours the manager coaches, measures and celebrates.",
        },
      ],
      visuals: [
        { kind: "table", title: "Contribution per room-hour: two treatments compared honestly", headers: ["", "60-min signature massage", "90-min luxury ritual"], rows: [
          ["Selling price", "£120", "£150"],
          ["Direct product cost", "£4", "£22"],
          ["Room time inc. reset", "70 minutes", "105 minutes"],
          ["Contribution", "£116", "£128"],
          ["Contribution per room-hour", "~£99", "~£73"],
        ], caption: "The ritual looks superior on the price list and is a quarter less productive per hour of the spa's scarcest asset. Know the trade-off; schedule the ritual into softer dayparts; never discount it reflexively." },
        { kind: "flow", title: "The revenue decomposition: three diseases, three cures", steps: [
          "Baseline: 60 room-hours × 70% utilisation × £95 ATV ≈ £3,990 a day - then revenue falls 8%",
          "Utilisation held, ATV fell to £87? Guests trading down or mix shifting shorter - a menu, pricing or upgrade-offer question",
          "ATV held, utilisation fell to 64%? Demand softening or availability mismatched - a marketing, scheduling or daypart question",
          "Both held, retail fell? A coaching question",
        ], caption: "The wrong response to the right symptom - discounting when the issue was Sunday staffing - costs twice." },
      ],
      scenario: "Your director suggests discounting the 90-minute ritual by 20% to fill quiet Tuesdays: 'it's our most expensive treatment, so the discount will feel generous.'\n\nBefore agreeing, run the maths from this module. At £150 with £22 of product and 105 minutes of room time, what does the ritual contribute per room-hour already - and what does a £30 discount do to that figure? What would the same Tuesday hour earn if a value-added facial filled it instead? Draft the alternative you would put to the director, with the numbers attached.",
      activity: "Run contribution per room-hour across your top five treatments this week: selling price, minus direct product cost, divided by room time including reset. Rank them, then compare the ranking with what your team is currently trained to recommend and what your marketing features at peak times. Bring the mismatches to your next management meeting.",
      knowledgeCheck: [
        { q: "A 90-minute ritual sells at £150, uses £22 of product and occupies 105 minutes of room time including reset. Its contribution per room-hour is roughly...", options: ["£85", "£73", "£128", "£64"], answer: 1, why: "£150 - £22 = £128 contribution, divided by 1.75 room-hours = about £73 per room-hour - a quarter below the £99 the signature massage earns. Price is not profitability; room time is the divisor that tells the truth." },
        { q: "Revenue is down 8%. Utilisation has held at 70%, but ATV has fallen from £95 to £87. Where does the diagnosis point?", options: ["Demand is softening - increase marketing spend", "The team needs a retail push", "Guests are trading down or the booking mix has shifted shorter - a menu, pricing or upgrade-offer question", "Rooms are out of service - check maintenance"], answer: 2, why: "Volume held; value per treatment fell. That is a rate and mix story, and treating it as a demand problem - with a promotion, say - would cut ATV further while solving nothing." },
        { q: "A spa delivering 600 treatments a month lifts its rebooking rate from 10% to 25%. What has it gained?", options: ["Roughly 90 additional pre-sold visits a quarter, before any marketing spend", "A 15% rise in ATV", "Roughly 15 extra bookings a month", "Nothing measurable - rebooking only shifts existing demand earlier"], answer: 0, why: "As the lesson works it, that 15-point uplift is worth roughly 90 pre-sold visits a quarter before a penny of marketing spend - the cheapest revenue in the building, coming from guests already at the checkout, glowing, with their wallets open." },
      ],
      keyTerms: [
        { term: "Average treatment value (ATV)", definition: "Treatment revenue divided by treatments delivered; falls when guests trade down or booking mix shortens, independent of how busy the spa is." },
        { term: "Contribution per room-hour", definition: "Selling price minus direct product cost, divided by total room time consumed including reset - the honest comparison metric across menu items." },
        { term: "Revenue per available treatment hour", definition: "Total treatment revenue divided by total room-hours open; combines utilisation and ATV into one daypart-trackable performance number." },
        { term: "Retail ratio", definition: "Retail sales as a percentage of treatment revenue; commonly 8-15% in hotel spas, above 20% in strong operations, coached per therapist rather than demanded per transaction." },
        { term: "Rebooking rate", definition: "The share of departing guests who leave with a future booking - the cheapest revenue available and a direct measure of treatment-close quality." },
      ],
      caseStudy: {
        title: "The menu that was busiest at a loss",
        scenario: "A destination spa's best-seller is a heavily marketed 105-minute 'Journey' ritual at £165, filling 30% of all room-hours. The spa is busy - utilisation 78% - yet monthly contribution is flat against a sister property with lower occupancy. The director asks the new manager why busy is not translating into profit.",
        insight: "The manager runs contribution per room-hour across the menu and finds the answer in twenty minutes of spreadsheet work: the Journey uses £31 of premium products and 120 minutes of room time including its elaborate reset, contributing about £67 per room-hour - while the 60-minute results facial at £110 contributes about £96 and the signature massage £99. The best-seller is occupying nearly a third of the spa's scarcest asset at the menu's weakest rate, and its marketing prominence is actively steering demand toward it during peak dayparts, displacing higher-contribution bookings. The response is engineering, not amputation: the Journey stays (it defines the brand and drives the spa's best retail attachment), but peak-daypart featuring shifts to the facial and massage, the Journey is repositioned as the hero of midweek and late-afternoon slots where rooms ran at 45%, its product cost is trimmed £9 by re-specifying two components the blind tests showed guests never noticed, and its price moves to £175 at the next menu print. Net effect after one quarter: identical utilisation, treatment revenue up 6%, contribution up 11% - from moving demand between dayparts and knowing, for the first time, what each hour of room time actually earned.",
      },
      summary: "Commercial management is decomposition: revenue into drivers, the menu into contribution per room-hour, retail and rebooking into coachable behaviours - so that 'busy' and 'profitable' stop being strangers.",
      nextStep: "This week, calculate contribution per room-hour for your three best-selling treatments and check whether your peak-time featuring matches what the numbers say.",
    },
    {
      title: "Manager Scorecards, SOPs & 30-Day Action Plan",
      whyThisMatters: "Everything else in this programme fails without machinery: standards drift, numbers go unread and good intentions dissolve into the seven-day operation. The scorecard, the SOP library and the 30-day method are what turn management judgement into an operating system - and a manager who arrives in a new role with this machinery is trusted with autonomy months before one who manages from memory.",
      objectives: [
        "Build a weekly and monthly scorecard with leading and lagging indicators",
        "Read variances and convert them into owned actions",
        "Write SOPs a trained team member can follow under pressure",
        "Construct a credible first-30-days plan for a new management role",
      ],
      sections: [
        {
          heading: "The scorecard: one page that runs the spa",
          body: "A manager who tracks everything manages nothing. The working instrument is one page, reviewed weekly, combining four families of measures.\n\nCommercial: revenue against target, utilisation by daypart, ATV, retail ratio, rebooking rate. Guest: satisfaction scores, complaints by root cause, online review movement. People: sickness, overtime hours, agency spend, one-to-ones held versus due, open vacancies. Operational: audit results, maintenance faults open, incidents.\n\nTwo design principles separate a scorecard from a spreadsheet graveyard. First, mix lagging indicators (results - last week's revenue, last month's reviews) with leading ones (predictors - forward bookings for the next 14 days, rebooking rate, staff vacancies). Lagging numbers tell you what happened; leading numbers give you time to act. Forward bookings looking 15% soft for a fortnight out is a problem you can still solve; the same news in the month-end pack is archaeology.\n\nSecond, every number needs a comparator - target, last period, same period last year - because a naked number ('retail was £4,200') carries no meaning. And every red needs a name and a date attached in the same meeting it is spotted: not 'retail is down, we should look into it', but 'retail is 3 points under - Sara is pulling the per-therapist split by Thursday and we decide Friday'. A scorecard that produces no owned actions is a weather report; the entire point is that it produces decisions.",
        },
        {
          heading: "Reading variance like a manager, not a spectator",
          body: "Numbers move constantly; the skill is knowing which movements deserve a response. Three disciplines keep you honest.\n\nDistinguish signal from noise. One soft Tuesday is noise. Three consecutive soft Tuesdays are a trend. Set rough thresholds - within 5% of plan is watch-only, 5-10% needs an explanation, beyond 10% needs an action - so your energy follows materiality rather than mood.\n\nAsk 'what is the driver?' before 'what is the fix?'. The decomposition habit from the revenue module applies to every line: payroll over budget splits into rate, hours, overtime or agency; complaint spikes split by journey stage; utilisation drops split by daypart and day of week. A variance explained by its driver almost suggests its own action; a variance answered with a generic initiative ('let's run a promotion') is usually money spent on a misdiagnosis.\n\nAnd watch for favourable variances that lie. Revenue 6% up with utilisation flat means price mix moved - fine. Revenue up with retail collapsing may mean the team is stretched past the point of finishing treatments properly. Payroll 8% under budget looks like discipline until you notice it is three unfilled vacancies burning the remaining team down. The scorecard is one system: every number is a sentence in the same story, and the manager's job is to read the story, not the words.",
        },
        {
          heading: "SOPs: judgement, bottled",
          body: "A standard operating procedure is not bureaucracy; it is the manager's judgement made available at moments the manager is absent - which is most moments. The test of a good SOP is brutal and practical: could a trained team member follow it correctly under pressure, alone, on a Saturday?\n\nStructure every SOP the same way, one page wherever possible: purpose (one sentence on why this exists), scope (when it applies), owner (who maintains it), the steps in order, safety or legal points highlighted, exceptions and escalation (what to do when the SOP does not fit, and who to call), records (what gets logged where), and a review date.\n\nWrite SOPs for the moments that are high-stakes, recurring, or done differently by different people: opening and closing, sickness cover, booking errors, treatment-room faults, guest accidents and first aid, chemical handling under COSHH, refunds and gestures, lost property, VIP arrivals, fire and evacuation specifics for the spa's wet and warm areas. Ten to fifteen documents cover a typical spa; more than that and the folder becomes furniture.\n\nKeep them alive: an SOP contradicted by three months of actual practice is worse than none, because it teaches the team that written standards are optional. Review dates, a named owner per document, and a habit of updating the SOP the same week an incident exposes its gap - the module-one discipline again: fix the system while the lesson is fresh.",
        },
        {
          heading: "The first 30 days: diagnose before you transform",
          body: "New managers fail in two symmetrical ways: arriving with a transformation plan built before meeting the team, or drifting for months absorbing 'how things are done here' until they have adopted every habit they were hired to change. The professional path between them has a shape.\n\nDays 1-10, diagnose: one-to-ones with every team member (what works, what is broken, what would you fix first?); sit in the guest journey yourself, from booking call to checkout; pull three months of the numbers this programme has taught you to read - utilisation by daypart, payroll ratio, retail spread per therapist, complaint log, agency spend; and audit the SOPs against actual practice. Say very little about change. Diagnosis delivered before credibility is earned lands as criticism of the people who were there before you.\n\nDays 11-20, pick your ground: choose three to five priorities where the evidence is strongest and at least one where results can show inside a month - a quick, visible win (the broken booking process, the Saturday staffing gap) buys the patience you will need for the slower structural work. For each priority: baseline, target, owner, first milestone.\n\nDays 21-30, commit publicly: present the plan to the team and your director as findings first, actions second - 'here is what the numbers and your own words told me; here is what we are doing about it, in order'. A plan the team recognises their own diagnosis inside is a plan they will deliver. Then govern it with the machinery this module built: the scorecard weekly, the priorities monthly, and the discipline of changing actions when evidence changes while keeping the goals stable.",
        },
      ],
      visuals: [
        { kind: "table", title: "The one-page scorecard: four families of measures", headers: ["Family", "Sample measures", "The leading indicator to watch"], rows: [
          ["Commercial", "Revenue vs target, utilisation by daypart, ATV, retail ratio", "Forward bookings for the next 14 days, rebooking rate"],
          ["Guest", "Satisfaction scores, complaints by root cause, review movement", "Complaint pattern shifts by journey stage"],
          ["People", "Sickness, overtime hours, agency spend, one-to-ones held vs due", "Open vacancies and time-to-fill"],
          ["Operational", "Audit results, maintenance faults open, incidents", "Recurring red audit items"],
        ], caption: "Every number needs a comparator, and every red needs a name and a date attached in the same meeting. A scorecard that produces no owned actions is a weather report." },
        { kind: "flow", title: "The first 30 days: diagnose, choose ground, commit", steps: [
          "Days 1-10: diagnose - one-to-ones with everyone, sit in the guest journey yourself, pull three months of numbers, audit SOPs against practice. Say very little about change",
          "Days 11-20: pick your ground - three to five evidenced priorities, at least one quick win visible inside a month, each with baseline, target, owner and first milestone",
          "Days 21-30: commit publicly - findings first, actions second, to the team and your director",
          "Then govern: scorecard weekly, priorities monthly; change actions when evidence changes, keep the goals stable",
        ], caption: "Diagnosis delivered before credibility is earned lands as criticism of the people who were there before you." },
      ],
      scenario: "Month-end brings apparent good news: payroll is 8% under budget and your director congratulates you in the leadership meeting.\n\nBefore accepting the praise, read the number like a manager. You have carried three unfilled vacancies all month, overtime is up, and two 'rushed treatment' comments have appeared in reviews. Work out what the favourable variance is actually made of, what invoice it will present later, and what you would say in the meeting - knowing that correcting your own good news is precisely what builds a director's trust in your reporting.",
      activity: "Build your own one-page scorecard this week using the four families - commercial, guest, people, operational - with a comparator for every number. Populate it with last month's actuals, mark every item outside threshold in red, and attach a named owner and a date to each red before you show it to anyone.",
      knowledgeCheck: [
        { q: "Forward bookings for the fortnight ahead are tracking 15% below normal pace. Why does this number deserve more attention than last month's revenue result?", options: ["It doesn't - actual revenue is always the more reliable figure", "Forward bookings are too volatile to act on", "Guests increasingly book last-minute, so the pace means little", "It is a leading indicator - the softness is a problem you can still solve, whereas the month-end pack is archaeology"], answer: 3, why: "Lagging numbers tell you what happened; leading numbers give you time to act. A soft fortnight spotted now can be met with targeted offers, rota adjustments and outreach; the same news at month-end can only be explained." },
        { q: "In the 30-day case study, agency cover costs £2,300 a month while filling the long-open vacancy would cost £2,050 a month at market rate. How should the manager present the hiring request?", options: ["As a net saving: the request arrives attached to the cost of not approving it", "As a service-quality investment that will pay for itself eventually", "As a headcount increase requiring next year's budget", "As a temporary trial hire to minimise risk"], answer: 0, why: "The GM approved the salary because, for the first time, the request carried the arithmetic of refusal: £2,300 of agency spend against £2,050 of permanent payroll. Framing hiring as closing a leak, not adding a cost, is what evidence-led management sounds like." },
        { q: "Using the variance thresholds in this module, revenue finishing 7% under plan calls for...", options: ["Watching only - it is within normal noise", "Immediate corrective action and a recovery plan", "An explanation: identify the driver - volume, rate or capacity - before proposing any fix", "Resetting the budget to match reality"], answer: 2, why: "Within 5% is watch-only, 5-10% needs an explanation, beyond 10% needs an action. At 7%, the job is diagnosis: decompose the variance by driver, because a generic initiative aimed at an unexplained variance is usually money spent on a misdiagnosis." },
      ],
      keyTerms: [
        { term: "Leading indicator", definition: "A measure that predicts future results while there is still time to act - forward bookings, rebooking rate, open vacancies - as against lagging results like last month's revenue." },
        { term: "Variance threshold", definition: "Pre-agreed bands (e.g. within 5% watch, 5-10% explain, beyond 10% act) that direct management attention by materiality rather than mood." },
        { term: "SOP", definition: "A one-page standard operating procedure - purpose, scope, owner, steps, safety points, exceptions, records, review date - testable by whether a trained person can follow it alone under pressure." },
        { term: "Baseline", definition: "The measured starting point recorded before an improvement begins, without which progress claims are opinions." },
        { term: "Quick win", definition: "An early, visible, evidence-backed improvement chosen partly for speed, which buys a new manager the credibility needed for slower structural change." },
      ],
      caseStudy: {
        title: "Thirty days at the inherited spa",
        scenario: "A newly promoted manager takes over an underperforming hotel spa: revenue 12% under budget, one therapist vacancy open for four months, agency covering 14% of hours, mixed reviews mentioning slow checkouts, and a previous manager who kept everything in his head - no scorecard, no SOPs, no one-to-one history. The GM wants 'a plan' in a month.",
        insight: "The manager resists the urge to announce anything in week one and diagnoses instead: eight one-to-ones surface that the team has been quietly triple-covering the vacancy and that checkout delays come from a till process only two people can operate; the numbers show Saturday utilisation at 92% against Tuesday's 44%, retail spread from 4% to 19% across therapists, and agency spend of £2,300 a month against a vacancy that would cost £2,050 to fill at market rate. The 30-day plan presented to the GM has four priorities, each with a baseline and owner: fill the vacancy at the market salary the data justifies (closing the agency leak - a net saving, framed exactly that way); rebuild the rota around the demand curve; train three more people on the till and write the checkout SOP (the quick win - visible in a fortnight); and start the scorecard plus monthly one-to-ones as permanent machinery. The GM approves the salary because, for the first time, the request arrives attached to the cost of not approving it. Ninety days later revenue is 3% under budget and closing, agency spend is £400, and checkout complaints have stopped - but the manager's own assessment names the scorecard and the one-to-ones as the real work: 'the first month bought the numbers; the machinery is what keeps them'.",
      },
      summary: "The final module is the connective tissue: a one-page scorecard that turns numbers into owned actions, SOPs that bottle judgement for the moments you are absent, and a first-30-days method - diagnose, choose ground, commit publicly - that turns everything this programme taught into an operating system rather than a set of good intentions.",
      nextStep: "Draft your scorecard and your first three SOPs this month - and if a new role is ahead of you, write the skeleton of your 30-day plan before day one.",
    },
  ],
}
