'use client'

import { useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import DashboardShell from '@/components/DashboardShell'
import { createClient } from '@/lib/supabase/client'
import { ROLE_LEVELS, CONTRACT_TYPES, JOB_TIERS, EMPLOYER_MEMBERSHIPS } from '@/lib/constants'
import { SERVICES_CATEGORIES, PRODUCT_HOUSES_FULL, QUALS_CATEGORIES, SYSTEMS_FULL } from '@/lib/taxonomy'
import CollapsibleCheckboxSection from '@/components/CollapsibleCheckboxSection'
import { Check, ArrowRight, Users, Upload, Image as ImageIcon, X } from 'lucide-react'

const TIER_KEYS = ['Bronze', 'Platinum'] as const
const SHIFT_OPTIONS = ['Early morning', 'Daytime', 'Evening', 'Overnight', 'Split shifts', 'Weekends only', 'Flexible']
const BUSINESS_SKILLS = ['Reception & Front of House','Revenue Management','Stock Control','Team Leadership','Staff Training','Rota Management','KPI Reporting','Health & Safety','COSHH Management','Budget Management','Client Consultation','Upselling & Retail','Social Media','Event Coordination','Membership Management']
const SCOPE_OPTIONS = [
  { value: 'same_level', title: 'Same level only', text: 'Prioritise people already working at this level. They may still see the role, but lower-level candidates will not be treated as a strong match.' },
  { value: 'step_up', title: 'Ready for the next step', text: 'Recommended. Match people at this level and strong candidates one career level below, such as Spa Manager → Spa Director.' },
  { value: 'emerging', title: 'Open to emerging talent', text: 'Also consider candidates up to two career levels below where their leadership, commercial and technical evidence supports progression.' },
  { value: 'open_transferable', title: 'Open / transferable experience', text: 'Allow WHC to surface less obvious candidates where transferable evidence makes the opportunity credible.' },
] as const

type ScopeValue = typeof SCOPE_OPTIONS[number]['value']
function scopesFromSaved(scope: string): ScopeValue[] { if(scope==='same_level')return['same_level']; if(scope==='emerging')return['step_up','emerging']; if(scope==='open_transferable')return['step_up','emerging','open_transferable']; return['step_up'] }

export default function PostRolePage() {
  const router=useRouter(); const searchParams=useSearchParams(); const supabase=createClient()
  const [profile,setProfile]=useState<any>(null); const [phase,setPhase]=useState<'form'|'tier'>('form'); const [selectedTier,setSelectedTier]=useState<'Bronze'|'Platinum'>('Bronze')
  const [saving,setSaving]=useState(false); const [checkoutLoading,setCheckoutLoading]=useState(false); const [createdJobId,setCreatedJobId]=useState<string|null>(null); const [uploadingImage,setUploadingImage]=useState(false); const [error,setError]=useState(''); const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({})
  const [selectedScopes,setSelectedScopes]=useState<ScopeValue[]>(['step_up'])
  const [form,setForm]=useState({title:'',description:'',job_image_url:'',location:'',location_postcode:'',radius_miles:'',job_type:'Full-time',contract_type:'permanent',required_role_level:'',candidate_scope:'step_up',salary_min:'',salary_max:'',required_skills:[] as string[],required_product_houses:[] as string[],required_qualifications:[] as string[],required_systems:[] as string[],preferred_business_skills:[] as string[],min_years_experience:'',shift_pattern:'',offers_accommodation:false,requirements:'',benefits:'',insurance_required:false,is_agency_role:false,is_residency_role:false,why_role_exists:'',success_90_days:'',reporting_line:'',team_size:'',opening_hours:'',commercial_responsibility:'',membership_size:'',key_kpis:'',why_move:'',career_progression:'',interview_process:''})
  const update=(field:keyof typeof form,value:any)=>{setForm(p=>({...p,[field]:value}));setFieldErrors(p=>{const n={...p};delete n[field];return n})}
  const resolvedCandidateScope=():ScopeValue=>selectedScopes.includes('open_transferable')?'open_transferable':selectedScopes.includes('emerging')?'emerging':selectedScopes.includes('step_up')?'step_up':'same_level'
  const toggleScope=(value:ScopeValue)=>{if(value==='same_level'){setSelectedScopes(['same_level']);return}setSelectedScopes(current=>{const withoutSame=current.filter(v=>v!=='same_level');if(withoutSame.includes(value)){const next=withoutSame.filter(v=>v!==value);return next.length?next:['same_level']}return[...withoutSame,value]})}

  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return}const {data}=await supabase.from('employer_profiles').select('*').eq('user_id',user.id).single();setProfile(data);const id=searchParams?.get('clone')||searchParams?.get('repost');if(!id)return;const {data:j}=await supabase.from('job_listings').select('*').eq('id',id).single();if(!j)return;const savedScope=String(j.candidate_scope||'step_up');setSelectedScopes(scopesFromSaved(savedScope));setForm({title:j.job_title||'',description:j.job_description||'',job_image_url:j.job_image_url||'',location:j.location||'',location_postcode:j.location_postcode||'',radius_miles:j.radius_miles?.toString()||'',job_type:j.job_type||'Full-time',contract_type:j.contract_type||'permanent',required_role_level:j.required_role_level||'',candidate_scope:savedScope,salary_min:j.salary_min?.toString()||'',salary_max:j.salary_max?.toString()||'',required_skills:j.required_skills||[],required_product_houses:j.required_brands||j.required_product_houses||[],required_qualifications:j.required_qualifications||[],required_systems:j.required_systems||[],preferred_business_skills:j.preferred_business_skills||[],min_years_experience:j.min_years_experience?.toString()||'',shift_pattern:j.shift_pattern||'',offers_accommodation:!!j.offers_accommodation,requirements:Array.isArray(j.requirements)?j.requirements.join('\n'):'',benefits:Array.isArray(j.benefits)?j.benefits.join('\n'):'',insurance_required:!!j.insurance_required,is_agency_role:!!j.is_agency_role,is_residency_role:!!j.is_residency_role,why_role_exists:j.why_role_exists||'',success_90_days:j.success_90_days||'',reporting_line:j.reporting_line||'',team_size:j.team_size?.toString()||'',opening_hours:j.opening_hours||'',commercial_responsibility:j.commercial_responsibility||'',membership_size:j.membership_size||'',key_kpis:Array.isArray(j.key_kpis)?j.key_kpis.join('\n'):'',why_move:j.why_move||'',career_progression:j.career_progression||'',interview_process:j.interview_process||''})})()},[])

  async function uploadJobImage(file:File){setUploadingImage(true);setError('');try{const fd=new FormData();fd.append('file',file);fd.append('bucket','site-images');const safe=(form.title||'job').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');fd.append('path',`jobs/${profile?.id||'employer'}/${safe}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`);const res=await fetch('/api/upload',{method:'POST',body:fd});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'Image upload failed');update('job_image_url',body.url)}catch(e:any){setError(e.message||'Image upload failed')}finally{setUploadingImage(false)}}

  const payload=()=>({employer_id:profile.id,job_title:form.title,job_description:form.description,job_image_url:form.job_image_url||null,location:form.location,location_postcode:form.location_postcode||null,radius_miles:form.radius_miles?parseInt(form.radius_miles):null,job_type:form.job_type,contract_type:form.contract_type,required_role_level:form.required_role_level||null,candidate_scope:resolvedCandidateScope(),salary_min:form.salary_min?parseInt(form.salary_min):null,salary_max:form.salary_max?parseInt(form.salary_max):null,required_skills:form.required_skills.length?form.required_skills:null,required_brands:form.required_product_houses.length?form.required_product_houses:null,required_qualifications:form.required_qualifications.length?form.required_qualifications:null,required_systems:form.required_systems.length?form.required_systems:null,preferred_business_skills:form.preferred_business_skills.length?form.preferred_business_skills:null,min_years_experience:form.min_years_experience?parseInt(form.min_years_experience):0,shift_pattern:form.shift_pattern||null,offers_accommodation:form.offers_accommodation,requirements:form.requirements?form.requirements.split('\n').filter(Boolean):null,benefits:form.benefits?form.benefits.split('\n').filter(Boolean):null,insurance_required:form.insurance_required,is_agency_role:form.is_agency_role,is_residency_role:form.is_residency_role,tier:selectedTier,why_role_exists:form.why_role_exists.trim()||null,success_90_days:form.success_90_days.trim()||null,reporting_line:form.reporting_line.trim()||null,team_size:form.team_size?parseInt(form.team_size):null,opening_hours:form.opening_hours.trim()||null,commercial_responsibility:form.commercial_responsibility.trim()||null,membership_size:form.membership_size.trim()||null,key_kpis:form.key_kpis?form.key_kpis.split('\n').map(k=>k.trim()).filter(Boolean):null,why_move:form.why_move.trim()||null,career_progression:form.career_progression.trim()||null,interview_process:form.interview_process.trim()||null})
  async function saveDraft(){if(!profile||!form.title||!form.location)return;setSaving(true);setError('');try{const r=await fetch('/api/employer/jobs/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload(),is_live:false,status:'draft'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Error saving draft');router.push('/employer/jobs?draft=saved')}catch(e:any){setError(e.message);setSaving(false)}}
  function next(){const e:Record<string,string>={};if(form.title.trim().length<5)e.job_title='Title must be at least 5 characters';if(form.description.trim().length<10)e.job_description='Description must be at least 10 characters';if(!form.location.trim())e.location='Location is required';setFieldErrors(e);if(Object.keys(e).length){setError('Please complete the highlighted fields.');window.scrollTo({top:0,behavior:'smooth'});return}setError('');setPhase('tier');window.scrollTo({top:0,behavior:'smooth'})}
  async function post(){if(!profile||saving||checkoutLoading)return;setSaving(true);setError('');try{
    // Reuse the draft created by an earlier attempt: without this, every retry
    // of "Post role & pay" left a duplicate listing behind.
    let jobId=createdJobId
    if(!jobId){const c=await fetch('/api/employer/jobs/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload(),is_live:false,status:'draft'})});const cd=await c.json();if(!c.ok||!cd.job)throw new Error(cd.error||'Failed to create listing');jobId=cd.job.id;setCreatedJobId(jobId)}
    const cd={job:{id:jobId}};setCheckoutLoading(true);const r=await fetch('/api/mobile/employer/jobs/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish',jobId:cd.job.id,tier:selectedTier})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not publish role');if(d.included){router.push('/employer/jobs?published=included');return}if(!d.url)throw new Error('Could not start checkout');window.location.href=d.url}catch(e:any){setError(e.message);setSaving(false);setCheckoutLoading(false)}}

  if(!profile)return <div/>
  const membership=String(profile.membership_tier||'free').toLowerCase();const allowance=Number(profile.annual_job_allowance||(membership==='group'?EMPLOYER_MEMBERSHIPS.group.includedJobs:0));const used=Number(profile.annual_jobs_used||0);const groupRemaining=membership==='group'?Math.max(0,allowance-used):0
  const tierCards=TIER_KEYS.map(name=>{const base=JOB_TIERS[name];const price=name==='Bronze'&&membership==='pro'?EMPLOYER_MEMBERSHIPS.pro.discountedStandardJobPrice:base.price;const included=name==='Bronze'&&membership==='group'&&groupRemaining>0;return{name,price,included,features:base.features as readonly string[]}})
  const selectedIncluded=selectedTier==='Bronze'&&membership==='group'&&groupRemaining>0;const selectedScopeLabels=SCOPE_OPTIONS.filter(o=>selectedScopes.includes(o.value)).map(o=>o.title)
  return <DashboardShell role="employer" userName={profile.company_name}>
    <div className="max-w-4xl"><p className="dashboard-eyebrow">Recruitment</p><h1 className="dashboard-title">Post a Role</h1><p className="dashboard-intro">Tell WHC what the job genuinely needs and how open you are to career progression.</p></div>
    {error&&<div className="max-w-4xl mt-6 bg-red-50 text-red-700 text-sm px-4 py-3 rounded-lg">{error}</div>}
    {phase==='form'?<div className="max-w-4xl mt-8 space-y-7">
      <section className="dashboard-card space-y-5"><p className="eyebrow">Job details</p>
        <Field label="Job title *"><input className={`input-field ${fieldErrors.job_title?'border-red-300':''}`} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Director of Spa"/></Field>
        <Field label="Job description *"><textarea className={`input-field ${fieldErrors.job_description?'border-red-300':''}`} rows={7} value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Responsibilities, priorities, reporting line, team size and what success looks like..."/></Field>
        <div><p className="eyebrow mb-1.5">Job image</p><p className="text-[11px] text-secondary mb-3">Upload a photo specifically for this vacancy. This will appear on Browse Roles and the role page. If you leave it blank, WHC will use your property photo as a fallback.</p><div className="grid md:grid-cols-[260px_1fr] gap-4 items-center border border-border rounded-xl p-4 bg-[#f5f6f8]">{form.job_image_url?<div className="aspect-[16/10] overflow-hidden rounded-xl bg-white"><img src={form.job_image_url} alt="Job preview" className="w-full h-full object-cover"/></div>:<div className="aspect-[16/10] rounded-xl border border-dashed border-border bg-white flex items-center justify-center text-muted"><ImageIcon size={30}/></div>}<div className="flex flex-wrap gap-2"><label className="btn-secondary inline-flex items-center gap-2 cursor-pointer"><Upload size={13}/>{uploadingImage?'Uploading...':form.job_image_url?'Replace image':'Upload job image'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploadingImage} onChange={e=>{const f=e.target.files?.[0];if(f)uploadJobImage(f);e.target.value=''}}/></label>{form.job_image_url&&<button type="button" onClick={()=>update('job_image_url','')} className="btn-secondary inline-flex items-center gap-2"><X size={13}/>Remove</button>}</div></div></div>
        <div className="grid md:grid-cols-2 gap-4"><Field label="Role level"><select className="input-field" value={form.required_role_level} onChange={e=>update('required_role_level',e.target.value)}><option value="">Use job title / any level</option>{ROLE_LEVELS.map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Contract type"><select className="input-field" value={form.contract_type} onChange={e=>update('contract_type',e.target.value)}>{CONTRACT_TYPES.map(t=><option key={t} value={t}>{t.replace('_',' ')}</option>)}</select></Field></div>
        <div className="grid md:grid-cols-2 gap-4"><Field label="Location *"><input className={`input-field ${fieldErrors.location?'border-red-300':''}`} value={form.location} onChange={e=>update('location',e.target.value)}/></Field><Field label="Postcode"><input className="input-field" value={form.location_postcode} onChange={e=>update('location_postcode',e.target.value)}/></Field></div>
        <div className="grid md:grid-cols-4 gap-4"><Field label="Min salary"><input type="number" className="input-field" value={form.salary_min} onChange={e=>update('salary_min',e.target.value)}/></Field><Field label="Max salary"><input type="number" className="input-field" value={form.salary_max} onChange={e=>update('salary_max',e.target.value)}/></Field><Field label="Experience"><input type="number" className="input-field" value={form.min_years_experience} onChange={e=>update('min_years_experience',e.target.value)}/></Field><Field label="Job type"><select className="input-field" value={form.job_type} onChange={e=>update('job_type',e.target.value)}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Temporary</option><option>Freelance</option></select></Field></div>
      </section>
      <section className="dashboard-card space-y-5"><div><p className="eyebrow">Tell the story</p><h2 className="text-[24px] mt-1">Why this role, why now, why here.</h2><p className="text-[12px] text-secondary mt-1.5">All optional, all worth doing. Candidates consistently shortlist the roles that explain themselves honestly.</p></div>
        <Field label="Why this role exists" help="One honest paragraph: new opening, growth, a leader moving on."><textarea rows={3} className="input-field" value={form.why_role_exists} onChange={e=>update('why_role_exists',e.target.value)}/></Field>
        <Field label="What success looks like in 90 days"><textarea rows={3} className="input-field" value={form.success_90_days} onChange={e=>update('success_90_days',e.target.value)}/></Field>
        <div className="grid md:grid-cols-2 gap-4"><Field label="Reporting line"><input className="input-field" value={form.reporting_line} onChange={e=>update('reporting_line',e.target.value)} placeholder="e.g. Reports to the Director of Spa"/></Field><Field label="Team size"><input type="number" className="input-field" value={form.team_size} onChange={e=>update('team_size',e.target.value)}/></Field></div>
        <div className="grid md:grid-cols-2 gap-4"><Field label="Opening hours"><input className="input-field" value={form.opening_hours} onChange={e=>update('opening_hours',e.target.value)} placeholder="e.g. Spa open 9:00-21:00, 7 days"/></Field><Field label="Membership size"><input className="input-field" value={form.membership_size} onChange={e=>update('membership_size',e.target.value)} placeholder="e.g. 600 active members"/></Field></div>
        <Field label="Commercial responsibility" help="Revenue, retail, payroll or membership accountability, in plain terms."><textarea rows={2} className="input-field" value={form.commercial_responsibility} onChange={e=>update('commercial_responsibility',e.target.value)}/></Field>
        <Field label="Key KPIs (one per line)" help="The numbers this role owns."><textarea rows={3} className="input-field" value={form.key_kpis} onChange={e=>update('key_kpis',e.target.value)}/></Field>
        <Field label="Why someone should move" help="The honest pitch: what this role offers that their current one probably does not."><textarea rows={3} className="input-field" value={form.why_move} onChange={e=>update('why_move',e.target.value)}/></Field>
        <Field label="Career progression"><textarea rows={2} className="input-field" value={form.career_progression} onChange={e=>update('career_progression',e.target.value)}/></Field>
        <Field label="Interview process" help="Stages and rough timeline - candidates rate employers who say this upfront."><textarea rows={2} className="input-field" value={form.interview_process} onChange={e=>update('interview_process',e.target.value)}/></Field>
      </section>
      <section className="dashboard-card"><div className="flex items-start gap-3"><Users size={20} className="text-[#5a6a76] mt-1"/><div><p className="eyebrow">Who should WHC consider?</p><h2 className="text-[25px] mt-1">Set the career-progression window.</h2></div></div><div className="grid md:grid-cols-2 gap-3 mt-6">{SCOPE_OPTIONS.map(o=>{const selected=selectedScopes.includes(o.value);return <button type="button" key={o.value} onClick={()=>toggleScope(o.value)} className={`text-left rounded-xl border p-4 ${selected?'border-[#0b2f4d] bg-[#f5f6f8]':'border-[#e3e7eb] bg-white'}`}><div className="flex justify-between gap-3"><p className="text-[14px] font-semibold">{o.title}</p><span className={`h-5 w-5 rounded border flex items-center justify-center ${selected?'bg-[#0b2f4d] border-[#0b2f4d]':'bg-white'}`}>{selected&&<Check size={13} className="text-white"/>}</span></div><p className="text-[11px] leading-5 text-secondary mt-2">{o.text}</p></button>})}</div>{selectedScopes.length>1&&<p className="text-[11px] text-secondary mt-4">Selected: {selectedScopeLabels.join(' + ')}</p>}</section>
      <section className="dashboard-card space-y-5"><div><p className="eyebrow">Matching criteria</p><h2 className="text-[24px] mt-1">Separate genuine requirements from preferences.</h2></div><CollapsibleCheckboxSection title="Required Services & Treatment Skills" categories={SERVICES_CATEGORIES} selected={form.required_skills} onChange={v=>update('required_skills',v)}/><CollapsibleCheckboxSection title="Required Product Houses" flatItems={[...PRODUCT_HOUSES_FULL]} selected={form.required_product_houses} onChange={v=>update('required_product_houses',v)}/><CollapsibleCheckboxSection title="Required Qualifications" categories={QUALS_CATEGORIES} selected={form.required_qualifications} onChange={v=>update('required_qualifications',v)}/><CollapsibleCheckboxSection title="Required Systems" flatItems={[...SYSTEMS_FULL]} selected={form.required_systems} onChange={v=>update('required_systems',v)}/><CollapsibleCheckboxSection title="Preferred Leadership & Business Skills" flatItems={BUSINESS_SKILLS} selected={form.preferred_business_skills} onChange={v=>update('preferred_business_skills',v)}/><div className="grid md:grid-cols-2 gap-4"><Field label="Shift pattern"><select className="input-field" value={form.shift_pattern} onChange={e=>update('shift_pattern',e.target.value)}><option value="">Any / Flexible</option>{SHIFT_OPTIONS.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Search radius (miles)"><input type="number" className="input-field" value={form.radius_miles} onChange={e=>update('radius_miles',e.target.value)}/></Field></div></section>
      <section className="dashboard-card space-y-5"><p className="eyebrow">Additional information</p><Field label="Requirements (one per line)"><textarea rows={4} className="input-field" value={form.requirements} onChange={e=>update('requirements',e.target.value)}/></Field><Field label="Benefits (one per line)"><textarea rows={4} className="input-field" value={form.benefits} onChange={e=>update('benefits',e.target.value)}/></Field><div className="flex flex-wrap gap-5">{[['insurance_required','Insurance required'],['offers_accommodation','Accommodation provided'],['is_agency_role','Agency role'],['is_residency_role','Residency role']].map(([k,l])=><label key={k} className="flex items-center gap-2 text-[13px] text-secondary"><input type="checkbox" checked={(form as any)[k]} onChange={e=>update(k as any,e.target.checked)}/>{l}</label>)}</div></section>
      <div className="flex gap-3"><button onClick={saveDraft} disabled={saving||uploadingImage} className="btn-secondary flex-1">Save as Draft</button><button onClick={next} disabled={saving||uploadingImage} className="btn-primary flex-1 inline-flex items-center justify-center gap-2">Continue <ArrowRight size={14}/></button></div>
    </div>:<div className="max-w-4xl mt-8"><div className="dashboard-card mb-6"><p className="eyebrow">Matching setup</p><h2 className="text-[25px] mt-1">{form.title}</h2><p className="text-[13px] text-secondary mt-2">{selectedScopeLabels.join(' + ')} · {form.required_role_level||'Role level inferred from title'} · {form.min_years_experience||0}+ years</p></div><div className="grid md:grid-cols-2 gap-4 mb-6">{tierCards.map(t=><button key={t.name} onClick={()=>setSelectedTier(t.name)} className={`dashboard-card text-left ${selectedTier===t.name?'border-[#0b2f4d] ring-1 ring-[#0b2f4d]/10':''}`}><div className="flex justify-between"><h3 className="text-[20px]">{t.name==='Bronze'?'Standard':'Featured'}</h3><strong>{t.included?'Included':`£${t.price/100}`}</strong></div><ul className="mt-4 space-y-2 text-[12px] text-secondary">{t.features.map(f=><li key={f} className="flex gap-2"><Check size={13}/>{f}</li>)}</ul></button>)}</div><div className="flex gap-3"><button onClick={()=>setPhase('form')} className="btn-secondary flex-1">← Back to edit</button><button onClick={post} disabled={saving||checkoutLoading} className="btn-primary flex-1">{checkoutLoading?(selectedIncluded?'Publishing...':'Redirecting...'):saving?'Processing...':selectedIncluded?'Post role':'Post role & pay'}</button></div></div>}
  </DashboardShell>
}
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <div><label className="eyebrow block mb-1.5">{label}</label>{help&&<p className="text-[11px] text-secondary mb-2">{help}</p>}{children}</div>}
