import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function PrivacyPage() {
  return <div className="min-h-screen bg-white"><Navbar />
    <main id="main-content">
    <section className="bg-[#0b2f4d] pt-32 pb-16"><div className="max-w-3xl mx-auto px-6 text-center"><h1 className="text-4xl font-semibold text-white">Privacy Policy</h1><p className="text-white/70 mt-3 text-[14px]">Last updated: 1 September 2026</p></div></section>
    <section className="py-16 bg-white"><div className="max-w-3xl mx-auto px-6 prose prose-lg prose-headings:text-[#10283b] prose-p:text-[#5a6a76] prose-li:text-[#5a6a76]">
      <h2>1. Who we are</h2><p>Wellness House Collective (&ldquo;WHC&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) operates a UK recruitment, flexible-work and professional-development platform for spa and wellness professionals and employers. We act as data controller for personal data processed through the platform. Privacy enquiries and data-rights requests can be sent to <a href="mailto:hello@wellnesshousecollective.co.uk">hello@wellnesshousecollective.co.uk</a>.</p>

      <h2>2. Data we process</h2><p>Depending on the service you use, this can include account and contact information, professional profile information, CVs, qualifications and certificates, right-to-work information, optional insurance documents, skills, career history, availability, location and travel preferences, job applications, interviews, messages, reviews, Agency and Residency booking records, payment records, communication preferences, consent records, activity records of how the platform is used (see section 12) and security/audit information.</p><p>Employer data can include company and property details, job descriptions, salaries, role requirements, candidate-search preferences and recruitment activity.</p>

      <h2>3. Matching and recruitment intelligence</h2><p>WHC uses profile and job information to calculate match scores and rankings. Factors can include role level, employer-selected career-progression scope, experience, treatments and technical skills, qualifications, product houses, systems, leadership and business skills, location, shift preferences, travel and accommodation requirements.</p><p>An employer can choose whether WHC should prioritise candidates already at the same level, candidates ready for the next step, emerging talent, or transferable experience. A match score is a decision-support tool. It does not mean that a person is guaranteed an interview, employment or suitability for a regulated activity.</p><p>No hiring decision is made solely by the WHC matching algorithm. Employers remain responsible for reviewing candidates, verifying requirements and making recruitment decisions.</p>

      <h2>4. AI-assisted CV analysis</h2><p>CV analysis is optional. When a Talent user actively selects <strong>Analyse CV with WHC AI</strong> and confirms the processing notice, WHC may process readable text from their CV using an AI service to identify supported career evidence, leadership/commercial skills and possible progression signals.</p><ul><li>AI must not invent qualifications, employers, responsibilities or results.</li><li>AI suggestions do not automatically change a profile.</li><li>The user reviews and approves suggestions before they are saved.</li><li>WHC does not use AI analysis to silently change the user&apos;s current job title or seniority.</li><li>The WHC application does not store raw extracted CV text in the analysis record; approved short evidence statements may be saved to the user&apos;s profile.</li></ul><p>Where AI processing is used, the user&apos;s explicit action is recorded in WHC&apos;s consent/audit ledger.</p>

      <h2>5. Communications and marketing</h2><p>Service communications such as security notices, application updates, booking updates, password resets, payment confirmations and other messages necessary to provide the service are kept separate from marketing.</p><p>Marketing email is off by default unless the user chooses it. WHC uses double opt-in for email marketing: a marketing request remains pending until the user confirms it using the confirmation link. Users can unsubscribe or withdraw marketing consent at any time. We maintain a record of consent requests, confirmations and withdrawals.</p><p>Users can manage separate preferences for job alerts, Academy/product updates, partner marketing and other optional communications where available.</p>

      <h2>6. Profile visibility and data sharing</h2><p>Talent controls whether their profile can be discoverable to approved employers, subject to the relevant service settings. WHC does not sell personal data. We do not give third parties permission to use WHC user data for their own unrelated marketing.</p><p>Where a user chooses a feature involving an employer, property, booking, application or partner service, we share only the information reasonably required to provide that feature. Optional partner-profile sharing and partner marketing are kept separate from core recruitment processing.</p>

      <h3>What an employer receives when you apply</h3><p>When a Talent user sends an application, the property that posted the role receives, from that user&apos;s profile: name, headline, role level, location and profile photograph; bio, career evidence, desired roles and portfolio link; treatments and skills, qualifications, product houses, systems experience, business skills and commercial experience; years of experience, team size managed, revenue responsibility and availability; whether the user holds their own insurance; WHC review score and review count, verified certificates, WHC Academy courses and any endorsements; the covering letter, and the fit score WHC calculated for that role.</p><p>Salary expectation is private by default. The matching engine uses it, but the figure itself is shown to an employer only where the user has chosen to make it visible.</p><p><strong>Documents.</strong> A CV, insurance certificate, right-to-work evidence or uploaded certificate opens to an employer only where the Talent user took part in creating the relationship: an application they submitted, a mutual match, or an Agency booking. Being shortlisted by an employer does not on its own open a Talent user&apos;s documents, because shortlisting is employer-initiated and the candidate is never told it happened. WHC administrators can access documents for verification and support.</p>

      <h2>7. Legal bases</h2><ul><li><strong>Contract:</strong> account provision, matching, applications, bookings, payments and other services requested by the user.</li><li><strong>Consent:</strong> marketing, optional AI CV analysis and other optional processing where consent is the appropriate basis.</li><li><strong>Legitimate interests:</strong> platform security, fraud prevention, service improvement and proportionate recruitment functionality where those interests do not override individual rights.</li><li><strong>Legal obligation:</strong> records or disclosures we are required to maintain or make by law.</li></ul>

      <h2>8. Processors and service providers</h2><p>WHC uses specialist providers to operate the service. Each receives only the data needed for the service it performs and is subject to its own data-processing and security terms.</p><ul>
        <li><strong>Supabase</strong> - database, file storage and authentication. Holds the platform record, including profiles, applications, messages and uploaded documents.</li>
        <li><strong>Stripe</strong> - payments, subscriptions and payouts. Receives payment and identity details needed to take or make a payment.</li>
        <li><strong>Resend</strong> - email delivery. Receives the recipient email address and the content of the email.</li>
        <li><strong>Twilio</strong> - SMS notifications. Receives the mobile number and a deliberately non-specific message. WHC does not put names, rates, interview details or message content into an SMS; the text only says that something is waiting and links to the signed-in platform.</li>
        <li><strong>Expo</strong> - push notifications to the WHC mobile app. Receives the device push token and the notification title and body.</li>
        <li><strong>getAddress.io</strong> - UK postcode and address lookup. Receives the postcode being looked up, and a property name where one has been entered. Where that lookup is unavailable, WHC falls back to <strong>Nominatim</strong>, the OpenStreetMap search service, which receives the same postcode and property name.</li>
        <li><strong>Netlify</strong> - hosting and deployment of the website and API.</li>
        <li><strong>OpenAI</strong> - only where a user chooses an AI-assisted feature such as CV analysis or Interview Ready.</li>
      </ul>

      <h3>Where your data is held</h3><p>The WHC database and all uploaded files - CVs, insurance certificates, right-to-work evidence, certificates, message attachments and photographs - are hosted in the <strong>United Kingdom</strong>, in the Supabase London region (eu-west-2). They are not replicated outside the UK.</p><p>The following processors are established outside the UK and personal data reaches them in the course of the service they provide: <strong>Stripe</strong>, <strong>Resend</strong>, <strong>Twilio</strong>, <strong>Expo</strong>, <strong>Netlify</strong> and <strong>OpenAI</strong> (United States). Supabase Inc. is also incorporated in the United States, although the data it stores for WHC remains in London. <strong>getAddress.io</strong> is a UK provider; Nominatim is operated by the OpenStreetMap Foundation on servers in the European Union. Where personal data is transferred outside the UK, WHC relies on the transfer safeguards in each provider&apos;s data-processing terms, such as the UK International Data Transfer Addendum or an applicable adequacy decision.</p>

      <h2>9. Security</h2><p>WHC uses role-based access controls, authenticated server routes, Supabase row-level security where appropriate, protected document storage, server-side payment verification, security logging and production-readiness checks. Sensitive platform secrets are not intended to be exposed in browser code. No internet service can be guaranteed to be completely risk-free, so we review controls as the platform develops.</p>

      <h2>10. Retention</h2><p>WHC applies the following periods. They are held in one place in the platform code and applied by a retention sweep that WHC runs against the live database.</p><ul>
        <li><strong>Activity records (analytics events)</strong> - 13 months.</li>
        <li><strong>In-app notifications</strong> - 12 months.</li>
        <li><strong>Contact and complaint enquiries</strong> - 12 months.</li>
        <li><strong>Used or expired marketing confirmation tokens</strong> - 30 days. The consent itself is recorded separately in the consent ledger.</li>
        <li><strong>Expired newsletter confirmation tokens</strong> - 30 days, after which the token is cleared from the subscriber record.</li>
        <li><strong>Job applications and platform messages</strong> - 24 months after the last activity on them.</li>
        <li><strong>Verification records belonging to a closed account</strong> - 12 months. The documents themselves are deleted at the moment the account is deleted, not after a delay.</li>
      </ul>
      <p><strong>Accounts.</strong> When a user deletes their account, their profile, applications, messages, notifications, activity records and every uploaded file - CV, insurance certificate, right-to-work document and certificates - are deleted at that point.</p>
      <p><strong>Financial and statutory records are the exception.</strong> Agency and Residency bookings, purchases, Academy enrolments, placements and salary records carry amounts, payment references and hire outcomes that UK company and tax law requires WHC to keep for six years from the end of the relevant accounting period. Those records are <em>anonymised</em> rather than deleted: the link to the person is removed and the amounts and dates survive. A user deleting their account is told which records this applies to.</p>
      <p>WHC may also need to keep information longer where there is a continuing legal claim, a live dispute, or a legal obligation to retain it.</p>

      <h2>11. Your UK GDPR rights</h2><p>Subject to the law and the circumstances, you may have rights to access, rectify, erase, restrict or object to processing, obtain portable data, withdraw consent and complain to the Information Commissioner&apos;s Office. You also have protections relating to solely automated decisions with legal or similarly significant effects. WHC matching is designed as decision support rather than a solely automated hiring decision.</p><p>Requests can be sent to <a href="mailto:hello@wellnesshousecollective.co.uk">hello@wellnesshousecollective.co.uk</a>. We may need to verify identity before releasing or changing account data.</p>

      <h2>12. Cookies and activity records</h2><p>WHC uses necessary authentication and security cookies to provide logged-in services. It sets no analytics or advertising cookies, and none may be introduced without the appropriate consent mechanism. Payment providers may set cookies necessary for fraud prevention and payment security.</p>
      <p><strong>WHC does, however, keep a record of activity on its own servers.</strong> This is not a cookie and it is not a third-party analytics product: it is a table in the WHC database. It records events such as a job being viewed, a candidate profile being viewed by an employer, an application moving between stages, a search being run and an administrative decision being taken. Each row can hold the acting account, the candidate, employer, job or application involved, a timestamp and a small amount of context about the event. Over time this amounts to a behavioural record of how an individual uses the platform.</p>
      <p>The lawful basis is <strong>legitimate interests</strong>: WHC needs to know whether roles are being seen, whether matching is working, where applications stall and where the platform is being misused. WHC has weighed that against the interests of the people involved - the record is not sold, not shared with third parties for their own purposes, not used to build advertising profiles, and not used to make an automated decision about anyone. These records are <strong>deleted after 13 months</strong>, and are deleted immediately when the account they relate to is deleted.</p>
      <p>Any user can obtain their own activity records through the data export in their account settings, and can object to this processing by writing to <a href="mailto:hello@wellnesshousecollective.co.uk">hello@wellnesshousecollective.co.uk</a>.</p>

      <h2>13. Changes</h2><p>We may update this policy as the platform, service providers or law change. Material changes will be communicated where required, and fresh consent will be sought when the law requires it for a new processing purpose.</p>
    </div></section></main><Footer /></div>
}
