import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function PrivacyPage() {
  return <div className="min-h-screen bg-white"><Navbar />
    <section className="bg-[#0b2f4d] pt-32 pb-16"><div className="max-w-3xl mx-auto px-6 text-center"><h1 className="text-4xl font-semibold text-white">Privacy Policy</h1><p className="text-white/70 mt-3 text-[14px]">Last updated: 26 August 2026</p></div></section>
    <section className="py-16 bg-white"><div className="max-w-3xl mx-auto px-6 prose prose-lg prose-headings:text-[#10283b] prose-p:text-[#4d4d4d] prose-li:text-[#4d4d4d]">
      <h2>1. Who we are</h2><p>Wellness House Collective (&ldquo;WHC&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) operates a UK recruitment, flexible-work and professional-development platform for spa and wellness professionals and employers. We act as data controller for personal data processed through the platform. Privacy enquiries and data-rights requests can be sent to <a href="mailto:rebecca.whc@outlook.com">rebecca.whc@outlook.com</a>.</p>

      <h2>2. Data we process</h2><p>Depending on the service you use, this can include account and contact information, professional profile information, CVs, qualifications and certificates, right-to-work information, optional insurance documents, skills, career history, availability, location and travel preferences, job applications, interviews, messages, reviews, Agency and Residency booking records, payment records, communication preferences, consent records and security/audit information.</p><p>Employer data can include company and property details, job descriptions, salaries, role requirements, candidate-search preferences and recruitment activity.</p>

      <h2>3. Matching and recruitment intelligence</h2><p>WHC uses profile and job information to calculate match scores and rankings. Factors can include role level, employer-selected career-progression scope, experience, treatments and technical skills, qualifications, product houses, systems, leadership and business skills, location, shift preferences, travel and accommodation requirements.</p><p>An employer can choose whether WHC should prioritise candidates already at the same level, candidates ready for the next step, emerging talent, or transferable experience. A match score is a decision-support tool. It does not mean that a person is guaranteed an interview, employment or suitability for a regulated activity.</p><p>No hiring decision is made solely by the WHC matching algorithm. Employers remain responsible for reviewing candidates, verifying requirements and making recruitment decisions.</p>

      <h2>4. AI-assisted CV analysis</h2><p>CV analysis is optional. When a Talent user actively selects <strong>Analyse CV with WHC AI</strong> and confirms the processing notice, WHC may process readable text from their CV using an AI service to identify supported career evidence, leadership/commercial skills and possible progression signals.</p><ul><li>AI must not invent qualifications, employers, responsibilities or results.</li><li>AI suggestions do not automatically change a profile.</li><li>The user reviews and approves suggestions before they are saved.</li><li>WHC does not use AI analysis to silently change the user&apos;s current job title or seniority.</li><li>The WHC application does not store raw extracted CV text in the analysis record; approved short evidence statements may be saved to the user&apos;s profile.</li></ul><p>Where AI processing is used, the user&apos;s explicit action is recorded in WHC&apos;s consent/audit ledger.</p>

      <h2>5. Communications and marketing</h2><p>Service communications such as security notices, application updates, booking updates, password resets, payment confirmations and other messages necessary to provide the service are kept separate from marketing.</p><p>Marketing email is off by default unless the user chooses it. WHC uses double opt-in for email marketing: a marketing request remains pending until the user confirms it using the confirmation link. Users can unsubscribe or withdraw marketing consent at any time. We maintain a record of consent requests, confirmations and withdrawals.</p><p>Users can manage separate preferences for job alerts, Academy/product updates, partner marketing and other optional communications where available.</p>

      <h2>6. Profile visibility and data sharing</h2><p>Talent controls whether their profile can be discoverable to approved employers, subject to the relevant service settings. WHC does not sell personal data. We do not give third parties permission to use WHC user data for their own unrelated marketing.</p><p>Where a user chooses a feature involving an employer, property, booking, application or partner service, we share only the information reasonably required to provide that feature. Optional partner-profile sharing and partner marketing are kept separate from core recruitment processing.</p>

      <h2>7. Legal bases</h2><ul><li><strong>Contract:</strong> account provision, matching, applications, bookings, payments and other services requested by the user.</li><li><strong>Consent:</strong> marketing, optional AI CV analysis and other optional processing where consent is the appropriate basis.</li><li><strong>Legitimate interests:</strong> platform security, fraud prevention, service improvement and proportionate recruitment functionality where those interests do not override individual rights.</li><li><strong>Legal obligation:</strong> records or disclosures we are required to maintain or make by law.</li></ul>

      <h2>8. Processors and service providers</h2><p>WHC uses specialist providers to operate the service. These can include <strong>Supabase</strong> for database, storage and authentication; <strong>Stripe</strong> for payments; <strong>Resend</strong> for email delivery; <strong>Netlify</strong> for hosting/deployment; and <strong>OpenAI</strong> where a user chooses an AI-assisted feature such as CV analysis or Interview Ready. Each provider only receives data needed for the service being performed and is subject to its own data-processing and security terms.</p><p>Where personal data is processed outside the UK, WHC uses or relies on appropriate transfer safeguards where required, such as UK-approved contractual safeguards or an applicable adequacy mechanism.</p>

      <h2>9. Security</h2><p>WHC uses role-based access controls, authenticated server routes, Supabase row-level security where appropriate, protected document storage, server-side payment verification, security logging and production-readiness checks. Sensitive platform secrets are not intended to be exposed in browser code. No internet service can be guaranteed to be completely risk-free, so we review controls as the platform develops.</p>

      <h2>10. Retention</h2><p>We keep personal data only for as long as needed for the service, legal obligations, disputes, fraud/security prevention and legitimate record-keeping. Financial records may need to be retained for statutory periods. Users can request deletion, although some information may need to be retained where WHC has a legal obligation or a continuing legal claim.</p>

      <h2>11. Your UK GDPR rights</h2><p>Subject to the law and the circumstances, you may have rights to access, rectify, erase, restrict or object to processing, obtain portable data, withdraw consent and complain to the Information Commissioner&apos;s Office. You also have protections relating to solely automated decisions with legal or similarly significant effects. WHC matching is designed as decision support rather than a solely automated hiring decision.</p><p>Requests can be sent to <a href="mailto:rebecca.whc@outlook.com">rebecca.whc@outlook.com</a>. We may need to verify identity before releasing or changing account data.</p>

      <h2>12. Cookies</h2><p>WHC uses necessary authentication and security cookies to provide logged-in services. Optional analytics or advertising cookies must not be introduced without the appropriate consent mechanism. Payment providers may set cookies necessary for fraud prevention and payment security.</p>

      <h2>13. Changes</h2><p>We may update this policy as the platform, service providers or law change. Material changes will be communicated where required, and fresh consent will be sought when the law requires it for a new processing purpose.</p>
    </div></section><Footer /></div>
}
