-- 20260904180000: Before You Arrive starts working.
--
-- Additive and idempotent. Safe to run more than once.
--
-- WHY
--
-- The arrival pack - the property's address, the staff entrance, who to ask
-- for, parking, the booking system they run, everything a professional needs
-- before walking into a building they have never been to - is generated by a
-- trigger on agency_bookings, and by a function both gated on the same words:
--
--   if new.status in ('confirmed','completed') then
--     perform public.generate_booking_arrival_pack('agency', new.id);
--
-- An accepted Agency booking has status 'accepted'. Nothing in the application
-- ever writes 'confirmed' to that column - the vocabulary is pending,
-- accepted, declined, expired, lapsed, open. So that condition has never once
-- been true, the function filters on the same two words and would have
-- returned nothing even if called by hand, and Before You Arrive has shown
-- "No confirmed arrival packs yet" to every professional who ever took a
-- shift.
--
-- Both now read the vocabulary the platform actually uses. The old words are
-- kept so Residency and any future status are untouched, and the body of the
-- generator below is the original from migration 044, unchanged apart from
-- that one line.

create or replace function public.generate_booking_arrival_pack(p_booking_type text, p_booking_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  b record;
  e record;
  f record;
  payload jsonb;
begin
  if p_booking_type = 'agency' then
    -- An accepted Agency booking has status 'accepted'. Nothing in the
    -- application has ever written 'confirmed' to that column.
    select * into b from public.agency_bookings where id = p_booking_id and status in ('accepted','confirmed','completed');
  elsif p_booking_type = 'residency' then
    select * into b from public.residency_bookings where id = p_booking_id and status in ('confirmed','paid','active','completed');
  else
    return;
  end if;
  if not found then return; end if;

  select * into e from public.employer_profiles where id = b.employer_id;
  if not found then return; end if;
  select * into f from public.property_fact_files where employer_id = b.employer_id;

  payload := jsonb_build_object(
    'type', p_booking_type,
    'property', jsonb_build_object(
      'name', coalesce(e.property_name, e.company_name),
      'address', coalesce(f.property_address, concat_ws(', ', e.address, e.city, e.postcode, e.country)),
      'map_url', f.map_url,
      'directions', f.directions,
      'nearest_transport', coalesce(f.nearest_transport, e.nearest_transport),
      'parking_available', coalesce(f.parking_available, e.parking_available),
      'parking_details', f.parking_details,
      'staff_entrance', f.staff_entrance
    ),
    'arrival', jsonb_build_object(
      'contact_name', coalesce(f.arrival_contact_name, e.contact_name, e.spa_director_name),
      'contact_role', f.arrival_contact_role,
      'phone', coalesce(f.arrival_phone, e.contact_phone),
      'recommended_buffer_minutes', coalesce(f.recommended_arrival_buffer_minutes, 15),
      'uniform_required', f.uniform_required,
      'bring', f.worker_should_bring,
      'changing_facilities', f.changing_facilities,
      'locker_information', f.locker_information
    ),
    'welfare', jsonb_build_object(
      'food_provided', f.food_provided,
      'staff_restaurant', f.staff_restaurant,
      'refreshments', f.refreshments,
      'break_policy', f.break_policy
    ),
    'safety', jsonb_build_object(
      'fire_emergency_basics', f.fire_emergency_basics,
      'assembly_point', f.assembly_point,
      'health_safety_acknowledgement', f.health_safety_acknowledgement
    ),
    'spa', jsonb_build_object(
      'products_brands', coalesce(f.products_brands, array_to_string(coalesce(e.product_houses_used, e.product_houses), ', ')),
      'treatment_protocols', f.treatment_protocols,
      'booking_system', coalesce(f.booking_system, array_to_string(e.systems_used, ', ')),
      'retail_commission', f.retail_commission,
      'treatment_commission', f.treatment_commission,
      'gratuities_service_charge', f.gratuities_service_charge,
      'retail_targets', f.retail_targets,
      'guest_service_standards', f.guest_service_standards,
      'property_rules', f.property_rules
    ),
    'documents', coalesce(f.useful_documents, '[]'::jsonb),
    'booking', case when p_booking_type = 'agency' then jsonb_build_object(
      'date', b.shift_date,
      'start_time', b.shift_start_time,
      'end_time', b.shift_end_time,
      'shift_type', b.shift_type,
      'specialism', b.specialism,
      'notes', b.notes
    ) else jsonb_build_object(
      'start_date', b.start_date,
      'end_date', b.end_date,
      'days_required', b.days_required,
      'services_required', b.services_required,
      'accommodation_included', b.accommodation_included,
      'travel_included', b.travel_included,
      'notes', b.notes
    ) end,
    'residency', case when p_booking_type = 'residency' then jsonb_build_object(
      'accommodation', f.residency_accommodation,
      'accommodation_address', f.residency_accommodation_address,
      'check_in', f.residency_check_in,
      'check_out', f.residency_check_out,
      'travel_arrangements', f.residency_travel_arrangements,
      'staff_contacts', f.residency_staff_contacts,
      'programme_brief', f.residency_programme_brief,
      'facilities_access', f.residency_facilities_access,
      'commercial_targets', f.residency_commercial_targets,
      'working_pattern', f.residency_working_pattern,
      'laundry_housekeeping', f.residency_laundry_housekeeping,
      'expenses_process', f.residency_expenses_process,
      'local_information', f.residency_local_information,
      'other_notes', f.residency_other_notes
    ) else null end
  );

  insert into public.booking_arrival_packs (booking_type, booking_id, employer_id, candidate_id, fact_file_id, snapshot, generated_at, updated_at)
  values (p_booking_type, p_booking_id, b.employer_id, b.candidate_id, f.id, payload, now(), now())
  on conflict (booking_type, booking_id) do update set
    snapshot = excluded.snapshot,
    fact_file_id = excluded.fact_file_id,
    generated_at = excluded.generated_at,
    updated_at = now();
end; $$;

create or replace function public.trg_generate_agency_arrival_pack() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status in ('accepted','confirmed','completed') and (tg_op = 'INSERT' or old.status is distinct from new.status or old.paid_at is distinct from new.paid_at) then
    perform public.generate_booking_arrival_pack('agency', new.id);
  end if;
  return new;
end; $$;

drop trigger if exists trg_agency_arrival_pack on public.agency_bookings;
create trigger trg_agency_arrival_pack after insert or update on public.agency_bookings for each row execute function public.trg_generate_agency_arrival_pack();


-- Every shift that should already have had a pack. Somebody who took a booking
-- last week should not have to take another one to find out where they are
-- going.
DO $backfill$
DECLARE
  booking_id uuid;
  made integer := 0;
BEGIN
  IF to_regclass('public.agency_bookings') IS NULL THEN RETURN; END IF;
  FOR booking_id IN
    SELECT id FROM public.agency_bookings WHERE status IN ('accepted','confirmed','completed')
  LOOP
    BEGIN
      PERFORM public.generate_booking_arrival_pack('agency', booking_id);
      made := made + 1;
    EXCEPTION WHEN others THEN
      -- One property with an incomplete fact file must not stop the rest.
      RAISE NOTICE 'arrival pack skipped for %: %', booking_id, sqlerrm;
    END;
  END LOOP;
  RAISE NOTICE 'arrival packs generated for % bookings', made;
END $backfill$;

NOTIFY pgrst, 'reload schema';
